### PR TITLE
Merge 'flags' stanzas in cabal.project (fix #10767)

### LINKED ISSUE #10767: Ignored `flags` from cabal.project
**Describe the bug**
If there is more than one `flags: ...` stanza in a `cabal.project` file, only one of them is taken into account.

**To Reproduce**

```
> cat foo.cabal
cabal-version:  3.0
name:           foo
version:        0.1
license:        BSD-3-Clause
build-type:     Simple

flag bar
  default: True
  manual: True

flag baz
  default: True
  manual: True

Library
    if flag(bar) || flag (baz)
      buildable: false

> cat cabal.project
packages: .

package foo
  flags: -bar
  flags: -baz
  -- flags: -bar -baz -- this works

> cabal build
Error: [Cabal-7127]
Cannot build the package foo-0.1 because none of the components are available to build: the library is marked as 'buildable: False'
```

If we set all the flags at once (i.e. uncomment the last line in `cabal.project`) then it works.

**Expected behavior**
I would expect flags to be merged. Or at least a warning that some `flags` stanza has been ignored.

**System information**
 - cabal: 3.12.1.0 and HEAD

### PR DESCRIPTION
**Pull request by hsyl20**
Please read [Github PR Conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions) and then fill in *one* of these two templates.

**Template Α: This PR modifies [behaviour or interface](https://github.com/cabalism/cabal/blob/master/CONTRIBUTING.md#changelog)**

Include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
  * [x] [Is the change significant?](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#is-my-change-significant) If so, remember to add `significance: significant` in the changelog file.
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [x] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

### CODE REVIEW

**Review by ulysses4ever — APPROVED** [review]
Awesome, thank you! Special thanks for the test! 

It looks like a good candidate for backport to 3.14 in case we have another point release there.

File: cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs [hunk 1]
```diff
@@ -1568,7 +1568,7 @@ legacyPackageConfigFieldDescrs =
             dispFlagAssignment
             parsecFlagAssignment
             configConfigurationsFlags
-            (\v conf -> conf{configConfigurationsFlags = v})
+            (\v conf -> conf{configConfigurationsFlags = configConfigurationsFlags conf <> v})
```
Comment (mpickering) [inline cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs:1571]: Perhaps this indicates there should be a helper like `commaListField` which operates on a generic `Monoid` rather than a list. Otherwise, looks like a precise fix to me :+1:

**Review by mpickering — APPROVED** [review]

File: cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs (hunk 1 above)
Comment (hsyl20) [reply cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs]: Good idea, I've added one.

**Comment by ulysses4ever** [comment]
Now that it extends API, backporting it becomes more dangerous. Although it's `cabal-install` "API", which maybe not as important as Cabal API.

**Comment by ulysses4ever** [comment]
@hsyl20 do you want to put the merge(+squash, probably) label as described in the contributing guidelines?

**Comment by hsyl20** [comment]
> @hsyl20 do you want to put the merge(+squash, probably) label as described in the contributing guidelines?

Done. Thanks for the review!

**Comment by hsyl20** [comment]
@mergifyio requeue
