### PR TITLE
Don't include requests for non-existent stanzas in pkgStanzasRequested, fixes #3340.

### LINKED ISSUE #3340: [nix-local-build] Packages without tests should not considered --enable-tests as part of configuration
Steps to reproduce:
1. Create a Cabal package with no test suite
2. `cabal new-build`
3. `cabal new-build --enable-tests`

Expected behavior: Cabal reports nothing to do

Actual behavior: Cabal decides to rebuild the package, because configuration has changed

CC @dcoutts

### PR DESCRIPTION
**Pull request by ezyang**
First three commits are just some extra commenting from when I was analyzing the code.

### CODE REVIEW

File: cabal-install/Distribution/Client/ProjectPlanning.hs [hunk 1]
```diff
@@ -177,26 +177,38 @@ import           System.FilePath
...
                                        -> Bool
 sanityCheckElaboratedConfiguredPackage sharedConfig
                                        pkg@ElaboratedConfiguredPackage{..} =
 
+    -- we should only have enabled stanzas that actually can be built
+    -- (according to the solver)
     pkgStanzasEnabled `Set.isSubsetOf` pkgStanzasAvailable
 
-    -- the stanzas explicitly enabled should be available and enabled
+    -- the stanzas that the user explicitlyr requested should be
```
Comment (23Skidoo) [inline cabal-install/Distribution/Client/ProjectPlanning.hs]: Typo: explicitlyr.

File: cabal-install/Distribution/Client/ProjectPlanning.hs [hunk 2]
```diff
@@ -181,37 +181,41 @@ import           System.FilePath
...
+                                       -> a
 sanityCheckElaboratedConfiguredPackage sharedConfig
-                                       pkg@ElaboratedConfiguredPackage{..} =
+                                       pkg@ElaboratedConfiguredPackage{..}
+                                       ret =
 
     -- we should only have enabled stanzas that actually can be built
     -- (according to the solver)
-    pkgStanzasEnabled `Set.isSubsetOf` pkgStanzasAvailable
+    assert (pkgStanzasEnabled `Set.isSubsetOf` pkgStanzasAvailable)
```
Comment (23Skidoo) [inline cabal-install/Distribution/Client/ProjectPlanning.hs]: Aren't asserts removed when optimisation is enabled?

**Comment by 23Skidoo** [comment]
LGTM.

File: cabal-install/Distribution/Client/ProjectPlanning.hs (hunk 2 above)
Comment (ezyang) [inline cabal-install/Distribution/Client/ProjectPlanning.hs]: Yes. I just converted it into multiple asserts so that we know WHICH one failed when one fails. But arguably we should have a proper assert mechanism that is decoupled from optimization.

Comment (23Skidoo) [inline cabal-install/Distribution/Client/ProjectPlanning.hs]: Or just compile with `-fno-ignore-asserts`.
