### PR TITLE
Fix cabal project caching bug, Add verbose printing

### LINKED ISSUE #4662: switching project-file does not properly mark stuff as dirty
Setup: Two project files:

- cabal.project.opt
  ~~~~
  packages: .
  package mypackage
    optimization: 1
  ~~~~
- cabal.project.noopt
  ~~~~
  packages: .
  package mypackage
    optimization: 0
  ~~~~

Now, doing

~~~~
[manually remove dist-newstyle]
> cabal new-build --project-file=cabal.project.noopt lib:mypackage
[builds lib]
> cabal new-build --project-file=cabal.project.opt exe:myexecutable
[builds exe]
~~~~

In the second step, I expected that `lib` is rebuilt, since the only existing build products for it are without optimizations. Instead, it seems to build a `-O1` exe against the `-O0` lib.

Note that doing the same without `--project-file` works as expected, i.e.

~~~~
[manually remove dist-newstyle]
> cabal new-build -O0 lib:mypackage
[builds lib]
> cabal new-build -O1 exe:myexecutable
[rebuilds lib, builds exe]
~~~~

### PR DESCRIPTION
**Pull request by lspitzner**
- Use (projectConfigConfigFile, distProjectFile "") as key
  for config FileMonitor, instead of ().
- Add verbose printing of relevant config file paths.

Fixes #4662 and probably #5225.

Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [ ] The documentation has been updated, if necessary.
* [ ] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

File: cabal-install/Distribution/Client/ProjectPlanning.hs [hunk 1]
```diff
@@ -294,48 +295,62 @@ sanityCheckElaboratedPackage ElaboratedConfiguredPackage{..}
...
+          projectConfig <- phaseReadProjectConfig
+          localPackages <- phaseReadLocalPackages projectConfig
+          return (projectConfig, localPackages)
+
+    when (verbosity >= verbose) $ do
+      monitorFileList <- getFileMonitorSimpleFileList fileMonitorProjectConfig
+      info verbosity
+        $ unlines
+        $ ("this build was affected by the following (project) config files:" :)
+        $ filter (\x -> not (".cabal" `isSuffixOf` x) && x /= ".")
```
Comment (alexbiehl) [inline cabal-install/Distribution/Client/ProjectPlanning.hs]: Filtering out only cabal files might lead to a lot of false-posives in this list. Consider the support for local tarballs, which adds a file monitor to a `.tar.gz` file which will count as "config file" here.

Comment (lspitzner) [reply cabal-install/Distribution/Client/ProjectPlanning.hs]: raah that's a good point, but I don't see any elegant to solution for this without creating some kind of duplication or implication what config files we have. Perhaps this should just not do any filtering and not pretend it only contains config files, but "configuration input stuff"?

Comment (alexbiehl) [reply cabal-install/Distribution/Client/ProjectPlanning.hs]: Well, we have `distProjectFile` in scope, we could do something like this:

filterM doesFileExist $ map distProjectFile ["", "local", "freeze"]

Comment (alexbiehl) [reply cabal-install/Distribution/Client/ProjectPlanning.hs]: Or better: we have `projectConfigProvenance` which should hold all the paths from the involved configuration files.

**Comment by lspitzner** [comment]
@alexbiehl Like that?

File: cabal-install/Distribution/Client/ProjectConfig.hs [hunk 2]
```diff
@@ -418,38 +418,19 @@ renderBadProjectRoot (BadProjectRootExplicitFile projectFile) =
 readProjectConfig :: Verbosity -> Flag FilePath -> DistDirLayout -> Rebuild ProjectConfig
 readProjectConfig verbosity configFileFlag distDirLayout = do
     global <- readGlobalConfig             verbosity configFileFlag
-    local  <- readProjectLocalConfig       verbosity distDirLayout
+    hasCabalProjectFile <- liftIO $ doesFileExist projectFile
```
Comment (alexbiehl) [inline cabal-install/Distribution/Client/ProjectConfig.hs]: I liked it better as it was before with 

```
thing1 <- read this
thing2 <- read that
thing3 <- read that 
... 
```

The logic here looks a bit out of place.

Comment (alexbiehl) [reply cabal-install/Distribution/Client/ProjectConfig.hs]: you could lift `addProjectFileProvenance` to top level for example to reduce the duplication that way.

File: cabal-install/Distribution/Client/ProjectPlanning.hs [hunk 3]
```diff
@@ -294,48 +294,61 @@ sanityCheckElaboratedPackage ElaboratedConfiguredPackage{..}
...
-rebuildProjectConfig verbosity
-                     distDirLayout@DistDirLayout {
-                       distProjectRootDirectory,
-                       distDirectory,
-                       distProjectCacheFile,
-                       distProjectCacheDirectory
-                     }
-                     cliConfig = do
+                     -> IO
+                          ( ProjectConfig
```
Comment (alexbiehl) [inline cabal-install/Distribution/Client/ProjectPlanning.hs]: IMHO these stylistic changes distract the diff from the meat somewhat, there are some others further down

File: cabal-install/Distribution/Client/ProjectPlanning.hs [hunk 4]
```diff
@@ -294,48 +294,61 @@ sanityCheckElaboratedPackage ElaboratedConfiguredPackage{..}
...
-      runRebuild distProjectRootDirectory $
-      rerunIfChanged verbosity fileMonitorProjectConfig () $ do
-
-        projectConfig <- phaseReadProjectConfig
-        localPackages <- phaseReadLocalPackages projectConfig
-        return (projectConfig, localPackages)
+      runRebuild distProjectRootDirectory
+      $ rerunIfChanged verbosity
+                       fileMonitorProjectConfig
+                       (projectConfigConfigFile, distProjectFile "")
```
Comment (alexbiehl) [inline cabal-install/Distribution/Client/ProjectPlanning.hs]: Don't pass the tuple directly. Instead make a new `fileMonitorProjectConfigValue` or `fileMonitorProjectConfigInput` or something.

File: cabal-install/Distribution/Client/ProjectPlanning.hs [hunk 5]
```diff
@@ -294,48 +294,61 @@ sanityCheckElaboratedPackage ElaboratedConfiguredPackage{..}
...
+      $ do
+          liftIO $ info verbosity "Project settings changed, reconfiguring..."
+          projectConfig <- phaseReadProjectConfig
+          localPackages <- phaseReadLocalPackages projectConfig
+          return (projectConfig, localPackages)
+
+    info verbosity
+      $ unlines
+      $ ("this build was affected by the following (project) config files:" :)
+      $ [ path
```
Comment (alexbiehl) [inline cabal-install/Distribution/Client/ProjectPlanning.hs]: Maybe make this a list of filepaths by prepending '- ' to the paths.

File: cabal-install/Distribution/Client/ProjectPlanning.hs [hunk 6]
```diff
@@ -294,48 +294,61 @@ sanityCheckElaboratedPackage ElaboratedConfiguredPackage{..}
...
+                  , distProjectCacheDirectory
+                  , distProjectFile
+                  }
+      = distDirLayout
+    ProjectConfigShared { projectConfigConfigFile } =
+      projectConfigShared cliConfig
+
+    fileMonitorProjectConfig =
+      newFileMonitor (distProjectCacheFile "config") :: FileMonitor
+          (Flag FilePath, FilePath)
```
Comment (alexbiehl) [inline cabal-install/Distribution/Client/ProjectPlanning.hs]: we should not pass a `Flag FilePth` into the monitor.  I suggest you use `getConfigFilePath` to resolve to properly resolve the config file path.

File: cabal-install/Distribution/Client/ProjectConfig.hs (hunk 2 above)
Comment (lspitzner) [reply cabal-install/Distribution/Client/ProjectConfig.hs]: The downside to that is that the reader might very well expect the same kind of logic behind the three `read` functions, especially when they have so similar names (`readProjectLocalConfig`, `readProjectLocalFreezeConfig`, `readProjectLocalExtraConfig`).

The `addProjectFileProvenance` change is not necessary afaict.

File: cabal-install/Distribution/Client/ProjectPlanning.hs (hunk 3 above)
Comment (lspitzner) [reply cabal-install/Distribution/Client/ProjectPlanning.hs]: Right, sorry about that. I blanket-applied `brittany` to some stuff and did not revert these unnecessary changes. I will fix that.

File: cabal-install/Distribution/Client/ProjectPlanning.hs (hunk 4 above)
Comment (lspitzner) [reply cabal-install/Distribution/Client/ProjectPlanning.hs]: You mean a new datatype, right?

File: cabal-install/Distribution/Client/ProjectPlanning.hs (hunk 6 above)
Comment (lspitzner) [reply cabal-install/Distribution/Client/ProjectPlanning.hs]: Ah, good I added that type signature to counteract the `NoMonoLocalBinds` then :D

File: cabal-install/Distribution/Client/ProjectPlanning.hs (hunk 4 above)
Comment (alexbiehl) [reply cabal-install/Distribution/Client/ProjectPlanning.hs]: I think tuple is ok here. 

I meant something like 
  ```
  let 
    fileMonitorProjectConfigInput = 
      (..., ...)
```

File: cabal-install/Distribution/Client/ProjectConfig.hs (hunk 2 above)
Comment (alexbiehl) [reply cabal-install/Distribution/Client/ProjectConfig.hs]: Right, would it make sense to pass the implicit config as a parameter in case the file doesn't exist? Then you could handle the "file does not exist case"  in `readProjectFile`. Does that make sense?

**Comment by lspitzner** [comment]
@alexbiehl Squashed the changes, hope that is alright.

This probably still contains some stylistic changes, but have a really hard time determining what the proper style is, as the codebase is not very consistent. I might also argue that the prevalent use of hanging indentation is also at fault for creating larger diffs than necessary, for example on the function renames in this commit.

Unless I have missed something, all comments should be addressed, apart from "pass the implicit config as a parameter". With the rename, the code seems to be sufficiently clear and free of redundancies already.

File: cabal-install/Distribution/Client/ProjectConfig.hs [hunk 7]
```diff
@@ -480,19 +474,22 @@ readProjectLocalExtraConfig verbosity distDirLayout =
...
 
 -- | Reads a named config file in the given project root dir, or returns empty.
 --
-readProjectExtensionFile :: Verbosity -> DistDirLayout -> String -> FilePath
-                         -> Rebuild ProjectConfig
-readProjectExtensionFile verbosity DistDirLayout{distProjectFile}
+readProjectFile :: Verbosity
+                -> DistDirLayout
+                -> String
+                -> String
```
Comment (alexbiehl) [inline cabal-install/Distribution/Client/ProjectConfig.hs]: I think this used to be FilePath

**Comment by lspitzner** [comment]
Oh, there was one other thing I wanted to ask: Would it make sense to output this at lower verbosity? It seems sufficiently important, almost (and i don't like to have to wade through the `-v2` output just to see this).

File: cabal-install/Distribution/Client/ProjectConfig.hs (hunk 7 above)
Comment (lspitzner) [reply cabal-install/Distribution/Client/ProjectConfig.hs]: Which is clearly wrong, is it not? It is the `extensionDescription` after all, a string meant for displaying purposes.

Comment (alexbiehl) [reply cabal-install/Distribution/Client/ProjectConfig.hs]: yeah, sorry

**Comment by lspitzner** [comment]
Thanks for the very prompt reviewing!

**Comment by alexbiehl** [comment]
@23Skidoo can we merge this?

File: cabal-install/Distribution/Client/ProjectConfig.hs [hunk 8]
```diff
@@ -480,19 +474,22 @@ readProjectLocalExtraConfig verbosity distDirLayout =
...
+                -> Rebuild ProjectConfig
+readProjectFile verbosity DistDirLayout{distProjectFile}
                          extensionName extensionDescription = do
     exists <- liftIO $ doesFileExist extensionFile
     if exists
       then do monitorFiles [monitorFileHashed extensionFile]
-              liftIO readExtensionFile
+              addProjectFileProvenance <$> liftIO readExtensionFile
       else do monitorFiles [monitorNonExistentFile extensionFile]
```
Comment (23Skidoo) [inline cabal-install/Distribution/Client/ProjectConfig.hs]: Perhaps we shouldn't mention "extension file" here now that the function has been renamed.

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by 23Skidoo** [comment]
@lspitzner Congrats on commit number 10000!

**Comment by lspitzner** [comment]
@23Skidoo 
Heh, thanks. If I could I would pass this on to the much more frequent contributors. Perhaps we can just view it more as a collective achievement.
