### PR TITLE
Fix #7714: use `nroff -man | less` as backend for `cabal man`

### LINKED ISSUE #7714: `cabal man` does not work on macOS
Re #6548:

`cabal man` does not work on macOS
```
$ cabal man 
man: invalid option -- l
man, version 1.6c

usage: man [-adfhktwW] [section] [-M path] [-P pager] [-S list]
	[-m system] [-p string] name ...

  a : find all matching entries
...
fd:13: commitBuffer: resource vanished (Broken pipe)
```

Also, there is a typo in an error message:
```
$ cabal man happy
Error: cabal: 'manpage' doesn't take any extra arguments: happy
```

### PR DESCRIPTION
**Pull request by andreasabel**
Fix #7714: use `nroff -man /dev/stdin | less` as backend for `cabal man`

WIP: This does not work yet, I need some help with constructing the pipe correctly in Haskell.

I seem to follow the example at
https://stackoverflow.com/questions/41030168/haskell-using-the-handle-created-from-createprocess-and-createpipe-to-pipe-int
which works for me, but my patch does not seem to invoke `less` correctly.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by andreasabel** [comment]
> WIP: This does not work yet, I need some help with constructing the pipe correctly in Haskell.

Weirdly enough, it could be because the generated text is too long (800kB).  If I truncate it to 192kB (this is a precise hard bound, 1 char more is too much(!)), it works...

**Comment by phadej** [comment]
> The documentation suggests that a pipe is created when the `CreatePipe` constructor is supplied

Yes a pipe is created, for example `stdout`. Library gives the writing end to the spawned process and gives the reading end to you. A pipe (= two FDs) is created, but you get only one end of it.

**Comment by phadej** [comment]
For the record, e.g. `git commit --help` seems to simply call `man git-commit` as git installs the man pages. That works on BSD-derivatives too, obviously. Also doesn't need `*roff` to be available.

**Comment by phadej** [comment]
> and do stdin writing as elsewhere.

refers to the wish that we rather add a new helper to `Distribution.Simple.Utils` to spawn processes with inherited outputs, rather then going low-level in a particular command implementation.

**Comment by andreasabel** [comment]
Can this PR be merged now? I may not be perfect, but it improves on the status quo, I think.

**Comment by Mikolaj** [comment]
Any further comments, anybody? 

@hasufell, would you like to review?

File: cabal-install/src/Distribution/Client/Manpage.hs [hunk 1]
```diff
@@ -22,12 +22,17 @@ module Distribution.Client.Manpage
 
 import Distribution.Client.Compat.Prelude
 import Prelude ()
+import qualified Data.List.NonEmpty as List1
 
+import Distribution.Client.Init.Utils   (trim)
+  -- TODO #7744: move 'trim' to a more canonical place
```
Comment (fgaz) [inline cabal-install/src/Distribution/Client/Manpage.hs:28]: Looks like #7744 is fixed

File: cabal-install/src/Distribution/Client/Manpage.hs [hunk 2]
```diff
@@ -50,24 +55,44 @@ manpageCmd pname commands flags
...
+          Nothing  -- Inherit environment
+          (Just $ IODataText contents)
+          IODataModeText
+
+        unless (ec1 == ExitSuccess) $ exitWith ec1
+
+        -- Pipe output of @nroff@ into @less@
+        (Just inLess, _, _, procLess) <- createProcessWithEnv
+          Verbosity.normal
+          "less"
```
Comment (hasufell) [inline cabal-install/src/Distribution/Client/Manpage.hs:85]: `most` is much better and also seems to have no problem with the newlines I think.

One way would be to check the `$PAGER` env var and fall back to `less` if that isn't set.

Comment (hasufell) [reply cabal-install/src/Distribution/Client/Manpage.hs:85]: https://github.com/andreasabel/cabal/pull/1

Comment (hasufell) [reply cabal-install/src/Distribution/Client/Manpage.hs:85]: using `less` is borked here:

## Less

Screenshot_2022-01-20_11-51-49

## Most

Screenshot_2022-01-20_11-52-06

Comment (fgaz) [reply cabal-install/src/Distribution/Client/Manpage.hs:85]: less needs `-R` (or `-r`) to display colours

Comment (hasufell) [reply cabal-install/src/Distribution/Client/Manpage.hs:85]: > less needs `-R` (or `-r`) to display colours

Is that safe to add unconditionally?

```
       -r or --raw-control-chars
              Causes "raw" control characters to be displayed.  The default is to display control characters using the caret notation; for  ex‐
              ample,  a  control-A (octal 001) is displayed as "^A".  Warning: when the -r option is used, less cannot keep track of the actual
              appearance of the screen (since this depends on how the screen responds to each type of control character).  Thus,  various  dis‐
              play problems may result, such as long lines being split in the wrong place.

              USE OF THE -r OPTION IS NOT RECOMMENDED.
```

Comment (hasufell) [reply cabal-install/src/Distribution/Client/Manpage.hs:85]: Seems `-R` should be ok and also works under FreeBSD

Comment (hasufell) [reply cabal-install/src/Distribution/Client/Manpage.hs:85]: https://github.com/andreasabel/cabal/pull/1/commits/c4140b19e827a97fc9152dc60fbe763ce5d02529

**Review by hasufell — CHANGES_REQUESTED** [review]
@andreasabel I added some fixes here: https://github.com/andreasabel/cabal/pull/1

**Review by Mikolaj — APPROVED** [review]

**Comment by andreasabel** [comment]
Mergiofy was waiting on the "Artifacts" workflows, but these seem gone.  So I deleted them from the required statuses list for master in Settings/Branches.  Hope that was intended.

**Comment by Mikolaj** [comment]
> Mergiofy was waiting on the "Artifacts" workflows, but these seem gone. So I deleted them from the required statuses list for master in Settings/Branches. Hope that was intended.

Yes, it was, thank you!

**Comment by fgaz** [comment]
This will need a changelog entry

**Comment by andreasabel** [comment]
> This will need a changelog entry

@fgaz: See https://github.com/haskell/cabal/pull/7935
