### PR TITLE
Issue 989 range op wild

### LINKED ISSUE #989: Context needed for ParseFailed: >= 1.2.*
I had a `build-depends` section with a trailing comma, a syntax error which is arguably hard to spot.

Cabal gave me this error:

```
cabal: <name>.cabal:<lineno>: Parse of field 'build-depends' failed.
```
1. The `<lineno>` was always the first line of the `build-depends` section, not the last (which had the syntax error).
2. There is no mention of the character that failed to parse.

Can we improve this? The logic is defined in `ParseUtils.hs`. I find the code there to be a little dense and wasn't sure how to get started.

### PR DESCRIPTION
**Pull request by phadej**
- No more `try`
- It recognises wild-card version after all operators,
  but fails with more descriptive warning after non-==
  Fixes #989

---

Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [x] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.
* [x] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

File: Cabal/Distribution/Types/VersionRange.hs [hunk 1]
```diff
@@ -411,37 +411,61 @@ instance Parsec VersionRange where
...
+                        _ -> fail $ "Unknown version operator " ++ show op
+
+        -- either wildcard or normal version
+        verOrWild :: CabalParsing m => m (Bool, Version)
+        verOrWild = do
+            x <- P.integral
+            verLoop (x :)
+
+        -- trailing: wildcard (.y.*) or normal version (optional tags) (.y.z-tag)
+        verLoop :: CabalParsing m => ([Int] -> [Int]) -> m (Bool, Version)
```
Comment (23Skidoo) [inline Cabal/Distribution/Types/VersionRange.hs]: May be a good idea to vendor `dlist` to improve readability in cases like this one.

Comment (phadej) [reply Cabal/Distribution/Types/VersionRange.hs]: Will do.

Comment (phadej) [reply Cabal/Distribution/Types/VersionRange.hs]: In fact, we have DList in `Compat`

File: Cabal/Distribution/Types/VersionRange.hs [hunk 2]
```diff
@@ -440,17 +441,17 @@ instance Parsec VersionRange where
...
         verOrWild = do
             x <- P.integral
-            verLoop (x :)
+            verLoop (DList.singleton x)
 
         -- trailing: wildcard (.y.*) or normal version (optional tags) (.y.z-tag)
-        verLoop :: CabalParsing m => ([Int] -> [Int]) -> m (Bool, Version)
-        verLoop acc = verLoop' acc <|> (tags >> pure (False, mkVersion (acc [])))
+        verLoop :: CabalParsing m => DList.DList Int -> m (Bool, Version)
+        verLoop acc = verLoop' acc <|> (tags >> pure (False, mkVersion (DList.toList acc)))
```
Comment (23Skidoo) [inline Cabal/Distribution/Types/VersionRange.hs]: You can also cut down the number of parentheses by rewriting this bit as `mkVersion . DList.toList $ acc`

File: Cabal/Distribution/Types/VersionRange.hs [hunk 3]
```diff
@@ -440,17 +441,17 @@ instance Parsec VersionRange where
...
 
-        verLoop' :: CabalParsing m => ([Int] -> [Int]) -> m (Bool, Version)
+        verLoop' :: CabalParsing m => DList.DList Int -> m (Bool, Version)
         verLoop' acc = do
             _ <- P.char '.'
-            ((\x -> verLoop (acc . (x :))) =<< P.integral)
-                <|> (\_ -> (True, mkVersion (acc []))) <$> P.char '*'
+            ((\x -> verLoop (DList.snoc acc x)) =<< P.integral)
```
Comment (23Skidoo) [inline Cabal/Distribution/Types/VersionRange.hs]: and here you can drop the lambda on the first line and use `const` on the second line.

Comment (phadej) [reply Cabal/Distribution/Types/VersionRange.hs]: done, used `<$`

**Comment by 23Skidoo** [comment]
Merged, thanks!
