### PR TITLE
Fix haddock interface and HTML paths for sub-libraries

### LINKED ISSUE #11475: Internal library .haddock path mismatch in cabal haddock --haddock-all
**Describe the bug**

When a package has an internal library and the main library re-exports from it using `module X` syntax, `cabal haddock --haddock-all` fails to find the internal library's `.haddock` interface file because it looks for it at the wrong path.

Haddock dumps the internal library's interface file to:

```
.../l/internal/doc/html/cabal-bug/internal/internal.haddock
```

But when processing the main library, cabal looks for it at (missing the extra `internal/` subdirectory):

```
.../l/internal/doc/html/cabal-bug/internal.haddock
```

Because the file is not found, no `--read-interface` flag is passed for the internal library, so haddock cannot resolve re-exported documentation.

**To Reproduce**

Using the attached minimal reproduction (`cabal-haddock-bug.zip`):

```
$ cabal haddock --haddock-all
```

The `.cabal` file defines an internal library `internal` and a main library that re-exports it via `module Internal`:

```cabal
cabal-version: 2.2
name: cabal-bug
version: 0.1.0.0

library internal
  default-language: Haskell2010
  hs-source-dirs: libs/internal/src
  exposed-modules: Internal
  build-depends: base >= 4.18 && < 4.22

library
  default-language: Haskell2010
  hs-source-dirs: src
  exposed-modules: Lib
  build-depends:
    base >= 4.18 && < 4.22,
    internal
```

Verbose output (`cabal haddock -v3 --haddock-all`) confirms:
- `--dump-interface` for the internal library writes to `.../cabal-bug/internal/internal.haddock`
- Cabal checks for the file at `.../cabal-bug/internal.haddock` (without the subdirectory)
- No `--read-interface` is emitted for the internal library

**Expected behavior**

100% haddock coverage for `Lib`, with all re-exported items (`hello`, `Greeting`) documented from the internal library.

**Actual behavior**

```
Warning: Lib: Could not find documentation for exported module: Internal
Warning: Lib: Couldn't find .haddock for export hello
Warning: Lib: Couldn't find .haddock for export Greeting
  33% (  1 /  3) in 'Lib'
  Missing documentation for:
    hello
    Greeting
```

**System information**
- Operating system: Linux (x86_64)
- `cabal`: 3.16.1.0, also reproduced with 3.14.2.0
- `ghc`: 9.12.2, also reproduced with 9.10.3 and 9.8.4
- Works correctly with GHC 9.6.7

**Additional context**

No known workaround. The `--haddock-all` flag correctly triggers haddock for the internal library, but the resulting `.haddock` file is not found by the main library's haddock invocation due to the path mismatch. This appears to be a regression introduced somewhere between GHC 9.6 and 9.8. 

[cabal-haddock-bug.zip](https://github.com/user-attachments/files/25093466/cabal-haddock-bug.zip)

### PR DESCRIPTION
**Pull request by Tritlo**
Fixes #11475

## Summary

- Fix `haddockInterfaces` and `haddockHTMLs` paths in `generalInstalledPackageInfo` to include the sub-library name subdirectory for internal libraries
- Without this fix, `cabal haddock --haddock-all` can't find the `.haddock` interface file for internal sub-libraries, causing "could not find link destinations" warnings and missing documentation

## Checklist

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
  * [ ] [Is the change significant?](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#is-my-change-significant) If so, remember to add `significance: significant` in the changelog file.
* [x] The documentation has been updated, if necessary.
* [x] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [x] Tests have been added.

## QA Notes

1. Create a package with an internal sub-library and a main library that re-exports from it
2. Run `cabal haddock --haddock-all`
3. Before this fix: haddock emits warnings like "Could not find documentation for exported module" and "Couldn't find .haddock for export"
4. After this fix: documentation builds cleanly with full coverage and cross-library links resolved

### CODE REVIEW

File: changelog.d/pr-11476.md [hunk 1]
```diff
@@ -0,0 +1,12 @@
+---
+synopsis: Fix haddock interface and HTML paths for sub-libraries
+packages: [Cabal]
+prs: 11476
+issues: [11475]
+---
+
+Fix `haddockInterfaces` and `haddockHTMLs` paths in `generalInstalledPackageInfo`
+to include the sub-library name subdirectory for internal libraries. Previously,
```
Comment (ulysses4ever) [inline changelog.d/pr-11476.md]: I'd lead with "Previously..." and dive into API details later.

**Review by ulysses4ever — APPROVED** [review]
Looks great to me, thanks! 

We have long had an issue with missing links to reexports on the Hackage page: https://hackage.haskell.org/package/Cabal (e.g. Distribution.Backpack, which is reexported from Cabal-syntax, isn't linked). I wonder if a similar patch would be required to fix that (a patch for hackage-server, presumably, as it generates the package pages on its own AFAIR).

**Comment by Tritlo** [comment]
Yes! This seems to have been broken since 9.6, I'm not sure what changed.

File: Cabal/src/Distribution/Simple/Register.hs [hunk 2]
```diff
@@ -545,8 +545,18 @@ generalInstalledPackageInfo adjustRelIncDirs pkg abi_hash lib lbi clbi installDi
...
+          LSubLibName n -> haddockdir installDirs </> prettyShow n </> haddockLibraryPath pkg lib
+          LMainLibName -> haddockdir installDirs </> haddockLibraryPath pkg lib
+        | hasModules
+        ]
+    , IPI.haddockHTMLs =
+        [ case libName lib of
+          LSubLibName n -> htmldir installDirs </> prettyShow n
+          LMainLibName -> htmldir installDirs
+        | hasModules
+        ]
```
Comment (mpickering) [inline Cabal/src/Distribution/Simple/Register.hs]: We should set `htmldir` to the right thing directly by using `haddockLibraryDirPath`. I'll push a commit which does this.

File: cabal-testsuite/PackageTests/NewHaddock/HaddockAllInternalLib/cabal.test.hs [hunk 3]
```diff
@@ -0,0 +1,6 @@
+import Test.Cabal.Prelude
+-- Test that `cabal haddock --haddock-all` correctly finds the .haddock
+-- interface file for an internal sub-library (no "could not find link
+-- destinations" warning).
+main = cabalTest $ do
+    cabal "haddock" ["--haddock-all"]
```
Comment (mpickering) [inline cabal-testsuite/PackageTests/NewHaddock/HaddockAllInternalLib/cabal.test.hs]: This test currently passes with or without the change, I have modified it so it checks that the warning doesn't appear in the output.

File: Cabal/src/Distribution/Simple/Register.hs (hunk 2 above)
Comment (Tritlo) [reply Cabal/src/Distribution/Simple/Register.hs]: Thanks! But you seem to have rolled back the change to the interfaces. Is that intended?

Comment (mpickering) [reply Cabal/src/Distribution/Simple/Register.hs]: Yes, the patch instead picks the right directory for `htmldir` initially by using `haddockLibraryDirPath`.

**Comment by Tritlo** [comment]
Merged!

**Comment by Mikolaj** [comment]
CI seems stuck. Let me try to restart it...

**Comment by Mikolaj** [comment]
Success! Restarting has been enough to make it green. Thank you for the PR!
