### PR TITLE
Fix cabal init name deduction

### LINKED ISSUE #6861: Cabal interactive init is broken if project names overlap
**Describe the bug**
If the directory overlaps with an existing Hackage pacakge, choosing "yes" when presented with `Should I generate a simple project with sensible defaults? [default: y]` fails to produce a valid build, or even a valid `.cabal` file. 

**To Reproduce**

```
λ П(a: A) haskell → mkdir foo
λ П(a: A) haskell → cd foo 
λ П(a: A) foo → cabal init
Should I generate a simple project with sensible defaults? [default: y] y

Guessing dependencies...

Generating LICENSE...
Generating Setup.hs...
Generating CHANGELOG.md...
Generating src/MyLib.hs...
Generating exe/Main.hs...
Generating test/MyLibTest.hs...
Error: no package name provided.
λ П(a: A) foo → ls
CHANGELOG.md LICENSE      Setup.hs     exe          src          test
```

**Expected behavior**
If we're going to offer this feature, it should work regardless of Hackage. The counter-intuitive fix is to choose a name directory name that doesn't overlap with Hackage: 

```
λ П(a: A) haskell → mv foo foofoo 
λ П(a: A) haskell → cd foofoo 
λ П(a: A) foofoo → cabal init 
Should I generate a simple project with sensible defaults? [default: y] y

Guessing dependencies...

Generating LICENSE...
Generating Setup.hs...
Generating CHANGELOG.md...
Generating src/MyLib.hs...
Generating exe/Main.hs...
Generating test/MyLibTest.hs...
Generating foofoo.cabal...

Warning: no synopsis given. You should edit the .cabal file and add one.
You may want to edit the .cabal file and add a Description field.
λ П(a: A) foofoo → ls
CHANGELOG.md LICENSE      Setup.hs     exe          foofoo.cabal src          test
```

However, if I'm a beginner, or offline, I have no way of checking this information. In fact, for a bare install, I have no way of knowing that this is a requirement! If i have a brand new install, then it works (RIP my `~/.cabal`): 

```
λ П(a: A) foofoo → rm -rf ~/.cabal
λ П(a: A) foofoo → cd ..
λ П(a: A) haskell → rm -rf foofoo 
λ П(a: A) haskell → mkdir foo
λ П(a: A) haskell → cd foo 
λ П(a: A) foo → cabal init
Config file path source is default config file.
Config file /Users/emilypi/.cabal/config not found.
Writing default configuration to /Users/emilypi/.cabal/config
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.RemoteRepo {remoteRepoName = "hackage.haskell.org",
remoteRepoURI = http://hackage.haskell.org/, remoteRepoSecure = Just True,
remoteRepoRootKeys =
["fe331502606802feac15e514d9b9ea83fee8b6ffef71335479a2e68d84adc6b0","1ea9ba32c526d1cc91ab5e5bd364ec5e9e8cb67179a471872f6e26f0ae773d42","2c6c3627bd6c982990239487f1abd02e08a02e6cf16edb105a8012d444d870c3","0a5c7ea47cd1b15f01f5f51a33adda7e655bc0f0b0615baa8e271f4c3351e21d","51f0161b906011b52c6613376b1ae937670da69322113a246a09f807c62f6921"],
remoteRepoKeyThreshold = 3, remoteRepoShouldTryHttps = True}

Guessing dependencies...

Generating LICENSE...
Warning: unknown license type, you must put a copy in LICENSE yourself.
Generating Setup.hs...
Generating CHANGELOG.md...
Generating Main.hs...
Generating foo.cabal...

Warning: no synopsis given. You should edit the .cabal file and add one.
You may want to edit the .cabal file and add a Description field.
λ П(a: A) foo → 
```
**System information**
 - MacOS
 - Cabal 3.2
 - GHC 8.8.3

### PR DESCRIPTION
**Pull request by aurieh**
Fixes #6861, #6236

* [X] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [X] Any changes that could be relevant to users have been recorded in the changelog (add file to `changelog.d` directory).
* [X] The documentation has been updated, if necessary.

Regarding item number 2 on the checklist, I do not think this bugfix is significant enough to warrant a changelog entry.

### Non-interactive use
```
auri@aoi lens $ cabal init --non-interactive
cabal: The name lens is already in use by another package on Hackage.

auri@aoi lens $ cabal init --non-interactive --package-name=microlens
cabal: The name microlens is already in use by another package on Hackage.

```

### Interactive use
```
auri@aoi lens $ cabal init --interactive --package-name=microlens
Should I generate a simple project with sensible defaults? [default: y] y
cabal: The name microlens is already in use by another package on Hackage.

auri@aoi lens $ cabal init --interactive --package-name=microlens
Should I generate a simple project with sensible defaults? [default: y] n
[snip]
The name microlens is already in use by another package on Hackage. Do you want to choose a different name? [default: y] y
Package name? [default: lens] lens
The name lens is already in use by another package on Hackage. Do you want to choose a different name? [default: y] n
[snip]
Guessing dependencies...
Generating CHANGELOG.md...
Generating src/MyLib.hs...
Generating test/MyLibTest.hs...
Generating lens.cabal...

Warning: no synopsis given. You should edit the .cabal file and add one.
You may want to edit the .cabal file and add a Description field.

```

These are all the changes. Otherwise, `init` behaves the same as before.

### CODE REVIEW

File: cabal-install/src/Distribution/Client/Init/Command.hs [hunk 1]
```diff
@@ -208,29 +210,34 @@ getCabalVersion flags = do
...
-    else return $ flags { packageName = maybeToFlag pkgName' }
+    then getPackageName verbosity sourcePkgDb flags
+    else return $ flags { packageName = Flag pkgName }
 
   where
-    isPkgRegistered (Just pkg) = elemByPackageName (packageIndex sourcePkgDb) pkg
-    isPkgRegistered Nothing    = False
+    isPkgRegistered pkg = elemByPackageName (packageIndex sourcePkgDb) pkg
+
+    deathNameMsg pkgName = "The name " ++ (P.unPackageName pkgName) ++
```
Comment (m-renaud) [inline cabal-install/src/Distribution/Client/Init/Command.hs:239]: Could you merge this function (which takes the package name for a more descriptive message) with `prompOtherNameMsg` and use the latter in both places?

**Review by m-renaud — COMMENTED** [review]
Overall LGTM! Thanks so much for the fix (and apologies for the glacial review). For posterity, could you include in the PR description a couple of sessions with the change in both interactive and non-interactive trying to create a package with the same name as one that already exists on Hackage?

**Comment by aurieh** [comment]
Thank you for pointing out the lack of examples in the description. Adding them allowed me to pick up on an issue that I missed when originally drafting this pull request: asking for new name when `--package-name` is passed in interactive mode.

**Review by m-renaud — APPROVED** [review]
LGTM!

**Comment by m-renaud** [comment]
Re-running the failed checks now (appear to be noise), will merge when the finish successfully.

**Comment by m-renaud** [comment]
Windows CI timed out again :( Trying again.

FYI @phadej since I saw you were looking at Windows CI somewhat recently.

**Comment by phadej** [comment]
8.8.4 doesn't work. Just ping me and I'll use my administrator privileges
