### PR TITLE
testsuite: Supress stderr when running integration tests

### LINKED ISSUE #8419: ci: github action error annotations despite passing tests
Successful test runs cause error annotations in Github Actions, making it easy to miss actual problems with the CI.

E.g. here https://github.com/haskell/cabal/actions/runs/2904212306
Screenshot 2022-08-22 at 16 13 38

Raw log output shows this:

```
2022-08-22T13:41:09.8074706Z Main.hs:1:8: error: Variable not in scope: thisNameDoesNotExist
2022-08-22T13:41:09.8075066Z   |
2022-08-22T13:41:09.8075443Z 1 | main = thisNameDoesNotExist
2022-08-22T13:41:09.8075680Z   |        ^^^^^^^^^^^^^^^^^^^^
2022-08-22T13:41:24.6900541Z 
2022-08-22T13:41:24.6928686Z P.hs:4:5: error:
2022-08-22T13:41:24.6957177Z ##[error]    Variable not in scope: this_is_not_expected_to_compile :: Int
2022-08-22T13:41:24.6968223Z   |
2022-08-22T13:41:24.6968691Z 4 | p = this_is_not_expected_to_compile
2022-08-22T13:41:24.6968952Z   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2022-08-22T13:41:27.8968239Z 
2022-08-22T13:41:27.8990740Z P.hs:4:5: error:
2022-08-22T13:41:27.8992090Z ##[error]    Variable not in scope: this_is_not_expected_to_compile :: Int
2022-08-22T13:41:27.8992957Z   |
2022-08-22T13:41:27.8993344Z 4 | p = this_is_not_expected_to_compile
2022-08-22T13:41:27.8993685Z   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2022-08-22T13:41:37.6667032Z 
2022-08-22T13:41:37.6670365Z Q.hs:3:1: error:
2022-08-22T13:41:37.6672015Z ##[error]    Could not load module ‘P’
2022-08-22T13:41:37.6677914Z     It is a member of the hidden package ‘p-0.1’.
2022-08-22T13:41:37.6679288Z     Perhaps you need to add ‘p’ to the build-depends in your .cabal file.
2022-08-22T13:41:37.6680249Z     It is a member of the hidden package ‘p-0.1’.
2022-08-22T13:41:37.6680990Z     Perhaps you need to add ‘p’ to the build-depends in your .cabal file.
2022-08-22T13:41:37.6681451Z     Use -v (or `:set -v` in ghci) to see a list of the files searched for.
2022-08-22T13:41:37.6681684Z   |
2022-08-22T13:41:37.6681864Z 3 | import P
2022-08-22T13:41:37.6682047Z   | ^^^^^^^^
2022-08-22T13:41:49.4512830Z 
2022-08-22T13:41:49.4535576Z All 31 tests passed (129.89s)
2022-08-22T13:41:49.4817071Z [0;32m<<< **/integration-tests2 -j1 --hide-successes --with-ghc=ghc [0m (130/321 sec)
2022-08-22T13:41:49.4817596Z 
2022-08-22T13:41:49.4853596Z ##[group]Run sh validate.sh $FLAGS -s cli-suite
2022-08-22T13:41:49.4854431Z [36;1msh validate.sh $FLAGS -s cli-suite[0m
2022-08-22T13:41:49.4916107Z shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
2022-08-22T13:41:49.4916326Z env:
2022-08-22T13:41:49.4916512Z   GHC_FOR_RELEASE: 9.2.3
2022-08-22T13:41:49.4916825Z   GHC_FOR_SOLVER_BENCHMARKS: 9.2.3
2022-08-22T13:41:49.4917054Z   GHC_FOR_COMPLETE_HACKAGE_TESTS: 9.2.3
2022-08-22T13:41:49.4917273Z   COMMON_FLAGS: -j 2 -v
2022-08-22T13:41:49.4917458Z   FLAGS: -j 2 -v
2022-08-22T13:41:49.4917642Z ##[endgroup]
2022-08-22T13:41:49.5506766Z [0;96m=== cabal-install: cabal-testsuite ============================= 13:41:49 ===[0m
```

The `##[error]` markup seems to be involved. No idea where it comes from, it doesn't seem to be as simple as any `error:` or just stderr output causing this, compare the `thisNameDoesNotExist` line which doesn't cause an annotation.

### PR DESCRIPTION
**Pull request by mpickering**
This fixes a problem where test output was leaking into GitHub Actions results (#8419), making the output unnecessarily verbose and harder to read.

This makes the test output much cleaner while still preserving all the diagnostic information when tests fail.

Fixes #8419

Please read [Github PR Conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions) and then fill in *one* of these two templates.

---

**Template Α: This PR modifies [behaviour or interface](https://github.com/cabalism/cabal/blob/master/CONTRIBUTING.md#changelog)**

Include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
  * [ ] [Is the change significant?](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#is-my-change-significant) If so, remember to add `significance: significant` in the changelog file.
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [ ] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

---

**Template B: This PR does not modify behaviour or interface**

*E.g. the PR only touches documentation or tests, does refactorings, etc.*

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).

### CODE REVIEW

File: cabal-install/tests/IntegrationTests2.hs [hunk 1]
```diff
@@ -118,6 +123,23 @@ main = do
           (tests config)
     )
 
+-- Tests are run silently, unless they fail. Firstly because it is annoying to
+-- see lots of stderr from your unit tests. Secondly becaus this output
```
Comment (Bodigrim) [inline cabal-install/tests/IntegrationTests2.hs:127]:
```suggestion
-- see lots of stderr from your unit tests. Secondly because this output
```

File: cabal-install/tests/IntegrationTests2.hs [hunk 2]
```diff
@@ -118,6 +123,23 @@ main = do
...
+-- leaks into the result of github actions (#8419)
+silentTest :: TestTree -> TestTree
+silentTest = wrapTest silentHelper
```
Comment (Bodigrim) [inline cabal-install/tests/IntegrationTests2.hs:130]: Note that `wrapTest` does quite a few things internally. Another possibility (and not incurring a dependency on `tasty-expected-failure`) would be something like 
```haskell
newtype SilentTest a = SilentTest a 

instance IsTest a => IsTest (SilentTest a) where 
  run opts (SilentTest t) yieldProgress = do 
    (out, res) <- hCapture [stderr] (run opts t yieldProgress)
    let res' = if resultSuccessful res then res else res { resultDetailsPrinter = \indent printer -> printer $ map (replicate indent ' ' ++) (lines out) }
    pure res' 
```

File: cabal-install/tests/IntegrationTests2.hs [hunk 3]
```diff
@@ -118,6 +123,23 @@ main = do
...
+  where
+    silentHelper t = do
+      (out, res) <- hCapture [stderr] t
```
Comment (Bodigrim) [inline cabal-install/tests/IntegrationTests2.hs:133]: Could this capture `stderr` from other tests executed concurrently? Not a big deal obviously, but might be worth to add a comment or enforce single-threaded execution (if not enforced already).

File: cabal-install/tests/IntegrationTests2.hs (hunk 1 above)
Comment (mpickering) [reply cabal-install/tests/IntegrationTests2.hs:127]: Thanks.

File: cabal-install/tests/IntegrationTests2.hs (hunk 2 above)
Comment (mpickering) [reply cabal-install/tests/IntegrationTests2.hs:130]: I think I prefer to use `wrapTest`, since it is higher level, and other parts of the testsuite already depend on `tasty-expected-failure`. 

It's a very useful suggestion though, I didn't realise how simple it would have been to roll my own solution.

File: cabal-install/tests/IntegrationTests2.hs (hunk 3 above)
Comment (mpickering) [reply cabal-install/tests/IntegrationTests2.hs:133]: A good point, I tested with `-j8` without this patch and some tests fail anyway, so I will force this testsuite to run sequentially.

File: cabal-install/cabal-install.cabal [hunk 4]
```diff
@@ -425,6 +425,8 @@ test-suite integration-tests2
     , process
     , tasty >= 1.2.3 && <1.6
```
Comment (Bodigrim) [inline cabal-install/cabal-install.cabal:426]: `sequentialTestGroup` is only available since `tasty-1.5`
```suggestion
    , tasty >= 1.5 && <1.6
```

File: cabal-install/tests/IntegrationTests2.hs [hunk 5]
```diff
@@ -113,22 +118,42 @@ main = do
   defaultMainWithIngredients
     (defaultIngredients ++ [includingOptions projectConfigOptionDescriptions])
     ( withProjectConfig $ \config ->
-        testGroup
+        sequentialTestGroup
```
Comment (Bodigrim) [inline cabal-install/tests/IntegrationTests2.hs:121]: `tasty` story for sequential execution is admittedly finicky. If we want to run entire test suite in a single thread, I'd rather slap `defaultMain $ localOption (NumThreads 1) $ ...` on the very top level.

**Comment by ulysses4ever** [comment]
No updates for two weeks: just a gentle ping @mpickering! I know it's low priority but it'd be nice to get it done, and it's really close now. As usual, feel free to signal that you'd like someone else to pick it up.

@Bodigrim do you want to resolve your comments that were addressed?

**Comment by Bodigrim** [comment]
Sure, I resolved comments which were addressed. The remaining two are suggestions, but not blockers, up to you.

File: cabal-install/tests/IntegrationTests2.hs (hunk 5 above)
Comment (mpickering) [reply cabal-install/tests/IntegrationTests2.hs:121]: I will add that as well as a fail-safe but it does seem more declarative to specify that the tests have to run sequentially.

**Comment by mpickering** [comment]
I have resolved @Bodigrim's comments now.

**Review by Bodigrim — APPROVED** [review]

**Review by geekosaur — APPROVED** [review]

**Comment by ulysses4ever** [comment]
@mergify rebase

**Comment by ulysses4ever** [comment]
@mergify requeue

**Comment by ulysses4ever** [comment]
Seemed like a transient Windows failure, so I tried to restart.
