### PR TITLE
Fixing `cabal init` file output for `cabal-version < 2.2`

### LINKED ISSUE #7946: `cabal init` used with `cabal-version: 1.24` writes invalid  `.cabal` file (license id, caret operator)
I noticed if I run `cabal init` and then selecting:
- cabal-version 1.24
- license: BSD3

the generated `.cabal` file will have `license: BSD-3-Clause` which is not supported by version 1.24 of the cabal file language.

This leads to errors like the following:
```
$ cabal check
...
Warning: 'license: BSD-3' is not a recognised license. The known licenses are:
GPL, GPL-2, GPL-3, LGPL, LGPL-2.1, LGPL-3, AGPL, AGPL-3, BSD2, BSD3, MIT, ISC,
MPL-2.0, Apache, Apache-2.0, PublicDomain, AllRightsReserved, OtherLicense
....
Warning: bla-bla.cabal:6:33: version with tags
```
The latter seems to point to a parse error:
```
bla-bla.cabal:6:33: warning:
version with tags

    3 | version:            0.1.0.0
    4 | -- synopsis:
    5 | -- description:
    6 | license:            BSD-3-Clause
```
This is a weird parser bug in 1.24:  The `-Clause` seems to be attached to the version `0.1.0.0`...

UPDATE: also affects cabal-version 2.0

ATTN: @ptkato

### LINKED ISSUE #7947: `cabal init` should include `build-type: Simple` in the generated `.cabal` file
Atm, I cannot `cabal run` the default executable generated by `cabal init`, as the field `build-type` is not initialized.
The error I get on `cabal run` could be a bit cryptic for newcomers:
```
Errors encountered when parsing cabal file ./foo-bar.cabal:

foo-bar.cabal:0:0: error:
Since cabal-version: 1.24 specifying custom-setup section is mandatory
```
This is actually not even true, `build-type: Simple` does the job as well.

ATTN @ptkato

### PR DESCRIPTION
**Pull request by ptkato**
This PR aims to fix three buggy behaviours within the `cabal init` file output:
* the versions in the `build-depends` field should not use the caret style constraint for major bound versions if `cabal-version < 2.0`
* the license prompt, for the `License` field, should present legacy or SPDX license options depending on the cabal version picked previously
* for `cabal-version < 2.2`, the field `build-type` must be set

Fixes #7946 and fixes #7947.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

### CODE REVIEW

**Comment by Mikolaj** [comment]
@ptkato: should we merge @sekunho's #7942 before this PR or after or never?

**Comment by ptkato** [comment]
I dunno, I don't think they affect each other at all. I still have the extra tests to add onto this, so no need to hurry regardless.

**Comment by andreasabel** [comment]
@mergiofy rebase

**Comment by Mikolaj** [comment]
@mergifyio rebase

File: cabal-install/src/Distribution/Client/Init/Format.hs [hunk 1]
```diff
@@ -328,7 +329,9 @@ mkPkgDescription opts pkgDesc =
       False
       opts
 
-    , field  "license" pretty (_pkgLicense pkgDesc)
+    , (if _pkgCabalVersion pkgDesc < CabalSpecV2_2
+        then field "license" pretty (licenseFromSPDX $ _pkgLicense pkgDesc)
```
Comment (phadej) [inline cabal-install/src/Distribution/Client/Init/Format.hs:333]: There is `prettyVersioned`

Comment (phadej) [reply cabal-install/src/Distribution/Client/Init/Format.hs:333]: And https://hackage.haskell.org/package/Cabal-3.6.2.0/docs/Distribution-FieldGrammar-Newtypes.html#t:SpecLicense

**Comment by andreasabel** [comment]
@Mikolaj wrote:
> @Mergifyio rebase

Haha, I am a bad sorcerer's apprentice.

**Review by andreasabel — CHANGES_REQUESTED** [review]
I tested this PR and it fixed the OP.
However, when I select `4) Test suite` instead of `2) Executable` the problem still remains for the caret syntax:
```
testsuite-one-dot-twenty-four.cabal:74:39: error:
unexpected major bounded version syntax (caret, ^>=) used. To use this syntax the package need to specify at least 'cabal-version: 2.0'. Alternatively, if broader compatibility is important then use: >=4.16.0.0 && <4.17
expecting "." or "-"

   71 |     main-is:          Main.hs
   72 | 
   73 |     -- Test dependencies.
   74 |     build-depends:    base ^>=4.16.0.0
```
Maybe there is some refactoring to be done so that this works uniformly?

**Comment by phadej** [comment]
> Maybe there is some refactoring to be done so that this works uniformly?

`prettyVersioned` would help, but  not with caret syntax as is, as pre-2.2 there simply shouldn't be carets. Although the `prettyVersioned` of `VersionRange` could do the transformations then. (It doesn't currently, as that is not needed for roundtrip properties e.g.)

**Comment by ptkato** [comment]
> when I select `4) Test suite` instead of `2) Executable` the problem still remains for the caret syntax

Aye, I was using the wrong set of flags for the test portion of `cabal init`, it is working as intended now.

File: cabal-install/src/Distribution/Client/Init/Format.hs (hunk 1 above)
Comment (ptkato) [reply cabal-install/src/Distribution/Client/Init/Format.hs:333]: I'll take a look into it.

**Comment by ptkato** [comment]
> as pre-2.2 there simply shouldn't be carets

You meant pre-2.0, yes? According to the cabal file format changelog, that's when carets were introduced. Also, it seems that the `prettyVersioned` for `VersionRange` outputs carets for `cabal-version > 1.6`, that seems wrong.

**Comment by phadej** [comment]
`cabal-version: 1.6` split is for

```haskell
-- | Don't use && and || operators. If possible.
```

**Review by gbaz — APPROVED** [review]

**Comment by jneira** [comment]
@ptkato: was @andreasabel request fullfilled? or is it sensible it it is not?

**Comment by jneira** [comment]
@Mergifyio rebase master

**Comment by Kleidukos** [comment]
@andreasabel I see you haven't approved of the changes after your review. Is it still the case?

**Comment by jneira** [comment]
I've built this pr and test manually @andreasabel failing case and worked:

<details> <summary> console log init tests with cabal spec 1.24 </summary>

```
D:\ws\haskell\issues\init>cabal init
What does the package build:
   1) Library
 * 2) Executable
   3) Library and Executable
   4) Test suite
Your choice? [default: Executable] 4
Please choose version of the Cabal specification to use:
   1) 1.24  (legacy)
   2) 2.0   (+ support for Backpack, internal sub-libs, '^>=' operator)
   3) 2.2   (+ support for 'common', 'elif', redundant commas, SPDX)
   4) 2.4   (+ support for '**' globbing)
 * 5) 3.0   (+ set notation for ==, common stanzas in ifs, more redundant commas
, better pkgconfig-depends)
   6) 3.4   (+ support for 'pkg:sublib' syntax, active repo configuration, rich
index-state syntax)
Your choice? [default: 3.0] 1
Package name? [default: init]
Package version? [default: 0.1.0.0]
Please choose a license:
   1) GPL
   2) GPL-2
   3) GPL-3
   4) LGPL
   5) LGPL-2.1
   6) LGPL-3
   7) AGPL
   8) AGPL-3
   9) BSD2
  10) BSD3
  11) MIT
  12) ISC
  13) MPL-2.0
  14) Apache
  15) Apache-2.0
  16) PublicDomain
  17) AllRightsReserved
  18) OtherLicense
  19) Other (specify)
Your choice?
Empty input is not a valid choice.
Your choice? 10
Author name? [optional] jneira
Maintainer email? [optional]
Project homepage URL? [optional]
Project synopsis? [optional]
Project category:
   1) Codec
   2) Concurrency
   3) Control
   4) Data
   5) Database
   6) Development
   7) Distribution
   8) Game
   9) Graphics
  10) Language
  11) Math
  12) Network
  13) Sound
  14) System
  15) Testing
  16) Text
  17) Web
  18) Other (specify)
Your choice? [default: (none)]
What is the main module of the test suite?:
 * 1) Main.hs
   2) Main.lhs
   3) Other (specify)
Your choice? [default: Main.hs]
Test directory? [default: test]
Choose a language for your test suite:
 * 1) Haskell2010
   2) Haskell98
   3) Other (specify)
Your choice? [default: Haskell2010]
Add informative comments to each field in the cabal file. (y/n)? [default: y]

Log: Using cabal specification: 1.24

Log: Creating LICENSE...

Log: Creating fresh file LICENSE...

Log: Creating CHANGELOG.md...

Log: Creating fresh file CHANGELOG.md...

Log: Creating fresh directory ./test...

Log: Creating fresh file test\Main.hs...

Log: Creating fresh file init.cabal...

Warning: no synopsis given. You should edit the .cabal file and add one.

Info: You may want to edit the .cabal file and add a Description field.

D:\ws\haskell\issues\init>cabal check
Warning: These warnings may cause trouble when distributing the package:
Warning: No 'category' field.
Warning: No 'maintainer' field.
Warning: The following errors will cause portability problems on other
environments:
Warning: No 'synopsis' or 'description' field.
Warning: Hackage would reject this package.

D:\ws\haskell\issues\init>cabal build --enable-tests
Resolving dependencies...
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - init-0.1.0.0 (test:init-test) (first run)
Configuring test suite 'init-test' for init-0.1.0.0..
Preprocessing test suite 'init-test' for init-0.1.0.0..
Building test suite 'init-test' for init-0.1.0.0..
[1 of 1] Compiling Main             ( test\Main.hs, D:\ws\haskell\issues\init\di
st-newstyle\build\x86_64-windows\ghc-8.6.5\init-0.1.0.0\t\init-test\build\init-t
est\init-test-tmp\Main.o )
Linking D:\ws\haskell\issues\init\dist-newstyle\build\x86_64-windows\ghc-8.6.5\i
nit-0.1.0.0\t\init-test\build\init-test\init-test.exe ...
``` 

</details>

**Review by jneira — APPROVED** [review]
thanks for fixing init and the tests :100:
