### PR TITLE
cabal update: don't show comment with builddir in the default config

### LINKED ISSUE #11050: Cabal incorrectly adds `-- builddir:` to default configuration file
The user configuration file installed by `cabal update` when no configuration file exists contains the commented-out hint `-- builddir:`, implying that this can be used in that configuration file. It cannot, and thus this comment should not be in the default file that is installed.

Reproduce with:
```
$ rm -rf ~/.cabal/ ~/.config/cabal/config
$ cabal-3.14.2.0 update        # latest version installed with GHCup
Config file path source is default config file.
Config file not found: /home/cjs/.config/cabal/config
Writing default configuration to /home/cjs/.config/cabal/config
...
$ grep builddir ~/.config/cabal/config 
-- builddir:

#   Confirm that Cabal doesn't accept 'builddir:' in this config file.
$ echo 'builddir: ./.cabal/' >> ~/.config/cabal/config
$ cabal update
Warning: The builddir option is not supported in project and config files. It
will be ignored.
...
```

### PR DESCRIPTION
**Pull request by ulysses4ever**
When calling `cabal update` with an empty state (empty CABAL_DIR or new machine), cabal writes out a default config file with many fields commented out to show their defaults. This suggests that the user can uncomment the field and override the default. This is wrong for fields that aren't allowed in the config file like `builddir`. This patch avoids generating a comment with `builddir` in the default config.

Fix #11050. 

## Manual QA Notes

```shellsession
❯ cabal build cabal
❯ c=$(cabal list-bin cabal)
❯ CABAL_DIR=$PWD/cabal-dir-testing $c update
❯ grep builddir ./cabal-dir-testing/config
❯ 
```

---

**Template Α: This PR modifies [behaviour or interface](https://github.com/cabalism/cabal/blob/master/CONTRIBUTING.md#changelog)**

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
  * [x] [Is the change significant?](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#is-my-change-significant) If so, remember to add `significance: significant` in the changelog file.
* [x] The documentation has been updated, if necessary.
* [x] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [ ] Tests have been added. — no harness currently to assert absence of certain lines in config.

### CODE REVIEW

File: cabal-install/src/Distribution/Client/Config.hs [hunk 1]
```diff
@@ -1784,7 +1784,7 @@ showConfigWithComments comment vals =
 
     -- skip fields based on field name.  currently only skips "remote-repo",
     -- because that is rendered as a section.  (see 'ppRemoteRepoSection'.)
```
Comment (sheaf) [inline cabal-install/src/Distribution/Client/Config.hs]: Seems like the comment should be updated as well.

Comment (ulysses4ever) [reply cabal-install/src/Distribution/Client/Config.hs]: oh, good catch!

**Review by geekosaur — APPROVED** [review]
(assuming the next push fixes the comment)

**Comment by geekosaur** [comment]
Oh, whoops, there's a test that checks these (which IIRC you already pointed out to someone else?).

**Comment by ulysses4ever** [comment]
does anyone get why CI fails?

**Comment by geekosaur** [comment]
https://github.com/haskell/cabal/actions/runs/16221656912/job/45803418293?pr=11067#step:17:2585

File: cabal-install/src/Distribution/Client/Config.hs (hunk 1 above)
Comment (ulysses4ever) [reply cabal-install/src/Distribution/Client/Config.hs]: Addressed.

**Comment by ulysses4ever** [comment]
Added changelog and manual QA notes in the PR description.
