### PR TITLE
Only reregister inplace package if we built it.

### LINKED ISSUE #3916: new-repl sometimes fails in mysterious ways
So I did this:

```
$ cabal get bloodhound
$ cd bloodhound-0.11.1.0 
$ cabal new-repl
```

And I got this result:

```
Resolving dependencies...
In order, the following will be built (use -v for more details):
 - bloodhound-0.11.1.0 (first run)
[1 of 1] Compiling Main             ( /home/refold/code/scrive/bloodhound-0.11.1.0/dist-newstyle/build/x86_64-linux/ghc-8.0.1.20160919/bloodhound-0.11.1.0/setup/setup.hs, /home/refold/code/scrive/bloodhound-0.11.1.0/dist-newstyle/build/x86_64-linux/ghc-8.0.1.20160919/bloodhound-0.11.1.0/setup/Main.o )
Linking /home/refold/code/scrive/bloodhound-0.11.1.0/dist-newstyle/build/x86_64-linux/ghc-8.0.1.20160919/bloodhound-0.11.1.0/setup/setup ...
Configuring bloodhound-0.11.1.0...
setup: '/opt/ghc/8.0.2/bin/ghc' exited with an error:
<command line>: Failed to load interface for ‘Database.Bloodhound’
It is a member of the hidden package ‘bloodhound-0.11.1.0’.
Perhaps you need to add ‘bloodhound’ to the build-depends in your .cabal file.
It is a member of the hidden package ‘bloodhound-0.11.0.0’.
Perhaps you need to add ‘bloodhound’ to the build-depends in your .cabal file.
Use -v to see a list of the files searched for.
cabal: Failed to build bloodhound-0.11.1.0. The failure occurred during the
final install step.
```
I tried changing the `build-type` to `Simple` in `bloodhound.cabal`, but that didn't help either:
```
$ cabal new-repl        
Resolving dependencies...
In order, the following will be built (use -v for more details):
 - bloodhound-0.11.1.0 (lib) (first run)
Configuring component lib from bloodhound-0.11.1.0
cabal: '/opt/ghc/8.0.2/bin/ghc' exited with an error:
<command line>: Failed to load interface for ‘Database.Bloodhound’
Use -v to see a list of the files searched for.
cabal: Failed to build bloodhound-0.11.1.0. The failure occurred during the
final install step.
```
`new-build` seems to work, however, as well as `new-repl` on packages that depend on `bloodhound` (e.g. `log`).

**edit:**  I'm not sure what I did, but the issue has now disappeared. Maybe the package DB was in an inconsistent state and running `new-repl` and/or `new-build` on `log` fixed it. Leaving this open for now as a FYI for @dcoutts.

### PR DESCRIPTION
**Pull request by ezyang**
Fixes #3916.

Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>

### CODE REVIEW

File: cabal-install/Distribution/Client/ProjectBuilding.hs [hunk 1]
```diff
@@ -1133,10 +1133,11 @@ buildInplaceUnpackedPackage verbosity
...
       | otherwise            = return ()
 
-    whenReRegister  action = case buildStatus of
-      BuildStatusConfigure          _ -> action
-      BuildStatusBuild Nothing      _ -> action
-      BuildStatusBuild (Just mipkg) _ -> return mipkg
+    whenReRegister  action
+      = case buildStatus of
+          BuildStatusBuild (Just mipkg) _ -> return mipkg
+          _ | null (elabBuildTargets pkg) -> return Nothing -- ick
```
Comment (dcoutts) [inline cabal-install/Distribution/Client/ProjectBuilding.hs]: Yeah, this line highlights the difficulty. Consider the case of

     BuildStatusBuild Nothing _
      | null (elabBuildTargets pkg) -> ...

So in this case there's no previous registration and normally we'd try and register, but because we're not doing a full build for this component then actually we still don't want to register. But there's no way to represent this because the Nothing result here means that the thing is an executable with no registration, not that we're skipping the registration phase.

Now I had previously expected that we'd solve this problem by adjusting the planning phase to say that registration is not required, i.e. `elabRequiresRegistration = False`, but now I see that's going to have the same issue as above, and would cause problems for keeping track of whether we did register or not if we do `cabal repl; cabal build`.

I think either way the solution is going to have to involve extending the BuildResult's buildResultLibInfo so that it can properly represent the situation of not having registered yet, distinct from registration not needed for exes. 

We'll have the same issue once we support building only specific modules.

I've also been working on build status, and this feels related, so I'll have another think about it in that context.

Comment (ezyang) [inline cabal-install/Distribution/Client/ProjectBuilding.hs]: Well, I half wanted to just drop the recorded InstalledPackageInfo entirely; I couldn't figure out where it was being used. Adjusting it to have another case certainly seems like it could work; I wonder if there is something simpler.

Comment (dcoutts) [inline cabal-install/Distribution/Client/ProjectBuilding.hs]: You're right, it is no longer used, so it's not necessary to collect and return the `InstalledPackageInfo`.
