### PR TITLE
Split --repl-options on whitespace

### LINKED ISSUE #6190: --repl-options doesn’t split on whitespace
`--repl-options` doesn’t split its argument on whitespace the way e.g. `--ghc-options` does.

**To Reproduce**

Run `cabal v2-repl` with `--repl-options`:

```
cabal v2-repl --repl-options="-fwrite-interface -fobject-code"
```

**Expected behaviour**

I expected it to behave like `--ghc-options`, i.e. to pass `-fwrite-interface` and `-fobject-code` to ghc as separate options.

**Actual behaviour**

It actually passes them both as a single option, resulting in an error:

```
ghc: unrecognised flag: -fwrite-interface -fobject-code
```

**Workaround**

Passing multiple `--repl-options` arguments, one per GHC option, works:

```
cabal v2-repl --repl-options=-fwrite-interface --repl-options=-fobject-code
```

**System informataion**
 - macOS 10.14.6
- `cabal-install version 2.4.1.0`
- `compiled using version 2.4.1.0 of the Cabal library`
- `The Glorious Glasgow Haskell Compilation System, version 8.6.5`

### PR DESCRIPTION
**Pull request by kczulko**
Attempt to fix #6190

Function `words` used instead of cons operator which was just adding
full string value to an empty array.

I'm newbie here but is there any place with kind of CLI tests where I could capture this behavior?

For now I tested it manually and I think it works:
1. ~Negative scenario:
```bash
$ cabal-new v2-repl --repl-options="-fwrite-interface -fbyte-codeaa"
Build profile: -w ghc-8.10.7 -O1
In order, the following will be built (use -v for more details):
 - programming-in-haskell-0.1.0.0 (lib:chapters) (first run)
Preprocessing library 'chapters' for programming-in-haskell-0.1.0.0..
GHCi, version 8.10.7: https://www.haskell.org/ghc/  :? for help
ghc: unrecognised flag: -fbyte-codeaa
did you mean one of:
  -fbyte-code

Usage: For basic information, try the `--help' option.
Error: cabal: repl failed for lib:chapters from
programming-in-haskell-0.1.0.0.
```

2. Positive scenario:
```bash
$ cabal-new v2-repl --repl-options="-fwrite-interface -fbyte-code"
Build profile: -w ghc-8.10.7 -O1
In order, the following will be built (use -v for more details):
 - programming-in-haskell-0.1.0.0 (lib:chapters) (first run)
Preprocessing library 'chapters' for programming-in-haskell-0.1.0.0..
GHCi, version 8.10.7: https://www.haskell.org/ghc/  :? for help
Ok, 8 modules loaded.
Prelude Excs1>
```

Best regards,
Karol

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by Mikolaj** [comment]
The following show some `repl` tests:

    git grep -30 " repl$"
    git grep -30 "\"repl\""

**Comment by kczulko** [comment]
Hi there,

I added some tests and I think it's ready for review.

**Comment by Mikolaj** [comment]
Could you instead expect "ghc.exe: unrecognised flag: -fdiagnostics-show-baret" as an alternative to the version without ".exe"? Because that's the problem, right?

**Comment by Mikolaj** [comment]
Could you also add a short changelog file? Please look at closed PRs how it's done.

**Comment by kczulko** [comment]
@Mikolaj 

Changelog added (I think so).

Best regards,
Karol

File: Cabal/src/Distribution/Simple/Setup.hs [hunk 1]
```diff
@@ -1809,7 +1809,7 @@ replOptions _ =
   , option [] ["repl-options"]
     "use this option for the repl"
```
Comment (Mikolaj) [inline Cabal/src/Distribution/Simple/Setup.hs:1810]: Should this be "Use the option(s) for the repl"?

**Review by Mikolaj — APPROVED** [review]
Perfect. Thank you.

**Review by Kleidukos — APPROVED** [review]
LGTM

**Comment by Mikolaj** [comment]
@kczulko: once you rebase and fix conflicts, feel free to set "merge_me" label and it's go!

**Comment by kczulko** [comment]
Thx @Mikolaj ,

Will do but now I'm AFK for this weekend so probably Monday.

Best regards,
Karol

**Comment by Mikolaj** [comment]
No hurry at all. Thank you!
