### PR TITLE
Fix `v2-repl` changing directory incorrectly.

### LINKED ISSUE #5544: cabal new-repl outside the project cwd is /tmp/....
So I cannot `:l mySmallExample.hs` as easily

### PR DESCRIPTION
**Pull request by typedrat**
Fixes #5544.

--

Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.
* [x] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

File: cabal-install/Distribution/Client/CmdRepl.hs [hunk 1]
```diff
@@ -335,16 +338,21 @@ data OriginalComponentInfo = OriginalComponentInfo
   }
   deriving (Show)
 
-withProject :: ProjectConfig -> Verbosity -> [String] -> IO (ProjectBaseContext, [TargetSelector], IO ())
+data ReplType = ProjectRepl | GlobalRepl FilePath
```
Comment (phadej) [inline cabal-install/Distribution/Client/CmdRepl.hs]: please add some haddocks.

Is `GlobalRepl`'s `FilePath` argument intended working directory?

Comment (typedrat) [reply cabal-install/Distribution/Client/CmdRepl.hs]: Correct.

File: cabal-install/Distribution/Client/CmdRepl.hs [hunk 2]
```diff
@@ -335,16 +338,23 @@ data OriginalComponentInfo = OriginalComponentInfo
   }
   deriving (Show)
 
-withProject :: ProjectConfig -> Verbosity -> [String] -> IO (ProjectBaseContext, [TargetSelector], IO ())
+-- | Tracks what type of GHCi instance we're creating.
+data ReplType = ProjectRepl 
+              | GlobalRepl FilePath -- ^ The 'FilePath' argument is the correct CWD.
```
Comment (phadej) [inline cabal-install/Distribution/Client/CmdRepl.hs]: As I read more closely, that argument seems to be an argument to a `-ghci-script`.

File: cabal-install/Distribution/Client/CmdRepl.hs [hunk 3]
```diff
@@ -272,6 +272,9 @@ replAction (configFlags, configExFlags, installFlags, haddockFlags, testFlags, r
           replFlags' = case originalComponent of 
             Just oci -> generateReplFlags includeTransitive elaboratedPlan' oci
             Nothing  -> []
+          replFlags'' = case replType of
+            GlobalRepl scriptPath -> ("-ghci-script" ++ scriptPath) : replFlags'
```
Comment (phadej) [inline cabal-install/Distribution/Client/CmdRepl.hs]: this is funny. it seems it doesn't actually require a space in between. However:

```
% ghci-7.0.4 -ghci-script foo
GHCi, version 7.0.4: http://www.haskell.org/ghc/  :? for help
ghc: unrecognised flags: -ghci-script
Usage: For basic information, try the `--help' option.
```

```
% ghci-7.4.2 -ghci-script foo
GHCi, version 7.4.2: http://www.haskell.org/ghc/  :? for help
ghc: unrecognised flags: -ghci-script
Usage: For basic information, try the `--help' option.
```

```
% ghci-7.6.3 -ghci-script foo
GHCi, version 7.6.3: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
"foo"
```

So for pre-GHC-7.6 we need to do something else, or at least don't pass `-ghci-script`.

Comment (phadej) [reply cabal-install/Distribution/Client/CmdRepl.hs]: ref https://downloads.haskell.org/~ghc/7.6.1/docs/html/users_guide/release-7-6-1.html

> GHCi now supports loading additional `.ghci` files via the `-ghci-script` flag

Comment (phadej) [reply cabal-install/Distribution/Client/CmdRepl.hs]: And to clarify, I personally will be ok if out-of-project `cabal repl` will be somewhere not in CWD (due to limitations of old GHC) , but it shouldn't fail to load.

File: cabal-install/changelog [hunk 4]
```diff
@@ -1,6 +1,8 @@
 -*-change-log-*-
 
 3.0.0.0 (current development version)
+	* `v2-repl` no longer changes directory to a randomized temporary folder
```
Comment (phadej) [inline cabal-install/changelog]: Note: the 3.0 branch is cut, but this PR is against `master`.

@23Skidoo should we introduce "needs-backport-to-3.0" label to remember cherry-pick those?

Comment (typedrat) [reply cabal-install/changelog]: I missed that! Should this be backported, or should I just move the changelog entry?

I feel like the QoL gain is pretty big. 🙂

File: cabal-install/Distribution/Client/CmdRepl.hs (hunk 3 above)
Comment (typedrat) [reply cabal-install/Distribution/Client/CmdRepl.hs]: Added a check, now it just puts you in the wrong directory rather than failing on dinosauric GHCs. 🙂

File: cabal-install/changelog (hunk 4 above)
Comment (23Skidoo) [reply cabal-install/changelog]: @phadej We already have `attention: needs-backport`.

Comment (23Skidoo) [reply cabal-install/changelog]: @typedrat I can defo cherry-pick this one.

**Comment by 23Skidoo** [comment]
Cherry-picked to 3.0.
