### PR TITLE
Cabal Init Omnibus

### LINKED ISSUE #1074: cabal init / cabal check inconsistency in allowed licenses
`cabal init` allows me to specify a license that it does not recognize, by using option 11. However, `cabal check`, which is used by hackage, rejects an unrecognized field, such as ISC.

### LINKED ISSUE #6507: `cabal init` incorrectly writes non-ASCII file names in `library:exposed-modules`
**Describe the bug**
Consider a folder hierarchy that looks like

```
proglet/
|- Typeclass/
   |- Pokémon.hs
```

Running `cabal init --interactive` when the working directory is `proglet` generates the files necessary for `cabal v2-build`.

Running `cabal v2-build`, however, gives the unexpected error

```
Typeclass/Pokémon.hs:1:8: error:
    File name does not match module name:
    Saw: ‘Typeclass.Pokémon’
    Expected: ‘Typeclass.Pokémon’
  |
1 | module Typeclass.Pokémon where
  |        ^^^^^^^^^^^^^^^^^
```

**To Reproduce**
1. Create folder `proglet`
2. Create folder `proglet/Typeclass`
3. Create file `proglet/Typeclass/Pokémon.hs` with content

```
module Typeclass.Pokémon where

x = 1
```

4. Change the working directory to `proglet`
5. Run `cabal init --interactive` and complete the prompts this way
  - Don't generate a "simple project with sensible defaults"
  - Build a library
  - Use any version of the Cabal specification
  - Any package name of your choosing
  - Any package version
  - Any license
  - Any author name
  - Any email
  - Any project URL
  - Any synopsis
  - Any category
  - No source directory
  - No test suite
  - Haskell2010
  - No "informative comments"
6. Run `cabal v2-build` and observe the error

**Expected behavior**
I expected the build to succeed.

**System information**
- Operating system: macOS 10.14
- `cabal` version: 3.0.0.0
- `ghc` version: 8.6.5

**Additional context**
It seems that the "e with acute accent" under "Saw" is the UTF-8 character U+00E9, while the "e with acute accent" under "Expected" is a combination of the normal letter "e" (U+0065) and some acute accent character.

Since the "e with acute accent" under "Expected" corresponds to the contents of the `library:exposed-modules` section of the `.cabal` file, I checked `proglet.cabal` (I have removed the comment lines below).

```
cabal-version:       2.4

name:                proglet
version:             0.1.0.0
license:             BSD-3-Clause
license-file:        LICENSE
author:              Fyrbll
maintainer:          unnecessary
extra-source-files:  CHANGELOG.md

library
  exposed-modules:     Typeclass.Pokémon
  build-depends:       base ^>=4.12.0.0
  default-language:    Haskell2010
```

I changed `Typeclass.Pokémon` in the file above to `Typeclass.Pokémon`, where the latter actually uses U+00E9, and then `cabal build` worked painlessly.

### LINKED ISSUE #6758: knownCategories in Init.Heuristics are unused
Either they should be used or removed.

### LINKED ISSUE #6864: cabal init produces `extra-source-files: CHANGELOG.md`
**Describe the bug**
`CHANGELOG.md`(sic `ChangeLog.md`) (and `README.md`) should be listed as `extra-doc-files` not `extra-source-files` (see also #5813).

**To Reproduce**

```
$ cabal init --non-interactive
```

Please use version-prefixed commands (e.g. `v2-build` or `v1-build`) to avoid ambiguity.

**Expected behavior**
`extra-doc-files:  CHANGELOG.md`

**System information**
 - Operating system: Fedora
 - `cabal-3.2.0.0`, `ghc-8.6.5` versions

**Additional context**
`extra-source-files:  CHANGELOG.md` is put in .cabal file.

### LINKED ISSUE #7251: `cabal init --lib` puts build-tools(happy, alex) generated modules twice into exposed-modules
`cabal init` nicely auto-detects `build-tools` like `happy` and `alex`.  However, it puts their generated modules twice into `exposed-modules`, like:
```
library
  exposed-modules: Main, Foo.Print, Foo.Lex, Foo.Skel, Foo.Par, Foo.Lex, Foo.Test, Foo.Abs, Foo.ErrM, Foo.Par
```
Note that `Foo.Lex` and `Foo.Par` are listed twice each.

`cabal build` then fails with a confusing error message:
```
Error:
    Module name  Foo.Lex  is exported multiple times.
    In the stanza 'library'
    In the inplace package 'DuplicateModules-0.1.0.0'
```
That's hard to understand.  Took me a while, esp. since I didn't know where to look for the "inplace package".

I suppose a simple `nub` would solve this issue.  Anyway, the order in `exposed-modules` looks random, wouldn't it anyway be nicer in alphabetical order?  Then `Set.toList . Set.fromList` would do the job.

Tested `cabal` versions: 3.2.0.0 and 3.5.0.0.

Steps to reproduce (using BNFC to generate .x and .y files cheaply):
```
cabal install BNFC
echo "Foo. Bar ::= Integer" > Foo.cf
bnfc -dm Foo.cf
make
cabal init --lib
cabal build
```

Trivium: `hpack` had the very same problem: https://github.com/sol/hpack/issues/406

### LINKED ISSUE #7255: cabal init --lib creates MyLib.hs if Mylib.{something else} is present
**Describe the bug**

cabal init --lib creates MyLib.hs if Mylib.{something else} is present

**To Reproduce**

In an empty directory:
```
echo '> module MyLib where' > MyLib.lhs
cabal init --lib --source-dir .
cat MyLib.hs
```

**Expected behavior**

Since a module already exists, MyLib.hs does not get created

**System information**

cabal 3.2 and current master

### LINKED ISSUE #7256: `cabal init --libandexe` should add the `library` to the `build-depends` of the `executable`
cabal-3.5.0.0 seems to have no implicit `build-depends` of the `executable` on the `library` so `cabal init` should add this.

Here is a reproduction script (from https://github.com/haskell/cabal/pull/7253#issuecomment-765608772), __needs PR #7253__:
```
bnfc --version || cabal install BNFC
mkdir -p myparser
cd myparser
echo "Foo. Bar ::= Integer" > Foo.cf
bnfc -o src -d -m Foo.cf
make -C src
mv src/Foo/Test.hs Main.hs
cabal v2-init --libandexe --application-dir=.
cabal v2-build all
cat myparser.cabal
```

The `cabal build` fails with errors like
```
Main.hs:9:1: error:
    Could not load module ‘Foo.Lex’
    It is a member of the hidden package ‘myparser-0.1.0.0’.
    Perhaps you need to add ‘myparser’ to the build-depends in your .cabal file.
```

Manually adding `myparser` to the `build-depends` of the `executable` stanza fixes the problem.

Except for the warning now emitted by cabal which is obviously a lie:
```
Warning: The package has an extraneous version range for a dependency on an
internal library: myparser >=0 && ==0.1.0.0. This version range includes the
current package but isn't needed as the current package's library will always
be used.
```

**System information**
 - Operating system: macOS
 - `cabal`: development version (3.5.0.0)
 - `ghc` 8.10.3

### LINKED ISSUE #7273: Cabal init fails with 'no package name provided' if name is already taken on hackage
**Describe the bug**
When I do `cabal init` this doesn't prompt me for anything and just dies.

```
Guessing dependencies...

Generating LICENSE...
Warning: unknown license type, you must put a copy in LICENSE yourself.
Generating Setup.hs...
Generating CHANGELOG.md...
Generating Main.hs...
Error: no package name provided.
```

explicitly specifying interactive mode gets:

```
Should I generate a simple project with sensible defaults? [default: y] y

Guessing dependencies...

Generating LICENSE...
Warning: unknown license type, you must put a copy in LICENSE yourself.
Generating Setup.hs...
Warning: Setup.hs already exists, backing up old version in Setup.hs.save0
Generating CHANGELOG.md...
Warning: CHANGELOG.md already exists, backing up old version in CHANGELOG.md.save0
Error: no package name provided.
```

and the cabal file is never created. Only

```
CHANGELOG.md  Main.hs  Setup.hs
```

**To Reproduce**

```
$ cabal init
```

Please use version-prefixed commands (e.g. `v2-build` or `v1-build`) to avoid ambiguity.

**Expected behavior**

**System information**
 - Operating system: Windows 10 (bash or powershell)
 - `cabal`, `ghc` versions: `3.2.0.0` and `8.8.4`

**Additional context**

### PR DESCRIPTION
**Pull request by emilypi**
---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

## New additions

This PR does the following: 

- Completely rewrites the `cabal init` command to have a saner structure that can be tested easily. 
- Optimizing for individual component target generation allows us to golden test individual stanzas under various scenarios instead of just whole cabal files
- Coverage reports may now be generated for every component of the command. Coverage works for the whole project now, full stop. 
- Control flow for interactive vs. non-interactive vs. simple target generation is completely decoupled.
- Cleans up the file creation spaghetti, and prunes unused or redundant behavior wherever it arises. 
- Rewrites the prompt code to be less unnecessarily typed (strings are fine!)

This comes with bugfixes: 
 
- [x] Fixes #7273 
- [x] Fixes #7253 
- [x] Fixes #7256 
- [x] Fixes #7255  
- [x] Fixes #7251
- [x] Fixes #6758 
- [x] Fixes #6864 
- [x] Fixes #1074

### CODE REVIEW

File: Cabal/src/Distribution/Fields/Pretty.hs [hunk 1]
```diff
@@ -35,6 +35,7 @@ import qualified Text.PrettyPrint as PP
 data PrettyField ann
     = PrettyField ann FieldName PP.Doc
     | PrettySection ann FieldName [PP.Doc] [PrettyField ann]
+    | PrettyEmpty
```
Comment (phadej) [inline Cabal/src/Distribution/Fields/Pretty.hs:38]: Why this change?

**Comment by phadej** [comment]
Why bundle coverage changes and cabal init changes? Are they related? I don't see how.

File: cabal-install/cabal-install.cabal [hunk 2]
```diff
@@ -20,60 +17,38 @@ Copyright:          2003-2020, Cabal Development Team
...
-    hs-source-dirs: main
-    default-language: Haskell2010
-    ghc-options:    -Wall -fwarn-tabs -fwarn-incomplete-uni-patterns -fwarn-incomplete-record-updates
-    if impl(ghc >= 8.0)
-        ghc-options: -Wcompat
-                     -Wnoncanonical-monad-instances
-      if impl(ghc < 8.8)
-        ghc-options: -Wnoncanonical-monadfail-instances
 
+library
```
Comment (phadej) [inline cabal-install/cabal-install.cabal:42]: There are relevant issues, like
- https://github.com/haskell/cabal/issues/6090
- https://github.com/haskell/cabal/issues/7224
- https://github.com/haskell/cabal/issues/3781

Is this trying to address them?

**Comment by phadej** [comment]
I don't like how this contains at least three separate changes in one PR. I hope this is just a draft.

File: cabal-install/cabal-install.cabal (hunk 2 above)
Comment (emilypi) [reply cabal-install/cabal-install.cabal:42]: This is actually in service of coverage reporting, but if it fixes them, great.

**Comment by emilypi** [comment]
@phadej it's clearly marked a draft. I'll split it out into several PRs if that makes you less uneasy.

File: Cabal/src/Distribution/Fields/Pretty.hs (hunk 1 above)
Comment (phadej) [reply Cabal/src/Distribution/Fields/Pretty.hs:38]: I'd suggesting trying whether using `Maybe (PrettyField ann)` and collecting `[Maybe (PrettyField ann)]` and `catMaybes` that into sections.

Another option is to have

```haskell
    | PrettyEmpty ann
```

so 

```haskell
prettyFieldAnn :: PrettyField ann -> ann
```

is definable. I.e. every constructor of `PrettyField` can be annotated.

(There is such function for parser `Field`: https://hackage.haskell.org/package/Cabal-3.4.0.0/docs/Distribution-Fields-Field.html#v:fieldAnn)

Comment (emilypi) [reply Cabal/src/Distribution/Fields/Pretty.hs:38]: I like the `PrettyEmpty ann` suggestion. The use of `Maybe` here is what i'm trying to avoid, since we must accept `Maybe` returns and the use of `catMaybes` in every bit of code that interfaces with the formatter, when it's such a small and useful addition to just add directly in the printer.

Comment (emilypi) [reply Cabal/src/Distribution/Fields/Pretty.hs:39]: it occurred to me that we can still write `prettyFieldAnn`, we just have to choose a sensible annotation default. That is, we would not have `PrettyField ann -> ann`, but rather 

```haskell
prettyFieldAnn :: Default ann => PrettyField ann -> ann
```

Or `Monoid ann` which could provide a mempty in the case of the printer. Just adding that case for `PrettyEmpty` traded in 20 lines of code in 3 modules for 3 lines of code in 1 module, and I have less finicky data prep to be concerned with in the stanza creation. I'm inclined to keep it as-is.

**Comment by emilypi** [comment]
@fgaz just so @ptkato and I can parallelize a bit, how do you want to split this PR up into reviewable chunks?

**Comment by fgaz** [comment]
At the commit level, ideally the smallest chunks that make sense (and build) on their own. At the pr level, strongly related changes can be on the same pr. Or not. So something like this, following OP:

* PR: infrastructure stuff (should probably be a single pr since most of the stuff depends on the previous)
  * commit: Expose modules as part of a cabal-install library
  * commit: Gets rid of the dogfooding framework...
  * commit: generate coverage reports
  * commit: Move cabal-install-solver out to its own directory.
  * commit: Move all long-running tests to their own test target
* PR: fix for HPC generation (or was this the pr that just got merged?)
* PR: init stuff
  * no idea if this can be split. probably not?

**Comment by emilypi** [comment]
> fix for HPC generation (or was this the pr that just got merged?)

Yes, i depended on his PR to get us multiproject support and generate coverage for the tests we're writing in this PR. 

> PR: infrastructure stuff (should probably be a single pr since most of the stuff depends on the previous)

Okay so piggy-backing on those suggestions, in terms of a timeline, i think this sequence is the one we need:

1.  Expose `cabal-install` library + remove dogfooding (these are dependent upon each other for testing)
2.  Split out the `cabal-install-solver` package
3.  Split tests out into unit-tests and long-running test targets (prerequisite)
4.  Change to the `cabal.project` setup for coverage generation 
5. Init work

File: cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-and-exe-with-comments.golden [hunk 3]
```diff
@@ -80,31 +76,36 @@ executable foo
...
     -- The entrypoint to the test suite.
-    main-is:          MyLibTest.hs
+    main-is:          Main.hs
 
     -- Test dependencies.
     build-depends:
-        base ^>=4.13.0.0,
-        containers ^>=5.7.0.0,
-        unordered-containers ^>=2.7.0.0
+        base,
```
Comment (emilypi) [inline cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-and-exe-with-comments.golden:109]: FYI, these `base` dependencies are artificially mangled so that we can check that the golden files are generated homogeneously across GHC versions. There are other unit tests that cover the correctness of the `base` dependency version inferrance, and the user will see `base ^>=4.14.0.0` etc. in practice. 

As they are, the original golden files are actually _incorrect_ for any GHC < 8.8 in more ways than one: note the version commentary generated above. It's off by 1!

File: cabal-install/src/Distribution/Client/Init/Interactive/Command.hs [hunk 4]
```diff
@@ -69,11 +70,12 @@ import Language.Haskell.Extension (Language(..))
 createProject
     :: Interactive m
     => Verbosity
+    -> Compiler
     -> InstalledPackageIndex
     -> SourcePackageDb
     -> InitFlags
     -> m ProjectSettings
-createProject v pkgIx srcDb initFlags = do
+createProject v _comp pkgIx srcDb initFlags = do
```
Comment (emilypi) [inline cabal-install/src/Distribution/Client/Init/Interactive/Command.hs:78]: This is unused in 2 cases (interactive + simple). I'd just configure `NonInteractive.createProject` to take the compiler arg first and then return `NonInteractive.createProject comp` as the function returned in the where clause.

File: tests/fixtures/init/golden/pkg-desc/pkg-with-comments.golden [hunk 5]
```diff
@@ -0,0 +1,46 @@
...
+-- An email address to which users can send suggestions, bug reports, and patches.
+maintainer:         foo-kmett@kmett.kmett
+
+-- A copyright notice.
+-- copyright:
+category:           Data
+build-type:         Simple
+
+-- Extra files to be distributed with the package, such as examples or a README.
+extra-source-files: CHANGELOG.md
```
Comment (Mikolaj) [inline tests/fixtures/init/golden/pkg-desc/pkg-with-comments.golden:46]: The PR supposedly fixes #6864, but this doesn't list the changelog as `extra-doc-files`. How so?

Comment (emilypi) [reply tests/fixtures/init/golden/pkg-desc/pkg-with-comments.golden:46]: We're finding a few bugs in a few places like that as we go along with our internal review. It seems we marked "ready to review" a little prematurely. I'll ping when we have this fixed (it's simple fix)

Comment (Mikolaj) [reply tests/fixtures/init/golden/pkg-desc/pkg-with-comments.golden:46]: I'm still seeing this.

Comment (emilypi) [reply tests/fixtures/init/golden/pkg-desc/pkg-with-comments.golden:46]: Where are you still seeing this? It doesn't match the golden files I'm seeing: https://github.com/haskell/cabal/blob/76468fbedbbc92e613fceaf43057de24caeebc1a/cabal-install/tests/fixtures/init/golden/pkg-desc/pkg-with-comments.golden

Comment (Mikolaj) [reply tests/fixtures/init/golden/pkg-desc/pkg-with-comments.golden]: I think github was lying to me. I see the problem no longer. :)

Comment (emilypi) [reply tests/fixtures/init/golden/pkg-desc/pkg-with-comments.golden]: I actually found the problem (and it was a problem!): check out the file name. It's at the root of the project! Golden files must have been run from the root using `cabal run cabal-install:unit-tests`, which creates the golden files at whatever the current directory is :angry:

I've cleared out the stale golden files.

File: cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-and-exe-with-comments.golden (hunk 3 above)
Comment (Mikolaj) [reply cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-and-exe-with-comments.golden:112]: Is this comment resolved? It's the only one I can see in https://github.com/haskell/cabal/pull/7344/files view.

**Review by Mikolaj — APPROVED** [review]
Awesome mega-PR. I can't do it justice, not taking part in the epic struggle from the beginning, but I'm duly impressed by its breadth and the law and order it imposes. I would feel uncomfortable with such a large PR, but I understand it provides an excellent test coverage for what it changes. Great job.

File: cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-and-exe-with-comments.golden (hunk 3 above)
Comment (emilypi) [reply cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-and-exe-with-comments.golden:112]: Yes this is resolved.

**Comment by emilypi** [comment]
:tada:
