### PR TITLE
hpc: Don't cover non-dependency libraries

### LINKED ISSUE #10046: [3.12.0.0] Failed to find the installed unit
**Describe the bug**

Building a package with cabal 3.12.0.0, I encountered this error:
```
> cabal test all
...
Error: [Cabal-9341]
Failed to find the installed unit 'cardano-submit-api-3.2.2-inplace' in package database stack.
...
Error: [Cabal-7125]
Tests failed for test:unit from cardano-submit-api-3.2.2.
```

[Output](https://pastebin.com/EcJtc6kz)

A subsequent `cabal build all` was able to find the library and build it, Output collapsed below:

[Output](https://pastebin.com/jQpv36gt)

**To Reproduce**
Not sure how to reproduce it. I used the branch https://github.com/IntersectMBO/cardano-node/tree/js/cabal-error-report. I had compiled the project before the latest commit, and then after updating those source-repository-package this error showed up, but it doesn't seem to be deterministic :(

**System information**
 - Operating system: Windows 11 + WSL Ubuntu 22.04.4
 - `cabal`, `ghc` versions:
```
❯ cabal --version && ghc --version
cabal-install version 3.11.0.0
compiled using version 3.12.0.0 of the Cabal library
The Glorious Glasgow Haskell Compilation System, version 9.8.2
```

**Additional context**
In this same scenario I saw a paraphrasing of the following error (but I lost the terminal output, I will make a proper issue if I see it again, but maybe it is helpful to guess the cause):

```
When building ouroboros-consensus-cardano:
Encountered private or missing dependencies:
  diff-containers >= 1.1
```

A `cabal clean && cabal build all` solved it. Perhaps `cabal clean` would not have been needed.

### PR DESCRIPTION
**Pull request by alt-romes**
We were passing the flag --coverage-for for every library in the package when building the testsuites.

However, if a particular testsuite doesn't depend on one of the packages passed with --coverage-for we would crash.

Since we look for the unit ids of all packages given in --coverage-for in the package database (to find hpc artifacts), if the testsuite builds before the library this lookup would fail.

The fix is easy: don't pass --coverage-for=<lib> to <testsuite> if <testsuite> doesn't depend on <lib>. If <lib> is an indirect dependency of <testsuite> it'll no longer be covered by HPC, but this is a weird behaviour that I doubt anyone relies on.

Fixes #10046

Please read [Github PR Conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions) and then fill in *one* of these two templates.

**Template Α: This PR modifies [behaviour or interface](https://github.com/cabalism/cabal/blob/master/CONTRIBUTING.md#changelog)**

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.
* [x] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [x] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

### CODE REVIEW

File: cabal-install-solver/src/Distribution/Solver/Modular/Tree.hs [hunk 1]
```diff
@@ -1,4 +1,5 @@
 {-# LANGUAGE DeriveFunctor, DeriveFoldable, DeriveTraversable #-}
+{-# OPTIONS_GHC -ddump-to-file -ddump-simpl -ddump-stg-final #-}
```
Comment (jasagredo) [inline cabal-install-solver/src/Distribution/Solver/Modular/Tree.hs:2]: This looks like a leftover?

**Comment by ulysses4ever** [comment]
Good to see progress on this regression, thanks!

> Template B: This PR does not modify behaviour or interface

I think it does modify behavior, because cabal will crash less after the patch. Remember, template B is mostly just for documentation, tests, CI.

File: cabal-install-solver/src/Distribution/Solver/Modular/Tree.hs (hunk 1 above)
Comment (alt-romes) [reply cabal-install-solver/src/Distribution/Solver/Modular/Tree.hs:2]: Yes.

**Comment by alt-romes** [comment]
> Good to see progress on this regression, thanks!
> 
> > Template B: This PR does not modify behaviour or interface
> 
> I think it does modify behavior, because cabal will crash less after the patch. Remember, template B is mostly just for documentation, tests, CI.

Fine, updated.

**Review by jasagredo — APPROVED** [review]
The changes look good! Thanks for the super quick fix 🙏

**Review by ulysses4ever — APPROVED** [review]
I'm not the best person to review it, but this is a pretty significant regression, so, in the interest of delivering 3.14 sooner, let's fire it :fire:
