### PR TITLE
Fix PATH changes not triggering REPL reconfiguration (#2015)

### LINKED ISSUE #2015: cabal repl: Change in PATH environment variable not reflected
# Description

A change in the PATH environment variable is not visible in cabal repl.
# Versions

Confirmed in versions:
- Linux,
  cabal-install version 1.20.0.3,
  using version 1.20.0.1 of the Cabal library,
  ghc 7.6.3,
- OS X 10.9,
  cabal-install version 1.18.0.5,
  ghc 7.8.3
# Steps to reproduce

```
$ echo $PATH
/home/jakobro/.opam/4.01.0/bin:/home/jakobro/.cabal/bin:/home/jakobro/bin:/home/jakobro/.cabal/bin:/home/jakobro/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
$ export PATH=$PATH:/tmp
$ cabal repl
Prelude> :m Control.Monad System.Environment
Prelude Control.Monad System.Environment> liftM (lookup "PATH") getEnvironment 
Just "/home/jakobro/.opam/4.01.0/bin:/home/jakobro/.cabal/bin:/home/jakobro/bin:/home/jakobro/.cabal/bin:/home/jakobro/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
```

The environment when accessed from cabal repl-based ghci does not reflect the change in the PATH variable.

It does work with newly created environment variables, though.
# GHCI

In pure GHCI everything works fine:

```
$ echo $PATH
/home/jakobro/.opam/4.01.0/bin:/home/jakobro/.cabal/bin:/home/jakobro/bin:/home/jakobro/.cabal/bin:/home/jakobro/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/tmp
$ ghci
GHCi, version 7.6.3: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Prelude> :m System.Environment Control.Monad
Prelude System.Environment Control.Monad> liftM (lookup "PATH") getEnvironment 
Just "/home/jakobro/.opam/4.01.0/bin:/home/jakobro/.cabal/bin:/home/jakobro/bin:/home/jakobro/.cabal/bin:/home/jakobro/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/tmp"
```

### PR DESCRIPTION
**Pull request by mpickering**
When a user's PATH environment variable changes between Cabal commands, the environment in the REPL becomes incorrect. This occurs because during initial package configuration, the current PATH is captured via `programSearchPathAsPATHVar` and then stored in the `programOverrideEnv` field of a ConfiguredProgram. These `ConfiguredProgram`s are subsequently serialized into the setup-config file, effectively baking in the PATH environment from the time of configuration.

The issue manifests when `PATH` is updated after initial configuration. Although the solver re-runs when detecting `PATH` changes, the `dryRunLocalPkg` function examines `ElaboratedConfiguredPackage` and incorrectly determines that nothing has changed that would require reconfiguration. This decision is incorrect because `setup-config` now contains a stale reference to the original `PATH` value, which no longer matches the current environment.

To fix this problem, we need to store the `ConfiguredProgram`s directly in `ElaboratedConfiguredPackage`. This approach will ensure that when `PATH` changes, the `ConfiguredProgram`s will also change, properly triggering reconfiguration. While this solution will cause more recompilations when `PATH` changes, it guarantees that the correct environment is always used during builds and REPL sessions.

An alternative approach would be to stop baking the `PATH` variable into the environment of programs, but this would require more substantial changes to how Cabal manages environment variables.

Fixes #2015

Please read [Github PR Conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions) and then fill in *one* of these two templates.

---

**Template Α: This PR modifies [behaviour or interface](https://github.com/cabalism/cabal/blob/master/CONTRIBUTING.md#changelog)**

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
  * [ ] [Is the change significant?](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#is-my-change-significant) If so, remember to add `significance: significant` in the changelog file.
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [x] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

### CODE REVIEW

**Comment by Mikolaj** [comment]
Is this ready for review? If so, could you please add the label?

**Comment by mpickering** [comment]
Any reviewers? @ulysses4ever ?

1 week without movement, so I am happy to just merge it if no-one wishes to review.

**Comment by ulysses4ever** [comment]
Sorry for slow progress here: everyone was busy with the release. I'll try to take a look today.

I don't think it's possible to merge anything without reviews. Unless you're going to change repository settings, which is a big change for the project and should be discussed on a meeting.

File: changelog.d/pr-10817 [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+prs: #10817
+issues: #2015
+
+When modifying your PATH environment variable between Cabal commands, REPL
+sessions will now correctly use the updated environment. Previously, if you
+changed your PATH after initial configuration, Cabal would continue using the
+old PATH settings in REPL sessions without warning.
+
+With this fix, Cabal properly detects PATH changes and reconfigures the REPL
+accordingly, ensuring tools and libraries in your current PATH are available.
```
Comment (ulysses4ever) [inline changelog.d/pr-10817:12]: This text, including the title, feels a little repetitive. I suggest dropping the first sentence in the description and make it into one paragraph:

```suggestion
Previously, if you changed your PATH after initial configuration, Cabal would
continue using the old PATH settings in REPL sessions without warning.
With this fix, Cabal properly detects PATH changes and reconfigures the REPL
accordingly, ensuring tools and libraries in your current PATH are available.
```
Again, consider that it appears right after the title ("synopsis" field). And that the former third sentence basically repeated the former first one that I suggest to drop.

**Review by ulysses4ever — APPROVED** [review]
I'd suggest that you mention in the commit message why adding a new field, seemingly unused anywhere, changes the behaviour (it's because of the Generic business afaiu).

**Review by geekosaur — APPROVED** [review]

**Comment by Mikolaj** [comment]
@mpickering: would you like to respond and then set the merge label maybe?
