### PR TITLE
Make renameFile in writeFileAtomic more robust

### LINKED ISSUE #10938: writeFileAtomic retry strategy could be improved with threadDelay
https://github.com/haskell/cabal/blob/c2d835310c0e8c0b1008c8970e2f5f085c38078c/Cabal-syntax/src/Distribution/Utils/Generic.hs#L184-L200

So if `renameFile` failed we immediately try `copyFile` followed by `removeFile`. My experience however is that this is not helpful, at least on Windows. The most common reason for `renameFile` to fail is because another process (typically, an antivirus) opened the source file for reading. If this is the case then `copyFile` is likely to be too short delay for `removeFile` to succeed, because the source file remains locked by antivirus. 

To make it worse, `copyFile` from `directory` internally makes its own attempt at atomicity, creating a temporary file and renaming it, which triggers the antivirus yet again. 

In short, if `renameFile` fails then there is no reason to expect `copyFile` / `removeFile` to succeed. 

I'd suggest to scrap `copyFile` / `removeFile` catch: just keep retrying `renameFile` after `threadDelay 10000` a few times more.

CC @GulinSS who was looking at `writeFileAtomic` recently.

### PR DESCRIPTION
**Pull request by Bodigrim**
Closes #10938. 

The existing `writeFileAtomic` executes `renameFile` under assumption that the only reason it can fail is `EXDEV` error from `rename(2)` (see https://pubs.opengroup.org/onlinepubs/9799919799/functions/rename.html). The error means that source and target files are on different devices and physical copying must be performed instead of simply renaming a file system node. So `writeFileAtomic` catches an exception and immediately tries to `copyFile` instead of `renameFile`. If `copyFile` fails, the exception is not caught and crashes the entire Cabal process.

In practice however there are could be multiple reasons why `renameFile` might be unsuccessful, such as busy device or files temporarily locked by third party (for example, an antivirus). In such cases going for `copyFile` without delay only makes things worse.

Cabal often runs `writeFileAtomic` in a middle of long `cabal build` process. It's very discouraging when the entire build fails because of a temporary issue with file system.

The patch implements a more robust strategy for `renameFile`: we retry renaming thrice with a 1ms delay between them. We only switch to `copyFile` if the caught exception is precisely `UnsupportedOperation` (which is how `EXDEV` is mapped to `IOException`).

**Template Α: This PR modifies [behaviour or interface](https://github.com/cabalism/cabal/blob/master/CONTRIBUTING.md#changelog)**

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
  * [ ] [Is the change significant?](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#is-my-change-significant) If so, remember to add `significance: significant` in the changelog file.
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [ ] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

### CODE REVIEW

File: Cabal-syntax/src/Distribution/Utils/Generic.hs [hunk 1]
```diff
@@ -197,14 +198,37 @@ writeFileAtomic targetPath content = do
...
+    -- If no retries left then throw whatever exception we ended up with.
+    retryRename 0 exception = throwIO exception
+    retryRename retriesLeft exception
+      -- UnsupportedOperation means EXDEV from rename(2) with source and target
+      -- on different devices. In such case we resort to copying instead of renaming.
+      | ioeGetErrorType exception == UnsupportedOperation =
+          copyFile srcPath targetPath `Exception.catch` retryCopy (retriesLeft - 1)
+      | otherwise = do
+          -- Wait 1ms between retries: maybe device is busy, maybe antivirus locked srcPath.
+          threadDelay 1000
```
Comment (philderbeast) [inline Cabal-syntax/src/Distribution/Utils/Generic.hs:220]: Would it help to lengthen the wait each time around? If so, perhaps the signature could change to take those delays?

```haskell
retryRename :: [Int] -> IOException -> IO ()
```

Comment (Bodigrim) [reply Cabal-syntax/src/Distribution/Utils/Generic.hs:220]: In general an exponential backoff is a sound approach, but I'm cautious to overcomplicate the implementation without a strong justification. My (limited) experience is that a fixed delay is usually good enough for file I/O.

Comment (philderbeast) [reply Cabal-syntax/src/Distribution/Utils/Generic.hs:220]: I asked "how long should I wait for a locked file to try again in \<lang\>" in chromium and each time got different advice from AI with each language I tried. I tried C#, C, Rust and Haskell.

Comment (Bodigrim) [reply Cabal-syntax/src/Distribution/Utils/Generic.hs:220]: I don't think it depends much on a programming language, rather on the nature of the locking process. My guesstimate is that if a monitoring process (such as an antivirus) peeks into a temporary file (of smallish-to-medium size, given that it's something created by Cabal), it should not take longer than 1ms to finish its scan.

If you feel strongly about it, I don't particularly mind to increase the delay and/or make it exponentially growing.

Comment (philderbeast) [reply Cabal-syntax/src/Distribution/Utils/Generic.hs:220]: > I don't think it depends much on a programming language

Me neither, but I was surprised that AI was so inconsistent answering the same question.

I've approved and am not asking for a change.

Comment (geekosaur) [reply Cabal-syntax/src/Distribution/Utils/Generic.hs:220]: I'm not; it's basically tendering the varied opinions of various programmers in various programming languages, and I suspect a not insignificant number of such opinions are not well informed.
