### PR TITLE
Sort the unit order for --enable-multi-repl

### LINKED ISSUE #9195: Cabal multi components repl arguments order does not match the ghc `-unit` argument order
**Describe the bug**
When using the upcoming multi-repl feature with ghcid to run a test command from one of the target, it appears to fail randomly with a `Not in scope` error when the ghc `-unit` argument order is incorrect.

**To Reproduce**

Given this project:

```
.
├── multi-repl-repro.cabal
├── src
│   └── A.hs
└── src-b
    └── B.hs
```

With the following content:

```
-- multi-repl-repro.cabal
cabal-version:      3.0
name:               multi-repl-repro
version:            0.1
build-type:         Simple

library
  hs-source-dirs: src
  default-language: GHC2021
  build-depends: base
  exposed-modules: A

library pkgb
  hs-source-dirs: src-b
  default-language: GHC2021
  build-depends: base, multi-repl-repro
  exposed-modules: B
```

```haskell
-- src/A.hs
module A where
a :: String
a = "I am a"
```

```haskell
-- src/B.hs
module B where
b :: String
b = "I am b"
```

Running the following command fails:

```ShellSession
$ cabal --verbose repl --keep-temp-files --enable-multi-repl lib:multi-repl-repro lib:pkgb
[..]
Running: /nix/store/si6b9w2k6mbhnmh22dzm69cs3lvq5lss-ghc-9.6.2-with-packages/bin/ghc --interactive -package-env - -j 'NumJobs (Just 4)' -unit '@/srv/github.com/TristanCacqueray/multi-repl-repro/dist-newstyle/multi-out-585608/multi-repl-repro-0.1-inplace-pkgb' -unit '@/srv/github.com/TristanCacqueray/multi-repl-repro/dist-newstyle/multi-out-585608/multi-repl-repro-0.1-inplace' 
GHCi, version 9.6.2: https://www.haskell.org/ghc/  :? for help
[1 of 2] Compiling A                ( /srv/github.com/TristanCacqueray/multi-repl-repro/src/A.hs, interpreted )[multi-repl-repro-0.1-inplace]
[2 of 2] Compiling B                ( /srv/github.com/TristanCacqueray/multi-repl-repro/src-b/B.hs, interpreted )[multi-repl-repro-0.1-inplace-pkgb]
Ok, two modules loaded.
ghci> B.b
<interactive>:1:1: error: [GHC-76037]                                                                                                                                                                                                                                                                                                                                                       
    Not in scope: ‘B.b’                                                                                                                                                                                                                                                                                                                                                                     
    NB: no module named ‘B’ is imported.
ghci> A.a
"I am a"
```

**Expected behavior**
I expected `B.b` to be in scope.

**System information**
 - fedora 38
 - cabal-3.11 (built with [f77585](https://github.com/haskell/cabal/commit/f75df7ba3191645c1873dfa00126168091377668))
 - ghc-9.6.2
 
**Additional context**
Note that the reproducer may succeed when the ghc `-unit` argument are in the same order as passed on the cabal command (e.g. pkgb at the end). This issue was discovered in https://github.com/ButlerOS/haskell-butler/issues/49 , and out of 4 different systems, only one system is affected.

How is the `-unit` argument order defined? If the order does not matter, could this be a bug in ghc?

### PR DESCRIPTION
**Pull request by TristanCacqueray**
When using the multi components repl, the last unit given to ghc
is the active unit. This change uses the cabal repl argument
order instead of relying on the 'listDirectory' ordering.

Fixes #9195 

---

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
I guess we can also use a new command line argument to select the initial active target/unit, but until then, I have confirmed this PR does fix the random failure described in the issue. Please let me know what you think.

**Review by geekosaur — APPROVED** [review]

**Comment by michaelpj** [comment]
Just going to throw my bikeshedding hat in the arena and say... maybe it should be the _first_ unit? i.e.
```
cabal repl foo -- foo is active
cabal repl foo bar baz -- foo is still active
```
It seems slightly more natural to read `cabal repl foo bar baz` as "cabal repl for foo, plus bar and baz" rather than "cabal repl for baz, plus foo and bar"?

**Comment by TristanCacqueray** [comment]
@michaelpj I think it's better to use the same order as GHC, that is: the last unit is the active unit.

**Comment by michaelpj** [comment]
I think the cabal interface for this is much more user-facing than the GHC one. Now might be the time to give some thought to the UX :)

**Comment by TristanCacqueray** [comment]
Ok, as you prefer @michaelpj, [d837545](https://github.com/haskell/cabal/pull/9202/commits/d837545fc7b32209ecbd2ea6a0f8a632d5992a2e) reverse the order.

**Comment by TristanCacqueray** [comment]
Is there any chance this could be part of the 3.11 release? This fix seems required to be able to eval tests in a multi-repl session...

**Comment by Mikolaj** [comment]
Yes, let's aim at 3.11 (== 3.12).

Nobody from the IRC/Matrix channel frequenters objected to the changed order of arguments (as currently in this PR), so I think we can finalize.

@michaelpj: would you mind making a final review?

File: cabal-install/src/Distribution/Client/CmdRepl.hs [hunk 1]
```diff
@@ -451,6 +451,23 @@ replAction flags@NixStyleFlags{extraFlags = r@ReplFlags{..}, ..} targetStrings g
         -- unit files for components
         unit_files <- listDirectory dir
 
+        -- Order the unit files so that the last target becomes the active unit
```
Comment (michaelpj) [inline cabal-install/src/Distribution/Client/CmdRepl.hs:454]:
```suggestion
        -- Order the unit files so that the first target becomes the active unit
```

File: cabal-install/src/Distribution/Client/CmdRepl.hs [hunk 2]
```diff
@@ -451,6 +451,23 @@ replAction flags@NixStyleFlags{extraFlags = r@ReplFlags{..}, ..} targetStrings g
...
+        let active_unit_fp :: Maybe FilePath
+            active_unit_fp = do
+              -- Get the first target selectors from the cli
+              activeTarget <- safeHead targetSelectors
+              -- Lookup the targets :: Map UnitId [(ComponentTarget, NonEmpty TargetSelector)]
+              Map.toList targets
+                -- Keep the UnitId matching the desired target selector
+                & filter (\(_, xs) -> any (\(_, selectors) -> activeTarget `elem` selectors) xs)
```
Comment (michaelpj) [inline cabal-install/src/Distribution/Client/CmdRepl.hs:462]: `safeHead . filter p == find p`?

File: cabal-install/src/Distribution/Client/CmdRepl.hs [hunk 3]
```diff
@@ -451,6 +451,23 @@ replAction flags@NixStyleFlags{extraFlags = r@ReplFlags{..}, ..} targetStrings g
...
+                -- Convert to filename
```
Comment (michaelpj) [inline cabal-install/src/Distribution/Client/CmdRepl.hs:463]: Is this a safe way to do this? I have no idea. Maybe there is a conversion function exported somewhere?

File: cabal-install/src/Distribution/Client/CmdRepl.hs [hunk 4]
```diff
@@ -451,6 +451,23 @@ replAction flags@NixStyleFlags{extraFlags = r@ReplFlags{..}, ..} targetStrings g
...
+                & map (prettyShow . fst)
+                & safeHead
+            unit_files_ordered :: [FilePath]
+            unit_files_ordered =
+              let (active_unit_files, other_units) = partition (\fp -> Just fp == active_unit_fp) unit_files
+               in other_units ++ active_unit_files
```
Comment (michaelpj) [inline cabal-install/src/Distribution/Client/CmdRepl.hs:469]:
```suggestion
               -- GHC considers the last unit passed to be the active one
               in other_units ++ active_unit_files
```

**Review by michaelpj — APPROVED** [review]

**Comment by TristanCacqueray** [comment]
@Mikolaj may I request an update on this PR please?

**Comment by ulysses4ever** [comment]
@Mergify rebase

**Comment by Mikolaj** [comment]
> @Mikolaj may I request an update on this PR please?

In general, you are in charge of the process described at

https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions

Are you blocked? At which step?

**Comment by ulysses4ever** [comment]
There needs to be another approval. Any takers?

**Comment by Mikolaj** [comment]
> There needs to be another approval. Any takers?

Well spotted. Apparently, approvals from people with Triage permissions don't count for the sum total of approvals. I've promoted @michaelpj to Write permissions and now github is happy.

**Comment by TristanCacqueray** [comment]
@michaelpj could you please take another look, it would be nice if this could get merged. Does this need any final touches
?

**Comment by ulysses4ever** [comment]
@TristanCacqueray could you please add a changelog? https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog

A test would be great too. This looks like something that can be tested without too much trouble. But our test suite is quite a beast, of course, so feel free to ask for help. The standard way to start is to browse cabal-testsuite/PackageTests for similar tests. There should be repl-tests...

**Comment by ulysses4ever** [comment]
Actually, since multi-repl hasn't been released, there's no need in changelog, I think

**Comment by ulysses4ever** [comment]
Sorry, my bad about the tests too. 

From my point of view, this is good to go. Do we want to edit for Michael's approval still? I'm ambivalent. There's no rush with this PR because multi-repl will only appear in 3.12, and it's not planned yet.

**Comment by michaelpj** [comment]
I was happy before and I haven't changed my mind :)

**Comment by ulysses4ever** [comment]
Thank you, Michael!

@TristanCacqueray could you, please, proceed according to https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions which is: put a merge label when you're happy with the state of the patch.

**Comment by TristanCacqueray** [comment]
Thanks, I didn't realize I could add the label, so here is a doc update: https://github.com/haskell/cabal/pull/9598
