### PR TITLE
multi-repl: Support module renaming for ghc-9.12 onwards

### LINKED ISSUE #10181: Multi-repl doesn't support renaming of reexported modules
**Describe the bug**

Loading mutliple components where one reexports a module from the other one fails with:
```
cabal repl io-classes:io-classes io-classes:strict-stm 
Resolving dependencies...
Build profile: -w ghc-9.8.2 -O1
In order, the following will be built (use -v for more details):
 - io-classes-1.5.0.0 (interactive) (lib) (configuration changed)
 - io-classes-1.5.0.0 (interactive) (lib:strict-stm) (configuration changed)
Configuring library for io-classes-1.5.0.0...
Preprocessing library for io-classes-1.5.0.0...
Configuring library 'strict-stm' for io-classes-1.5.0.0...
Preprocessing library 'strict-stm' for io-classes-1.5.0.0...
GHCi, version 9.8.2: https://www.haskell.org/ghc/  :? for help
Command is not supported (yet) in multi-mode
Command is not supported (yet) in multi-mode
Command is not supported (yet) in multi-mode
Command is not supported (yet) in multi-mode
Command is not supported (yet) in multi-mode
Command is not supported (yet) in multi-mode
Command is not supported (yet) in multi-mode
Loaded GHCi configuration from /home/coot/.ghci

<no location info>: error: [GHC-68286]
    Modules are listed as reexported in options for ‘io-classes-1.5.0.0-inplace-strict-stm’ but can't be found in any dependency:
        Control.Concurrent.Class.MonadSTM.Strict.TSem

```

**To Reproduce**
This can be reproduced using `coot/io-classes` branch of the [input-output-hk/io-sim](https://github.com/input-output-hk/io-sim/tree/coot/io-classes) repo. If `reexported-modules` in `strict-stm` package is removed from the `io-classes.cabal` file the session is loaded.

**System information**
 - `cabal-3.12.1.0`
 - `ghc-9.8.2`

### PR DESCRIPTION
**Pull request by mpickering**
In ghc-9.12 the -rexported-module flag was extended to add support for module renaming.

Therefore now if a module uses a module renaming, then the -reexported-module flag is passed the renaming.

Fixes #10181

Please read [Github PR Conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions) and then fill in *one* of these two templates.

---

**Template Α: This PR modifies [behaviour or interface](https://github.com/cabalism/cabal/blob/master/CONTRIBUTING.md#changelog)**

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
  * [ ] [Is the change significant?](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#is-my-change-significant) If so, remember to add `significance: significant` in the changelog file.
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [x] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

---

**Template B: This PR does not modify behaviour or interface**

*E.g. the PR only touches documentation or tests, does refactorings, etc.*

Include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).

### CODE REVIEW

File: changelog.d/pr-10880.md [hunk 1]
```diff
@@ -0,0 +1,12 @@
+---
+synopsis: 'Fix multi-repl when using reexported-modules with renaming for  GHC >= 9.12'
```
Comment (Bodigrim) [inline changelog.d/pr-10880.md:2]:
```suggestion
synopsis: 'Fix multi-repl when using reexported-modules with renaming for GHC >= 9.12'
```

**Comment by mpickering** [comment]
Fixed the test being run with a GHC version which doesn't support multi-repl at all.

File: changelog.d/pr-10880.md (hunk 1 above)
Comment (mpickering) [reply changelog.d/pr-10880.md]: Thanks Andrew.

**Comment by Mikolaj** [comment]
@mpickering: let me take the liberty of setting the review-needed label.

**Comment by mpickering** [comment]
Two weeks and no reviews, can I merge this patch? I am confident it's correct.

**Review by geekosaur — APPROVED** [review]
