### PR TITLE
Fix extra-prog-path propagation in the codebase.

### LINKED ISSUE #8391: `cabal test` sees the executable, but `cabal run` does not.
There is a package called `fourmolu` that is going to be my example here. The relevant issue is fourmolu/fourmolu#231. The appropriate commit is 12af899611cea08c5d9a1f547d432edfbce38be4 — the current `main`.

## See for yourself:

1. Remove all instances of `fourmolu` on the path. You should have this:

   ```
   % where fourmolu
   fourmolu not found
   ```

2. See that the tests pass:

   ```
   % cabal test
   Build profile: -w ghc-8.10.7 -O1
   In order, the following will be built (use -v for more details):
    - fourmolu-0.8.1.0 (test:fixity-tests) (ephemeral targets)
    - fourmolu-0.8.1.0 (test:region-tests) (ephemeral targets)
    - fourmolu-0.8.1.0 (test:tests) (ephemeral targets)
   Preprocessing test suite 'fixity-tests' for fourmolu-0.8.1.0..
   Building test suite 'fixity-tests' for fourmolu-0.8.1.0..
   Preprocessing test suite 'region-tests' for fourmolu-0.8.1.0..
   Building test suite 'region-tests' for fourmolu-0.8.1.0..
   Preprocessing test suite 'tests' for fourmolu-0.8.1.0..
   Building test suite 'tests' for fourmolu-0.8.1.0..
   Running 1 test suites...
   Running 1 test suites...
   Test suite region-tests: RUNNING...
   Test suite fixity-tests: RUNNING...
   Test suite region-tests: PASS
   Test suite logged to:
   /home/kindaro/projects/haskell/fourmolu/dist-newstyle/build/x86_64-linux/ghc-8.10.7/fourmolu-0.8.1.0/t/region-tests/test/fourmolu-0.8.1.0-region-tests.log
   1 of 1 test suites (1 of 1 test cases) passed.
   Test suite fixity-tests: PASS
   Test suite logged to:
   /home/kindaro/projects/haskell/fourmolu/dist-newstyle/build/x86_64-linux/ghc-8.10.7/fourmolu-0.8.1.0/t/fixity-tests/test/fourmolu-0.8.1.0-fixity-tests.log
   1 of 1 test suites (1 of 1 test cases) passed.
   Running 1 test suites...
   Test suite tests: RUNNING...
   Test suite tests: PASS
   Test suite logged to:
   /home/kindaro/projects/haskell/fourmolu/dist-newstyle/build/x86_64-linux/ghc-8.10.7/fourmolu-0.8.1.0/t/tests/test/fourmolu-0.8.1.0-tests.log
   1 of 1 test suites (1 of 1 test cases) passed.
   ```

3. See that the tests fail if run with `cabal run`:

   ```
   % grep 'test-suite' fourmolu.cabal | cut -d ' ' -f 2 | while read name; do cabal run test:"$name"; done
   Build profile: -w ghc-8.10.7 -O1
   In order, the following will be built (use -v for more details):
    - fourmolu-0.8.1.0 (test:tests) (additional components to build)
   Preprocessing test suite 'tests' for fourmolu-0.8.1.0..
   Building test suite 'tests' for fourmolu-0.8.1.0..
   …
   Finished in 4.1124 seconds
   985 examples, 1 failure, 2 pending
   Build profile: -w ghc-8.10.7 -O1
   In order, the following will be built (use -v for more details):
    - fourmolu-0.8.1.0 (test:region-tests) (additional components to build)
   Preprocessing test suite 'region-tests' for fourmolu-0.8.1.0..
   Building test suite 'region-tests' for fourmolu-0.8.1.0..
   …
   Finished in 0.0011 seconds
   8 examples, 1 failure, 7 pending
   Build profile: -w ghc-8.10.7 -O1
   In order, the following will be built (use -v for more details):
    - fourmolu-0.8.1.0 (test:fixity-tests) (additional components to build)
   Preprocessing test suite 'fixity-tests' for fourmolu-0.8.1.0..
   Building test suite 'fixity-tests' for fourmolu-0.8.1.0..
   …
   Finished in 0.0015 seconds
   6 examples, 1 failure, 5 pending
   ```

4. See that the tests pass if run with `cabal run` after `cabal install`:

   ```
   % cabal install
   …
   Symlinking 'fourmolu' to '/home/kindaro/.cabal/bin/fourmolu'
   % grep 'test-suite' fourmolu.cabal | cut -d ' ' -f 2 | while read name; do cabal run test:"$name"; done
   Resolving dependencies...
   Up to date
   …
   Finished in 6.4715 seconds
   985 examples, 0 failures
   Up to date
   …
   Finished in 0.3642 seconds
   8 examples, 0 failures
   Up to date
   …
   Finished in 0.7731 seconds
   6 examples, 0 failures
   ```

### Expected:

Either the tests fail, or the tests pass. It does not matter which way I run them. In particular, Cabal makes the same executables available in the same way: either the `fourmolu` executable is made available to both `cabal run` and `cabal test` or to neither.

### Actual:

The executable `fourmolu` is made available to the test programs when they are run with `cabal test` but not with `cabal run`.

## System information:

```
% uname --all
Linux kindrom-silverheart 5.18.13-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 22 Jul 2022 13:05:04 +0000 x86_64 GNU/Linux
% cabal --version
cabal-install version 3.8.1.0
compiled using version 3.8.1.0 of the Cabal library 
% ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.10.7
```

### LINKED ISSUE #9519: `cabal` doesn't inherit the path from `cabal/config` in PowerShell
**Describe the bug**

Cabal config specifies (as configured by `GHCup`):

```cabal
extra-include-dirs: C:\msys64\mingw64\include
extra-lib-dirs: C:\msys64\mingw64\lib
extra-prog-path: C:\ghcup\bin,
                 C:\cabal\bin,
                 C:\msys64\mingw64\bin,
                 C:\msys64\usr\bin
```

And I have this test-suite that depends on external DLLs:
```zsh
➜ ldd ./dist-newstyle/build/x86_64-windows/ghc-9.6.3/ouroboros-consensus-cardano-0.12.1.0/t/cardano-test/build/cardano-test/cardano-test.exe
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7ffcf45d0000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7ffcf34c0000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7ffcf1ef0000)
        ucrtbase.dll => /c/WINDOWS/System32/ucrtbase.dll (0x7ffcf1da0000)
        SHELL32.dll => /c/WINDOWS/System32/SHELL32.dll (0x7ffcf2770000)
        msvcp_win.dll => /c/WINDOWS/System32/msvcp_win.dll (0x7ffcf1d00000)
        libsodium-26.dll => /mingw64/bin/libsodium-26.dll (0x7ffc37c60000)
        libsecp256k1-0.dll => /mingw64/bin/libsecp256k1-0.dll (0x7ffbf91c0000)
        msvcrt.dll => /c/WINDOWS/System32/msvcrt.dll (0x7ffcf3650000)
        ADVAPI32.dll => /c/WINDOWS/System32/ADVAPI32.dll (0x7ffcf3590000)
        USER32.dll => /c/WINDOWS/System32/USER32.dll (0x7ffcf3f50000)
        sechost.dll => /c/WINDOWS/System32/sechost.dll (0x7ffcf2440000)
        win32u.dll => /c/WINDOWS/System32/win32u.dll (0x7ffcf1ec0000)
        GDI32.dll => /c/WINDOWS/System32/GDI32.dll (0x7ffcf2ff0000)
        RPCRT4.dll => /c/WINDOWS/System32/RPCRT4.dll (0x7ffcf3740000)
        gdi32full.dll => /c/WINDOWS/System32/gdi32full.dll (0x7ffcf1b70000)
        WS2_32.dll => /c/WINDOWS/System32/WS2_32.dll (0x7ffcf3d10000)
        libgcc_s_seh-1.dll => /mingw64/bin/libgcc_s_seh-1.dll (0x7ffcc3fa0000)
        ole32.dll => /c/WINDOWS/System32/ole32.dll (0x7ffcf24f0000)
        dbghelp.dll => /c/WINDOWS/SYSTEM32/dbghelp.dll (0x7ffcebaa0000)
        combase.dll => /c/WINDOWS/System32/combase.dll (0x7ffcf3870000)
        libwinpthread-1.dll => /mingw64/bin/libwinpthread-1.dll (0x7ffccef00000)
        combase.dll => /c/Windows/System32/combase.dll (0x1462d380000)
        OLEAUT32.dll => /c/WINDOWS/System32/OLEAUT32.dll (0x7ffcf2690000)
        CRYPTBASE.DLL => /c/WINDOWS/SYSTEM32/CRYPTBASE.DLL (0x7ffcf1190000)
        WINMM.dll => /c/WINDOWS/SYSTEM32/WINMM.dll (0x7ffce7f50000)
        IPHLPAPI.DLL => /c/WINDOWS/SYSTEM32/IPHLPAPI.DLL (0x7ffcf0370000)
        dbgcore.DLL => /c/WINDOWS/SYSTEM32/dbgcore.DLL (0x7ffcbd580000)
```

However, when I try to run it the following just aborts with no error message:

```powershell
PS C:\Users\Javier\code\cardano\ouroboros-consensus> cabal run cardano-test --verbose -- -p "/ExtLedgerState_Conway/"
Warning: C:\cabal\config: Unrecognized stanza on line 33
Project settings changed, reconfiguring...
Warning: C:\cabal\config: Unrecognized stanza on line 33
creating C:\Users\Javier\code\cardano\ouroboros-consensus\dist-newstyle
creating C:\Users\Javier\code\cardano\ouroboros-consensus\dist-newstyle\cache
this build was affected by the following (project) config files:
- ./asserts.cabal
- C:\Users\Javier\code\cardano\ouroboros-consensus\cabal.project
- C:\Users\Javier\code\cardano\ouroboros-consensus\cabal.project.local
creating C:\Users\Javier\code\cardano\ouroboros-consensus\dist-newstyle\build
creating C:\Users\Javier\code\cardano\ouroboros-consensus\dist-newstyle\tmp
Selecting ouroboros-consensus-cardano-0.12.1.0-inplace-cardano-test to supply
cardano-test
Running: "C:\Users\Javier\code\cardano\ouroboros-consensus\dist-newstyle\build\x86_64-windows\ghc-9.6.3\ouroboros-consensus-cardano-0.12.1.0\t\cardano-test\build\cardano-test\cardano-test" "-p" "/ExtLedgerState_Conway/"
```

It _is_ using `C:\cabal\config` because if I introduce garbage there I see:

```
Warning: C:\cabal\config: Unrecognized stanza on line 33
Project settings changed, reconfiguring...
Warning: C:\cabal\config: Unrecognized stanza on line 33
```

If I manually extend the PATH, it works:
```powershell
PS C:\Users\Javier\code\cardano\ouroboros-consensus> $env:Path += ';C:\msys64\mingw64\bin'
PS C:\Users\Javier\code\cardano\ouroboros-consensus> cabal run cardano-test -- -p "/ExtLedgerState_Conway/"
cardano
  Golden tests
    SerialiseDisk
      ExtLedgerState
        ExtLedgerState_Conway: OK

All 1 tests passed (0.01s)
```

Which suggests the pwsh path is not being extended properly.

**Expected behavior**

I would expect cabal to extend the PATH also on PowerShell.

**System information**
 - MINGW64_NT-10.0-22621
 - cabal-install version 3.10.2.0, compiled using version 3.10.2.1 of the Cabal library

**Additional context**

In MinGW shell it works just fine.

### PR DESCRIPTION
**Pull request by jasagredo**
Fixes #9519.
Fixes #8391.

This allows finding system executables in:
- `cabal exec` will find whatever executable
- `cabal build` when cloning `source-repository-packages` will find git
- `cabal get` if invoking git (with `-s` for example) will work
- `cabal run`'ed executable inherits the path

In particular this fixes PATH issues when running MinGW cabal in PowerShell.

Paths added are also now logged in info verbosity.

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.
* [x] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [ ] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

# QA Notes

In a Windows system with MSYS2/MinGW installed, either system-wide or by ghcup.

Running the following in a PowerShell with previous cabal should fail:
```
PS C:\Users\Javier\code> cabal exec sh
Error: cabal-3.10.2.0.exe: The program 'sh' is required but it could not be
found.
```

And now it should work:
```
PS C:\Users\Javier\code> C:\\Users\\Javier\\code\\cabal\\dist-newstyle\\build\\x86_64-windows\\ghc-9.6.3\\cabal-install-3.11.0.0\\x\\cabal\\build\\cabal\\cabal.exe exec sh
sh-5.2$
```

Also when you have `source-repository-package` stanzas in your cabal.project, it doesn't work:
```
PS C:\Users\Javier\code\foo> cabal build
Error: cabal-3.10.2.0.exe: The program 'git' is required but it could not be
found.
```

And after this PR it does:
```
PS C:\Users\Javier\code\foo> C:\\Users\\Javier\\code\\cabal\\dist-newstyle\\build\\x86_64-windows\\ghc-9.6.3\\cabal-install-3.11.0.0\\x\\cabal\\build\\cabal\\cabal.exe build
Warning: this is a debug build of cabal-install with assertions enabled.
Cloning into '/c/Users/Javier/code/foo/dist-newstyle/src/quickchec_-904b1af1c882c12e'...
remote: Enumerating objects: 6266, done.
...
```

`cabal get -s` used to fail:
```
PS C:\Users\Javier\code\tasty> cabal get quickcheck-state-machine -s --verbose=3
...
Searching for git in path.
Cannot find git on the path
CallStack (from HasCallStack):
  withMetadata, called at src\\Distribution\\Simple\\Utils.hs:368:14 in Cabal-3.10.2.1-inplace:Distribution.Simple.Utils
Error: cabal-3.10.2.0.exe: The program 'git' is required but it could not be
found.
```

not anymore:
```
PS C:\Users\Javier\code\tasty> C:\\Users\\Javier\\code\\cabal\\dist-newstyle\\build\\x86_64-windows\\ghc-9.6.3\\cabal-install-3.11.0.0\\x\\cabal\\build\\cabal\\cabal.exe get quickcheck-state-machine-0.7.0 -s --verbose=3
...
Searching for git in path.
Found git at C:\msys64\usr\bin\git.exe
Running: "C:\msys64\usr\bin\git.exe" "--version"
C:\msys64\usr\bin\git.exe is version 2.43.0
```

The PATH printed in the verbose mode used to sometimes have `\n` interleaved, can be seen with `cabal get -s ... --verbose=3`:
```
("PATH","C:\\ghcup\\bin,\nC:\\cabal\\bin,\nC:\\msys64\\mingw64\\bin,\nC:\\msys64\\usr\\bin;C:\\Program Files\\...")
```
not anymore after this change.

### CODE REVIEW

**Comment by jasagredo** [comment]
It does seem I went a bit over the board. `cabal get` seems to work without this modification and so does compilation of `network` (which invokes other executables), so maybe the fix I did in those was not really needed.

**Comment by jasagredo** [comment]
Ah no actually `cabal get` without this change shows:
```
("PATH","C:\\ghcup\\bin,\nC:\\cabal\\bin,\nC:\\msys64\\mingw64\\bin,\nC:\\msys64\\usr\\bin;C:\\Program Files\\...")
```
(notice the `\n`s). After this change it is ok.

**Comment by jasagredo** [comment]
And in fact `get` doesn't always work!

```
PS C:\Users\Javier\code\tasty> cabal get quickcheck-state-machine -s --verbose=3
...
Searching for git in path.
Cannot find git on the path
CallStack (from HasCallStack):
  withMetadata, called at src\\Distribution\\Simple\\Utils.hs:368:14 in Cabal-3.10.2.1-inplace:Distribution.Simple.Utils
Error: cabal-3.10.2.0.exe: The program 'git' is required but it could not be
found.
```

versus the new version
```
PS C:\Users\Javier\code\tasty> C:\\Users\\Javier\\code\\cabal\\dist-newstyle\\build\\x86_64-windows\\ghc-9.6.3\\cabal-install-3.11.0.0\\x\\cabal\\build\\cabal\\cabal.exe get quickcheck-state-machine-0.7.0 -s --verbose=3
...
Searching for git in path.
Found git at C:\msys64\usr\bin\git.exe
Running: "C:\msys64\usr\bin\git.exe" "--version"
C:\msys64\usr\bin\git.exe is version 2.43.0
```

**Comment by jasagredo** [comment]
And in fact `get` doesn't always work!

```
PS C:\Users\Javier\code\tasty> cabal get quickcheck-state-machine -s --verbose=3
...
Searching for git in path.
Cannot find git on the path
CallStack (from HasCallStack):
  withMetadata, called at src\\Distribution\\Simple\\Utils.hs:368:14 in Cabal-3.10.2.1-inplace:Distribution.Simple.Utils
Error: cabal-3.10.2.0.exe: The program 'git' is required but it could not be
found.
```

versus the new version
```
PS C:\Users\Javier\code\tasty> C:\\Users\\Javier\\code\\cabal\\dist-newstyle\\build\\x86_64-windows\\ghc-9.6.3\\cabal-install-3.11.0.0\\x\\cabal\\build\\cabal\\cabal.exe get quickcheck-state-machine-0.7.0 -s --verbose=3
...
Searching for git in path.
Found git at C:\msys64\usr\bin\git.exe
Running: "C:\msys64\usr\bin\git.exe" "--version"
C:\msys64\usr\bin\git.exe is version 2.43.0
```

**Comment by jasagredo** [comment]
Fixed it also for `cabal run`!

```
PS C:\Users\Javier\code\auxxx> cat .\app\Main.hs
module Main where

import System.Process

main :: IO ()
main = callCommand "git --version"
PS C:\Users\Javier\code\auxxx> cabal run
'git' is not recognized as an internal or external command,
operable program or batch file.
PS C:\Users\Javier\code\auxxx> C:\\Users\\Javier\\code\\cabal\\dist-newstyle\\build\\x86_64-windows\\ghc-9.6.3\\cabal-install-3.11.0.0\\x\\cabal\\build\\cabal\\cabal.exe run
...
git version 2.43.0
```

**Review by fendor — DISMISSED** [review]
Idea looks good to me, some small nitpicking.

I am going to manually check the change later.

File: cabal-install/src/Distribution/Client/CmdExec.hs [hunk 1]
```diff
@@ -163,9 +170,15 @@ execAction flags@NixStyleFlags{..} extraArgs globalFlags = do
 
   -- Some dependencies may have executables. Let's put those on the PATH.
   extraPaths <- pathAdditions verbosity baseCtx buildCtx
+  let configProgPathExtras =
+        fromNubList
+          . projectConfigProgPathExtra
+          . projectConfigShared
+          . projectConfig
+          $ baseCtx
```
[the remark this answers is not in the document]
Comment (jasagredo) [reply cabal-install/src/Distribution/Client/CmdExec.hs:178]: I think that is the case yeah. I also think this is transported into a different structure somewhere along the path of `CmdBuild` et al, because it works in that command. This is part of my confusion, I don't know exactly what is `baseCtx` then `targetCtx` etc etc.

File: Cabal/src/Distribution/Simple/GHC.hs [hunk 2]
```diff
@@ -853,47 +855,47 @@ installLib verbosity lbi targetDir dynlibTargetDir _builtDir pkg lib clbi = do
       whenGHCi $ installOrdinary builtDir targetDir ghciProfLibName
     whenShared $
       if
-          -- The behavior for "extra-bundled-libraries" changed in version 2.5.0.
```
Comment (jasagredo) [inline Cabal/src/Distribution/Simple/GHC.hs:856]: Not sure what happened here, I just called Fourmolu

**Comment by jasagredo** [comment]
I have reworked the solution a bit, in the same spirit as before but more principled. The commit message should give some guidance for the review.

**Comment by alt-romes** [comment]
Great! Looks good to me.

**Review by alt-romes — APPROVED** [review]

File: Cabal/src/Distribution/Simple/Program/Db.hs [hunk 3]
```diff
@@ -221,6 +222,18 @@ modifyProgramSearchPath
...
+-- | Modify the current 'ProgramSearchPath' used by the 'ProgramDb'
+-- by appending the provided extra paths. Also logs the added paths
+-- in info verbosity.
+appendProgramSearchPath
+  :: Verbosity
+  -> [FilePath]
+  -> ProgramDb
+  -> IO ProgramDb
+appendProgramSearchPath verbosity extraPaths db = do
+  logExtraProgramSearchPath verbosity extraPaths
```
Comment (jasagredo) [inline Cabal/src/Distribution/Simple/Program/Db.hs:234]: Perhaps we should only log when `not $ null extraPaths`?

**Review by Kleidukos — APPROVED** [review]

**Comment by Kleidukos** [comment]
@fendor has been volunteered to perform the QA, thank you fendor <3

**Comment by Kleidukos** [comment]
@jasagredo Only one conflict to fix and we're ready for merge!

**Comment by jasagredo** [comment]
Pushed plus cherry-picked #9341

**Comment by jasagredo** [comment]
@fendor requested changes, so this cannot be merged until that request is removed

**Comment by fendor** [comment]
Can confirm, the QA steps work now and didn't work before on windows 10.

The changes look a little bit scattered still and easy to miss in new `Cmd*` commands.

**Comment by jasagredo** [comment]
It is indeed easy to miss. Perhaps we should rework it in a principled step for all commands? Perhaps even in the acquiring of configuration for commands we could already populate the path and only slightly tweak it later on for some special commands?

**Comment by jasagredo** [comment]
Each command action is its own function, so there is no better way right now to do this I think without breaking many things. So I'd rather leave it as is.

**Comment by jasagredo** [comment]
@mergify backport 3.10
