### PR TITLE
Pass `@...` as a literal argument if the response file does not exist and support recursive response files

### LINKED ISSUE #6061: cabal --index-state broken
Another `@`-related regression in HEAD I stumbled over:

```
cabal build --index-state @1474732068
```

used to work for various v2 commands... but now it fails with

```
Error while expanding response file: 1474732068: openFile: does not exist (No such file or directory)
```

/cc @angerman @JoshMeredith

### PR DESCRIPTION
**Pull request by JoshMeredith**
Fixes #6061

Arguments to `--index-state` also use the `@` syntax, so instead of exiting when a non-existent response file is passed as an argument, print a warning and pass it as a literal argument. `--index-state=@1234` continues to work without warnings.

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [ ] The documentation has been updated, if necessary.
* [ ] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

File: Cabal/Distribution/Compat/ResponseFile.hs [hunk 1]
```diff
@@ -57,8 +56,6 @@ expandResponse = fmap concat . mapM expand
     expand x = return [x]
 
     readFileExc f =
-      readFile f `catch` \(e :: IOException) -> do
-        hPutStrLn stderr $ "Error while expanding response file: " ++ show e
-        exitFailure
-
-#endif
+      readFile f `catch` \(_e :: IOException) -> do
+        hPutStrLn stderr $ "Response file `@" ++ f ++ "` does not exist, assuming literal argument."
```
Comment (hvr) [inline Cabal/Distribution/Compat/ResponseFile.hs]: do we really have to be that noisy?

Comment (23Skidoo) [reply Cabal/Distribution/Compat/ResponseFile.hs]: Hmm yeah, we can't use `notice` et al. here though since we don't know the verbosity level yet. Let's just be silent.

Comment (hvr) [reply Cabal/Distribution/Compat/ResponseFile.hs]: For reference, here's GNU Binutils' implementation of `@file`-expansion:

http://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob;f=libiberty/argv.c;h=6444896f995a8e4abfb6a1edc510f3a4bbe1a30b;hb=HEAD#l342

File: Cabal/Distribution/Compat/ResponseFile.hs [hunk 2]
```diff
@@ -47,8 +50,18 @@ unescape args = reverse . map reverse $ go args NoneQ False [] []
 #endif
 
 expandResponse :: [String] -> IO [String]
-expandResponse = fmap concat . mapM expand
+expandResponse = go recursionLimit "."
   where
-    expand :: String -> IO [String]
-    expand arg@('@':f) = unescapeArgs <$> readFile f `catchIOError` (const $ return arg)
-    expand x = return [x]
+    recursionLimit = 100
```
Comment (23Skidoo) [inline Cabal/Distribution/Compat/ResponseFile.hs]: `libiberty` uses 2000, but I'm okay with using 100.

Comment (JoshMeredith) [reply Cabal/Distribution/Compat/ResponseFile.hs]: I think they expand iteratively, so the 2000 is the total number of response files encountered in their expansion tree, whereas this 100 is tree depth.
