### PR TITLE
stubMain now catches exceptions

### LINKED ISSUE #1426: “cabal test” crashes if test executable throws an exception
When this happens, the parent process (the one calling Description.Simple.Test.testController) ends with a read error, hiding the former error.

This seems to happen because testController pipes stderr along with stdout in the so-called “machine-readable log file” and, of course, the error message on stderr isn't readable.

It would be good to see the error at least. Which test caused it would also be appreciated, I think. Should the user manage to put exception handlers or could cabal convert the exception into a Distribution.TestSuite.Error ? And isn't testController a bit complicated ?

Here's a not-so-minimal example to reproduce the error :
Sardinia.cabal
```cabal
name: Sardinia
version: 1
build-type: Simple
cabal-version: >=1.8

-- Put a placeholder program in helloworld.hs.
executable helloworld
  main-is: helloworld.hs
  build-depends: base

test-suite Guttiau
-- The Guttiau is a delicious Sardinian Bread!
  type: detailed-0.9
  test-module: Guttiau
  build-depends: base, Cabal
```
Guttiau.hs
```haskell
module Guttiau where

import           Control.Exception
import           Distribution.TestSuite


tests :: IO [Test]
-- Let me show a bunch of examples that cause the bug.
tests = return $ [ test "return" $ return $ error "Governo"
                   -- On this one, the error isn't raised until the value
                   -- returned by the IO action is evaluated. The next two
                   -- throw in the IO action.
                 , test "evaluate" $ evaluate $ error "Governo"
                 , test "throw" $ throwIO $ ErrorCall "Governo"
                   -- Same result.
                 , test "error" $ error "Governo"
                 ]
  where test tag r = Test $ TestInstance { run = r
                                         , name = tag
                                         , tags = [tag]
                                         }
```

### PR DESCRIPTION
**Pull request by NovaDenizen**
Currently, when a detailed-0.9 test suite raises an exception, it fails to write its `TestLogs` data to a log file, and cabal experiences a parse error when trying to read it.  This patch adds exception catching code to `Distribution.Simple.Test.LibV09.stubMain`.

Really, there should be another per-test exception handler in `stubRunTests'`.  This one will still be necessary to handle exceptions that occur outside of a test suite, like in the `tests :: IO [Test]` computation.

I think this will fix #1426

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Seems to break Travis: some stuff it needs is not exported on older GHCs.

**Comment by 23Skidoo** [comment]
Otherwise LGTM.

File: Cabal/Distribution/Simple/Test/LibV09.hs [hunk 1]
```diff
@@ -212,7 +213,12 @@ stubMain :: IO [Test] -> IO ()
 stubMain tests = do
     (f, n) <- fmap read getContents
     dir <- getCurrentDirectory
-    results <- tests >>= stubRunTests
+    let errhandler :: SomeException -> IO TestLogs
+        errhandler e = do
+          return $ TestLog { testName = "Cabal test suite exception",
+                             testOptionsReturned = [],
+                             testResult = Error $ displayException e }
```
Comment (dcoutts) [inline Cabal/Distribution/Simple/Test/LibV09.hs]: As a matter of style, can I suggest that you move this handler to a `where` clause, since it doesn't need to capture any earlier context and it reads better to gets the exception case out of the main flow.

Otherwise, it looks fine (modulo compile errors with older library versions).

Comment (dcoutts) [inline Cabal/Distribution/Simple/Test/LibV09.hs]: Oh, also, are we really sure we should catch all exceptions here, including async exceptions? What do we expect to happen if the user hits ctl-C during the test run? That should not be reported as a test suite exception right, that should just stop.

If I'm right about that then this handler ought to work like this: catch all exception types *except for* async exceptions. We can do that like so:

    case fromException e of
      Just UserInterrupt -> throwIO e -- let ctl-C propagate
      _ -> return TestLog {.... etc

**Comment by dcoutts** [comment]
@NovaDenizen Thanks for the contribution. Have a look at the issues we pointed out and then I think this is fine to go in.

**Comment by NovaDenizen** [comment]
Ok, so I need to let async exceptions pass through, ditch `displayException` and make it work with base as old as 4.5.0.0, and improve the style.  Seems doable.

**Comment by ezyang** [comment]
Looks reasonable. Best way to avoid tearing your hair out fixing -Werror is to get a local build of the relevant GHC version going and iterate on that ;)

**Comment by NovaDenizen** [comment]
Looking at the travis build that failed, it says "Cabal: canonicalizePath: interrupted (Interrupted system call)".  It looks to me like this instance caught a signal of some sort and it's not my code's fault.  It doesn't look like any tests had been built yet, let alone run, so my code would not have been compiled or run yet.

**Comment by 23Skidoo** [comment]
I restarted the Travis build.

**Comment by NovaDenizen** [comment]
Tests succeeded.  I've been doing my own manual tests of the feature.  Exceptions and Ctrl-C's are working as we want them to.

**Comment by 23Skidoo** [comment]
OK, let's merge then!
