### PR TITLE
haddock/hscolour: fix highlighted source location

### LINKED ISSUE #3451: `cabal haddock --for-hackage` missing pretty-printed source-code
With cabal 1.24.0.0:

```
$ cabal get deepseq-1.4.2.0
$ cd deepseq-1.4.2.0/
$ cabal haddock --for-hackage
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
Resolving dependencies...
Configuring deepseq-1.4.2.0...
Running Haddock for deepseq-1.4.2.0...
Running hscolour for deepseq-1.4.2.0...
Preprocessing library deepseq-1.4.2.0...
Preprocessing library deepseq-1.4.2.0...
Haddock coverage:
 100% (  5 /  5) in 'Control.DeepSeq'
Warning: Control.DeepSeq: could not find link destinations for:
    GNFData
Documentation created: dist/doc/html/deepseq-1.4.2.0-docs/index.html,
dist/doc/html/deepseq-1.4.2.0-docs/deepseq.txt
Documentation tarball created: dist/deepseq-1.4.2.0-docs.tar.gz

$ tar tvf dist/deepseq-1.4.2.0-docs.tar.gz
drwxr-xr-x 0/0               0 2016-05-21 10:58 deepseq-1.4.2.0-docs/
-rw-r--r-- 0/0           16196 2016-05-21 10:58 deepseq-1.4.2.0-docs/deepseq.txt
-rw-r--r-- 0/0             859 2016-05-21 10:58 deepseq-1.4.2.0-docs/frames.html
-rw-r--r-- 0/0            8182 2016-05-21 10:58 deepseq-1.4.2.0-docs/haddock-util.js
-rw-r--r-- 0/0              56 2016-05-21 10:58 deepseq-1.4.2.0-docs/minus.gif
-rw-r--r-- 0/0            1684 2016-05-21 10:58 deepseq-1.4.2.0-docs/hslogo-16.png
-rw-r--r-- 0/0              59 2016-05-21 10:58 deepseq-1.4.2.0-docs/plus.gif
-rw-r--r-- 0/0            9306 2016-05-21 10:58 deepseq-1.4.2.0-docs/ocean.css
-rw-r--r-- 0/0           11327 2016-05-21 10:58 deepseq-1.4.2.0-docs/synopsis.png
-rw-r--r-- 0/0            1226 2016-05-21 10:58 deepseq-1.4.2.0-docs/mini_Control-DeepSeq.html
-rw-r--r-- 0/0          101649 2016-05-21 10:58 deepseq-1.4.2.0-docs/Control-DeepSeq.html
-rw-r--r-- 0/0            1733 2016-05-21 10:58 deepseq-1.4.2.0-docs/doc-index.html
-rw-r--r-- 0/0           24290 2016-05-21 10:58 deepseq-1.4.2.0-docs/deepseq.haddock
```

Now the problem is that the pretty-printed source-code is supposed to be in a `src/` folder,

```html
<a href="src/Control-DeepSeq.html#deepseq" class="link">Source</a>
```

and, in fact it was generated, but wasn't moved into the tarball-folder:

```
$ ls -lR dist/doc/html/
dist/doc/html/:
total 0
drwxr-xr-x 3 hvr hvr  60 May 21 10:58 deepseq
drwxr-xr-x 2 hvr hvr 280 May 21 10:58 deepseq-1.4.2.0-docs

dist/doc/html/deepseq:
total 0
drwxr-xr-x 2 hvr hvr 80 May 21 10:58 src

dist/doc/html/deepseq/src:
total 128
-rw-rw-r-- 1 hvr hvr 123726 May 21 10:58 Control-DeepSeq.html
-rw-rw-r-- 1 hvr hvr    243 May 21 10:58 hscolour.css

dist/doc/html/deepseq-1.4.2.0-docs:
total 196
-rw-rw-r-- 1 hvr hvr 101649 May 21 10:58 Control-DeepSeq.html
-rw-rw-r-- 1 hvr hvr  24290 May 21 10:58 deepseq.haddock
-rw-rw-r-- 1 hvr hvr  16196 May 21 10:58 deepseq.txt
-rw-rw-r-- 1 hvr hvr   1733 May 21 10:58 doc-index.html
-rw-r--r-- 1 hvr hvr    859 May 21 10:58 frames.html
-rw-r--r-- 1 hvr hvr   8182 May 21 10:58 haddock-util.js
-rw-r--r-- 1 hvr hvr   1684 May 21 10:58 hslogo-16.png
-rw-rw-r-- 1 hvr hvr   1226 May 21 10:58 mini_Control-DeepSeq.html
-rw-r--r-- 1 hvr hvr     56 May 21 10:58 minus.gif
-rw-r--r-- 1 hvr hvr   9306 May 21 10:58 ocean.css
-rw-r--r-- 1 hvr hvr     59 May 21 10:58 plus.gif
-rw-r--r-- 1 hvr hvr  11327 May 21 10:58 synopsis.png
```

/cc @bennofs

### PR DESCRIPTION
**Pull request by bennofs**
When generating haddocks with the `--for-hackage` switch, the generated
haddocks are placed in a different directory than the normal ones, which
includes the package id instead of just the package name. When we ran
hscolour, we didn't respect this, so the highlighted source would not
be placed in the correct directory and thus was missing from the tarball.
This patch fixes that.

Fixes #3451

### CODE REVIEW

**Comment by bennofs** [comment]
Oops, seems like this still has a small bug. Please don't merge yet.

**Comment by bennofs** [comment]
Fixed, should be ready to merge now.

**Comment by 23Skidoo** [comment]
@bennofs Apparently, this breaks the test suite. Can you look into that?

File: Cabal/Distribution/Simple/BuildPaths.hs [hunk 1]
```diff
@@ -48,12 +49,18 @@ import System.FilePath ((</>), (<.>))
 srcPref :: FilePath -> FilePath
 srcPref distPref = distPref </> "src"
 
-hscolourPref :: FilePath -> PackageDescription -> FilePath
+data PathMode = ForDistribution | ForDevelopment
```
Comment (23Skidoo) [inline Cabal/Distribution/Simple/BuildPaths.hs]: Needs a Haddock comment.

**Comment by bennofs** [comment]
Alright, fixed that. I also renamed `PathMode` to `DistributionMode` since `PathMode` was quite generic (I was not able to come up with a better name than `DistributionMode` :|

**Comment by 23Skidoo** [comment]
If `ForDistribution` only gets set when `--for-hackage` is enabled, why not call it `ForHackage`? And then maybe we can change the type of `haddockForHackage` to `Flag DistributionMode` and perhaps also rename it to `haddockDistributionMode`.

**Comment by bennofs** [comment]
Alright, that is a good idea. I'll do that.

**Comment by bennofs** [comment]
Finally got around to finish this up. Should be ready now.

**Comment by 23Skidoo** [comment]
Merged, thanks!
