### PR TITLE
Fix multi-repl closure computation with invalid Custom setup

### LINKED ISSUE #9710: cabal v2-repl broken with head
**Describe the bug**

`cabal v2-repl <component>` with cabal-head seems to just exit with exitcode 0 and not launch ghci.
This also breaks HLS.

**To Reproduce**
````
> cabal v2-repl foo
Resolving dependencies...
> echo $?
0
````

**Expected behavior**
This should open a repl

### PR DESCRIPTION
**Pull request by mpickering**
This patch deletes a lot of hairy logic to do with removing "bad" edges from the closure. Now the solver just forces `Cabal >= 3.11` universally when `--enable-multi-repl` is enabled.

Fixes #9710

Please read [Github PR Conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions) and then fill in *one* of these two templates.

---

**Template Α: This PR modifies `cabal` behaviour**

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [x] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

---

**Template Β: This PR does not modify `cabal` behaviour (documentation, tests, refactoring, etc.)**

Include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).

### CODE REVIEW

**Comment by Kleidukos** [comment]
Okay _constraint from --enable-multi-repl requires >=3.11_ is a good message, thank you @mpickering!

**Review by Kleidukos — APPROVED** [review]

**Review by geekosaur — APPROVED** [review]

File: cabal-install/src/Distribution/Client/ProjectPlanning.hs [hunk 1]
```diff
@@ -3236,7 +3233,7 @@ pruneInstallPlanPass1
 pruneInstallPlanPass1 pkgs
   -- if there are repl targets, we need to do a bit more work
   -- See Note [Pruning for Multi Repl]
```
Comment (alt-romes) [inline cabal-install/src/Distribution/Client/ProjectPlanning.hs:3235]: Is this note still relevant?

File: cabal-testsuite/PackageTests/MultiRepl/EnabledBadClosure/cabal.test.hs [hunk 2]
```diff
@@ -0,0 +1,11 @@
+import Test.Cabal.Prelude
+
+main = do
+  cabalTest $ do
+    -- MP: TODO: This should query Cabal library version
```
Comment (alt-romes) [inline cabal-testsuite/PackageTests/MultiRepl/EnabledBadClosure/cabal.test.hs:5]: I think the failures are related to this TODO.
The failure seems to be when parsing the `custom-setup` stanza, and we see in the failure message that the `Cabal` library being used is 2.4.

```
Warning: foo.cabal:0:0: Unsupported cabal-version. See https://github.com/haskell/cabal/issues/4899.
-----END CABAL OUTPUT-----
CallStack (from HasCallStack):
  die', called at libraries/Cabal/Cabal/Distribution/Parsec/ParseResult.hs:184:13 in Cabal-2.4.0.1:Distribution.Parsec.ParseResult
  parseString, called at libraries/Cabal/Cabal/Distribution/Parsec/ParseResult.hs:169:5 in Cabal-
```

Comment (alt-romes) [reply cabal-testsuite/PackageTests/MultiRepl/EnabledBadClosure/cabal.test.hs:5]: I think we can do with `skipUnlessGhcVersion ">= 8.8"`

File: cabal-install/src/Distribution/Client/ProjectPlanning.hs (hunk 1 above)
Comment (mpickering) [reply cabal-install/src/Distribution/Client/ProjectPlanning.hs:3239]: The last part is out of date, I updated it.

**Review by alt-romes — APPROVED** [review]
