### PR TITLE
Fix cabal install in the presence of extra-packages

### LINKED ISSUE #8848: extra-packages make cabal install fail
**Describe the bug**

It looks like the mere existence of a package in `extra-packages` make cabal install fail.

**To Reproduce**

```bash
mkdir temp-cabal-install && cd temp-cabal-install
cabal init -n -m
echo -e 'packages: .\nextra-packages: lens' > cabal.project
cabal v2-install temp-cabal-install --dry-run
```

The output is

```
Wrote tarball sdist to
/home/andrea/temp-cabal-install/dist-newstyle/sdist/temp-cabal-install-0.1.0.0.tar.gz
Got NamedPackage lens
CallStack (from HasCallStack):
  error, called at src/Distribution/Client/CmdInstall.hs:524:33 in cabal-install-3.10.1.0-inplace:Distribution.Client.CmdInstall
```

Notes:
- The same happens using the more explicit target `temp-cabal-install:exe:temp-cabal-install`
- Adding `-v3` shows that this happens after planning. Indeed `dist-newstyle/cache/plan.json` is created and it seems correct (it includes both `lens` and `temp-cabal-install`)
- cabal v2-build has no issues
- There seem to be some re-planning when alternating between `cabal v2-build temp-cabal-install --dry-run` and the failing `cabal v2-install temp-cabal-install --dry-run`. You can see the replanning using `-v2` or `-v3` but `dist-newstyle/cache/plan.json` does not change (according to sha256sum).

**Expected behavior**

I'd expect cabal to be able to install `temp-cabal-install:exe:temp-cabal-install` just like without the line `extra-packages: lens` in cabal.project (which of course works).

**System information**
 - x86_64 GNU/Linux
 - ghc-9.2.6
 - cabal-3.6.2.0, cabal-3.8.1.0 and cabal-3.10.1.0 seem all affected.

**Additional context**

In the [cardano-node](https://github.com/input-output-hk/cardano-node) repo we moved from using source-repository-packages to external repository for some dependencies not present on Hackage. So in https://github.com/input-output-hk/cardano-node/pull/4921 the following lines were removed from cabal.project

```
source-repository-package
  type: git
  location: https://github.com/input-output-hk/ouroboros-network
  tag: 679c7da2079a5e9972a1c502b6a4d6af3eb76945
  --sha256: 138mqd5cv0b13giwjvlz3pr6l1cwgpn38n0q3m11mrjwwmmxl0mw
  subdir:
    monoidal-synchronisation
    network-mux
    ouroboros-consensus
    ouroboros-consensus-byron
    ouroboros-consensus-cardano
    ouroboros-consensus-protocol
    ouroboros-consensus-shelley
    ouroboros-network
    ouroboros-network-framework
    ouroboros-network-testing
    ouroboros-consensus-cardano-tools
```

This had the unintended effect of removing the executables `ouroboros-consensus-cardano-tools:exe:db-analyser` and `ouroboros-consensus-cardano-tools:exe:db-synthesizer` from the plan, since `ouroboros-consensus-cardano-tools` had no other reasons to be brought into the plan other than the, now removed, `source-repository-package` stanza.

Our nix setup relied on those executables being built as part of the cabal project so I added `extra-packages: ouroboros-consensus-cardano-tools` to have them back into the plan. This fixed the nix setup, but broke `cabal install`.

The package `cardano-cli` is a local package (in `packages:`) and now `cabal install cardano-cli` fails as described above.

We will be able to find a workaround but I am a bit surprised by this failure. I haven't yet looked at the code.

### PR DESCRIPTION
**Pull request by alt-romes**
Extra-packages listed in a cabal project are to be fetched from hackage,
and will be in memory as 'NamedPackages' rather than resolved to
'SpecificSourcePackage'.

On install, we need to make source-dists for all the specific source
packages, and fetch other packages from hackage. Since extra-packages
are already 'NamedPackages', we simply return them along the sdistize-d
specific source packages and the hackage source packages -- they will be
correctly fetched from Hackage from install.

Previously, cabal install <tgt> on a project with extra-packages would
fail because the branch of 'NamedPackage' for 'PackageSpecifier' was
simply unimplemented.

Fixes #8848

### CODE REVIEW

**Comment by alt-romes** [comment]
Rebased on #9706.

File: cabal-install/src/Distribution/Client/CmdInstall.hs [hunk 1]
```diff
@@ -649,7 +554,143 @@ installAction flags@NixStyleFlags{extraFlags = clientInstallFlags', ..} targetSt
...
+withProject verbosity cliConfig targetStrings installLibs = do
+  -- First, we need to learn about what's available to be installed.
+  baseCtx <- establishProjectBaseContext reducedVerbosity cliConfig InstallCommand
+
+  (pkgSpecs, targetSelectors) <-
+    -- If every target is already resolved to a package id, we can return without any further parsing.
+    if null unresolvedTargetStrings
+      then return (parsedPkgSpecs, parsedTargets)
+      else do
+        -- Anything that could not be parsed as a packageId (e.g. a pacakge name with not version or
```
Comment (geekosaur) [inline cabal-install/src/Distribution/Client/CmdInstall.hs:572]:
```suggestion
        -- Anything that could not be parsed as a packageId (e.g. a package name without a version or
```

File: cabal-install/src/Distribution/Client/CmdInstall.hs [hunk 2]
```diff
@@ -649,7 +554,143 @@ installAction flags@NixStyleFlags{extraFlags = clientInstallFlags', ..} targetSt
...
+        -- a target syntax using colons) must be resolved inside the project context.
+        (resolvedPkgSpecs, resolvedTargets) <-
+          resolveTargetSelectorsInProjectBaseContext verbosity baseCtx unresolvedTargetStrings targetFilter
+        return (resolvedPkgSpecs ++ parsedPkgSpecs, resolvedTargets ++ parsedTargets)
+
+  -- Apply the local configuration (e.g. cli flags) to all direct targets of install command, see note
+  -- in 'installAction'.
+  --
+  -- NOTE: If a target string had to be resolved inside the project conterxt, then pkgSpecs will include
```
Comment (geekosaur) [inline cabal-install/src/Distribution/Client/CmdInstall.hs:581]:
```suggestion
  -- NOTE: If a target string had to be resolved inside the project context, then pkgSpecs will include
```

**Review by geekosaur — APPROVED** [review]
Just some comment spelling nits.

**Comment by mpickering** [comment]
I talked about this with Rodrigo and this fix at least does not seem worse than what is currently there.

It would be good if there are some more tests for `extra-packages` in the testsuite as it wasn't very clear to us what the specification for this field was supposed to be used for. The documentation mentions something about ghci, but we couldn't get ghci to work very well with `extra-packages`.

**Comment by andreabedini** [comment]
> It would be good if there are some more tests for `extra-packages` in the testsuite as it wasn't very clear to us what the specification for this field was supposed to be used for. The documentation mentions something about ghci, but we couldn't get ghci to work very well with `extra-packages`.

I just extra-packages to add packages into the plan, so their presence affects the solver. I haven't thought about the implication for `cabal install`.

**Comment by alt-romes** [comment]
> I just extra-packages to add packages into the plan, so their presence affects the solver. I haven't thought about the implication for cabal install.

We mean how extra-packages should behave in general wrt other features like `build` or `repl`..

For `install` the behavior should likely be what I've implemented in this patch, which is to install the specified install target (be it source, extra packages, or from hackage...)

**Review by ffaf1 — APPROVED** [review]

**Comment by ffaf1** [comment]
@mergify backport 3.12
