### PR TITLE
Fix multi-repl when only building some internal library targets

### LINKED ISSUE #10775: "Error: Dependency on unbuildable library" with three internal libraries and `--enable-multi-repl`
**Describe the bug**

Given three internal libraries `x`, `y`, and `z`, where `z` depends on both `x` and `y`, `cabal repl --enable-multi-repl x z` fails with:

```
Error: Dependency on unbuildable library 'x' from foo
```

Modifying `y` to depend on `x` causes that `cabal repl` invocation to succeed.

Here is a concrete `foo.cabal` to demonstrate:

```cabal
cabal-version: 3.14

name:           foo
version:        0.1.0.0
build-type:     Simple

library x
  exposed-modules:
      X
  hs-source-dirs:
      components/x
  build-depends:
      base

library y
  exposed-modules:
      Y
  hs-source-dirs:
      components/y
  build-depends:
      base
    -- uncommenting this causes 'cabal repl --enable-multi-repl x z`' to succeed
    -- , foo:x

library z
  exposed-modules:
      Z
  hs-source-dirs:
      components/z
  build-depends:
      base
    , foo:x
    , foo:y
```

**To Reproduce**

Run `cabal repl --enable-multi-repl x z` with the above `foo.cabal` file.

I've created a repository at https://github.com/nspin/cabal-multi-repl-bug-repro with all the necessary files, instructions, and a Nix shell.

**Expected behavior**

I would expect this `cabal repl` invocation to succeed.

**System information**

 - Operating system: NixOS
 - `cabal`, `ghc` versions: `cabal` version 3.14.1.0, `ghc`  version 9.8.4

**Additional context**

Could be related to https://github.com/haskell/cabal/issues/6470 from 2019.

### PR DESCRIPTION
**Pull request by mpickering**
When combining together --dependency and --promised-dependency flags, we were using `Map.union` in the wrong place. If you had a dependency and promised-dependency from the same package (ie when using an internal library) then the promised dependency wouldn't be taken into account.

The fix is straightforward, don't use `Map.union`. First create a list of everything and then create a map using `fromListWith`.

Fixes #10775

Please read [Github PR Conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions) and then fill in *one* of these two templates.

---

**Template Α: This PR modifies [behaviour or interface](https://github.com/cabalism/cabal/blob/master/CONTRIBUTING.md#changelog)**

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
  * [ ] [Is the change significant?](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#is-my-change-significant) If so, remember to add `significance: significant` in the changelog file.
* [] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [x] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

---

**Template B: This PR does not modify behaviour or interface**

*E.g. the PR only touches documentation or tests, does refactorings, etc.*

Include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).

### CODE REVIEW

**Review by ulysses4ever — APPROVED** [review]
LGTM, thanks!

File: Cabal/src/Distribution/Backpack/Configure.hs [hunk 1]
```diff
@@ -113,10 +115,10 @@ configureComponentLocalBuildInfos
               )
             | pkg <- prePkgDeps
             ]
-            `Map.union` Map.fromListWith
-              Map.union
+              ++
+              -- Promised dependencies
               [ (pkg, Map.singleton (ann_cname aid) aid)
-              | ConfiguredPromisedComponent pkg aid <- promisedPkgDeps
+              | ConfiguredPromisedComponent pkg aid <- (promisedPkgDeps)
```
Comment (MangoIV) [inline Cabal/src/Distribution/Backpack/Configure.hs:121]:
```suggestion
              | ConfiguredPromisedComponent pkg aid <- promisedPkgDeps
```

**Review by MangoIV — APPROVED** [review]
I don't have any say but here's my review anyway: looks good to me!

**Review by Mikolaj — APPROVED** [review]
LGTM

**Comment by Mikolaj** [comment]
@mpickering: would you like to submit this for merging once you made the final tweaks?

**Comment by Mikolaj** [comment]
@mpickering: a humble ping?

**Comment by Mikolaj** [comment]
@mergify backport 3.14
