### PR TITLE
Pass `ld-options` through to GHC

### LINKED ISSUE #4925: ld-options is not taken into account when passed by command line or cabal.project.local
Hello,

While migrating some project from Stack to Cabal new-style I stumbled upon an issue regarding the ld-options field, which is not taken into account into command line and cabal.project.local but is, if added directly into xxx.cabal file of the project.

My goal is to compile the binary of the project with static linking instead of the standard dynamic one.
To do so, I am following those two steps:

1.  Do a specific configure
```
cabal new-configure --disable-executable-dynamic --ld-options='-static' --ghc-options='-fPIC -fllvm -split-sections'
```
2. Do the build
```
cabal new-build
```

After the build finish, sadly the final executable is still dinamicaly linked 
```
/mnt/greenclip # ldd /mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip
        /lib/ld-musl-x86_64.so.1 (0x55c3fe225000)
        libX11.so.6 => /usr/lib/libX11.so.6 (0x7f940ea6a000)
        libxcb.so.1 => /usr/lib/libxcb.so.1 (0x7f940e844000)
        libXau.so.6 => /usr/lib/libXau.so.6 (0x7f940e641000)
        libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x7f940e43b000)
        libXrandr.so.2 => /usr/lib/libXrandr.so.2 (0x7f940e231000)
        libXext.so.6 => /usr/lib/libXext.so.6 (0x7f940e021000)
        libgmp.so.10 => /usr/lib/libgmp.so.10 (0x7f940ddbd000)
        libffi.so.6 => /usr/lib/libffi.so.6 (0x7f940dbb5000)
        libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x55c3fe225000)
        libXrender.so.1 => /usr/lib/libXrender.so.1 (0x7f940d9ab000)

```

The result is the same if we pass the configuration to new-build as so
```
cabal new-build --ld-options='-static'
```

here the output of cabal -v 
```
/root/.cabal/bin/cabal act-as-setup --build-type=Simple -- configure
--verbose=2
--builddir=/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip
--ghc --prefix=/root/.cabal --bindir=/root/.cabal/bin
--libdir=/root/.cabal/lib/x86_64-linux-ghc-8.0.2/greenclip-2.0.0-inplace-greenclip
--libsubdir= --dynlibdir=/root/.cabal/lib/x86_64-linux-ghc-8.0.2
--libexecdir=/root/.cabal/libexec/x86_64-linux-ghc-8.0.2/greenclip-2.0.0
--libexecsubdir=
--datadir=/root/.cabal/share/x86_64-linux-ghc-8.0.2/greenclip-2.0.0
--datasubdir=
--docdir=/root/.cabal/share/doc/x86_64-linux-ghc-8.0.2/greenclip-2.0.0
--htmldir=/root/.cabal/share/doc/x86_64-linux-ghc-8.0.2/greenclip-2.0.0/html
--haddockdir=/root/.cabal/share/doc/x86_64-linux-ghc-8.0.2/greenclip-2.0.0/html
--sysconfdir=/root/.cabal/etc --enable-library-vanilla
--disable-library-profiling --enable-shared --disable-executable-dynamic
--disable-profiling --profiling-detail=default
--library-profiling-detail=default --enable-optimization --disable-debug-info
--disable-library-for-ghci --disable-split-objs --disable-executable-stripping
--disable-library-stripping --package-db=clear --package-db=global
--package-db=/root/.cabal/store/ghc-8.0.2/package.db
--package-db=/mnt/greenclip/dist-newstyle/packagedb/ghc-8.0.2
--cid=greenclip-2.0.0-inplace-greenclip --extra-prog-path=/root/.cabal/bin
--dependency=base=base-4.9.1.0
--dependency=protolude=protolude-0.2-c53bf72e4f41aa227abef214396e7b501c06d3dae194a0f95a0803881df2840e
--dependency=exceptions=exceptions-0.8.3-99df7fb1091e82595f8751da3e3af1cd171c7de1921f797c8cff3ba91ffbe7fb
--dependency=bytestring=bytestring-0.10.8.1
--dependency=text=text-1.2.2.2-8dc9a27ecc7d86c9dacc1255b386b9059d5ae508d3cebdda054efbca38ed4a30
--dependency=vector=vector-0.12.0.1-80b03ad733196f0c3ccac3c3ff0300000efd98a9c471f70d7b74b45be9251148
--dependency=hashable=hashable-1.2.6.1-96c00ce9d2eb5dd6361b4db269be00e167ed4fe746cb0a1d64ccd0f4a0426239
--dependency=binary=binary-0.8.3.0
--dependency=microlens=microlens-0.4.8.1-f929d694e6c04256470f468b607ed297de07735e53576b7536c21d7be72a2d6d
--dependency=microlens-mtl=microlens-mtl-0.1.11.0-bdac7266c988b74d81cf60e03d24df2c8fb6d2c5351451f69c8d06e31e94d453
--dependency=directory=directory-1.3.0.0 --dependency=unix=unix-2.7.2.1
--dependency=wordexp=wordexp-0.2.0.0-411de64aea6f9aff20aeca21e9e72d8f8a044b5f571214e5933a865c073a768d
--dependency=X11=X11-1.8-2e8690b52cae71974ff8f6b53277c7da9f070360d3543201d95a1a2f5bbd5197
--disable-coverage --exact-configuration --with-ghc=/usr/bin/ghc
--with-ghc-pkg=/usr/bin/ghc-pkg --ghc-option=-fPIC --ghc-option=-fllvm
--ghc-option=-split-sections --ld-option=-static exe:greenclip
...
/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip-tmp
/usr/bin/ghc --make -no-link -fbuilding-cabal-package -O -static -outputdir /mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip-tmp -odir /mnt/greenclip/
dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip-tmp -hidir /mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/gre
enclip-tmp -stubdir /mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip-tmp -i -i/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.
0/c/greenclip/build/greenclip/greenclip-tmp -isrc -i/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/autogen -i/mnt/greenclip/dist-newstyle/build/x86_64-linux/g
hc-8.0.2/greenclip-2.0.0/c/greenclip/build/global-autogen -I/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/autogen -I/mnt/greenclip/dist-newstyle/build/x86_64
-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/global-autogen -I/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip-tmp -optP-include -optP/mnt/green
clip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/autogen/cabal_macros.h -hide-all-packages -no-user-package-db -package-db /root/.cabal/store/ghc-8.0.2/package.db -packag
e-db /mnt/greenclip/dist-newstyle/packagedb/ghc-8.0.2 -package-db /mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/package.conf.inplace -package-id base-4.9.1.0 -package-id pro
tolude-0.2-c53bf72e4f41aa227abef214396e7b501c06d3dae194a0f95a0803881df2840e -package-id exceptions-0.8.3-99df7fb1091e82595f8751da3e3af1cd171c7de1921f797c8cff3ba91ffbe7fb -package-id bytestring-0.10.8.1 -package-id
 text-1.2.2.2-8dc9a27ecc7d86c9dacc1255b386b9059d5ae508d3cebdda054efbca38ed4a30 -package-id vector-0.12.0.1-80b03ad733196f0c3ccac3c3ff0300000efd98a9c471f70d7b74b45be9251148 -package-id hashable-1.2.6.1-96c00ce9d2eb
5dd6361b4db269be00e167ed4fe746cb0a1d64ccd0f4a0426239 -package-id binary-0.8.3.0 -package-id microlens-0.4.8.1-f929d694e6c04256470f468b607ed297de07735e53576b7536c21d7be72a2d6d -package-id microlens-mtl-0.1.11.0-bda
c7266c988b74d81cf60e03d24df2c8fb6d2c5351451f69c8d06e31e94d453 -package-id directory-1.3.0.0 -package-id unix-2.7.2.1 -package-id wordexp-0.2.0.0-411de64aea6f9aff20aeca21e9e72d8f8a044b5f571214e5933a865c073a768d -pa
ckage-id X11-1.8-2e8690b52cae71974ff8f6b53277c7da9f070360d3543201d95a1a2f5bbd5197 -XHaskell2010 Clipboard src/Main.hs -Wall -O3 -fPIC -fllvm -split-sections
Linking...
/usr/bin/ghc --make -fbuilding-cabal-package -O -static -outputdir /mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip-tmp -odir /mnt/greenclip/dist-news
tyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip-tmp -hidir /mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip-tm
p -stubdir /mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip-tmp -i -i/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/green
clip/build/greenclip/greenclip-tmp -isrc -i/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/autogen -i/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/
greenclip-2.0.0/c/greenclip/build/global-autogen -I/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/autogen -I/mnt/greenclip/dist-newstyle/build/x86_64-linux/gh
c-8.0.2/greenclip-2.0.0/c/greenclip/build/global-autogen -I/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip-tmp -optP-include -optP/mnt/greenclip/dist
-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/autogen/cabal_macros.h -lX11 -lxcb -lXau -lXdmcp -hide-all-packages -no-user-package-db -package-db /root/.cabal/store/ghc-8.0.2/p
ackage.db -package-db /mnt/greenclip/dist-newstyle/packagedb/ghc-8.0.2 -package-db /mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/package.conf.inplace -package-id base-4.9.1.
0 -package-id protolude-0.2-c53bf72e4f41aa227abef214396e7b501c06d3dae194a0f95a0803881df2840e -package-id exceptions-0.8.3-99df7fb1091e82595f8751da3e3af1cd171c7de1921f797c8cff3ba91ffbe7fb -package-id bytestring-0.1
0.8.1 -package-id text-1.2.2.2-8dc9a27ecc7d86c9dacc1255b386b9059d5ae508d3cebdda054efbca38ed4a30 -package-id vector-0.12.0.1-80b03ad733196f0c3ccac3c3ff0300000efd98a9c471f70d7b74b45be9251148 -package-id hashable-1.2
.6.1-96c00ce9d2eb5dd6361b4db269be00e167ed4fe746cb0a1d64ccd0f4a0426239 -package-id binary-0.8.3.0 -package-id microlens-0.4.8.1-f929d694e6c04256470f468b607ed297de07735e53576b7536c21d7be72a2d6d -package-id microlens
-mtl-0.1.11.0-bdac7266c988b74d81cf60e03d24df2c8fb6d2c5351451f69c8d06e31e94d453 -package-id directory-1.3.0.0 -package-id unix-2.7.2.1 -package-id wordexp-0.2.0.0-411de64aea6f9aff20aeca21e9e72d8f8a044b5f571214e5933
a865c073a768d -package-id X11-1.8-2e8690b52cae71974ff8f6b53277c7da9f070360d3543201d95a1a2f5bbd5197 -XHaskell2010 Clipboard src/Main.hs -o /mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c
/greenclip/build/greenclip/greenclip -Wall -O3 -fPIC -fllvm -split-sections

```

and the output of ld in verbose mode (note the  -dynamic-linker)
```
Linking /mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip ...
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-alpine-linux-musl/6.2.1/lto-wrapper
Target: x86_64-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-6.2.0/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=x86_64-alpine-linux-musl --host=x86_64-alpine-linux-musl --target=x86_64-alpine-linux-musl --with-pkgversion='Alpine 6.2.1' --enable-checking=release --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-cloog-backend --enable-languages=c,c++,objc,java,fortran,ada --disable-libssp --disable-libmpx --disable-libmudflap --disable-libsanitizer --enable-shared --enable-threads --enable-tls --with-system-zlib --with-linker-hash-style=gnu
Thread model: posix
gcc version 6.2.1 20160822 (Alpine 6.2.1)
COMPILER_PATH=/usr/libexec/gcc/x86_64-alpine-linux-musl/6.2.1/:/usr/libexec/gcc/x86_64-alpine-linux-musl/6.2.1/:/usr/libexec/gcc/x86_64-alpine-linux-musl/:/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/:/usr/lib/gcc/x86_64-alpine-linux-musl/:/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../../x86_64-alpine-linux-musl/bin/
LIBRARY_PATH=/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/:/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../../x86_64-alpine-linux-musl/lib/../lib/:/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../../lib/:/lib/../lib/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../../x86_64-alpine-linux-musl/lib/:/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-fno-stack-protector' '-D' 'TABLES_NEXT_TO_CODE' '-v' '-o' '/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip' '-no-pie' '-L/root/.cabal/store/ghc-8.0.2/X11-1.8-2e8690b52cae71974ff8f6b53277c7da9f070360d3543201d95a1a2f5bbd5197/lib' '-L/root/.cabal/store/ghc-8.0.2/data-default-0.7.1.1-1d6731841f6d4a20a28fdbb40d8ed8720152355a7a18f9e5ff740d7f8dc3cd3d/lib' '-L/root/.cabal/store/ghc-8.0.2/data-default-instances-old-locale-0.0.1-cdbfd2d06c51c8bc4a9b5a371d3d27606ab0c4c81ec5540193e4c95568c2c91f/lib' '-L/root/.cabal/store/ghc-8.0.2/old-locale-1.0.0.7-70c2803c804464839444221fd353ab6f9e047590ea834322a5f041e9dba1bc49/lib' '-L/root/.cabal/store/ghc-8.0.2/data-default-instances-dlist-0.0.1-3b1b94e89dea89d74187347544b050af62c1f3137a5b451b0946fe5350bb88a4/lib' '-L/root/.cabal/store/ghc-8.0.2/dlist-0.8.0.3-493d8062a8ea2e0d95e1183b076874b1fc5b797ce13be040b36e099ed6f1b6c8/lib' '-L/root/.cabal/store/ghc-8.0.2/data-default-instances-containers-0.0.1-f77fa4937ea7b1523d543ecd32f55772d2e044bcec586d8bf092fbd1dbe0e579/lib' '-L/root/.cabal/store/ghc-8.0.2/data-default-class-0.1.2.0-f1dddfa0fcfc68706933e810083fe7415c43e226c8ac0eb2211a30a87248751d/lib' '-L/root/.cabal/store/ghc-8.0.2/wordexp-0.2.0.0-411de64aea6f9aff20aeca21e9e72d8f8a044b5f571214e5933a865c073a768d/lib' '-L/root/.cabal/store/ghc-8.0.2/semigroups-0.18.3-c52b824fc1c06b35ce32f544444fec565c778ccf420451dc1282113e034b8281/lib' '-L/usr/lib/ghc-8.0.2/directory-1.3.0.0' '-L/usr/lib/ghc-8.0.2/unix-2.7.2.1' '-L/usr/lib/ghc-8.0.2/time-1.6.0.1' '-L/usr/lib/ghc-8.0.2/filepath-1.4.1.1' '-L/root/.cabal/store/ghc-8.0.2/microlens-mtl-0.1.11.0-bdac7266c988b74d81cf60e03d24df2c8fb6d2c5351451f69c8d06e31e94d453/lib' '-L/root/.cabal/store/ghc-8.0.2/microlens-0.4.8.1-f929d694e6c04256470f468b607ed297de07735e53576b7536c21d7be72a2d6d/lib' '-L/root/.cabal/store/ghc-8.0.2/vector-0.12.0.1-80b03ad733196f0c3ccac3c3ff0300000efd98a9c471f70d7b74b45be9251148/lib' '-L/root/.cabal/store/ghc-8.0.2/primitive-0.6.2.0-44275745c4df1b2f5395fe1440d73a10ae9d5f3578ec835e40642a8288763d18/lib' '-L/root/.cabal/store/ghc-8.0.2/exceptions-0.8.3-99df7fb1091e82595f8751da3e3af1cd171c7de1921f797c8cff3ba91ffbe7fb/lib' '-L/root/.cabal/store/ghc-8.0.2/transformers-compat-0.5.1.4-7be4c4d6cde89ab173539e66812807feecdbd2bdd2efc145f3dd2e005d8838e3/lib' '-L/usr/lib/ghc-8.0.2/template-haskell-2.11.1.0' '-L/usr/lib/ghc-8.0.2/pretty-1.1.3.3' '-L/usr/lib/ghc-8.0.2/ghc-boot-th-8.0.2' '-L/root/.cabal/store/ghc-8.0.2/protolude-0.2-c53bf72e4f41aa227abef214396e7b501c06d3dae194a0f95a0803881df2840e/lib' '-L/root/.cabal/store/ghc-8.0.2/safe-0.3.15-1af51dd522929d45c1a66eef6a529e23e2ae9bb24ae6473959e9d99a0e718546/lib' '-L/root/.cabal/store/ghc-8.0.2/mtl-2.2.1-e2c9cbe58118c91f775f4633409c5854e4e34cf118cdb44c6c47d55e029751db/lib' '-L/usr/lib/ghc-8.0.2/transformers-0.5.2.0' '-L/root/.cabal/store/ghc-8.0.2/hashable-1.2.6.1-96c00ce9d2eb5dd6361b4db269be00e167ed4fe746cb0a1d64ccd0f4a0426239/lib' '-L/root/.cabal/store/ghc-8.0.2/text-1.2.2.2-8dc9a27ecc7d86c9dacc1255b386b9059d5ae508d3cebdda054efbca38ed4a30/lib' '-L/usr/lib/ghc-8.0.2/binary-0.8.3.0' '-L/usr/lib/ghc-8.0.2/bytestring-0.10.8.1' '-L/usr/lib/ghc-8.0.2/containers-0.5.7.1' '-L/usr/lib/ghc-8.0.2/deepseq-1.4.2.0' '-L/root/.cabal/store/ghc-8.0.2/async-2.1.1.1-cee2bad558628b433d25a6de758678702e9cbc0056c5553c3b863155e2f9b5c7/lib' '-L/root/.cabal/store/ghc-8.0.2/stm-2.4.4.1-4c5351fe1cfc4fe9a86154164bf9b602574d00b424e0eeef53f628baadaf6a8f/lib' '-L/usr/lib/ghc-8.0.2/array-0.5.1.1' '-L/usr/lib/ghc-8.0.2/base-4.9.1.0' '-L/usr/lib/ghc-8.0.2/integer-gmp-1.0.0.1' '-L/usr/lib/ghc-8.0.2/ghc-prim-0.5.0.0' '-L/usr/lib/ghc-8.0.2/rts' '-L/usr/lib/../lib' '-mtune=generic' '-march=x86-64'
 /usr/libexec/gcc/x86_64-alpine-linux-musl/6.2.1/collect2 -plugin /usr/libexec/gcc/x86_64-alpine-linux-musl/6.2.1/liblto_plugin.so -plugin-opt=/usr/libexec/gcc/x86_64-alpine-linux-musl/6.2.1/lto-wrapper -plugin-opt=-fresolution=/tmp/ccnBMedL.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --eh-frame-hdr --hash-style=gnu -m elf_x86_64 --as-needed -dynamic-linker /lib/ld-musl-x86_64.so.1 -z relro -z now -o /mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip /usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../../lib/crt1.o /usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../../lib/crti.o /usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/crtbegin.o -L/root/.cabal/store/ghc-8.0.2/X11-1.8-2e8690b52cae71974ff8f6b53277c7da9f070360d3543201d95a1a2f5bbd5197/lib -L/root/.cabal/store/ghc-8.0.2/data-default-0.7.1.1-1d6731841f6d4a20a28fdbb40d8ed8720152355a7a18f9e5ff740d7f8dc3cd3d/lib -L/root/.cabal/store/ghc-8.0.2/data-default-instances-old-locale-0.0.1-cdbfd2d06c51c8bc4a9b5a371d3d27606ab0c4c81ec5540193e4c95568c2c91f/lib -L/root/.cabal/store/ghc-8.0.2/old-locale-1.0.0.7-70c2803c804464839444221fd353ab6f9e047590ea834322a5f041e9dba1bc49/lib -L/root/.cabal/store/ghc-8.0.2/data-default-instances-dlist-0.0.1-3b1b94e89dea89d74187347544b050af62c1f3137a5b451b0946fe5350bb88a4/lib -L/root/.cabal/store/ghc-8.0.2/dlist-0.8.0.3-493d8062a8ea2e0d95e1183b076874b1fc5b797ce13be040b36e099ed6f1b6c8/lib -L/root/.cabal/store/ghc-8.0.2/data-default-instances-containers-0.0.1-f77fa4937ea7b1523d543ecd32f55772d2e044bcec586d8bf092fbd1dbe0e579/lib -L/root/.cabal/store/ghc-8.0.2/data-default-class-0.1.2.0-f1dddfa0fcfc68706933e810083fe7415c43e226c8ac0eb2211a30a87248751d/lib -L/root/.cabal/store/ghc-8.0.2/wordexp-0.2.0.0-411de64aea6f9aff20aeca21e9e72d8f8a044b5f571214e5933a865c073a768d/lib -L/root/.cabal/store/ghc-8.0.2/semigroups-0.18.3-c52b824fc1c06b35ce32f544444fec565c778ccf420451dc1282113e034b8281/lib -L/usr/lib/ghc-8.0.2/directory-1.3.0.0 -L/usr/lib/ghc-8.0.2/unix-2.7.2.1 -L/usr/lib/ghc-8.0.2/time-1.6.0.1 -L/usr/lib/ghc-8.0.2/filepath-1.4.1.1 -L/root/.cabal/store/ghc-8.0.2/microlens-mtl-0.1.11.0-bdac7266c988b74d81cf60e03d24df2c8fb6d2c5351451f69c8d06e31e94d453/lib -L/root/.cabal/store/ghc-8.0.2/microlens-0.4.8.1-f929d694e6c04256470f468b607ed297de07735e53576b7536c21d7be72a2d6d/lib -L/root/.cabal/store/ghc-8.0.2/vector-0.12.0.1-80b03ad733196f0c3ccac3c3ff0300000efd98a9c471f70d7b74b45be9251148/lib -L/root/.cabal/store/ghc-8.0.2/primitive-0.6.2.0-44275745c4df1b2f5395fe1440d73a10ae9d5f3578ec835e40642a8288763d18/lib -L/root/.cabal/store/ghc-8.0.2/exceptions-0.8.3-99df7fb1091e82595f8751da3e3af1cd171c7de1921f797c8cff3ba91ffbe7fb/lib -L/root/.cabal/store/ghc-8.0.2/transformers-compat-0.5.1.4-7be4c4d6cde89ab173539e66812807feecdbd2bdd2efc145f3dd2e005d8838e3/lib -L/usr/lib/ghc-8.0.2/template-haskell-2.11.1.0 -L/usr/lib/ghc-8.0.2/pretty-1.1.3.3 -L/usr/lib/ghc-8.0.2/ghc-boot-th-8.0.2 -L/root/.cabal/store/ghc-8.0.2/protolude-0.2-c53bf72e4f41aa227abef214396e7b501c06d3dae194a0f95a0803881df2840e/lib -L/root/.cabal/store/ghc-8.0.2/safe-0.3.15-1af51dd522929d45c1a66eef6a529e23e2ae9bb24ae6473959e9d99a0e718546/lib -L/root/.cabal/store/ghc-8.0.2/mtl-2.2.1-e2c9cbe58118c91f775f4633409c5854e4e34cf118cdb44c6c47d55e029751db/lib -L/usr/lib/ghc-8.0.2/transformers-0.5.2.0 -L/root/.cabal/store/ghc-8.0.2/hashable-1.2.6.1-96c00ce9d2eb5dd6361b4db269be00e167ed4fe746cb0a1d64ccd0f4a0426239/lib -L/root/.cabal/store/ghc-8.0.2/text-1.2.2.2-8dc9a27ecc7d86c9dacc1255b386b9059d5ae508d3cebdda054efbca38ed4a30/lib -L/usr/lib/ghc-8.0.2/binary-0.8.3.0 -L/usr/lib/ghc-8.0.2/bytestring-0.10.8.1 -L/usr/lib/ghc-8.0.2/containers-0.5.7.1 -L/usr/lib/ghc-8.0.2/deepseq-1.4.2.0 -L/root/.cabal/store/ghc-8.0.2/async-2.1.1.1-cee2bad558628b433d25a6de758678702e9cbc0056c5553c3b863155e2f9b5c7/lib -L/root/.cabal/store/ghc-8.0.2/stm-2.4.4.1-4c5351fe1cfc4fe9a86154164bf9b602574d00b424e0eeef53f628baadaf6a8f/lib -L/usr/lib/ghc-8.0.2/array-0.5.1.1 -L/usr/lib/ghc-8.0.2/base-4.9.1.0 -L/usr/lib/ghc-8.0.2/integer-gmp-1.0.0.1 -L/usr/lib/ghc-8.0.2/ghc-prim-0.5.0.0 -L/usr/lib/ghc-8.0.2/rts -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1 -L/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../../x86_64-alpine-linux-musl/lib/../lib -L/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../../x86_64-alpine-linux-musl/lib -L/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../.. @/tmp/ccClpCpI -lssp_nonshared -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/crtend.o /usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../../lib/crtn.o
COLLECT_GCC_OPTIONS='-fno-stack-protector' '-D' 'TABLES_NEXT_TO_CODE' '-v' '-o' '/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip' '-no-pie' '-L/root/.cabal/store/ghc-8.0.2/X11-1.8-2e8690b52cae71974ff8f6b53277c7da9f070360d3543201d95a1a2f5bbd5197/lib' '-L/root/.cabal/store/ghc-8.0.2/data-default-0.7.1.1-1d6731841f6d4a20a28fdbb40d8ed8720152355a7a18f9e5ff740d7f8dc3cd3d/lib' '-L/root/.cabal/store/ghc-8.0.2/data-default-instances-old-locale-0.0.1-cdbfd2d06c51c8bc4a9b5a371d3d27606ab0c4c81ec5540193e4c95568c2c91f/lib' '-L/root/.cabal/store/ghc-8.0.2/old-locale-1.0.0.7-70c2803c804464839444221fd353ab6f9e047590ea834322a5f041e9dba1bc49/lib' '-L/root/.cabal/store/ghc-8.0.2/data-default-instances-dlist-0.0.1-3b1b94e89dea89d74187347544b050af62c1f3137a5b451b0946fe5350bb88a4/lib' '-L/root/.cabal/store/ghc-8.0.2/dlist-0.8.0.3-493d8062a8ea2e0d95e1183b076874b1fc5b797ce13be040b36e099ed6f1b6c8/lib' '-L/root/.cabal/store/ghc-8.0.2/data-default-instances-containers-0.0.1-f77fa4937ea7b1523d543ecd32f55772d2e044bcec586d8bf092fbd1dbe0e579/lib' '-L/root/.cabal/store/ghc-8.0.2/data-default-class-0.1.2.0-f1dddfa0fcfc68706933e810083fe7415c43e226c8ac0eb2211a30a87248751d/lib' '-L/root/.cabal/store/ghc-8.0.2/wordexp-0.2.0.0-411de64aea6f9aff20aeca21e9e72d8f8a044b5f571214e5933a865c073a768d/lib' '-L/root/.cabal/store/ghc-8.0.2/semigroups-0.18.3-c52b824fc1c06b35ce32f544444fec565c778ccf420451dc1282113e034b8281/lib' '-L/usr/lib/ghc-8.0.2/directory-1.3.0.0' '-L/usr/lib/ghc-8.0.2/unix-2.7.2.1' '-L/usr/lib/ghc-8.0.2/time-1.6.0.1' '-L/usr/lib/ghc-8.0.2/filepath-1.4.1.1' '-L/root/.cabal/store/ghc-8.0.2/microlens-mtl-0.1.11.0-bdac7266c988b74d81cf60e03d24df2c8fb6d2c5351451f69c8d06e31e94d453/lib' '-L/root/.cabal/store/ghc-8.0.2/microlens-0.4.8.1-f929d694e6c04256470f468b607ed297de07735e53576b7536c21d7be72a2d6d/lib' '-L/root/.cabal/store/ghc-8.0.2/vector-0.12.0.1-80b03ad733196f0c3ccac3c3ff0300000efd98a9c471f70d7b74b45be9251148/lib' '-L/root/.cabal/store/ghc-8.0.2/primitive-0.6.2.0-44275745c4df1b2f5395fe1440d73a10ae9d5f3578ec835e40642a8288763d18/lib' '-L/root/.cabal/store/ghc-8.0.2/exceptions-0.8.3-99df7fb1091e82595f8751da3e3af1cd171c7de1921f797c8cff3ba91ffbe7fb/lib' '-L/root/.cabal/store/ghc-8.0.2/transformers-compat-0.5.1.4-7be4c4d6cde89ab173539e66812807feecdbd2bdd2efc145f3dd2e005d8838e3/lib' '-L/usr/lib/ghc-8.0.2/template-haskell-2.11.1.0' '-L/usr/lib/ghc-8.0.2/pretty-1.1.3.3' '-L/usr/lib/ghc-8.0.2/ghc-boot-th-8.0.2' '-L/root/.cabal/store/ghc-8.0.2/protolude-0.2-c53bf72e4f41aa227abef214396e7b501c06d3dae194a0f95a0803881df2840e/lib' '-L/root/.cabal/store/ghc-8.0.2/safe-0.3.15-1af51dd522929d45c1a66eef6a529e23e2ae9bb24ae6473959e9d99a0e718546/lib' '-L/root/.cabal/store/ghc-8.0.2/mtl-2.2.1-e2c9cbe58118c91f775f4633409c5854e4e34cf118cdb44c6c47d55e029751db/lib' '-L/usr/lib/ghc-8.0.2/transformers-0.5.2.0' '-L/root/.cabal/store/ghc-8.0.2/hashable-1.2.6.1-96c00ce9d2eb5dd6361b4db269be00e167ed4fe746cb0a1d64ccd0f4a0426239/lib' '-L/root/.cabal/store/ghc-8.0.2/text-1.2.2.2-8dc9a27ecc7d86c9dacc1255b386b9059d5ae508d3cebdda054efbca38ed4a30/lib' '-L/usr/lib/ghc-8.0.2/binary-0.8.3.0' '-L/usr/lib/ghc-8.0.2/bytestring-0.10.8.1' '-L/usr/lib/ghc-8.0.2/containers-0.5.7.1' '-L/usr/lib/ghc-8.0.2/deepseq-1.4.2.0' '-L/root/.cabal/store/ghc-8.0.2/async-2.1.1.1-cee2bad558628b433d25a6de758678702e9cbc0056c5553c3b863155e2f9b5c7/lib' '-L/root/.cabal/store/ghc-8.0.2/stm-2.4.4.1-4c5351fe1cfc4fe9a86154164bf9b602574d00b424e0eeef53f628baadaf6a8f/lib' '-L/usr/lib/ghc-8.0.2/array-0.5.1.1' '-L/usr/lib/ghc-8.0.2/base-4.9.1.0' '-L/usr/lib/ghc-8.0.2/integer-gmp-1.0.0.1' '-L/usr/lib/ghc-8.0.2/ghc-prim-0.5.0.0' '-L/usr/lib/ghc-8.0.2/rts' '-L/usr/lib/../lib' '-mtune=generic' '-march=x86-64'
```

now if we override the .cabal file of the project and add the ld-options directly in it, ld is correctly told to link in static mode (note the -static instead -dynamic-linker)
```
Linking /mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip ...
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-alpine-linux-musl/6.2.1/lto-wrapper
Target: x86_64-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-6.2.0/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=x86_64-alpine-linux-musl --host=x86_64-alpine-linux-musl --target=x86_64-alpine-linux-musl --with-pkgversion='Alpine 6.2.1' --enable-checking=release --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-cloog-backend --enable-languages=c,c++,objc,java,fortran,ada --disable-libssp --disable-libmpx --disable-libmudflap --disable-libsanitizer --enable-shared --enable-threads --enable-tls --with-system-zlib --with-linker-hash-style=gnu
Thread model: posix
gcc version 6.2.1 20160822 (Alpine 6.2.1)
COMPILER_PATH=/usr/libexec/gcc/x86_64-alpine-linux-musl/6.2.1/:/usr/libexec/gcc/x86_64-alpine-linux-musl/6.2.1/:/usr/libexec/gcc/x86_64-alpine-linux-musl/:/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/:/usr/lib/gcc/x86_64-alpine-linux-musl/:/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../../x86_64-alpine-linux-musl/bin/
LIBRARY_PATH=/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/:/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../../x86_64-alpine-linux-musl/lib/../lib/:/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../../lib/:/lib/../lib/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../../x86_64-alpine-linux-musl/lib/:/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-fno-stack-protector' '-D' 'TABLES_NEXT_TO_CODE' '-v' '-static' '-o' '/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip' '-no-pie' '-L/root/.cabal/store/ghc-8.0.2/X11-1.8-2e8690b52cae71974ff8f6b53277c7da9f070360d3543201d95a1a2f5bbd5197/lib' '-L/root/.cabal/store/ghc-8.0.2/data-default-0.7.1.1-1d6731841f6d4a20a28fdbb40d8ed8720152355a7a18f9e5ff740d7f8dc3cd3d/lib' '-L/root/.cabal/store/ghc-8.0.2/data-default-instances-old-locale-0.0.1-cdbfd2d06c51c8bc4a9b5a371d3d27606ab0c4c81ec5540193e4c95568c2c91f/lib' '-L/root/.cabal/store/ghc-8.0.2/old-locale-1.0.0.7-70c2803c804464839444221fd353ab6f9e047590ea834322a5f041e9dba1bc49/lib' '-L/root/.cabal/store/ghc-8.0.2/data-default-instances-dlist-0.0.1-3b1b94e89dea89d74187347544b050af62c1f3137a5b451b0946fe5350bb88a4/lib' '-L/root/.cabal/store/ghc-8.0.2/dlist-0.8.0.3-493d8062a8ea2e0d95e1183b076874b1fc5b797ce13be040b36e099ed6f1b6c8/lib' '-L/root/.cabal/store/ghc-8.0.2/data-default-instances-containers-0.0.1-f77fa4937ea7b1523d543ecd32f55772d2e044bcec586d8bf092fbd1dbe0e579/lib' '-L/root/.cabal/store/ghc-8.0.2/data-default-class-0.1.2.0-f1dddfa0fcfc68706933e810083fe7415c43e226c8ac0eb2211a30a87248751d/lib' '-L/root/.cabal/store/ghc-8.0.2/wordexp-0.2.0.0-411de64aea6f9aff20aeca21e9e72d8f8a044b5f571214e5933a865c073a768d/lib' '-L/root/.cabal/store/ghc-8.0.2/semigroups-0.18.3-c52b824fc1c06b35ce32f544444fec565c778ccf420451dc1282113e034b8281/lib' '-L/usr/lib/ghc-8.0.2/directory-1.3.0.0' '-L/usr/lib/ghc-8.0.2/unix-2.7.2.1' '-L/usr/lib/ghc-8.0.2/time-1.6.0.1' '-L/usr/lib/ghc-8.0.2/filepath-1.4.1.1' '-L/root/.cabal/store/ghc-8.0.2/microlens-mtl-0.1.11.0-bdac7266c988b74d81cf60e03d24df2c8fb6d2c5351451f69c8d06e31e94d453/lib' '-L/root/.cabal/store/ghc-8.0.2/microlens-0.4.8.1-f929d694e6c04256470f468b607ed297de07735e53576b7536c21d7be72a2d6d/lib' '-L/root/.cabal/store/ghc-8.0.2/vector-0.12.0.1-80b03ad733196f0c3ccac3c3ff0300000efd98a9c471f70d7b74b45be9251148/lib' '-L/root/.cabal/store/ghc-8.0.2/primitive-0.6.2.0-44275745c4df1b2f5395fe1440d73a10ae9d5f3578ec835e40642a8288763d18/lib' '-L/root/.cabal/store/ghc-8.0.2/exceptions-0.8.3-99df7fb1091e82595f8751da3e3af1cd171c7de1921f797c8cff3ba91ffbe7fb/lib' '-L/root/.cabal/store/ghc-8.0.2/transformers-compat-0.5.1.4-7be4c4d6cde89ab173539e66812807feecdbd2bdd2efc145f3dd2e005d8838e3/lib' '-L/usr/lib/ghc-8.0.2/template-haskell-2.11.1.0' '-L/usr/lib/ghc-8.0.2/pretty-1.1.3.3' '-L/usr/lib/ghc-8.0.2/ghc-boot-th-8.0.2' '-L/root/.cabal/store/ghc-8.0.2/protolude-0.2-c53bf72e4f41aa227abef214396e7b501c06d3dae194a0f95a0803881df2840e/lib' '-L/root/.cabal/store/ghc-8.0.2/safe-0.3.15-1af51dd522929d45c1a66eef6a529e23e2ae9bb24ae6473959e9d99a0e718546/lib' '-L/root/.cabal/store/ghc-8.0.2/mtl-2.2.1-e2c9cbe58118c91f775f4633409c5854e4e34cf118cdb44c6c47d55e029751db/lib' '-L/usr/lib/ghc-8.0.2/transformers-0.5.2.0' '-L/root/.cabal/store/ghc-8.0.2/hashable-1.2.6.1-96c00ce9d2eb5dd6361b4db269be00e167ed4fe746cb0a1d64ccd0f4a0426239/lib' '-L/root/.cabal/store/ghc-8.0.2/text-1.2.2.2-8dc9a27ecc7d86c9dacc1255b386b9059d5ae508d3cebdda054efbca38ed4a30/lib' '-L/usr/lib/ghc-8.0.2/binary-0.8.3.0' '-L/usr/lib/ghc-8.0.2/bytestring-0.10.8.1' '-L/usr/lib/ghc-8.0.2/containers-0.5.7.1' '-L/usr/lib/ghc-8.0.2/deepseq-1.4.2.0' '-L/root/.cabal/store/ghc-8.0.2/async-2.1.1.1-cee2bad558628b433d25a6de758678702e9cbc0056c5553c3b863155e2f9b5c7/lib' '-L/root/.cabal/store/ghc-8.0.2/stm-2.4.4.1-4c5351fe1cfc4fe9a86154164bf9b602574d00b424e0eeef53f628baadaf6a8f/lib' '-L/usr/lib/ghc-8.0.2/array-0.5.1.1' '-L/usr/lib/ghc-8.0.2/base-4.9.1.0' '-L/usr/lib/ghc-8.0.2/integer-gmp-1.0.0.1' '-L/usr/lib/ghc-8.0.2/ghc-prim-0.5.0.0' '-L/usr/lib/ghc-8.0.2/rts' '-L/usr/lib/../lib' '-mtune=generic' '-march=x86-64'
 /usr/libexec/gcc/x86_64-alpine-linux-musl/6.2.1/collect2 -plugin /usr/libexec/gcc/x86_64-alpine-linux-musl/6.2.1/liblto_plugin.so -plugin-opt=/usr/libexec/gcc/x86_64-alpine-linux-musl/6.2.1/lto-wrapper -plugin-opt=-fresolution=/tmp/ccBFhKDk.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_eh -plugin-opt=-pass-through=-lc --hash-style=gnu -m elf_x86_64 --as-needed -static -z relro -z now -o /mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip /usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../../lib/crt1.o /usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../../lib/crti.o /usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/crtbeginT.o -L/root/.cabal/store/ghc-8.0.2/X11-1.8-2e8690b52cae71974ff8f6b53277c7da9f070360d3543201d95a1a2f5bbd5197/lib -L/root/.cabal/store/ghc-8.0.2/data-default-0.7.1.1-1d6731841f6d4a20a28fdbb40d8ed8720152355a7a18f9e5ff740d7f8dc3cd3d/lib -L/root/.cabal/store/ghc-8.0.2/data-default-instances-old-locale-0.0.1-cdbfd2d06c51c8bc4a9b5a371d3d27606ab0c4c81ec5540193e4c95568c2c91f/lib -L/root/.cabal/store/ghc-8.0.2/old-locale-1.0.0.7-70c2803c804464839444221fd353ab6f9e047590ea834322a5f041e9dba1bc49/lib -L/root/.cabal/store/ghc-8.0.2/data-default-instances-dlist-0.0.1-3b1b94e89dea89d74187347544b050af62c1f3137a5b451b0946fe5350bb88a4/lib -L/root/.cabal/store/ghc-8.0.2/dlist-0.8.0.3-493d8062a8ea2e0d95e1183b076874b1fc5b797ce13be040b36e099ed6f1b6c8/lib -L/root/.cabal/store/ghc-8.0.2/data-default-instances-containers-0.0.1-f77fa4937ea7b1523d543ecd32f55772d2e044bcec586d8bf092fbd1dbe0e579/lib -L/root/.cabal/store/ghc-8.0.2/data-default-class-0.1.2.0-f1dddfa0fcfc68706933e810083fe7415c43e226c8ac0eb2211a30a87248751d/lib -L/root/.cabal/store/ghc-8.0.2/wordexp-0.2.0.0-411de64aea6f9aff20aeca21e9e72d8f8a044b5f571214e5933a865c073a768d/lib -L/root/.cabal/store/ghc-8.0.2/semigroups-0.18.3-c52b824fc1c06b35ce32f544444fec565c778ccf420451dc1282113e034b8281/lib -L/usr/lib/ghc-8.0.2/directory-1.3.0.0 -L/usr/lib/ghc-8.0.2/unix-2.7.2.1 -L/usr/lib/ghc-8.0.2/time-1.6.0.1 -L/usr/lib/ghc-8.0.2/filepath-1.4.1.1 -L/root/.cabal/store/ghc-8.0.2/microlens-mtl-0.1.11.0-bdac7266c988b74d81cf60e03d24df2c8fb6d2c5351451f69c8d06e31e94d453/lib -L/root/.cabal/store/ghc-8.0.2/microlens-0.4.8.1-f929d694e6c04256470f468b607ed297de07735e53576b7536c21d7be72a2d6d/lib -L/root/.cabal/store/ghc-8.0.2/vector-0.12.0.1-80b03ad733196f0c3ccac3c3ff0300000efd98a9c471f70d7b74b45be9251148/lib -L/root/.cabal/store/ghc-8.0.2/primitive-0.6.2.0-44275745c4df1b2f5395fe1440d73a10ae9d5f3578ec835e40642a8288763d18/lib -L/root/.cabal/store/ghc-8.0.2/exceptions-0.8.3-99df7fb1091e82595f8751da3e3af1cd171c7de1921f797c8cff3ba91ffbe7fb/lib -L/root/.cabal/store/ghc-8.0.2/transformers-compat-0.5.1.4-7be4c4d6cde89ab173539e66812807feecdbd2bdd2efc145f3dd2e005d8838e3/lib -L/usr/lib/ghc-8.0.2/template-haskell-2.11.1.0 -L/usr/lib/ghc-8.0.2/pretty-1.1.3.3 -L/usr/lib/ghc-8.0.2/ghc-boot-th-8.0.2 -L/root/.cabal/store/ghc-8.0.2/protolude-0.2-c53bf72e4f41aa227abef214396e7b501c06d3dae194a0f95a0803881df2840e/lib -L/root/.cabal/store/ghc-8.0.2/safe-0.3.15-1af51dd522929d45c1a66eef6a529e23e2ae9bb24ae6473959e9d99a0e718546/lib -L/root/.cabal/store/ghc-8.0.2/mtl-2.2.1-e2c9cbe58118c91f775f4633409c5854e4e34cf118cdb44c6c47d55e029751db/lib -L/usr/lib/ghc-8.0.2/transformers-0.5.2.0 -L/root/.cabal/store/ghc-8.0.2/hashable-1.2.6.1-96c00ce9d2eb5dd6361b4db269be00e167ed4fe746cb0a1d64ccd0f4a0426239/lib -L/root/.cabal/store/ghc-8.0.2/text-1.2.2.2-8dc9a27ecc7d86c9dacc1255b386b9059d5ae508d3cebdda054efbca38ed4a30/lib -L/usr/lib/ghc-8.0.2/binary-0.8.3.0 -L/usr/lib/ghc-8.0.2/bytestring-0.10.8.1 -L/usr/lib/ghc-8.0.2/containers-0.5.7.1 -L/usr/lib/ghc-8.0.2/deepseq-1.4.2.0 -L/root/.cabal/store/ghc-8.0.2/async-2.1.1.1-cee2bad558628b433d25a6de758678702e9cbc0056c5553c3b863155e2f9b5c7/lib -L/root/.cabal/store/ghc-8.0.2/stm-2.4.4.1-4c5351fe1cfc4fe9a86154164bf9b602574d00b424e0eeef53f628baadaf6a8f/lib -L/usr/lib/ghc-8.0.2/array-0.5.1.1 -L/usr/lib/ghc-8.0.2/base-4.9.1.0 -L/usr/lib/ghc-8.0.2/integer-gmp-1.0.0.1 -L/usr/lib/ghc-8.0.2/ghc-prim-0.5.0.0 -L/usr/lib/ghc-8.0.2/rts -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1 -L/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../../x86_64-alpine-linux-musl/lib/../lib -L/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../../x86_64-alpine-linux-musl/lib -L/usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../.. @/tmp/cckONdKB -lssp_nonshared --start-group -lgcc -lgcc_eh -lc --end-group /usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/crtend.o /usr/lib/gcc/x86_64-alpine-linux-musl/6.2.1/../../../../lib/crtn.o
```

the cabal new-build -v output 
```
/usr/bin/ghc --make -no-link -fbuilding-cabal-package -O -static -outputdir /mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip-tmp -odir /mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip-tmp -hidir /mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip-tmp -stubdir /mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip-tmp -i -i/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip-tmp -isrc -i/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/autogen -i/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/global-autogen -I/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/autogen -I/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/global-autogen -I/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip-tmp -optP-include -optP/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/autogen/cabal_macros.h -hide-all-packages -no-user-package-db -package-db /root/.cabal/store/ghc-8.0.2/package.db -package-db /mnt/greenclip/dist-newstyle/packagedb/ghc-8.0.2 -package-db /mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/package.conf.inplace -package-id base-4.9.1.0 -package-id protolude-0.2-c53bf72e4f41aa227abef214396e7b501c06d3dae194a0f95a0803881df2840e -package-id exceptions-0.8.3-99df7fb1091e82595f8751da3e3af1cd171c7de1921f797c8cff3ba91ffbe7fb -package-id bytestring-0.10.8.1 -package-id text-1.2.2.2-8dc9a27ecc7d86c9dacc1255b386b9059d5ae508d3cebdda054efbca38ed4a30 -package-id vector-0.12.0.1-80b03ad733196f0c3ccac3c3ff0300000efd98a9c471f70d7b74b45be9251148 -package-id hashable-1.2.6.1-96c00ce9d2eb5dd6361b4db269be00e167ed4fe746cb0a1d64ccd0f4a0426239 -package-id binary-0.8.3.0 -package-id microlens-0.4.8.1-f929d694e6c04256470f468b607ed297de07735e53576b7536c21d7be72a2d6d -package-id microlens-mtl-0.1.11.0-bdac7266c988b74d81cf60e03d24df2c8fb6d2c5351451f69c8d06e31e94d453 -package-id directory-1.3.0.0 -package-id unix-2.7.2.1 -package-id wordexp-0.2.0.0-411de64aea6f9aff20aeca21e9e72d8f8a044b5f571214e5933a865c073a768d -package-id X11-1.8-2e8690b52cae71974ff8f6b53277c7da9f070360d3543201d95a1a2f5bbd5197 -XHaskell2010 Clipboard src/Main.hs -Wall -O3 -fPIC -fllvm -split-sections
Linking...
/usr/bin/ghc --make -fbuilding-cabal-package -O -static -outputdir /mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip-tmp -odir /mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip-tmp -hidir /mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip-tmp -stubdir /mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip-tmp -i -i/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip-tmp -isrc -i/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/autogen -i/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/global-autogen -I/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/autogen -I/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/global-autogen -I/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip-tmp -optP-include -optP/mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/autogen/cabal_macros.h -optl-static -lX11 -lxcb -lXau -lXdmcp -hide-all-packages -no-user-package-db -package-db /root/.cabal/store/ghc-8.0.2/package.db -package-db /mnt/greenclip/dist-newstyle/packagedb/ghc-8.0.2 -package-db /mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/package.conf.inplace -package-id base-4.9.1.0 -package-id protolude-0.2-c53bf72e4f41aa227abef214396e7b501c06d3dae194a0f95a0803881df2840e -package-id exceptions-0.8.3-99df7fb1091e82595f8751da3e3af1cd171c7de1921f797c8cff3ba91ffbe7fb -package-id bytestring-0.10.8.1 -package-id text-1.2.2.2-8dc9a27ecc7d86c9dacc1255b386b9059d5ae508d3cebdda054efbca38ed4a30 -package-id vector-0.12.0.1-80b03ad733196f0c3ccac3c3ff0300000efd98a9c471f70d7b74b45be9251148 -package-id hashable-1.2.6.1-96c00ce9d2eb5dd6361b4db269be00e167ed4fe746cb0a1d64ccd0f4a0426239 -package-id binary-0.8.3.0 -package-id microlens-0.4.8.1-f929d694e6c04256470f468b607ed297de07735e53576b7536c21d7be72a2d6d -package-id microlens-mtl-0.1.11.0-bdac7266c988b74d81cf60e03d24df2c8fb6d2c5351451f69c8d06e31e94d453 -package-id directory-1.3.0.0 -package-id unix-2.7.2.1 -package-id wordexp-0.2.0.0-411de64aea6f9aff20aeca21e9e72d8f8a044b5f571214e5933a865c073a768d -package-id X11-1.8-2e8690b52cae71974ff8f6b53277c7da9f070360d3543201d95a1a2f5bbd5197 -XHaskell2010 Clipboard src/Main.hs -o /mnt/greenclip/dist-newstyle/build/x86_64-linux/ghc-8.0.2/greenclip-2.0.0/c/greenclip/build/greenclip/greenclip -Wall -O3 -fPIC -fllvm -split-sections
```

**What is expected ?**

When passing ld-option by command line or in cabal.project.local it should be taken into account. 

**Version of ghc and cabal**
```
/mnt # cabal --version
cabal-install version 2.0.0.1
compiled using version 2.0.1.0 of the Cabal library
```
```
/mnt # ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.2
```

### PR DESCRIPTION
**Pull request by nh2**
Tentative. Fixes #4925

Based on #5446; that one should be merged first and then this one rebased.

To review, only review the top commits (this change is much smaller than it looks here).

Please include the following checklist in your PR:

* [X] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [X] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.
* [x] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

* [x] I'll be testing it by using a `cabal init` mini project and checking that it "fails the right way" (linker errors) when `--ld-option=-static` is given.

### CODE REVIEW

**Comment by nh2** [comment]
Please let me know if there are docs I should update for this.

**Comment by nh2** [comment]
Hmm, this isn't working yet. The flags are passed to the linker, but they appear to early in the `cc` invocation; I intended them to appear at the very end but they appear before `-o` and before all the Haskell libraries.

Since with linker flags later `-l` flags fill in "holes" of symbols left by earlier `-l` flags, this isn't good yet.

I want them to appear at the end. Any hints?

Is this because of the position inside GHC flags as given in https://github.com/haskell/cabal/blob/d484bc469fe818ffbf17010435f371194f732132/Cabal/Distribution/Simple/Program/GHC.hs#L602 or is this a decision of GHC itself?

**Comment by nh2** [comment]
> Is this because of the position inside GHC flags as given in ...  or is this a decision of GHC itself?

I tried permuting the flags directly in the GHC invocation cabal makes, but the results are the same. So it seems like `ghc` sticks `-optl` options at the very front of the linker invocation (as the 5th argument for me), before it passes `-lHS...` flags.

**Comment by nh2** [comment]
Urgh, trouble. You cannot pass `--ld-option=-Wl,--start-group` to `cabal configure`:

* Cabal will pass that flag directly to `ld` like this:

```
/nix/store/3a74d03pq6d0cg3crkfw965k5s58hbn4-binutils-2.30/bin/ar -r dist/build/objs-27195/libHSdarcs-2.14.1-ARuU0cypkJyGiHVcj2sKnE.a '@dist/build/objs-27195/ar27195-1.rsp'
/nix/store/3a74d03pq6d0cg3crkfw965k5s58hbn4-binutils-2.30/bin/ar: creating dist/build/objs-27195/libHSdarcs-2.14.1-ARuU0cypkJyGiHVcj2sKnE.a
/nix/store/pgsjpn6hp8cgcbrvvabk6vnza2i7l7sg-binutils-wrapper-2.30/bin/ld -r -o dist/build/HSdarcs-2.14.1-ARuU0cypkJyGiHVcj2sKnE.o '@dist/build/ld27195-2.rsp' -Wl,--start-group -lgssapi_krb5 -lcom_err -lkrb5support -lkrb5 -lkrb5support -lk5crypto -lssl -lcrypto -lnghttp2 -lssh2
/nix/store/3a74d03pq6d0cg3crkfw965k5s58hbn4-binutils-2.30/bin/ld: unrecognized option '-Wl,--start-group'
```

But you also can't pass `--ld-option=--start-group`, because then at a later stage Cabal will pass `-optl--start-group` to `gcc` (which it uses as the linker), which doesn't understand `--start-group` and wants `-Wl,--start-group` instead.

This problem is created by the fact that GHC uses `gcc` for linking instead of `ld`.

Why is that? From `#ghc` IRC:

> geekosaur: because the C scaffolding is needed for libc to work, and it's not always clear how to set it up right; the C compiler knows how

**Comment by nh2** [comment]
I have researched how the various linkers do it:

### GNU `ld`

Implements `--start-group` and the workaround works conceptually (I have tried it with `ghc` directly).

### GNU `gold`

Implements `--start-group`; I have not tried it.

### LLVM `lld`

(See https://stackoverflow.com/questions/11893996/why-does-the-order-of-l-option-in-gcc-matter#comment89874319_11894098)

The `lld` linker of the LLVM project [does not implement](https://lld.llvm.org/NewLLD.html#key-concepts) the POSIX behaviour (see `R..`'s comment):

> Here is how LLD approaches the problem. Instead of memorizing only undefined symbols, we program LLD so that it memorizes all symbols. When it sees an undefined symbol that can be resolved by extracting an object file from an archive file it previously visited, it immediately extracts the file and link it. It is doable because LLD does not forget symbols it have seen in archive files.

**Comment by nh2** [comment]
Is this PR good?

**Comment by l29ah** [comment]
How can i test it without messing up my working ghc installation?

**Comment by nh2** [comment]
> How can i test it without messing up my working ghc installation?

You should be able to test it by just cloning from git, checking out the branch, and building it with cabal or stack. You don't need to install it globally.

**Comment by jkachmar** [comment]
Is there anything that an interested passerby like myself could do to help get this merged?

Statically linked Haskell executables are something I'm very much interested, so I'd like to help unblock anything if it's at all within my capability 😄

**Comment by sboosali** [comment]
any update?

**Comment by jkachmar** [comment]
Ping. #5446 has been merged, so it would be really nice if this could be merged in as well.

**Comment by nh2** [comment]
I've rebased (there was a formatting-to-80-line-limit change apparently).

This is ready to be merged from my side.

---

Also answering my own question from before:

> I want them to appear at the end. Any hints?
> 
> Is this because of the position inside GHC flags as given in
> 
> https://github.com/haskell/cabal/blob/d484bc469fe818ffbf17010435f371194f732132/Cabal/Distribution/Simple/Program/GHC.hs#L602
>
>  or is this a decision of GHC itself?

I found that this is a decision of GHC itself, not Cabal.

Using

```haskell
  , ["-l" ++ lib     | lib <- ghcOptLinkLibs opts]
  , ["-L" ++ dir     | dir <- flags ghcOptLinkLibPath ]
  , [ "-optl" ++ opt | opt <- ghcOptLinkOptions opts]
```

instead of

```haskell
  , [ "-optl" ++ opt | opt <- ghcOptLinkOptions opts]
  , ["-l" ++ lib     | lib <- ghcOptLinkLibs opts]
  , ["-L" ++ dir     | dir <- flags ghcOptLinkLibPath ]
```

doesn't help with the fact that the `-optl` flags appear before the

```
-lHStext-1.2.3.1
-lHSbinary-0.8.6.0
-lHScontainers-0.6.0.1
```

flags that GHC adds at the very end.

If we want to change that, we probably have to do that in GHC itself.

**Comment by nh2** [comment]
Also I would very very very much like if this could be cherry-picked on `3.0` (where it applies cleanly), so that 8.8 will have a good story for static building.

File: Cabal/Distribution/Simple/GHC.hs [hunk 1]
```diff
@@ -577,7 +577,11 @@ buildOrReplLib mReplFlags verbosity numJobs pkg_descr lbi lib clbi = do
       linkerOpts = mempty {
                       ghcOptLinkOptions       = PD.ldOptions libBi
```
Comment (phadej) [inline Cabal/Distribution/Simple/GHC.hs]: What's the difference between `PD.ldOptions libBi` and options for `ldProgram` ? How their origin differ?

**Comment by phadej** [comment]
This fixes only GHC, what about GHCJS? Wouldn't similar problem we there too?

**Comment by phadej** [comment]
> Also I would very very very much like if this could be cherry-picked on 3.0

This is completely @bgamari's call. This shouldn't break anything, but who knows...

---

I'd like to see similar change for GHCJS, and tests. Without those, I wouldn't merge this.

**Comment by phadej** [comment]
... i.e. IMHO 3.0 train has left the station.

**Comment by jkachmar** [comment]
I’d GHCJS supposed to be a first-class-citizen for Cabal support? I was under the impression that GHC was the primary support target for Cabal.

If this is the case it would more than make sense for this to be pulled into the 3.0 release train as this is a _significant_ feature for anyone building “relocatable” Haskell executables.

**Comment by nh2** [comment]
My goals with this are for statically linking Linux executables.

I would prefer to leave ghcjs related changes to those familiar with that toolchain; I'm not even sure to what program `ld-options` would be eventually given there in the end (probably some nodejs stuff, but certainly not a system linker), or what flags people might want to give there.

File: Cabal/Distribution/Simple/GHC.hs (hunk 1 above)
Comment (nh2) [reply Cabal/Distribution/Simple/GHC.hs]: * `PD.ldOptions libBi` contains the `ld-options` of the `library` section in the `.cabal` file.
  * The corresponding `PD.ldOptions bnfo` further down for when the executable is built contains the `ld-options` of the `executable` section in the `.cabal` file.
* The `programOverrideArgs` for `ldProgram` is what's given with the `--ld-options` CLI flag to e.g. `cabal build` or `cabal configure`.
  * Interestingly they are duplicated 2x, that is, if you give `--ld-options=-s` then `maybe [] programOverrideArgs (lookupProgram ldProgram (withPrograms lbi))` is `["-s","-s"]`.

Comment (nh2) [reply Cabal/Distribution/Simple/GHC.hs]: > I haven't figured out yet why that is, as that's a separate issue.

I have figured that out now. It happens for the new `ld-options` just as much as for the already-existing `gcc-options`. I've found the reason for that and file #6183 for it.

**Comment by nh2** [comment]
Repeating a side investigation from a review question, so that it's visible here (quoting myself):

> > The `programOverrideArgs` for `ldProgram` is what's given with the `--ld-options` CLI flag to e.g. `cabal build` or `cabal configure`.
> > 
> > * Interestingly they are duplicated 2x [...] I haven't figured out yet why that is, as that's a separate issue.
> 
> I have figured that out now. It happens for the new `ld-options` just as much as for the already-existing `gcc-options`. I've found the reason for that and file #6183 for it.

This addresses the last mystery I've encountered while implementing this.

**Comment by nh2** [comment]
Ready to merge from my side.

Please remember that this PR adds only 2 lines of code, and the 2 are identical.

Correspondingly, this is a 1-line PR with pretty obvious effect that's been waiting for > 1 year.

It would be great to get it landed.

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by 23Skidoo** [comment]
Also chery-picked into 3.0.

**Comment by 23Skidoo** [comment]
Cabal-3.0.0.0 has been released on Hackage with this change.

**Comment by nh2** [comment]
Now that this is done, who _should_ we ask that's familiar with the cabal parts of ghcjs whether a similar change would make sense for ghcjs?

**Comment by phadej** [comment]
Looks like `GHCJS` accepts `-optl` arguments, but doesn't really do anything with them.

Given some `Main.hs`,

```
% ghcjs -fforce-recomp -v -optl=BIG_CAPS_IS_EASY_TO_SPOT Main.hs
...
*** Deleting temp dirs:
Deleting: /tmp/ghc10471_0
```

and still produces `Main.jsexe`, where GHC barks

```
gcc: error: BIG_CAPS_IS_EASY_TO_SPOT: No such file or directory
...
Deleting: /tmp/ghc10650_0
`gcc' failed in phase `Linker'. (Exit code: 1)
```

---

There is however linking step in GHCJS compilation process too

```
link: linkables are ...
LinkableM (2019-08-10 16:54:34.309359487 UTC) Main
   [DotO lens-maybe.js_o]
Linking lens-maybe.jsexe (Main)
```

but I'm not sure if there's anything to configure, and whether it's just `ghcjs-options` then.

**Comment by nh2** [comment]
> ... flags that GHC adds at the very end.
> 
> If we want to change that, we probably have to do that in GHC itself.

I've filed a GHC bug for that now: https://gitlab.haskell.org/ghc/ghc/issues/17071

**Comment by nh2** [comment]
> I've filed a GHC bug for that now

I've made a tentative PR for that now: https://gitlab.haskell.org/ghc/ghc/merge_requests/1589

**Comment by 23Skidoo** [comment]
> Now that this is done, who _should_ we ask that's familiar with the cabal parts of ghcjs whether a similar change would make sense for ghcjs?

/cc @luite @JoshMeredith

**Comment by luite** [comment]
GHCJS has an internal linker and doesn't pass the options on to a separate program at the moment.

In general it ignores unsupported options. It should be safe to pass `-optl` arguments, but they are not really used yet.

**Comment by nh2** [comment]
> I've made a tentative PR for that now: https://gitlab.haskell.org/ghc/ghc/merge_requests/1589

My GHC PR was merged, so 8.10 should fix the remaining problems here.
