### PR TITLE
Fix mentions of overwrite and backup flags for v2-configure

### LINKED ISSUE #7590: Error in docs and changelog for append and backup configure options
@ptkato 

In https://github.com/haskell/cabal/pull/7402/files#diff-277f4cd76dc57540f0ad840e00ed445aa2da6df95ab749385330ea5950e08358 and https://github.com/haskell/cabal/pull/7402/files#diff-7366bf7292133a6cd2005aed5db013b2774af3c8d49c8b7e20ec5e8e03e1ff2e "overwrite" is mentioned, but the actual name is "backup"

### PR DESCRIPTION
**Pull request by ptkato**
This PR will close #7590, this time proper.

### CODE REVIEW

File: changelog.d/pr-7402 [hunk 1]
```diff
@@ -6,8 +6,7 @@ issues: #5591 #7180 #7405
 description: {
 
 - Removes the --dry-run part of the v2-configure command
-- Adds an --append flag to v2-configure, which allows new configuration to be appended to the old config file
-- Adds a --backup flag to v2-configure, which enables the backup feature for the config file
-- Includes unit tests for everything
```
Comment (ptkato) [inline changelog.d/pr-7402:11]: I removed this line because it doesn't have much context and it's also not a user-facing change.

**Review by Mikolaj — APPROVED** [review]
Smart move: don't say which option toggles on and which off, but just mention both generally. :)

LGTM.

**Review by gbaz — APPROVED** [review]
