### PR TITLE
Fix a bug where cabal tried to copy files after moving them.

### LINKED ISSUE #5458: Race condition with custom store directory and new-build on windows?
Building a package with a good deal of dependencies cabal fails after building a few successfully.

Restarting the build process eventually all packages get built.

```
$ cabal --version
cabal-install version 2.2.0.0
compiled using version 2.2.0.1 of the Cabal library
```

Using Windows 10/msys.

```
Andi@Horzube MINGW64 ~/container_investiagtion
$ cabal --store-dir=/c/temp/store -j9 new-run set-operations-set -- intersection-mix_sn
Build profile: -w ghc-8.7.20180718 -O1
In order, the following will be built (use -v for more details):
 - Glob-0.9.2 (lib) (requires build)
 - ansi-wl-pprint-0.6.8.2 (lib) (requires build)
 - exceptions-0.10.0 (lib) (requires build)
 - optparse-applicative-0.14.2.0 (lib) (requires build)
 - criterion-1.5.0.0 (lib) (dependency rebuilt)
 - containers-bench-0.6.0.1 (bench:set-operations-set) (dependency rebuilt)
Configuring ansi-wl-pprint-0.6.8.2 (lib)...
Configuring exceptions-0.10.0 (lib)...
Configuring Glob-0.9.2 (lib)...
Building exceptions-0.10.0 (lib)...
Building ansi-wl-pprint-0.6.8.2 (lib)...
Building Glob-0.9.2 (lib)...
cabal.exe: Failed to build Glob-0.9.2 (which is required by
bench:set-operations-set from containers-bench-0.6.0.1). The failure occurred
during the final install step. The exception was:
C:/temp/store\ghc-8.7.20180718\incoming\new-64796\temp\store\ghc-8.7.20180718\Glob-0.9.2-f8910a8f16bd7b20eda317d34ae7e8cc93e5ab40\share\doc\LICENSE.txt:
renameFile:renamePath:MoveFileEx
"\\\\?\\C:\\temp\\store\\ghc-8.7.20180718\\incoming\\new-64796\\temp\\store\\ghc-8.7.20180718\\Glob-0.9.2-f8910a8f16bd7b20eda317d34ae7e8cc93e5ab40\\share\\doc\\LICENSE.txt"
Just
"\\\\?\\C:\\temp\\store\\ghc-8.7.20180718\\Glob-0.9.2-f8910a8f16bd7b20eda317d34ae7e8cc93e5ab40\\share\\doc\\LICENSE.txt":
does not exist (The system cannot find the path specified.)
Failed to build ansi-wl-pprint-0.6.8.2 (which is required by
bench:set-operations-set from containers-bench-0.6.0.1). The failure occurred
during the final install step. The exception was:
C:/temp/store\ghc-8.7.20180718\incoming\new-64796\temp\store\ghc-8.7.20180718\ansi-wl-pprint-0.6.8.2-6cbf8c2b538b897413295b56e74d9a1351993b26\share\doc\LICENSE:
renameFile:renamePath:MoveFileEx
"\\\\?\\C:\\temp\\store\\ghc-8.7.20180718\\incoming\\new-64796\\temp\\store\\ghc-8.7.20180718\\ansi-wl-pprint-0.6.8.2-6cbf8c2b538b897413295b56e74d9a1351993b26\\share\\doc\\LICENSE"
Just
"\\\\?\\C:\\temp\\store\\ghc-8.7.20180718\\ansi-wl-pprint-0.6.8.2-6cbf8c2b538b897413295b56e74d9a1351993b26\\share\\doc\\LICENSE":
does not exist (The system cannot find the path specified.)
Failed to build exceptions-0.10.0 (which is required by
bench:set-operations-set from containers-bench-0.6.0.1). The failure occurred
during the final install step. The exception was:
C:/temp/store\ghc-8.7.20180718\incoming\new-64796\temp\store\ghc-8.7.20180718\exceptions-0.10.0-a7c4736b6cddc75311caa55e7d6569f2b0b5ad5d\share\doc\LICENSE:
renameFile:renamePath:MoveFileEx
"\\\\?\\C:\\temp\\store\\ghc-8.7.20180718\\incoming\\new-64796\\temp\\store\\ghc-8.7.20180718\\exceptions-0.10.0-a7c4736b6cddc75311caa55e7d6569f2b0b5ad5d\\share\\doc\\LICENSE"
Just
"\\\\?\\C:\\temp\\store\\ghc-8.7.20180718\\exceptions-0.10.0-a7c4736b6cddc75311caa55e7d6569f2b0b5ad5d\\share\\doc\\LICENSE":
does not exist (The system cannot find the path specified.)


Andi@Horzube MINGW64 ~/container_investiagtion
$ cabal --store-dir=/c/temp/store -j9 new-run set-operations-set -- intersection-mix_sn
Build profile: -w ghc-8.7.20180718 -O1
In order, the following will be built (use -v for more details):
 - optparse-applicative-0.14.2.0 (lib) (requires build)
 - criterion-1.5.0.0 (lib) (dependency rebuilt)
 - containers-bench-0.6.0.1 (bench:set-operations-set) (dependency rebuilt)
Configuring optparse-applicative-0.14.2.0 (lib)...
Building optparse-applicative-0.14.2.0 (lib)...
cabal.exe: Failed to build optparse-applicative-0.14.2.0 (which is required by
bench:set-operations-set from containers-bench-0.6.0.1). The failure occurred
during the final install step. The exception was:
C:/temp/store\ghc-8.7.20180718\incoming\new-75964\temp\store\ghc-8.7.20180718\optparse-appl_-0.14.2.0-a03c9eaf2422637a182a47434ba654b72455a492\share\doc\LICENSE:
renameFile:renamePath:MoveFileEx
"\\\\?\\C:\\temp\\store\\ghc-8.7.20180718\\incoming\\new-75964\\temp\\store\\ghc-8.7.20180718\\optparse-appl_-0.14.2.0-a03c9eaf2422637a182a47434ba654b72455a492\\share\\doc\\LICENSE"
Just
"\\\\?\\C:\\temp\\store\\ghc-8.7.20180718\\optparse-appl_-0.14.2.0-a03c9eaf2422637a182a47434ba654b72455a492\\share\\doc\\LICENSE":
does not exist (The system cannot find the path specified.)


Andi@Horzube MINGW64 ~/container_investiagtion
$ cabal --store-dir=/c/temp/store -j9 new-run set-operations-set -- intersection-mix_sn
Up to date
benchmarking intersection-mix_sn
time                 2.578 ms   (2.540 ms .. 2.625 ms)
                     0.995 R²   (0.992 R² .. 0.997 R²)
mean                 2.259 ms   (2.176 ms .. 2.337 ms)
std dev              261.8 μs   (225.6 μs .. 295.4 μs)
variance introduced by outliers: 73% (severely inflated)

benchmarking intersection-mix_sn
time                 2.214 ms   (2.096 ms .. 2.430 ms)
                     0.959 R²   (0.930 R² .. 0.983 R²)
mean                 2.393 ms   (2.325 ms .. 2.471 ms)
std dev              248.8 μs   (190.0 μs .. 368.0 μs)
variance introduced by outliers: 69% (severely inflated)

```

### PR DESCRIPTION
**Pull request by AndreasPK**
Using windows/msys paths can contain both kinds of slashes.
This causes issues when we compare paths but don't normalize
them, leading us to assume they refer to different locations.

I've tested it by using new-build on a bunch of projects with custom store dirs.

This fixes #5458

---
Please include the following checklist in your PR:

* [X] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions
https://github.com/AndreasPK/cabal/commits/master).
* [X] Any changes that could be relevant to users have been recorded in the changelog.
  No behaviour change.
* [X] The documentation has been updated, if necessary.
* [X] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

File: cabal-install/Distribution/Client/ProjectBuilding.hs [hunk 1]
```diff
@@ -977,7 +977,9 @@ buildAndInstallUnpackedPackage verbosity
             -- While this breaks the prefix-relocatable property of the lirbaries
             -- it is necessary on macOS to stay under the load command limit of the
             -- macOS mach-o linker. See also @PackageHash.hashedInstalledPackageIdVeryShort@.
-            otherFiles <- filter (not . isPrefixOf entryDir) <$> listFilesRecursive tmpDir
+            -- We also normalise paths to ensure that there are no different representations
+            -- for the same path. Like / and \\ on windows under msys.
+            otherFiles <- filter (not . isPrefixOf entryDir . normalise) <$> listFilesRecursive tmpDir
```
Comment (Mistuke) [inline cabal-install/Distribution/Client/ProjectBuilding.hs]: isn't it sufficient to normalize just `tmpDir` here? So we only have to apply the function once instead of for every entry. The rest of the path is created by `</>` which will keep it consistent.

**Comment by AndreasPK** [comment]
Should be better now.

**Comment by 23Skidoo** [comment]
Done.

**Comment by Mistuke** [comment]
Thanks @23Skidoo , everything looks ok, the travis issues seem unrelated.

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by 23Skidoo** [comment]
Also cherry-picked into 2.4.
