### PR TITLE
Filter out files that are not ending in .c from c-sources

### LINKED ISSUE #9190: cabal-install-3.10 fails with header files in 'c-sources'
Reproduce:

* `git clone -b refactor/vty-crossplatform https://github.com/hasufell/brick.git`
* `cd brick`
* `ghcup run --cabal 3.10 -- cabal build`
* `ghcup run --cabal 3.6 -- cabal build`

Originally spotted here: https://github.com/jtdaugherty/vty/issues/260#issuecomment-1686521942

Fixed here by changing the cabal file: https://github.com/jtdaugherty/vty-unix/pull/1

This is a *regression*.

### PR DESCRIPTION
**Pull request by Kleidukos**
This poc pre-filters file paths given in c-sources to only keep the ones ending in ".c", and outputs an appropriate message.

1. Should we check if there are ".h" files explicitly and redirect to "includes"?
2. Should we expand this to cxx-sources?

## QA Notes

1. Clone the repository `https://github.com/jtdaugherty/vty-unix`
2. Remove from its cabal file the exported modules, dependencies and executable component
3. Run `cabal build -w ghc-9.2.8`
4. Make sure the output is the following:

```
Preprocessing library for repro-0.1.0.0..
Building library for repro-0.1.0.0..
Warning: The following files listed in the main library's c-sources will not
be used: cbits/gwinsz.h.
Header files should be in the 'include' or 'install-include' stanza.
See https://cabal.readthedocs.io/en/3.10/cabal-package.html#pkg-field-includes
Preprocessing library 'lib2' for repro-0.1.0.0..
Building library 'lib2' for repro-0.1.0.0..
Warning: The following files listed in library lib2's c-sources will not be
used: cbits/gwinsz.h.
Header files should be in the 'include' or 'install-include' stanza.
See https://cabal.readthedocs.io/en/3.10/cabal-package.html#pkg-field-includes
Preprocessing executable 'exec1' for repro-0.1.0.0..
Building executable 'exec1' for repro-0.1.0.0..
[1 of 1] Compiling Main             ( Main.hs, /home/hecate/Vrac/cabal-9190-repro/dist-newstyle/build/x86_64-linux/ghc-9.4.5/repro-0.1.0.0/x/exec1/build/exec1/exec1-tmp/Main.o )
Warning: The following files listed in exec1's c-sources will not be used:
cbits/gwinsz.h.
Header files should be in the 'include' or 'install-include' stanza.
See https://cabal.readthedocs.io/en/3.10/cabal-package.html#pkg-field-includes
[2 of 2] Linking /home/hecate/Vrac/cabal-9190-repro/dist-newstyle/build/x86_64-linux/ghc-9.4.5/repro-0.1.0.0/x/exec1/build/exec1/exec1
```
5. Exit code should be 0 (you can check with `echo $?`

relates to #9190

@hasufell @mouse07410 @andreabedini @angerman

### CODE REVIEW

**Comment by andreabedini** [comment]
@Kleidukos I thought there was somehing like this somewhere. Let's wait until we figure out what changed the behaviour and how it changed.

**Comment by Kleidukos** [comment]
@andreabedini I'm not opposed to this for `master` but for 3.10 it's becoming *a bit* time-sensitive.

**Comment by andreabedini** [comment]
:disappointed: I understand.

**Review by Mikolaj — APPROVED** [review]
Thank you for adding the warning --- that's progress. Also, thank you for resisting the urge to deduplicate at the last moment before the releases. :)

**Comment by angerman** [comment]
I think the warning should suggest people to use the include or install-include section. And link to the cabal manual where it clearly says headers.

File: Cabal/src/Distribution/Simple/GHC.hs [hunk 1]
```diff
@@ -710,7 +710,10 @@ buildOrReplLib mReplFlags verbosity numJobs pkg_descr lbi lib clbi = do
     let (cSrcs', others) = partition (\filepath -> ".c"`isSuffixOf` filepath) (cSources libBi)
     unless (null others) $ do
       let files = intercalate ", " others
-      warn verbosity $ "The following files listed in c-sources will not be used: " <> files
+      let libraryName = case libName lib of
```
Comment (andreabedini) [inline Cabal/src/Distribution/Simple/GHC.hs:713]: We have [`showLibraryName`](https://hackage.haskell.org/package/Cabal-syntax-3.10.1.0/docs/Distribution-Types-LibraryName.html#v:showLibraryName)

File: Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs [hunk 2]
```diff
@@ -29,7 +29,7 @@ tests = testGroup "Distribution.Utils.Structured"
     , testCase "GenericPackageDescription" $
       md5Check (Proxy :: Proxy GenericPackageDescription) 0x8d8f340f10a58b8d8a87bf42213dac89
     , testCase "LocalBuildInfo" $
-      md5Check (Proxy :: Proxy LocalBuildInfo) 0xbb22c3258d3092f31e992bc093d09170
+      md5Check (Proxy :: Proxy LocalBuildInfo) 0x618ab257e99d0b21c617e1f8c39a5a4b
```
Comment (andreabedini) [inline Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs:32]: Why is `LocalBuildInfo` changing?

**Comment by andreabedini** [comment]
@Kleidukos Could you add a test case too? something that has `c-sources: file.h file.c`. I think this PR will emit a warning (which we can capture), while with the old behaviour nothing was displayed. This would allow us to notice if something changes again.
:pray: :bow: :heart:

File: Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs (hunk 2 above)
Comment (Kleidukos) [reply Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs:32]: No idea

File: Cabal/src/Distribution/Simple/GHC.hs (hunk 1 above)
Comment (Kleidukos) [reply Cabal/src/Distribution/Simple/GHC.hs:713]: The output is unsatisfying. Especially because it is:

> "library '" ++ prettyShow name ++ "'"

So the output would be:

> "The following files listed in library 'lib2''s c-sources  will not be used:

The double single quotes are not a mistake.

And if it's the main library, it only outputs "library", which breaks the flow of the sentence.

Comment (andreabedini) [reply Cabal/src/Distribution/Simple/GHC.hs:713]: Is
```
libraryNameStanza :: LibraryName -> String
libraryNameStanza LMainLibName       = "library"
libraryNameStanza (LSubLibName name) = "library " ++ prettyShow name
```
any better? Otherwise, it's ok.

File: cabal-testsuite/PackageTests/CSourcesSanitisation/cbits/gwinsz.c
Comment (andreabedini) [inline cabal-testsuite/PackageTests/CSourcesSanitisation/cbits/gwinsz.c:1]: I could reproduce with empty files too, if that makes it any easier

**Comment by Kleidukos** [comment]
@andreabedini would you mind running the `cabal-test` executable and accept the output? It never finishes on my machine.

File: Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs (hunk 2 above)
Comment (fgaz) [reply Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs:32]: Try rebasing, it should disappear

Comment (andreabedini) [reply Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs:32]: :thinking:

File: Cabal/src/Distribution/Simple/GHC.hs (hunk 1 above)
Comment (fgaz) [reply Cabal/src/Distribution/Simple/GHC.hs:713]: Or rephrase as "The following files listed in the c-sources of library 'lib2' will not be used"

File: Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs (hunk 2 above)
Comment (Kleidukos) [reply Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs:32]: @fgaz rebasing on current 3.10 you mean?

Comment (fgaz) [reply Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs:32]: Nevermind, I grepped the wrong branch :see_no_evil:

File: Cabal/src/Distribution/Simple/GHC.hs (hunk 1 above)
Comment (Kleidukos) [reply Cabal/src/Distribution/Simple/GHC.hs:713]: @fgaz I don't understand what this suggestion is addressing, sorry

**Comment by andreabedini** [comment]
@Kleidukos I took some liberties, I hope you are ok with it :relaxed:

File: cabal-testsuite/PackageTests/CSourcesSanitisation/cbits/gwinsz.c
Comment (Kleidukos) [reply cabal-testsuite/PackageTests/CSourcesSanitisation/cbits/gwinsz.c:1]: Yeah sure let's go with it :+1:

File: Cabal/src/Distribution/Simple/GHC.hs (hunk 1 above)
Comment (fgaz) [reply Cabal/src/Distribution/Simple/GHC.hs:713]: If you phrase it like that, you can use `showLibraryName`

Comment (Kleidukos) [reply Cabal/src/Distribution/Simple/GHC.hs:713]: But we lose the "main" bit, which is fairly important.

Comment (fgaz) [reply Cabal/src/Distribution/Simple/GHC.hs:713]: Good point. I wonder if `showLibraryName` produces confusing messages elsewhere too. Maybe we should add "main" there too...

Comment (Kleidukos) [reply Cabal/src/Distribution/Simple/GHC.hs:713]: Yes indeed, we will have to formalise a bit more the presentation layer for cabal-install.

**Comment by hamishmack** [comment]
This breaks the `double-conversion` package (uses `.cc` extension in `c-sources`). 

Also the warning did not work because it is only reached if `not (null cSrcs')`.  All the src files in `double-conversions` have `.cc` extensions.  So everything is ignored and no warning is issued.

**Comment by angerman** [comment]
Well, .cc is c++, so this should be under `cxx-sources` not `c-sources`. Treating c++ files as c files is another one of those "often works" scenarios.

**Comment by jasagredo** [comment]
Confirmed it works as expected on Mingw with cabal-3.10.2.0. I can confirm also that #9285 works on top of this one as expected:

```
Warning: The following header files listed in the main library's c-sources
will not be used: cbits/gwinsz.h.
Header files should be in the 'include' or 'install-include' stanza.
See https://cabal.readthedocs.io/en/3.10/cabal-package.html#pkg-field-includes
Warning: The following files listed in the main library's c-sources do not
have the expected '.c' extension cbits/gwinsz.cc.
C++ files should be in the 'cxx-sources' stanza.
See
https://cabal.readthedocs.io/en/3.10/cabal-package.html#pkg-field-cxx-sources
```

**Comment by sternenseemann** [comment]
Getting a changelog entry on this (retroactively) would maybe be nice, since the warning does not seem to work at all, at least in Setup.hs builds. Just had a fun afternoon debugging this.

Also, I feel like in this sort of case, the chance of people accidentally relying on the »incorrect« behavior is big enough not to have this in a minor point release…

**Comment by mpscholten** [comment]
This change caused one of our dependencies to silently fail. It would have been nice if this was a hard fail.
