### PR TITLE
Show abbreviated mixed versions with suffix

### LINKED ISSUE #9823: Shortening rejection message with an installed suffix
A follow on from #9559. The shortening is not applied when one of the versions has a `/installed-hash` suffix. Here I've followed the [head.hackage instructions](https://ghc.gitlab.haskell.org/head.hackage/);

```
$ cabal build all --enable-tests --enable-benchmarks
Warning: this is a debug build of cabal-install with assertions enabled.
Resolving dependencies...
Error: [Cabal-7107]
Could not resolve dependencies:
[__0] next goal: Cabal (user goal)
[__0] rejecting: Cabal-3.11.0.0
      (constraint from cabal.project.local requires ==2.4.1.0 || ==3.0.2.0 || ==3.2.1.0)
[__0] rejecting: Cabal-3.10.2.1, Cabal-3.10.2.0/installed-fd40, Cabal-3.10.2.0, Cabal-3.10.1.0, Cabal-3.8.1.0, Cabal-3.6.3.0, Cabal-3.6.2.0, Cabal-3.6.1.0, Cabal-3.6.0.0, Cabal-3.4.1.0, Cabal-3.4.0.0, Cabal-3.2.1.0, Cabal-3.2.0.0, Cabal-3.0.2.0, Cabal-3.0.1.0, Cabal-3.0.0.0, Cabal-2.4.1.0, Cabal-2.4.0.1, Cabal-2.4.0.0, Cabal-2.2.0.1, Cabal-2.2.0.0, Cabal-2.0.1.1, Cabal-2.0.1.0, Cabal-2.0.0.2, Cabal-1.24.2.0, Cabal-1.24.0.0, Cabal-1.22.8.0, Cabal-1.22.7.0, Cabal-1.22.6.0, Cabal-1.22.5.0, Cabal-1.22.4.0, Cabal-1.22.3.0, Cabal-1.22.2.0, Cabal-1.22.1.1, Cabal-1.22.1.0, Cabal-1.22.0.0, Cabal-1.20.0.4, Cabal-1.20.0.3, Cabal-1.20.0.2, Cabal-1.20.0.1, Cabal-1.20.0.0, Cabal-1.18.1.7, Cabal-1.18.1.6, Cabal-1.18.1.5, Cabal-1.18.1.4, Cabal-1.18.1.3, Cabal-1.18.1.2, Cabal-1.18.1.1, Cabal-1.18.1, Cabal-1.18.0, Cabal-1.16.0.3, Cabal-1.16.0.2, Cabal-1.16.0.1, Cabal-1.16.0, Cabal-1.14.0, Cabal-1.12.0, Cabal-1.10.2.0, Cabal-1.10.1.0, Cabal-1.10.0.0, Cabal-1.8.0.6, Cabal-1.8.0.4, Cabal-1.8.0.2, Cabal-1.6.0.3, Cabal-1.6.0.2, Cabal-1.6.0.1, Cabal-1.4.0.2, Cabal-1.4.0.1, Cabal-1.4.0.0, Cabal-1.2.4.0, Cabal-1.2.3.0, Cabal-1.2.2.0, Cabal-1.2.1, Cabal-1.1.6, Cabal-1.24.1.0 (constraint from user target requires ==3.11.0.0)
[__0] fail (backjumping, conflict set: Cabal)
After searching the rest of the dependency tree exhaustively, these were the goals I've had most trouble fulfilling: Cabal
```

We could show something like;

```
[__0] rejecting: Cabal; 3.10.2.1, 3.10.2.0/installed-fd40, 3.10.2.0, 3.10.1.0, 3.8.1.0, ...
```

### PR DESCRIPTION
**Pull request by philderbeast**
Fixes #9823.

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [x] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*), the expected output has changed for existing doctests.

With this fix, the solver rejection message of the reproduction for #9823 is shorter[^1];

```
$ cabal build all --enable-tests --enable-benchmarks --dry-run
Warning: this is a debug build of cabal-install with assertions enabled.
Resolving dependencies...
Error: [Cabal-7107]
Could not resolve dependencies:
[__0] next goal: Cabal (user goal)
[__0] rejecting: Cabal-3.11.0.0 (constraint from project config /home/.../cabal.project.local requires ==2.4.1.0 || ==3.0.2.0 || ==3.2.1.0)
[__0] rejecting: Cabal; 3.10.2.1, 3.10.2.0/installed-fd40, 3.10.2.0, 3.10.1.0, 3.8.1.0, 3.6.3.0, 3.6.2.0, 3.6.1.0, 3.6.0.0, 3.4.1.0, 3.4.0.0, 3.2.1.0, 3.2.0.0, 3.0.2.0, 3.0.1.0, 3.0.0.0, 2.4.1.0, 2.4.0.1, 2.4.0.0, 2.2.0.1, 2.2.0.0, 2.0.1.1, 2.0.1.0, 2.0.0.2, 1.24.2.0, 1.24.0.0, 1.22.8.0, 1.22.7.0, 1.22.6.0, 1.22.5.0, 1.22.4.0, 1.22.3.0, 1.22.2.0, 1.22.1.1, 1.22.1.0, 1.22.0.0, 1.20.0.4, 1.20.0.3, 1.20.0.2, 1.20.0.1, 1.20.0.0, 1.18.1.7, 1.18.1.6, 1.18.1.5, 1.18.1.4, 1.18.1.3, 1.18.1.2, 1.18.1.1, 1.18.1, 1.18.0, 1.16.0.3, 1.16.0.2, 1.16.0.1, 1.16.0, 1.14.0, 1.12.0, 1.10.2.0, 1.10.1.0, 1.10.0.0, 1.8.0.6, 1.8.0.4, 1.8.0.2, 1.6.0.3, 1.6.0.2, 1.6.0.1, 1.4.0.2, 1.4.0.1, 1.4.0.0, 1.2.4.0, 1.2.3.0, 1.2.2.0, 1.2.1, 1.1.6, 1.24.1.0 (constraint from user target requires ==3.11.0.0)
[__0] fail (backjumping, conflict set: Cabal)
After searching the rest of the dependency tree exhaustively, these were the goals I've had most trouble fulfilling: Cabal
```

[^1]: I see that the full path to `cabal.project.local` is shown. ~I'll need to check if I introduced that change inadvertently.~ I checked on master at `git rev-parse HEAD == 46e822152c9b3f38044870115d7a198b3a509d66` and the full path to `cabal.project.local` is shown there so I did not introduce this change with this fix.

### CODE REVIEW

**Review by geekosaur — APPROVED** [review]

**Comment by Kleidukos** [comment]
The documentation doesn't have any example of solver rejection?

**Comment by philderbeast** [comment]
> The documentation doesn't have any example of solver rejection?

Searching for "rejecting" in `*.rst` gets no hits.

**Comment by philderbeast** [comment]
Same goes when searching for "rejecting" in the [latest readthedocs](https://cabal.readthedocs.io/en/latest/search.html?q=rejecting&check_keywords=yes&area=default).

**Comment by Kleidukos** [comment]
Awesome, thank you

File: cabal-install-solver/src/Distribution/Solver/Modular/Message.hs [hunk 1]
```diff
@@ -236,61 +235,37 @@ blurbOption :: ProgressAction -> QPN -> POption -> String
...
-showIsOrVs q (Vs xs) = showQPN q ++ "; " ++ L.intercalate ", " (showVer `map` xs)
+showIsOrVs :: QPN -> [POption] -> String
+showIsOrVs _ [] = "unexpected empty list of versions"
+showIsOrVs q [x] = showOption q x
+showIsOrVs q xs = showQPN q ++ "; " ++ (L.intercalate ", "
+  [if isJust linkedTo
+    then showOption q x
+    else showI i -- Don't show the package, just the version
+  | x@(POption i linkedTo) <- xs
+  ])
```
Comment (grayjay) [inline cabal-install-solver/src/Distribution/Solver/Modular/Message.hs:268]: Could you please add a test for the linked case?

File: changelog.d/pr-9824 [hunk 2]
```diff
@@ -0,0 +1,10 @@
+synopsis: Abbrevate solver rejection messages with installed versions
+packages: cabal-install
```
[the remark this answers is not in the document]
Comment (philderbeast) [reply changelog.d/pr-9824]: Thanks.

File: cabal-install-solver/src/Distribution/Solver/Modular/Message.hs (hunk 1 above)
Comment (philderbeast) [reply cabal-install-solver/src/Distribution/Solver/Modular/Message.hs:272]: Yes, I've added these two;

```haskell
-- >>> showOptions foobarQPN [k2, k3]
-- "foo-bar; foo-bar~>foo-bar-2, foo-bar~>foo-bar-3"
-- >>> showOptions foobarQPN [v0, i1, k3]
-- "foo-bar; 0, 1/installed-inplace, foo-bar~>foo-bar-3"
```

We can't abbreviate the linked ones can we?

I haven't dropped the prefix when all are linked as in the first example above.

Comment (grayjay) [reply cabal-install-solver/src/Distribution/Solver/Modular/Message.hs:272]: Yes, I can't think of a clear way to abbreviate the linked ones, especially since the two `PackagePath`s are always different when the solver links packages, so there is never a common prefix. I also think that it would be better to use different `PackagePath`s for the `Maybe PackagePath` field of the `POption` for `k1` and `k2`, to make it more realistic.

Comment (philderbeast) [reply cabal-install-solver/src/Distribution/Solver/Modular/Message.hs:272]: Yes that is how it turned out;

```
-- >>> showOptions foobarQPN [k1, k2]
-- "foo-bar; foo-bar~>bazqux.foo-bar-1, foo-bar~>bazqux.foo-bar-2"
-- >>> showOptions foobarQPN [v0, i1, k2]
-- "foo-bar; 0, 1/installed-inplace, foo-bar~>bazqux.foo-bar-2"
```

**Review by grayjay — APPROVED** [review]
Thanks!

**Comment by philderbeast** [comment]
Label `merge+no rebase` is necessary when the pull request is from an organisation.
