### PR TITLE
Fix nix config option

### LINKED ISSUE #8452: "nix: True" in .cabal/config causes parsing error
**Describe the bug**

Nix integration not working as expected in cabal 3.8.1.0.

**To Reproduce**

```
~/.cabal 
❯ cabal user-config init
Writing default configuration to /home/amy/.cabal/config

~/.cabal 
❯ cabal v2-update
Downloading the latest package list from hackage.haskell.org
Package list of hackage.haskell.org is up to date.
The index-state is set to 2022-09-04T17:19:43Z.
```

Now edit `~/.cabal/config`, changing line 24 to:

```
nix: True
```

This used to work (e.g. in Cabal library and cabal-install version: 3.4.0.0), and it's what the [documentation](https://cabal.readthedocs.io/en/3.8/nix-integration.html#enabling-nix-integration) says to do.

```
~/.cabal 
✦ ❯ cabal v2-update
Error: cabal: Error parsing config file /home/amy/.cabal/config:24:
True
```

Please use version-prefixed commands (e.g. `v2-build` or `v1-build`) to avoid ambiguity.

**Expected behavior**

`cabal v2-update` should handle this setting, or if something has changed and this is no longer correct, the docs should be updated and cabal should warn me.

**System information**

```
❯ uname -a
Linux wombat11k 5.15.63 #1-NixOS SMP Thu Aug 25 09:40:49 UTC 2022 x86_64 GNU/Linux

❯ cabal --version
cabal-install version 3.8.1.0
compiled using version 3.8.1.0 of the Cabal library 

❯ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.0.2
```

**Additional context**

I'm running NixOS.

```
✦ ❯ cat ~/.cabal/config
-- This is the configuration file for the 'cabal' command line tool.
--
-- The available configuration options are listed below.
-- Some of them have default values listed.
--
-- Lines (like this one) beginning with '--' are comments.
-- Be careful with spaces and indentation because they are
-- used to indicate layout for nested sections.
--
-- This config file was generated using the following versions
-- of Cabal and cabal-install:
-- Cabal library version: 3.8.1.0
-- cabal-install version: 3.8.1.0


repository hackage.haskell.org
  url: http://hackage.haskell.org/
  -- secure: True
  -- root-keys:
  -- key-threshold: 3

-- ignore-expiry: False
-- http-transport:
nix: True
-- store-dir:
-- active-repositories:
-- local-no-index-repo:
remote-repo-cache: /home/amy/.cabal/packages
-- logs-dir: /home/amy/.cabal/logs
-- default-user-config:
-- verbose: 1
-- compiler: ghc
-- cabal-file:
-- with-compiler:
-- with-hc-pkg:
-- program-prefix:
-- program-suffix:
-- library-vanilla: True
-- library-profiling:
-- shared:
-- static:
-- executable-dynamic: False
-- executable-static: False
-- profiling:
-- executable-profiling:
-- profiling-detail:
-- library-profiling-detail:
-- optimization: True
-- debug-info: False
-- build-info:
-- library-for-ghci:
-- split-sections: False
-- split-objs: False
-- executable-stripping:
-- library-stripping:
-- configure-option:
-- user-install: True
-- package-db:
-- flags:
-- extra-include-dirs:
-- deterministic:
-- cid:
-- extra-lib-dirs:
-- extra-lib-dirs-static:
-- extra-framework-dirs:
extra-prog-path: /home/amy/.cabal/bin
-- instantiate-with:
-- tests: False
-- coverage: False
-- library-coverage:
-- exact-configuration: False
-- benchmarks: False
-- relocatable: False
-- response-files:
-- allow-depending-on-private-libs:
-- cabal-lib-version:
-- append:
-- backup:
-- constraint:
-- preference:
-- solver: modular
-- allow-older: False
-- allow-newer: False
-- write-ghc-environment-files:
-- documentation: False
-- doc-index-file: $datadir/doc/$arch-$os-$compiler/index.html
-- only-download: False
-- target-package-db:
-- max-backjumps: 4000
-- reorder-goals: False
-- count-conflicts: True
-- fine-grained-conflicts: True
-- minimize-conflict-set: False
-- independent-goals: False
-- shadow-installed-packages: False
-- strong-flags: False
-- allow-boot-library-installs: False
-- reject-unconstrained-dependencies: none
-- reinstall: False
-- avoid-reinstalls: False
-- force-reinstalls: False
-- upgrade-dependencies: False
-- index-state:
-- root-cmd:
-- symlink-bindir:
build-summary: /home/amy/.cabal/logs/build.log
-- build-log:
remote-build-reporting: none
-- report-planning-failure: False
-- per-component: True
-- run-tests:
jobs: $ncpus
-- keep-going: False
-- offline: False
-- lib: False
-- package-env:
-- overwrite-policy:
-- install-method:
installdir: /home/amy/.cabal/bin
-- username:
-- password:
-- password-command:
-- builddir:

haddock
  -- keep-temp-files: False
  -- hoogle: False
  -- html: False
  -- html-location:
  -- executables: False
  -- tests: False
  -- benchmarks: False
  -- foreign-libraries: False
  -- all:
  -- internal: False
  -- css:
  -- hyperlink-source: False
  -- quickjump: False
  -- hscolour-css:
  -- contents-location:

init
  -- interactive: False
  -- cabal-version: 3.0
  -- license:
  -- extra-doc-file:
  -- tests:
  -- test-dir:
  -- language: Haskell2010
  -- application-dir: app
  -- source-dir: src

install-dirs user
  -- prefix: /home/amy/.cabal
  -- bindir: $prefix/bin
  -- libdir: $prefix/lib
  -- libsubdir: $abi/$libname
  -- dynlibdir: $libdir/$abi
  -- libexecdir: $prefix/libexec
  -- libexecsubdir: $abi/$pkgid
  -- datadir: $prefix/share
  -- datasubdir: $abi/$pkgid
  -- docdir: $datadir/doc/$abi/$pkgid
  -- htmldir: $docdir/html
  -- haddockdir: $htmldir
  -- sysconfdir: $prefix/etc

install-dirs global
  -- prefix: /usr/local
  -- bindir: $prefix/bin
  -- libdir: $prefix/lib
  -- libsubdir: $abi/$libname
  -- dynlibdir: $libdir/$abi
  -- libexecdir: $prefix/libexec
  -- libexecsubdir: $abi/$pkgid
  -- datadir: $prefix/share
  -- datasubdir: $abi/$pkgid
  -- docdir: $datadir/doc/$abi/$pkgid
  -- htmldir: $docdir/html
  -- haddockdir: $htmldir
  -- sysconfdir: $prefix/etc

program-locations
  -- alex-location:
  -- ar-location:
  -- c2hs-location:
  -- cpphs-location:
  -- doctest-location:
  -- gcc-location:
  -- ghc-location:
  -- ghc-pkg-location:
  -- ghcjs-location:
  -- ghcjs-pkg-location:
  -- greencard-location:
  -- haddock-location:
  -- happy-location:
  -- haskell-suite-location:
  -- haskell-suite-pkg-location:
  -- hmake-location:
  -- hpc-location:
  -- hsc2hs-location:
  -- hscolour-location:
  -- jhc-location:
  -- ld-location:
  -- pkg-config-location:
  -- runghc-location:
  -- strip-location:
  -- tar-location:
  -- uhc-location:

program-default-options
  -- alex-options:
  -- ar-options:
  -- c2hs-options:
  -- cpphs-options:
  -- doctest-options:
  -- gcc-options:
  -- ghc-options:
  -- ghc-pkg-options:
  -- ghcjs-options:
  -- ghcjs-pkg-options:
  -- greencard-options:
  -- haddock-options:
  -- happy-options:
  -- haskell-suite-options:
  -- haskell-suite-pkg-options:
  -- hmake-options:
  -- hpc-options:
  -- hsc2hs-options:
  -- hscolour-options:
  -- jhc-options:
  -- ld-options:
  -- pkg-config-options:
  -- runghc-options:
  -- strip-options:
  -- tar-options:
  -- uhc-options:
```

### PR DESCRIPTION
**Pull request by cbclemmer**
Closes #8452
I did not create a test for the config files when I made #8054. This should test config files for leaving out nix, "nix: True", and "nix: False".
This also adds a line in the `--help` output for the nix option, it may not be necessary and can be easily removed if it is not needed.

@mhwombat it would be useful for you to confirm that this fix removes the error you were seeing
@Mikolaj I assigned you to review, if this isn't correct, please redirect the review.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by cbclemmer** [comment]
But uh... let me get the tests passing firsts

**Comment by cbclemmer** [comment]
It looks like [this](https://github.com/haskell/bytestring/pull/410) pr for bytestring is causing the tests to fail. It looks like the test that failed depended upon getting the latest version of bytestring and then building it, it then tried to build the `data-array-byte` package but couldn't find it. I'm getting the same results locally when running the test command but I can build the bytestring repo locally just fine. Maybe this is an issue with the server caching packages or something? @Mikolaj What do you think?

**Comment by cbclemmer** [comment]
Relevant links:
https://github.com/haskell/cabal/blob/master/cabal-testsuite/PackageTests/postCheckoutCommand/cabal.positive.project
https://github.com/haskell/bytestring/pull/410
https://github.com/Bodigrim/data-array-byte

**Comment by cbclemmer** [comment]
@Mikolaj Tests are passing 🎉

**Comment by Mikolaj** [comment]
@cbclemmer: thank you for the diagnosis of the spurious CI failure. Indeed that seems to have been the problem and we have since fixed it after a lot of confusion. A pity I haven't looked at this PR earlier. :)

@mhwombat, might we solicit your review? Even just an absent-minded look at the code, a checkout, a run and a report in a comment that it works fine now? I will have a closer look now, but another pair of eyes is very welcome (and also we formally require two reviews for each PR).

File: cabal-install/src/Distribution/Client/Setup.hs [hunk 1]
```diff
@@ -364,6 +364,11 @@ globalCommand commands = CommandUI {
       ,multiOption "nix"
         globalNix (\v flags -> flags { globalNix = v })
         [
+          optArg' "(True or False)" maybeStringToBoolFlag (\case
+            Flag True -> [Just "enable"]
+            Flag False -> [Just "disable"]
+            NoFlag -> [Just "disable"]) "" ["nix"]
+            "Nix integration: run commands through nix-shell if a 'shell.nix' file exists (default is False)",
```
Comment (Mikolaj) [inline cabal-install/src/Distribution/Client/Setup.hs:371]: Could this trivially be expressed using `trueArg` or `boolOpt` or similar? If not trivially, the extra `maybeStringToBoolFlag` function is fine.

**Review by Mikolaj — APPROVED** [review]
Thanks a lot for the fix, the test and the changelog.

File: cabal-install/src/Distribution/Client/Setup.hs (hunk 1 above)
Comment (cbclemmer) [reply cabal-install/src/Distribution/Client/Setup.hs:371]: @Mikolaj That part is to make the `nix: True|False` part work in the config file. The issue was that only `enable-nix` and `disable-nix` worked for both the command line arg and the config file. This makes it so that all three work while showing the correct help text. I tried a few different things and none of them satisfied all the things I wanted to do.

Comment (cbclemmer) [reply cabal-install/src/Distribution/Client/Setup.hs:371]: I can't remember exactly why I didn't go with it, but I'll try again and let you know

Comment (cbclemmer) [reply cabal-install/src/Distribution/Client/Setup.hs:371]: @Mikolaj looked at it again and this is what I found:
`boolOpt` creates two separate help text fields with the only difference being that "enable" or "disable" is prepended to the help text. This is what the original pr was addressing because that was what was being used there and creating bad help text.

`trueArg|falseArg` I can use this in conjunction with `boolOpt` to get the help text to work but they end up overriding each other in practice and the tests fail.

`optArg` is actually a more verbose version of `optArg'` so it saves characters and complexity to use `optArg'` over `optArg` (I assume this is why `optArg'` is used so much more in general)

Comment (Mikolaj) [reply cabal-install/src/Distribution/Client/Setup.hs:371]: Thank you for the analysis. TIL. Once a second review arrives, let's ship it!

File: Cabal/src/Distribution/Simple/Flag.hs [hunk 2]
```diff
@@ -124,6 +125,12 @@ maybeToFlag :: Maybe a -> Flag a
 maybeToFlag Nothing  = NoFlag
 maybeToFlag (Just x) = Flag x
 
+maybeStringToBoolFlag :: Maybe String -> Flag Bool
+maybeStringToBoolFlag Nothing = NoFlag
```
Comment (ulysses4ever) [inline Cabal/src/Distribution/Simple/Flag.hs:129]: Can it be defined simply as `maybeToFlag . (readMaybe =<<)`?

**Comment by Mikolaj** [comment]
The CI failure is probably caused by https://bugs.launchpad.net/ubuntu/+source/git/+bug/1993586 (and by us using the latest Ubuntu container).

**Comment by Mikolaj** [comment]
May be fixed in https://github.com/haskell/cabal/pull/8546 (if CI passes there).

**Comment by Mikolaj** [comment]
The CI fix seems to work. Let me rebase on it...

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by cbclemmer** [comment]
@Mikolaj Thank you, I was really confused

File: Cabal/src/Distribution/Simple/Flag.hs (hunk 2 above)
Comment (cbclemmer) [reply Cabal/src/Distribution/Simple/Flag.hs]: @ulysses4ever I changed it. Thanks, I hadn't used that function before.

**Review by ulysses4ever — APPROVED** [review]

**Comment by Mikolaj** [comment]
This time it seems it failed due to some corruption, hanging and cancellation after 360min. I'm restarting.

**Comment by Mikolaj** [comment]
Succes. Quick, @cbclemmer, set one of the merge_me labels to merge the PR while it still passes CI. :)

**Comment by Mikolaj** [comment]
Edit: with mergify waiting 2 days after the label is set, as per the process.
