### PR TITLE
cabal man handles $PAGER with more than one word now

### LINKED ISSUE #8405: cabal man should support spaces in PAGER env var
**Describe the bug**

When running e. g. `env PAGER="less -R" cabal man`, it will fail with:

```
less -R: createProcess: posix_spawnp: does not exist (No such file or directory)
```

**Expected behavior**

It is relatively common for `PAGER` to contain spaces and the usual convention is to either support custom env vars that allow specifying options and pager independently (e.g. git) or split on spaces in the `PAGER` env var (possibly implementing shell quoting rules is also necessary).

E.g. GNU `man-db`'s `man(1)` does support it:

```
       MANPAGER, PAGER
              If $MANPAGER or $PAGER is set ($MANPAGER is used in preference),
              its value is used as the name of the program used to display the
              manual page.  By default, less is used, falling back to cat if
              less is not found or is not executable.

              The value may be a simple command name or a command with
              arguments, and may use shell quoting (backslashes, single
              quotes, or double quotes).  It may not use pipes to connect
              multiple commands; if you need that, use a wrapper script, which
              may take the file to display either as an argument or on
              standard input.
```

**System information**
 - NixOS
 - cabal-install 3.8.1.0, GHC 8.8.4, 8.10.7, 9.0.2, 9.2.4

### PR DESCRIPTION
**Pull request by ulysses4ever**
Fix #8405

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

File: cabal-install/src/Distribution/Client/Manpage.hs [hunk 1]
```diff
@@ -78,9 +78,11 @@ manpageCmd pname commands flags
 
         unless (ec1 == ExitSuccess) $ exitWith ec1
 
-        pager <- fromMaybe "less" <$> lookupEnv "PAGER"
-        -- 'less' is borked with color sequences otherwise
-        let pagerArgs = if takeFileName pager == "less" then ["-R"] else []
+        pagerAndArgs <- fromMaybe "less -R" <$> lookupEnv "PAGER"
+        -- 'less' is borked with color sequences otherwise, hence -R
+        (pager : pagerArgs) <- case words pagerAndArgs of
```
Comment (andreasabel) [inline cabal-install/src/Distribution/Client/Manpage.hs:83]: I am suprised this does not earn you a pattern completeness warning by GHC (or maybe it uses MonadFail).
Anyhow, the best practice is:
```haskell
(x, xs) <- case mylist of
  [] -> error-out
  x:xs -> pure (x, xs)
```

File: cabal-install/src/Distribution/Client/Manpage.hs [hunk 2]
```diff
@@ -78,9 +78,11 @@ manpageCmd pname commands flags
...
+          [] -> die' verbosity "man: empty value of the PAGER environment variable"
+          pa -> pa
```
Comment (andreasabel) [inline cabal-install/src/Distribution/Client/Manpage.hs:85]: I bet there is a `pure` missing.

**Review by andreasabel — CHANGES_REQUESTED** [review]
Thanks for this fix!

File: cabal-install/src/Distribution/Client/Manpage.hs (hunk 1 above)
Comment (ulysses4ever) [reply cabal-install/src/Distribution/Client/Manpage.hs]: Tanks! Updated.

File: cabal-install/src/Distribution/Client/Manpage.hs [hunk 3]
```diff
@@ -78,9 +78,11 @@ manpageCmd pname commands flags
 
         unless (ec1 == ExitSuccess) $ exitWith ec1
 
-        pager <- fromMaybe "less" <$> lookupEnv "PAGER"
-        -- 'less' is borked with color sequences otherwise
-        let pagerArgs = if takeFileName pager == "less" then ["-R"] else []
+        pagerAndArgs <- fromMaybe "less -R" <$> lookupEnv "PAGER"
+        -- 'less' is borked with color sequences otherwise, hence -R
+        (pager, pagerArgs) <- case words pagerAndArgs of
```
Comment (sternenseemann) [inline cabal-install/src/Distribution/Client/Manpage.hs:83]: Note that GNU man also supports some shell escaping/quoting rules here. The question is, of course, how many rely on this feature.

**Review by andreasabel — APPROVED** [review]

File: cabal-install/src/Distribution/Client/Manpage.hs (hunk 3 above)
Comment (ulysses4ever) [reply cabal-install/src/Distribution/Client/Manpage.hs:83]: Hmm, do you have an example in mind? If you want to experiment, you can download the cabal binary built with this patch [on the CI page](https://github.com/haskell/cabal/actions/runs/2895724823) (very bottom of it).

I don’t think compatibility with GNU man (or any other implementation of the format) was necessarily the goal of `cabal man` — only compatibility with the format. But we certainly want to support most widely-used scenarios.

Comment (sternenseemann) [reply cabal-install/src/Distribution/Client/Manpage.hs:83]: In theory you can have spaces in there:

```console
> echo "#!/bin/sh"\n'exec less "$@"' > weird\ pager
> env PAGER=$HOME/weird\\\ pager man less
> env PAGER=$HOME/\"weird\ pager\" man less
```

This is just something to note, OpenBSD's man implementation for example doesn't support this, so I doubt it's something a lot of people rely on. I don't think the need to have spaces in an argument to the pager comes up a lot.

Comment (ulysses4ever) [reply cabal-install/src/Distribution/Client/Manpage.hs:83]: Ah, good point, thank you. Yeah, this would be much trickier to support, I guess. So, not today...

**Comment by ulysses4ever** [comment]
@Mergify refresh
