### PR TITLE
Handle removing files better

### LINKED ISSUE #11606: Handle removing files better
Cabal code is full of things like 
```haskell
    exists <- doesFileExist buildInfoFile
    when exists $ removeFile buildInfoFile
```

This is suboptimal. It's possible that the file got removed by a concurrent thread in between `doesFileExist` and `removeFile`. In such case `removeFile` will fail with exception about non-existent file, which is very stupid. A more robust way is to call `removeFile` straight ahead and catch `isDoesNotExistError`. 

Bonus points for catching `isPermissionError` to disable read-only flag on Windows and trying `removeFile` again. 

Perhaps checking for `EBUSY` (aka `UnsatisfiedConstraints`) to wait a millisecond and retry would be also helpful.

### PR DESCRIPTION
**Pull request by Bodigrim**
Closes #11606.

**Template Α: This PR modifies [behaviour or interface](https://github.com/cabalism/cabal/blob/master/CONTRIBUTING.md#changelog)**

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
  * [ ] [Is the change significant?](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#is-my-change-significant) If so, remember to add `significance: significant` in the changelog file.
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [ ] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

### CODE REVIEW

File: cabal-install/src/Distribution/Client/VCS.hs [hunk 1]
```diff
@@ -534,18 +530,15 @@ vcsGit =
...
-                  "attrib -s -h -r " <> dotGitModulesPath <> "\\*.* /s /d"
-
-            catch
-              (removePathForcibly dotGitModulesPath)
-              (\e -> if isPermissionError e then removePathForcibly dotGitModulesPath else throw e)
-          else removeDirectoryRecursive dotGitModulesPath
+        -- Windows can't delete some git files #10182
+        when (buildOS == Windows) $
+          void $
+            Process.createProcess_ "attrib" $
```
Comment (geekosaur) [inline cabal-install/src/Distribution/Client/VCS.hs:536]: Should this and the delayed retry perhaps be pushed down into `removeFileForcibly`, considering it already does so in some circumstances?

**Review by geekosaur — APPROVED** [review]

File: cabal-install/src/Distribution/Client/VCS.hs (hunk 1 above)
Comment (Bodigrim) [reply cabal-install/src/Distribution/Client/VCS.hs:536]: This commit belongs to (already merged) #11604, but let me answer anyway:

AFAICT there is no reason to change attributes via `createProcess_ "attrib"`, because `removeFileForcibly` will do it itself. But I don't really know for sure (it's Windows, after all) and it would be annoying to introduce a subtle regression. So perhaps it can stay as is for now.

File: Cabal/src/Distribution/Simple/Utils.hs [hunk 2]
```diff
@@ -1812,6 +1816,26 @@ copyFilesWith doCopy verbosity targetDir srcFiles = withFrozenCallStack $ do
...
+    -- reaching out for internal API, so instead of it we call 'removePathForcibly',
+    -- which is a bit of overkill for a single file, but well.
+    | isPermissionError e -> removePathForcibly fp
+    -- If device is busy, wait 1ms and give it another go.
+    -- EBUSY from unlink(2) is mapped to UnsatisfiedConstraints.
+    | ioeGetErrorType e == GHC.UnsatisfiedConstraints -> do
+        threadDelay 1000
+        removeFile fp
+    -- Else we give up.
+    | otherwise -> throwIO e
```
Comment (zlonast) [inline Cabal/src/Distribution/Simple/Utils.hs:1837]: In Haskell, we have very poor support for Windows operating system errors. The libraries provided by the compiler don't have a comprehensive manual catch for these errors for Windows. Essentially, we only catch errors on Linux and Mac (so-called errno). I think this will also silently crash, like renameFileWithRetry.

Comment (Bodigrim) [reply Cabal/src/Distribution/Simple/Utils.hs:1837]: The main idea here is having a shared helper to handle `isDoesNotExistError`, the rest of error handling is bolt-on. In my manual testing it works reasonably ok-ish, although certainly not bulletproof.

**Comment by Bodigrim** [comment]
Anyone else up for review please?

File: Cabal/src/Distribution/Simple/Utils.hs [hunk 3]
```diff
@@ -1812,6 +1816,26 @@ copyFilesWith doCopy verbosity targetDir srcFiles = withFrozenCallStack $ do
...
+    -- If we got a permission error, chances are that it's a read-only
+    -- file on Windows. Removing read-only attribute ourselves requires
+    -- reaching out for internal API, so instead of it we call 'removePathForcibly',
+    -- which is a bit of overkill for a single file, but well.
+    | isPermissionError e -> removePathForcibly fp
+    -- If device is busy, wait 1ms and give it another go.
+    -- EBUSY from unlink(2) is mapped to UnsatisfiedConstraints.
+    | ioeGetErrorType e == GHC.UnsatisfiedConstraints -> do
+        threadDelay 1000
+        removeFile fp
```
Comment (ulysses4ever) [inline Cabal/src/Distribution/Simple/Utils.hs:1835]: Shouldn't it be the removeFileForcibly once again?

File: Cabal/src/Distribution/Simple/Utils.hs (hunk 2 above)
Comment (ulysses4ever) [reply Cabal/src/Distribution/Simple/Utils.hs:1837]: Point of order: this has to be resolved before the pr can be merged.

File: Cabal/src/Distribution/Simple/GHCJS.hs [hunk 4]
```diff
@@ -1570,10 +1569,8 @@ gbuild verbosity numJobs pkg_descr lbi bm clbi = do
       -- Work around old GHCs not relinking in this
       -- situation, see #3294
       let target = targetDir </> makeRelativePathEx targetName
-      when (compilerVersion comp < mkVersion [7, 7]) $ do
-        let targetPath = i target
-        e <- doesFileExist targetPath
-        when e (removeFile targetPath)
+      when (compilerVersion comp < mkVersion [7, 7]) $
```
Comment (ulysses4ever) [inline Cabal/src/Distribution/Simple/GHCJS.hs:1572]: As zlonast mentioned elsewhere , checks for <7.7 could go. I understand if you prefer to not include it in this PR.

File: Cabal/src/Distribution/Simple/Utils.hs (hunk 3 above)
Comment (Bodigrim) [reply Cabal/src/Distribution/Simple/Utils.hs:1835]: Potentially, but in such case we would have to implement a limit of retries lest it ends up retrying forever.

File: Cabal/src/Distribution/Simple/GHCJS.hs (hunk 4 above)
Comment (zlonast) [reply Cabal/src/Distribution/Simple/GHCJS.hs:1572]: I guess we can just make this decision in my pr? https://github.com/haskell/cabal/pull/11630

File: Cabal/src/Distribution/Simple/Utils.hs (hunk 3 above)
Comment (ulysses4ever) [reply Cabal/src/Distribution/Simple/Utils.hs:1835]: Oh well ❤️‍🩹
