### PR TITLE
cabal-install: Fix the directory the build folder is created in

### LINKED ISSUE #10772: `cabal run` creates a `build` folder if `dist-newstyle` is already present
**Describe the bug**
`cabal run` creates a `build` folder if `dist-newstyle` is already present.
Offspring of #10686.

**To Reproduce**

1. Create new folder, cd into it.
2. Create a `dist-newstyle` folder inside it.
3. Create a minimal `script.hs`.
    ```
    #! /usr/bin/env cabal

    {- cabal:
    build-depends: base
                 , acme-missiles
    -}

    import Acme.Missiles
 
    main :: IO ()
    main = launchMissiles
    ```
4. Make it executable, run it.
5. Modify the script slightly (e.g. add a putStrLn), run it again
6. `ls -l`
7. There is a `build` folder.
**Expected behavior**
`build/` is not created.

**System information**
Debian bookworm. cabal 3.15.

**Additional context**
This is *not* fixed by #10771 , but neither is a regression and once #10771 lands, not urgent.

### PR DESCRIPTION
**Pull request by mpickering**
Clearly this path needs to be relative to the CWD, and the correct offset is passed as the `srcdir` parameter.

Fixes #10772

Please read [Github PR Conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions) and then fill in *one* of these two templates.

---

**Template Α: This PR modifies [behaviour or interface](https://github.com/cabalism/cabal/blob/master/CONTRIBUTING.md#changelog)**

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
  * [ ] [Is the change significant?](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#is-my-change-significant) If so, remember to add `significance: significant` in the changelog file.
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [ ] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

### CODE REVIEW

**Review by alt-romes — APPROVED** [review]
Very good. Please include the issue's reproducer as a regression test.

**Review by sheaf — APPROVED** [review]

File: changelog.d/pr-10800 [hunk 1]
```diff
@@ -0,0 +1,12 @@
+synopsis: Fix regression where 'build' folder was created in CWD when running standlone script.
```
Comment (sheaf) [inline changelog.d/pr-10800:1]:
```suggestion
synopsis: Fix regression where 'build' folder was created in CWD when running a standalone script.
```

File: changelog.d/pr-10800 [hunk 2]
```diff
@@ -0,0 +1,12 @@
...
+packages: cabal-install
+prs: #10800
+issues:
```
Comment (sheaf) [inline changelog.d/pr-10800:4]:
```suggestion
issues: #10772
```

**Comment by ffaf1** [comment]
How much of a hassle would it be to add a test?

**Comment by ulysses4ever** [comment]
Yes, a test would be highly desirable if it's not too hard...

**Comment by Mikolaj** [comment]
I suppose this is not on branch 3.14 yet? Do we want to backport this? One of issues marked as a regression pointed here, but I can't find it right now.

**Comment by Mikolaj** [comment]
@mergify backport 3.14
