### PR TITLE
Include package version in --promised-dependency flag

### LINKED ISSUE #10166: Cabal-4569 happens when running `cabal repl --enable-multi-repl all`
## How to reproduce:

```
$ git clone https://github.com/haskell-servant/servant
$ cabal repl --enable-multi-repl all

[…]


Running Haddock on library for servant-multipart-api-0.12.1...
Error: [Cabal-4569]
internal error when calculating transitive package dependencies.
Debug info: []

[…]

Running Haddock on library for servant-js-0.9.4.2...
Error: [Cabal-4569]
internal error when calculating transitive package dependencies.
Debug info: []
```

etc, etc.

No debug info is provided, so uh, no idea what's going on.

### PR DESCRIPTION
**Pull request by mpickering**
In the original implementation of promised dependencies I accidentally left over the hard coded `currentCabalId` in the `configureDependencies` function.

This led to several errors happening later when the package name and version would be incorrect if you looked at this field (package arguments are not computed using it), it is used when generating cabal macros and something in the haddock options.

The solution is to pass the package version in the `--promised-depenency` flag so the format is now

```
NAME-VER[:COMPONENT_NAME]=CID`
```

rather than

```
NAME[:COMPONENT_NAME]=CID
```

Fixes #10166

Please read [Github PR Conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions) and then fill in *one* of these two templates.

---

**Template Α: This PR modifies [behaviour or interface](https://github.com/cabalism/cabal/blob/master/CONTRIBUTING.md#changelog)**

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [x] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

### CODE REVIEW

File: Cabal/src/Distribution/Simple/Configure.hs [hunk 1]
```diff
@@ -1975,8 +1975,8 @@ selectDependency
       -- We have to look it up externally
       do_external_external :: LibraryName -> Either FailedDependency DependencyResolution
       do_external_external lib
-        | Just cid <- Map.lookup (dep_pkgname, CLibName lib) promisedIndex =
-            return $ PromisedDependency (PromisedComponent dep_pkgname (AnnotatedId currentCabalId (CLibName lib) cid))
+        | Just pc <- Map.lookup (dep_pkgname, CLibName lib) promisedIndex =
+            return $ PromisedDependency (ConfiguredPromisedComponent dep_pkgname (AnnotatedId (promisedComponentPackage pc) (CLibName lib) (promisedComponentId pc)))
```
Comment (mpickering) [inline Cabal/src/Distribution/Simple/Configure.hs:1979]: This is the main relevant change, removing `currentCabalId`.

**Review by geekosaur — APPROVED** [review]

File: Cabal/src/Distribution/Simple/Setup/Config.hs [hunk 2]
```diff
@@ -779,13 +779,13 @@ configureOptions showOrParseArgs =
        , option
           ""
           ["promised-dependency"]
-          "A list of promised dependencies. E.g., --promised-dependency=\"void=void-0.5.8-177d5cdf20962d0581fe2e4932a6c309\""
+          "A list of promised dependencies. E.g., --promised-dependency=\"void,0.1.1=void-0.5.8-177d5cdf20962d0581fe2e4932a6c309\""
```
Comment (sheaf) [inline Cabal/src/Distribution/Simple/Setup/Config.hs:782]:
```suggestion
          "A list of promised dependencies. E.g., --promised-dependency=\"void-0.5.8=void-0.5.8-177d5cdf20962d0581fe2e4932a6c309\""
```

**Review by sheaf — APPROVED** [review]

**Comment by mpickering** [comment]
Can I merge this without a delay? I want to get this and #10256 landed before I go on holiday next week but they both update the structured hashes so it will be a minimum of 5ish days to land both.
