### PR TITLE
Do not ask overwrite questions for empty dirs

### LINKED ISSUE #9150: cabal init regression: blank project asks to overwrite files
In a completely new directory, this made my heart jump a bit for Cabal 3.10: 

```
λ П arithmetic → cabal update
Downloading the latest package list from hackage.haskell.org
Package list of hackage.haskell.org has been updated.
The index-state is set to 2023-07-26T18:33:40Z.
To revert to previous state run:
    cabal v2-update 'hackage.haskell.org,2023-06-22T20:21:41Z'
λ П arithmetic → cabal init
What does the package build:
   1) Library
 * 2) Executable
   3) Library and Executable
   4) Test suite
Your choice? [default: Executable] 1
Do you wish to overwrite existing files (backups will be created) (y/n)? [default: n]
```

Why is it asking to overwrite existing files in a new directory? Why is it doing this *at all* in the interactive case? This is a UI/UX regression.

### PR DESCRIPTION
**Pull request by ffaf1**
Closes #9150, blank projects need not to ask permission to overwrite files.

---

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.
* [x] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.

Bonus points for added automated tests!

---

**Q&A instructions**

1. create an empty folder, `cd` into it
2. run `cabal init -i`,
3. with old cabal, you will see this string as second question `Do you wish to overwrite existing files (backups will be created) (y/n)? [default: n]`.
4. with new cabal, you will not see the question (since it is useless, as we are in an empty folder).

### CODE REVIEW

**Review by geekosaur — APPROVED** [review]

**Comment by ffaf1** [comment]
Learn how to break all the tests with this one weird trick

File: cabal-install/src/Distribution/Client/Init/Interactive/Command.hs [hunk 1]
```diff
@@ -276,10 +276,16 @@ genTestTarget flags pkgs = initializeTestSuitePrompt flags >>= go
 
 overwritePrompt :: Interactive m => InitFlags -> m Bool
 overwritePrompt flags = do
-  isOverwrite <- getOverwrite flags
-  promptYesNo
-    "Do you wish to overwrite existing files (backups will be created) (y/n)"
-    (DefaultPrompt isOverwrite)
+  con <- listDirectory $ fromFlagOrDefault "." (packageDir flags)
```
Comment (ptkato) [inline cabal-install/src/Distribution/Client/Init/Interactive/Command.hs:279]: You might want to use `getPackageDir` here, for consistency
https://github.com/haskell/cabal/blob/a40876dbdb0fe624cb8c64453ece3c768a79832c/cabal-install/src/Distribution/Client/Init/FlagExtractors.hs#L68-L69

**Review by ptkato — APPROVED** [review]

**Comment by ffaf1** [comment]
Finally! I really don't fancy cabal unit tests with pure interface, understanding fixing errors like:

```
tests/UnitTests/Distribution/Client/Init/Interactive.hs:128:
BreakException "Error: popList: \"xx\"\nStacktrace: \"3\" :| [\"quxTest/Main.hs\"]"
```

is a bit of a pain.

Thanks for the reviews!
