### PR TITLE
Force Cabal >= 1.24 dep when there's no custom-setup stanza.

### LINKED ISSUE #3199: Package with custom Setup.hs "Encountered missing dependencies"
New report (edited by @ezyang)

Cabal 1.23 and later #2731 allow you to skip specifying dependencies which are not part of a buildable component. cabal-install was updated to take advantage of this fact.

However, when a package has a `Custom` setup script, it is possible for the Setup script to be built against an old version of Cabal, which is doesn't know to ignore non-buildable dependencies. In this case, cabal-install will pass an insufficient set of dependencies, resulting in an error like this:

```
    setup: At least the following dependencies are missing:
    process -any, temporary >=1.1
```

(where these are dependencies of non-buildable components.)

A workaround is to explicitly request that all components be built. For example, if there is some flag which must be selected to make a component buildable, you should pass `--constraint="package-name +flagname"`

----

Original bug report:

Trying to build pandoc-citeproc (which has a custom Setup.hs with a couple of hooks) using the latest-packaged version from git in the HVR repository (Version: 1.23+git20160204.0.7aab356~wily) fails to find dependencies already installed in a sandbox (whether the dependencies are installed manually or via the dependency solver).

    $ uname -a
    Linux <hostname> 4.2.0-30-generic #35-Ubuntu SMP Fri Feb 19 13:52:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
    $ ghc --version
    The Glorious Glasgow Haskell Compilation System, version 7.10.3
    $ cabal --version
    cabal-install version 1.23.0.0
    compiled using version 1.23.1.0 of the Cabal library
    $ cabal sandbox init
    $ cabal install pandoc-citeproc
    Configuring pandoc-citeproc-0.9...
    setup: At least the following dependencies are missing:
    process -any, temporary >=1.1
    $ cabal sandbox hc-pkg list process
    process-1.2.3.0
    $ cabal sandbox hc-pkg list temporary
    temporary-1.2.0.4

This was previously filed as jgm/pandoc-citeproc#216

### PR DESCRIPTION
**Pull request by 23Skidoo**
Fixes #3199. 

To minimise the impact we should probably add default setup dependencies only to packages affected by #3199 (see @grayjay's [snippet](https://gist.github.com/grayjay/c5c2627d02303bd59a3b164055233bcb)). Note, however, that the setup wrapper will pick Cabal >= 1.24 anyway if it is installed, since it prefers new Cabal versions.

Note also that `cabal configure` will still fail (unlike `cabal install`), though the error message will be more helpful than it currently is:

```
Resolving dependencies...
Warning: solver failed to find a solution:
Could not resolve dependencies:
trying: test-t3199-0.1.0.0 (user goal)
next goal: test-t3199-setup.Cabal (dependency of test-t3199-0.1.0.0)
rejecting: test-t3199-setup.Cabal-1.22.5.0/installed-cfe... (conflict:
test-t3199 => test-t3199-setup.Cabal>=1.24)
Dependency tree exhaustively searched.
Trying configure anyway.
Configuring test-t3199-0.1.0.0...
```

/cc @dcoutts

### CODE REVIEW

**Comment by 23Skidoo** [comment]
I considered adding a test case, but it's a bit difficult given that you need to have a pre-1.24 version of Cabal installed for the bug to manifest.

**Comment by 23Skidoo** [comment]
GHC 8 failure is due to GHC 8 having an old snapshot of Cabal 1.24. Ugh, wish we could ignore it somehow.

**Comment by ezyang** [comment]
In principle, cabal-install should know what version of Cabal it was built with, so it can demand that from the package database. But this won't work if you're distributing a statically linked Cabal binary, in that case you can't assume the Cabal 1.24 library is installed.

**Comment by 23Skidoo** [comment]
> But this won't work if you're distributing a statically linked Cabal binary

Yep. Some people also like to build `cabal-install` inside a sandbox and then copy the executable to `~/bin`.

**Comment by ezyang** [comment]
I don't understand the approach this patch takes. Wasn't the original plan to only levy this implicit dependency if there was a `buildable` field?

**Comment by ezyang** [comment]
I think we want a test, if only to tell if the patch actually fixes the problem.

I think the easiest way to do this is to make the integration test GHC < 8.0 only. In these cases, we can assume GHC was distributed with an older version of Cabal. This will be sufficient for Travis.

**Comment by 23Skidoo** [comment]
> I don't understand the approach this patch takes. Wasn't the original plan to only levy this implicit dependency if there was a `buildable` field?

Sure, I can do that, just wanted to get some comments first. Though I think that forcing custom setup scripts to use the same Cabal version that cabal-install was compiled with is a good idea in general (provided that the user can force a different version manually via `--use-cabal-version`).

File: cabal-install/Distribution/Client/SetupWrapper.hs [hunk 1]
```diff
@@ -179,6 +181,13 @@ data SetupScriptOptions = SetupScriptOptions {
     -- style with no dependencies.
     useDependenciesExclusive :: Bool,
 
+    -- | Don't add a default dependency on Cabal even if
+    -- 'useDependenciesExclusive' is @False@. Assume that it is provided via
+    -- 'useDependencies'. This is turned on (in conjunction with
+    -- useDependenciesExclusive = False) when a default setup dependencies
+    -- stanza is added by cabal-install itself. See #3199.
+    noDefaultCabalDep :: Bool,
```
Comment (ezyang) [inline cabal-install/Distribution/Client/SetupWrapper.hs]: So, is useDependenciesExclusive == True, noDefaultCabalDep == True and impossible state?

**Comment by ezyang** [comment]
CC @dcoutts I know Duncan has stated we want the logic for compiling custom setups to be as simple as possible, so other tools (like Stack) can also handle them; I don't know how far the wrong way this goes.

**Comment by ezyang** [comment]
Re the Travis failure, a minor version bump should do the trick, right?

File: cabal-install/Distribution/Client/SetupWrapper.hs (hunk 1 above)
Comment (23Skidoo) [inline cabal-install/Distribution/Client/SetupWrapper.hs]: > `useDependenciesExclusive == True`

In that case `noDefaultCabalDep` is ignored.

**Comment by 23Skidoo** [comment]
Actually I think I can get rid of `noDefaultCabalDep`.

> Re the Travis failure, a minor version bump should do the trick, right?

Yes, I just didn't want the first 1.24 release to have a version number other than 1.24.0.0. Next time we create a release branch we should bump the version only just before the release.

**Comment by dcoutts** [comment]
@23Skidoo Unfortunately the first patch would break the use case in new-build. Have a look at:

https://github.com/haskell/cabal/blob/1223a395151b14d7899e8a93477d7b793314e589/cabal-install/Distribution/Client/ProjectPlanning.hs#L1624-L1668

There we apply custom deps for two cases, build-type custom with no explicit deps, but also non-custom when we need to build an external setup anyway.

So rather than changing how `addDefaultSetupDependencies` works, instead all you need to do is to change the function you pass to it, so that like `defaultSetupDeps` in the new-build code, you only return non-[] in the cases you're interested in, which in this case is only build-type custom with no explicit deps.

File: Cabal/Distribution/PackageDescription.hs [hunk 2]
```diff
@@ -308,18 +308,22 @@ instance Text BuildType where
 -- options authors can specify to just Haskell package dependencies.
 
 data SetupBuildInfo = SetupBuildInfo {
-        setupDepends :: [Dependency]
+        setupDepends        :: [Dependency],
+        defaultSetupDepends :: Bool
```
Comment (dcoutts) [inline Cabal/Distribution/PackageDescription.hs]: Ah, cunning. I went to some lengths in the new-build code to do this without changing the underlying type, but yes it is rather easier if we can just stash the info here. I might switch the new-build code over to use that, rather than keeping an extra Set around.

File: cabal-install/Distribution/Client/SetupWrapper.hs (hunk 1 above)
Comment (dcoutts) [inline cabal-install/Distribution/Client/SetupWrapper.hs]: I hope we can simplify the setup wrapper in future, the logic is getting really rather hairy. Fortunately the new-build code path only needs a fraction of the functionality, since it knows exactly what deps to use in advance, so doesn't need any of the guesswork that the setupWrapper currently does.

File: cabal-install/Distribution/Client/Dependency.hs [hunk 3]
```diff
@@ -451,6 +452,10 @@ standardInstallPolicy
   . hideInstalledPackagesSpecificBySourcePackageId
       [ packageId pkg | SpecificSourcePackage pkg <- pkgSpecifiers ]
 
+  . addDefaultSetupDependencies
+      (const [Dependency (PackageName "Cabal")
+              (orLaterVersion $ Version [1,24] [])])
+
```
Comment (dcoutts) [inline cabal-install/Distribution/Client/Dependency.hs]: So make this function conditional on the build-type Custom, and then we don't need the previous patch to apply that conditionality within `addDefaultSetupDependencies` itself.

**Comment by dcoutts** [comment]
So this fixes things for packages without custom setup deps, of course we still have the problem for packages that do specify an upper bound we would still have trouble communicating to them.

But it's ok as a quick hack before the release I'd say (modulo the fixes I've suggested above), but it'd be good to try and make it possible to use older Cabal versions, since we do want to be able to have packages explicitly specify versions they work with (especially since we do want to start breaking the Cabal lib API to let us make bigger improvemtns). So we may need a proper fix to this in master at some point, and perhaps also consider making releases off of older branches that work with newer compiler versions.

**Comment by hvr** [comment]
> of course we still have the problem for packages that do specify an upper bound we would still have trouble communicating to them

That's no different than a package specifying an upper bound on e.g. `base`. The solver ought to avoid such install-plans. Just as with ordinary upper bounds, we can introduce a `--setup-allow-newer=Cabal` flag...

> perhaps also consider making releases off of older branches that work with newer compiler versions.

...but then cabal would also need a way to know that, for instance, the preinstalled `Cabal-1.16.0` version that comes with GHC 7.6.3 is incompatible, but instead `Cabal-1.16.0.1` is compatible. It's a much simpler model imho to assume that there's a cut-off version of Cabal lib versions, e.g. `Cabal >= 1.18` which the current `cabal-install` is able to speak to.

@23Skidoo 

> Next time we create a release branch we should bump the version only just before the release.

that would cause problems for GHC dev (we request a bump-early-in-git policy especially for major ver bumps from bundled libraries, see https://ghc.haskell.org/trac/ghc/wiki/Commentary/Libraries/EagerVersionBump) and mask problems during RCs and/or cause annoying upper-bound-change-waves if last-minute upper bound changes occur :-/

**Comment by 23Skidoo** [comment]
@hvr
> Just as with ordinary upper bounds, we can introduce a `--setup-allow-newer=Cabal` flag...

`--allow-newer` already works for setup dependencies.

**Comment by 23Skidoo** [comment]
PR updated:

1. Removed `noDefaultCabalDep`.
1. Removed the first patch.
1. Limited the scope only to packages potentially affected by #3199.
1. Bumped Cabal version.
1. Added a test case.

@hvr 
> that would cause problems for GHC dev (we request a bump-early-in-git policy especially for major ver bumps from bundled libraries

Our versioning scheme (odd numbers == development, even == official releases) worked fine for GHC snapshots so far, I just want to extend it for release branches. So e.g. the 1.24 branch would continue to have the 1.23.x.y version right until the release. If reverse dependencies will specify the Cabal dep as `>= 1.23.x.y && < 1.25` then there should be no problems, I think.

The invariant I want to enforce is "version of Cabal in the repo" > "version of Cabal that came with GHC we're compiling with".

File: cabal-install/Distribution/Client/Dependency.hs [hunk 4]
```diff
@@ -449,12 +450,62 @@ standardInstallPolicy
...
+              , PD.extractCondition (f . PD.testBuildInfo) . snd
+                <$> PD.condTestSuites gpkg
+              , PD.extractCondition (f . PD.benchmarkBuildInfo) . snd
+                <$> PD.condBenchmarks gpkg
+              ]
+
+          alwaysTrue (PD.Lit True) = True
+          alwaysTrue _          = False
+
+          -- copied from D.PackageDescription.Configuration.extractCondition
```
Comment (ezyang) [inline cabal-install/Distribution/Client/Dependency.hs]: Blugh, copypasta!!

File: cabal-install/tests/IntegrationTests/regression/t3199/ChangeLog.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+# Revision history for logop
```
Comment (ezyang) [inline cabal-install/tests/IntegrationTests/regression/t3199/ChangeLog.md]: As a matter of personal preference, I always remove this (and the LICENSE)

File: cabal-install/tests/IntegrationTests/regression/t3199/test-3199.cabal [hunk 6]
```diff
@@ -0,0 +1,29 @@
+name:                test-t3199
+version:             0.1.0.0
+license:             BSD3
+license-file:        LICENSE
```
Comment (ezyang) [inline cabal-install/tests/IntegrationTests/regression/t3199/test-3199.cabal]: And then drop the license-field and extra-source-files fields

File: cabal-install/tests/IntegrationTests/regression/t3199.sh [hunk 7]
```diff
@@ -0,0 +1,8 @@
+. ./common.sh
+
+GHC_VERSION=`ghc --numeric-version`
+
+if [[ $GHC_VERSION < "8" ]]; then
```
Comment (ezyang) [inline cabal-install/tests/IntegrationTests/regression/t3199.sh]: I don't think this will have the intended semantics when GHC 10 is released.

File: cabal-install/tests/IntegrationTests/regression/common.sh [hunk 8]
```diff
@@ -0,0 +1,9 @@
+# Helper to run Cabal
+cabal() {
+    "$CABAL" $CABAL_ARGS "$@"
```
Comment (ezyang) [inline cabal-install/tests/IntegrationTests/regression/common.sh]: These files are no longer needed unless you need to override the default common.sh (which it does not seem to be the case.)

File: cabal-install/Distribution/Client/SetupWrapper.hs [hunk 9]
```diff
@@ -604,16 +605,22 @@ externalSetupMethod verbosity options pkg bt mkargs = do
...
           -- so only the given ones can be used. Otherwise we allow the use
           -- of packages in the ambient environment, and add on a dep on the
-          -- Cabal library.
+          -- Cabal library (unless 'useDependencies' already contains one).
           --
           -- With 'useVersionMacros' we use a version CPP macros .h file.
           --
           -- Both of these options should be enabled for packages that have
           -- opted-in and declared a custom-settup stanza.
           --
```
Comment (ezyang) [inline cabal-install/Distribution/Client/SetupWrapper.hs]: Ugh, this is annoying. Under what circumstances do we have `not useDependenciesExclusive` but we DO have a Cabal? (I guess something related to the default setup deps?)

File: cabal-install/Distribution/Client/ProjectPlanning.hs [hunk 10]
```diff
@@ -1575,14 +1575,15 @@ packageSetupScriptStylePreSolver pkg
 -- we still need to distinguish the case of explicit and implict setup deps.
 -- See 'rememberImplicitSetupDeps'.
 --
-defaultSetupDeps :: Platform -> PD.PackageDescription -> [Dependency]
+defaultSetupDeps :: Platform -> PD.PackageDescription -> Maybe [Dependency]
```
Comment (ezyang) [inline cabal-install/Distribution/Client/ProjectPlanning.hs]: Maybe we don't need this change anymore?

File: cabal-install/Distribution/Client/Dependency.hs [hunk 11]
```diff
@@ -449,12 +450,62 @@ standardInstallPolicy
...
+      -- and (potentially) 'buildable: False'? False positives are possible.
+      hasBuildableFalse :: PD.GenericPackageDescription -> Bool
+      hasBuildableFalse gpkg =
+        not (all alwaysTrue (zipWith cor buildableConditions noDepConditions))
+        where
+          buildableConditions = extractConditions PD.buildable
+          noDepConditions = extractConditions (null . PD.targetBuildDepends)
+          extractConditions f =
+            concat [
+              maybeToList $ PD.extractCondition (f . PD.libBuildInfo)
```
Comment (ezyang) [inline cabal-install/Distribution/Client/Dependency.hs]: It's a bit annoying if we don't already have some sort of fold function to do this logic...

**Comment by 23Skidoo** [comment]
The test case could be improved: right now we always install Cabal 1.24 before running the `cabal-install` test suite on Travis, so the failure can't manifest.

**Comment by ezyang** [comment]
What if we tell Cabal to not use the user database for these tests?

File: cabal-install/Distribution/Client/SetupWrapper.hs (hunk 9 above)
Comment (23Skidoo) [inline cabal-install/Distribution/Client/SetupWrapper.hs]: When we specify Cabal as a default setup dependency we want to prevent setup wrapper from adding another Cabal dependency. But we don't want it to set `-hide-all-packages`, since legacy setup scripts sometimes import stuff from libraries other than `base`/`Cabal`.

**Comment by 23Skidoo** [comment]
Something like that should work.

File: cabal-install/tests/IntegrationTests/regression/t3199/test-3199.cabal (hunk 6 above)
Comment (23Skidoo) [inline cabal-install/tests/IntegrationTests/regression/t3199/test-3199.cabal]: Fixed.

File: cabal-install/tests/IntegrationTests/regression/common.sh (hunk 8 above)
Comment (23Skidoo) [inline cabal-install/tests/IntegrationTests/regression/common.sh]: > These files are no longer needed 

Did that change make it into 1.24?

**Comment by 23Skidoo** [comment]
Will fix the remaining issues tomorrow.

File: cabal-install/Distribution/Client/ProjectPlanning.hs (hunk 10 above)
Comment (23Skidoo) [inline cabal-install/Distribution/Client/ProjectPlanning.hs]: May be. I wanted to minimise the impact of my changes.

**Comment by 23Skidoo** [comment]
Updated the test case.

**Comment by 23Skidoo** [comment]
Moved copy-pasted utilities into the Cabal library, improved the test case. I think that this is now ready to go in, will merge once the build bots are green.

File: Cabal/Distribution/PackageDescription.hs [hunk 12]
```diff
@@ -1193,11 +1199,30 @@ data Condition c = Var c
...
+
+-- | Boolean OR of two 'Condition' values.
+cOr :: Eq v => Condition v -> Condition v -> Condition v
+cOr  (Lit True)  _           = Lit True
+cOr  _           (Lit True)  = Lit True
+cOr  (Lit False) x           = x
+cOr  x           (Lit False) = x
+cOr  c           (CNot d)
+  | c == d                   = Lit True
+cOr  x           y           = COr x y
```
Comment (grayjay) [inline Cabal/Distribution/PackageDescription.hs]: I forgot to mention that I added a case to my snippet:

    cor  (CNot c)    d
      | c == d                   = Lit True

Without it, the function testing whether #3199 applies doesn't ignore this use of buildable:
```
executable exe
  if !flag(build-exe)
    buildable: False
  else
    build-depends: package
  [...]
```

Comment (hvr) [inline Cabal/Distribution/PackageDescription.hs]: indeed, it's kinda odd that symmetry was broken for the "x or (not x)" case...

Comment (23Skidoo) [inline Cabal/Distribution/PackageDescription.hs]: @grayjay Updated.
