### PR TITLE
Monitor contents of Cabal files so we rerun solver upon edits (#3323, #3324).

### LINKED ISSUE #3323: [nix-local-build] Change of version number of package not handled correctly
Steps to reproduce:
1. Create two packages `p-0.1` and `q-0.1`, with modules `P` and `Q`, and `q` depending on `p` (the contents of the modules are not important, blank modules will do.)
2. Create a cabal.project with `packages: p q`
3. `cabal new-build q`
4. Edit `p/p.cabal` so that its version is 0.2
5. `cabal new-build q -v`

Expected result: Invocation of GHC to build q refers to `p-0.2-inplace`.

Actual result: Invocation refers to `p-0.1-inplace`.

CC @dcoutts

### PR DESCRIPTION
**Pull request by ezyang**
There was a comment claiming that it was done already but this function
does not exist. I think it was referring to findProjectPackages, but
this function tests only matchFileGlob (so it will notice if a.cabal is
renamed to b.cabal) and not the actual contents of the file.

Fixes #3323 (probably) and #3324 (has test).

CC @dcoutts

### CODE REVIEW

**Comment by dcoutts** [comment]
Oh yes, `findProjectCabalFiles` did used to do that, but doesn't now (and it got renamed). However, we need to monitor as a glob, not just the results of the glob match, otherwise we'll fail to notice additions. So I think the right place to monitor is within the replacement of `findProjectCabalFiles`, ie `findProjectPackages`. It'll have to use a glob match if it parses it as a glob, and as single if it's just a single file, and no monitor if it's a http url.

File: cabal-install/Distribution/Client/ProjectPlanning.hs [hunk 1]
```diff
@@ -970,7 +970,7 @@ elaborateInstallPlan platform compiler compilerprogdb
                                 then BuildInplaceOnly else BuildAndInstall
         pkgBuildPackageDBStack    = buildAndRegisterDbs
         pkgRegisterPackageDBStack = buildAndRegisterDbs
-        pkgRequiresRegistration   = PD.hasPublicLib (PD.packageDescription gdesc)
+        pkgRequiresRegistration   = PD.hasPublicLib pkgDescription
```
Comment (dcoutts) [inline cabal-install/Distribution/Client/ProjectPlanning.hs]: Ah yes, quite right. Thanks.

**Comment by dcoutts** [comment]
I should figure out your new integration test approach and start using that myself for new tests. That said, I'm tempted to write some tests that go direct to the code, catch expected exceptions etc.

**Comment by dcoutts** [comment]
#3323 and #3324 are good examples of why we do need the integration tests. These I'm sure worked before I broke `findProjectCabalFiles`/`findProjectPackages`.

**Comment by ezyang** [comment]
@dcoutts I don't follow your reasoning. Indeed, we should monitor both the result of a glob (a filepath) and the contents of that filepath (a timestamp plus hash), but these are definitely separate concerns and should be monitored separately (unless there is no way to monitor a glob without also monitoring the contents of each globbed file; I hope not!) Having a call to monitor at the use-site helps prevent bugs which arise in the refactoring you did.

Unit tests are fine too. I just don't know how to write them. You'll probably need some DSL like the solver DSL.

**Comment by dcoutts** [comment]
@ezyang it's possible to separate things that way I guess. One can construct a glob monitor that only monitors for file existence rather than the default of mtime + content hash.

> monitorFileGlob = MonitorFileGlob FileHashed DirExists

We'd want:

> monitorFileGlobExistence = MonitorFileGlob FileExists DirExists

**Comment by dcoutts** [comment]
Working on a nicer fix, but also rearranging things to remove a class of bug (using the wrong root for glob matches).

**Comment by 23Skidoo** [comment]
I don't consider this blocking for 1.24.

**Comment by ezyang** [comment]
@23Skidoo, I don't know... this is a major bug in nix-local-build, and it has caused me plenty of very difficult to understand grief when I was affected by it.

**Comment by ezyang** [comment]
(Also, my fix is one line, and I don't think it is wrong, even though Duncan has identified a different bug. Can we perhaps just merge my fix to 1.24 and save a proper fix for master?)

**Comment by 23Skidoo** [comment]
Sure, I can do that.

**Comment by 23Skidoo** [comment]
I think I'll merge this into master as well for now so that the test case appears in both branches. @dcoutts can change the fix later.

**Comment by dcoutts** [comment]
Finally got this done. See #3347.
