### PR TITLE
Fix shebang handling code

### LINKED ISSUE #5600: accidentally typing `cabal (non-command) <path>` gives bogus output instead of reporting that 'non-command' does not exist
minimal reproducible example:

```bash
$ git clone git@github.com:chessai/semirings && cd semirings
$ cabal new-sdist
$ cabal new-upload dist-newstyle/sdist/semirings-0.2.1.1.tar.gz
Resolving dependencies...
Build profile: -w ghc-8.6.1 -O1
In order, the following will be built (use -v for more details):
 - fake-package-0 (exe:script) (configuration changed)
Configuring executable 'script' for fake-package-0..
Preprocessing executable 'script' for fake-package-0..
Building executable 'script' for fake-package-0..

Main.hs:1:1: error: lexical error at character '\US'
  |
1 | �������}kw�Ȳ��̯�}��6�`;N�3�
  | ^

```

Here's a picture:

what

Compare the above to the following, which behaves correctly:

```bash
$ cabal new-upload dist-newstyle/sdist/semirings-0.2.1.1.tar.gz --publish
cabal: unrecognised command: new-upload (try --help)
```

### PR DESCRIPTION
**Pull request by typedrat**
Fixes #5600.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [x] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.
* [x] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

File: cabal-install/main/Main.hs [hunk 1]
```diff
@@ -234,10 +235,9 @@ main' = do
 
 mainWorker :: [String] -> IO ()
 mainWorker args = do
-  validScript <-
-    if null args
-      then return False
-      else doesFileExist (last args)
+  hasScript <- if not (null args)
+    then validScript (head args)
```
Comment (hvr) [inline cabal-install/main/Main.hs]:
```suggestion
    then CmdRun.validScript (head args)
```

File: cabal-install/Distribution/Client/CmdRun.hs [hunk 2]
```diff
@@ -346,14 +351,14 @@ handleScriptCase verbosity baseCtx tempDir scriptContents = do
   -- We need to create a dummy package that lives in our dummy project.
   let
     sourcePackage = SourcePackage
-      { packageInfoId        = pkgId
-      , SP.packageDescription   = genericPackageDescription
-      , packageSource        = LocalUnpackedPackage tempDir
-      , packageDescrOverride = Nothing
+      { packageInfoId         = pkgId
```
Comment (hvr) [inline cabal-install/Distribution/Client/CmdRun.hs]: why these whitespace changes?

File: cabal-install/main/Main.hs [hunk 3]
```diff
@@ -186,7 +186,8 @@ import qualified Paths_cabal_install (version)
 import System.Environment       (getArgs, getProgName)
 import System.Exit              (exitFailure, exitSuccess)
 import System.FilePath          ( dropExtension, splitExtension
-                                , takeExtension, (</>), (<.>))
+                                , takeExtension, (</>), (<.>)
+                                , isPathSeparator, isValid )
```
Comment (hvr) [inline cabal-install/main/Main.hs]:
```
main/Main.hs:188:1: warning: [-Wunused-imports]
    The import of ‘isPathSeparator, isValid’
    from module ‘System.FilePath’ is redundant
    |
188 | import System.FilePath          ( dropExtension, splitExtension
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

File: cabal-install/Distribution/Client/CmdRun.hs [hunk 4]
```diff
@@ -172,7 +172,7 @@ runAction (configFlags, configExFlags, installFlags, haddockFlags, testFlags)
 
     let
       scriptOrError script err = do
-        exists <- doesFileExist script
+        exists <- validScript script
```
Comment (hvr) [inline cabal-install/Distribution/Client/CmdRun.hs]: using the same `validScript` here has the consequence that

    cabal run myscript.hs

doesn't work anymore because it doesn't contain any path-seps; i.e. you'd have to say

    cabal run ./myscript.hs

now. The path-separator heuristic is only desirable for the shebang-heuristic
