### PR TITLE
haddock-project fixes

### LINKED ISSUE #8843: The `index.html` that are supposed to be produced by `cabal haddock-project` are not here.
**Describe the bug**
The `index.html` that are supposed to be produced by `cabal haddock-project` are not here.

**To Reproduce**

```bash
$ git clone https://github.com/haskell-cryptography/libsodium-bindings && cd libsodium-bindings
$ cabal haddock-project
Warning: haddock-project command is experimental, it might break in the future
Resolving dependencies...
Build profile: -w ghc-9.4.4 -O1
[…]
Documentation created:
/tmp/libsodium-bindings/dist-newstyle/build/x86_64-linux/ghc-9.4.4/libsodium-bindings-0.0.1.0/doc/html/libsodium-bindings/index.html
Documentation created:
/tmp/libsodium-bindings/dist-newstyle/build/x86_64-linux/ghc-9.4.4/sel-0.0.1.0/doc/html/sel/index.html
Documentation created: haddocks/index.html
$ file haddocks/index.html
haddocks/index.html: cannot open `haddocks/index.html` (No such file or directory)
$ file /tmp/libsodium-bindings/dist-newstyle/build/x86_64-linux/ghc-9.4.4/sel-0.0.1.0/doc/html/sel/index.html
/tmp/libsodium-bindings/dist-newstyle/build/x86_64-linux/ghc-9.4.4/sel-0.0.1.0/doc/html/sel/index.html: cannot open `/tmp/libsodium-bindings/dist-newstyle/build/x86_64-linux/ghc-9.4.4/sel-0.0.1.0/doc/html/sel/index.html' (No such file or directory)
$ file /tmp/libsodium-bindings/dist-newstyle/build/x86_64-linux/ghc-9.4.4/libsodium-bindings-0.0.1.0/doc/html/libsodium-bindings/index.html
/tmp/libsodium-bindings/dist-newstyle/build/x86_64-linux/ghc-9.4.4/libsodium-bindings-0.0.1.0/doc/html/libsodium-bindings/index.html: cannot open `/tmp/libsodium-bindings/dist-newstyle/build/x86_64-linux/ghc-9.4.4/libsodium-bindings-0.0.1.0/doc/html/libsodium-bindings/index.html' (No such file or directory)
```

**Expected behavior**
The files that are advertised to be produced should be here

**System information**
 - Fedora 37
 - cabal-install version 3.10.1.0
 - The Glorious Glasgow Haskell Compilation System, version 9.4.4

### LINKED ISSUE #8958: `haddock-project --local` does not copy non-boot dependencies to output dir
**Describe the bug**
At least [the blog post](https://coot.me/posts/cabal-haddock-project.html) indicates that all dependencies (not just boot deps) should be supported:

> This command will build ./haddocks directory which you can serve with a http server. It will contain documentation of all the local packages and its dependencies. You can even control which dependencies should be included via [documentation option](https://cabal.readthedocs.io/en/3.4/cabal-project.html#cfg-field-documentation).

The code has a similar comment:
https://github.com/haskell/cabal/blob/9bf415a2d38b5e88c0ec71a839fc2003a99b6f74/cabal-install/src/Distribution/Client/CmdHaddockProject.hs#L302-L304

**To Reproduce**
https://github.com/amesgen/stuff/tree/cabal-haddock-project-deps
```
 $ git clone https://github.com/amesgen/stuff --single-branch --branch cabal-haddock-project-deps
 $ cd stuff
 $ cabal haddock-project --local
 $ ls haddocks/
array  containers  doc-index.html  exceptions  ghc-boot-th  haddock-bundle.min.js  linuwial.css  pretty          quick-jump.min.js  stuff         template-haskell
base   deepseq     doc-index.json  ghc-bignum  ghc-prim     index.html             mtl           quick-jump.css  stm                synopsis.png  transformers
```
Note that `resourcet` (a dependency of the test project) is not present.

**Expected behavior**
I would expect all dependencies to be copied to the output, or alternatively an indication in the documentation that it only works for boot deps. 

**System information**
 - NixOS, x86_64-linux
 - `cabal` 3.10.1.0, `ghc` 9.4.5

### PR DESCRIPTION
**Pull request by coot**
This PR includes three commits which later `haddock-project` command:

- use `UnitId` instead of package name
- changed default `haddock-project` options (fixes #8843)
- build dependencies so their haddocks are available in the store (fixes #8958)

# QA Notes:

## `cabal haddock-project`

Running `cabal haddock-project` should create documentation folder `./haddocks` which contains:
* `./haddocks/<package-name>` folder for every dependency of the project; in particular `./haddocks/<package-name>/<package-name>.haddock` should be present;
* `./haddocks/index.html`;
* `./haddocks/quick-jump.min.js`

When serving the `./haddocks` folder with `http` server the index page should list all the local packages.  Using quick jump from the index page should allow to find any identifier found in any of the local packages, when viewing documentation of one of them quick jump should allow to jump to any identifier of that package.  All entities should be linked, e.g. if you find `IO` in the documentation, it should lead you to base documentation of `IO`.

## `cabal haddock-project --hackage`

Running `cabal haddock-project --hackage` should create documentation folder `./haddocks` which only contains documentation of local packages.  Identifiers from dependencies should be linked to `hackage`.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] The documentation has been updated, if necessary.
* [x] Include [manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) if your PR relates to cabal-install.

Bonus points for added automated tests!

### CODE REVIEW

**Comment by coot** [comment]
@Kleidukos do you know a package published on `Hackage` which is using visible sublibraries? I haven't found any among recent uploads.

**Comment by coot** [comment]
haskell/hackage-server#1119 is still open...

**Comment by Mikolaj** [comment]
The CI failure seem to be expected at this point?

I've tentatively marked it for backport to 3.10 branch, since it fixes (semi-) regressions and it's not a huge risky PR.

**Comment by coot** [comment]
> The CI failure seem to be expected at this point?

It's unexpected. I'll try to reproduce it locally.

**Comment by coot** [comment]
Looking closer, these CI failures are expected.  I changed the log output of the `cabal haddock` command.  It no longer reports that `haddock` created `index.html` file if it didn't received `--gen-index` file.

`--gen-index` |  result                                       |
--------------|-----------------------------------------------|
present       | log location of the `index.html` file created |
not present   | log directory location of the documentation   |

**Comment by coot** [comment]
@Mikolaj do you want me to create a PR against the `3.10` branch?

**Comment by Mikolaj** [comment]
> @Mikolaj do you want me to create a PR against the `3.10` branch?

No, thank you. Mergify will do this automatically for us and I sincerely hope they won't be any conflicts.

**Comment by coot** [comment]
nice :), there shouldn't be any.

**Comment by Kleidukos** [comment]
> @Kleidukos do you know a package published on `Hackage` which is using visible sublibraries? I haven't found any among recent uploads.

@coot I don't even know if it's allowed. Hackage doesn't seem to support it?

**Comment by ulysses4ever** [comment]
> https://github.com/haskell/hackage-server/issues/1119 is still open...

It is but a comment there 
https://github.com/haskell/hackage-server/issues/1119#issuecomment-1482127224 says it should work. Just no one tried it...

File: cabal-install/src/Distribution/Client/CmdHaddockProject.hs [hunk 1]
```diff
@@ -138,6 +139,13 @@ haddockProjectAction flags _extraArgs globalFlags = do
                        { configVerbosity = haddockProjectVerbosity flags }
                    }
 
+    unless (   fromFlagOrDefault False (haddockProjectHackage flags)
+            || fromFlagOrDefault False (haddockProjectLocal flags)
```
Comment (Kleidukos) [inline cabal-install/src/Distribution/Client/CmdHaddockProject.hs:143]: I don't think I'm comfortable with the command doing most things but not quite everything without an additional flag. From a user perspective the most common use-case would be `--local` and I'd like to suggest it to be the default unless `--hackage` is passed.

**Review by Kleidukos — CHANGES_REQUESTED** [review]

File: cabal-install/src/Distribution/Client/CmdHaddockProject.hs (hunk 1 above)
Comment (coot) [reply cabal-install/src/Distribution/Client/CmdHaddockProject.hs:143]: But then, there's no way to use `haddock` the way one would want, e.g. maybe one is not interested in creating the `index.html` because it's created in another way.

I am not sure how useful this is though...

Comment (Kleidukos) [reply cabal-install/src/Distribution/Client/CmdHaddockProject.hs:143]: yeah I actually have never seen anyone able to generate the index outside of the "normal"(sic) workflow. Worst case, we can modularise it later, but I'd like to invest in usability first. :)

Comment (ulysses4ever) [reply cabal-install/src/Distribution/Client/CmdHaddockProject.hs:143]: +1 for having `--local` on by default unless `--hackage` is there.

Comment (coot) [reply cabal-install/src/Distribution/Client/CmdHaddockProject.hs]: Done, please review.

**Review by Kleidukos — APPROVED** [review]
Good for me!

**Comment by coot** [comment]
I pushed one more commit to fix #8958.

**Comment by ulysses4ever** [comment]
@coot could you add a test that ensures that dependencies are handled correctly?

**Comment by coot** [comment]
yes, I am planning to do that.

**Comment by coot** [comment]
@ulysses4ever I added a test.

File: cabal-install/tests/IntegrationTests2/haddock-project/dependencies/a.cabal [hunk 2]
```diff
@@ -0,0 +1,10 @@
+name: a
```
Comment (ulysses4ever) [inline cabal-install/tests/IntegrationTests2/haddock-project/dependencies/a.cabal:1]: This whole directory (`haddock-project`) looks out of place to me. I think it should be deeper in the directory structure. But I'm not familiar with `IntegrationTests2`: I usually use `cabal-testsuite/PackageTests` for integration tests -- I think, it's the latest rewrite of the integration test suite (cf. https://github.com/haskell/cabal/tree/master/cabal-testsuite#design-notes), which implies that extending the previous versions (e.g. `IntegrationTests2`) should, perhaps, be discouraged.

File: cabal-install/tests/IntegrationTests2.hs [hunk 3]
```diff
@@ -59,6 +59,12 @@ import Distribution.Version
 import Distribution.ModuleName (ModuleName)
 import Distribution.Text
 import Distribution.Utils.Path
+#if __GLASGOW_HASKELL__ >= 904
```
[the remark this answers is not in the document]
Comment (coot) [reply cabal-install/tests/IntegrationTests2.hs:62]: According to the [docs](https://downloads.haskell.org/ghc/latest/docs/users_guide/phases.html?highlight=cpp#standard-cpp-macros): `904` means `9.4.0`, `940` means `9.40.0`.

File: cabal-install/tests/IntegrationTests2.hs [hunk 4]
```diff
@@ -37,13 +37,13 @@ import Distribution.Solver.Types.ConstraintSource
...
          ( PackageProperty(PackagePropertySource) )
 
-import qualified Distribution.Client.CmdBuild   as CmdBuild
-import qualified Distribution.Client.CmdRepl    as CmdRepl
-import qualified Distribution.Client.CmdRun     as CmdRun
-import qualified Distribution.Client.CmdTest    as CmdTest
-import qualified Distribution.Client.CmdBench   as CmdBench
-import qualified Distribution.Client.CmdHaddock as CmdHaddock
-import qualified Distribution.Client.CmdListBin as CmdListBin
+import qualified Distribution.Client.CmdBuild          as CmdBuild
```
[the remark this answers is not in the document]
Comment (coot) [reply cabal-install/tests/IntegrationTests2.hs:40]: The reason is to keep the format consistent (the lines were aligned before I touched them).  If you think that's not worth it, I will revert it.

File: cabal-install/src/Distribution/Client/SetupWrapper.hs [hunk 5]
```diff
@@ -145,6 +145,7 @@ data SetupMethod = InternalMethod
                    -- child process
                  | ExternalMethod FilePath
                    -- ^ run Cabal commands through a custom \"Setup\" executable
+  deriving Show
```
[the remark this answers is not in the document]
Comment (coot) [reply cabal-install/src/Distribution/Client/SetupWrapper.hs:148]: That's a left over when I was debugging an issue.  I'll revert it.

File: cabal-install/tests/IntegrationTests2/haddock-project/dependencies/a.cabal (hunk 2 above)
Comment (coot) [reply cabal-install/tests/IntegrationTests2/haddock-project/dependencies/a.cabal:1]: I am not familiar with the integration test suite and I wasn't aware that `IntegrationTests2` is deprecated.  Are there some docs how to write the tests using `cabal-test`?

File: cabal-install/tests/IntegrationTests2.hs (hunk 3 above)
[the remark this answers is not in the document]
Comment (ulysses4ever) [reply cabal-install/tests/IntegrationTests2.hs:62]: Oh, my bad, thanks for the reference.

File: cabal-install/tests/IntegrationTests2.hs (hunk 4 above)
[the remark this answers is not in the document]
Comment (ulysses4ever) [reply cabal-install/tests/IntegrationTests2.hs:40]: Oh, i didn't notice that one line was added... I think it's fine.

File: cabal-install/tests/IntegrationTests2/haddock-project/dependencies/a.cabal (hunk 2 above)
Comment (coot) [reply cabal-install/tests/IntegrationTests2/haddock-project/dependencies/a.cabal:1]: I pushed a test using the new example.  The problem with it is that it passes even without the fix in this branch, maybe there's another way to add something to the store?

Comment (ulysses4ever) [reply cabal-install/tests/IntegrationTests2/haddock-project/dependencies/a.cabal:1]: `withRepo` is the only way to depend on a package in the tests, as far as I know. But I'm by no means an expert...

If the test doesn't come along, you could try to create a description for Manual QA (https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md?rgh-link-date=2023-04-25T20%3A36%3A28Z#qa-notes), i.e. explain how a human being can make sure that your changes achive the goal (and restating the goal would also help). But we all know that tests are a better deal.

**Comment by coot** [comment]
Finally got all tests passing. Ping @ulysses4ever.

**Comment by ulysses4ever** [comment]
@coot thank you! Currently, this PR has 7 commits. Do you intend to leave it as is or maybe squash some of them?

**Comment by coot** [comment]
I prefer to write smaller commits, each of which does one thing, so it's easier to review or dissect in the future.

**Comment by ulysses4ever** [comment]
No problem, just checking.

**Comment by ulysses4ever** [comment]
Is there any reason why having `--gen-index` on by default wouldn’t be a better default?

**Comment by coot** [comment]
This option was removed in this [commit](https://github.com/haskell/cabal/pull/8919/commits/f3c1170620c9184c4f2fb51470b7315d0cfeb110), it's on by default.

**Review by ulysses4ever — DISMISSED** [review]
Great work, thank you! I'm still working my way through it but in the meantime, I think, there are several essential things that should be done to accept this PR, namely...

1. Please, update the PR description in the first post, so that it describes where you arrived at with it. E.g., currently it says

  > it adds a warning when one is not passing --gen-index
  
  which is not the case anymore: the flag is removed.

2. Format the changelog file according to conventions, in particular: `synopsis` should be a short, preferably one-sentence description of the PR. The details should go into the `description` field. I don't think the extra layout (10 spaces in front of every line) is necessary or desirable.

3. The commits need massive squashing. if you don't want us to do it in the last moment and get one commit altogether. So, if you want this PR to implement three changes: (1) straighten up the flags (remove some flags because they're always implied now), (2) the UnitId thing, (3) fix for #8958 -- then you should have three commits. In particular, there should be NO separate commits for changelog, tests and docs.

4. The commit fixing https://github.com/haskell/cabal/issues/8958 should have a meaningful commit message (not simply `fix #XXXX`).

**Comment by ulysses4ever** [comment]
For changelogs, [feel free to consult this](https://github.com/haskell/cabal/blob/describe-changelogs-more/CONTRIBUTING.md#changelog)

File: cabal-install/src/Distribution/Client/CmdHaddockProject.hs [hunk 6]
```diff
@@ -254,6 +250,8 @@ haddockProjectAction flags _extraArgs globalFlags = do
           | not localStyle ->
               return []
         Left package -> do
+          -- TODO: this might not work for public packages with sublibraries
```
Comment (ulysses4ever) [inline cabal-install/src/Distribution/Client/CmdHaddockProject.hs:253]: This sounds a little worrying. Maybe we should preemptively create an issue describing this issue in a little more detail than it makes sense in a comment.

File: cabal-install/tests/IntegrationTests2.hs [hunk 7]
```diff
@@ -154,6 +160,13 @@ tests config =
       testCase "Test Config options for commented options" testConfigOptionComments,
       testCase "Test Ignore Project Flag" testIgnoreProjectFlag
     ]
+-- `haddock-project` is only supported by `haddock-2.26.1` and above which is
+-- shipped with `ghc-9.4`
+#if __GLASGOW_HASKELL__ >= 904
```
Comment (ulysses4ever) [inline cabal-install/tests/IntegrationTests2.hs:165]: CPP is a big red flag. I don't believe there's no other, more civil way to include a test only for newer compilers. If you can't find it in the old integration testsuite, I'd say, let's leave only the test in `cabal-testsuite` where we know how to check the compiler version.

**Review by ulysses4ever — COMMENTED** [review]
This PR is a breath I'm that it mostly removed code. But there's a concern about testing. Also, i believe we should do Manual QA for it, and for that we need some notes from the author.

File: cabal-install/tests/IntegrationTests2.hs (hunk 7 above)
Comment (coot) [reply cabal-install/tests/IntegrationTests2.hs:165]: I thought I removed that test, I probably need to squash some commits.

File: cabal-install/src/Distribution/Client/CmdHaddockProject.hs (hunk 6 above)
Comment (coot) [reply cabal-install/src/Distribution/Client/CmdHaddockProject.hs:253]: Do you know a package with sublibraries published on hackage?  I could test it, and remove the TODO if it works.

Comment (coot) [reply cabal-install/src/Distribution/Client/CmdHaddockProject.hs:253]: https://github.com/haskell/cabal/issues/9026

File: cabal-install/tests/IntegrationTests2.hs (hunk 7 above)
Comment (coot) [reply cabal-install/tests/IntegrationTests2.hs:163]: Actually the tests is still useful, I found a way to to avoid `CPP`.

**Comment by coot** [comment]
@ulysses4ever I think I addressed all your comments.

File: cabal-install/src/Distribution/Client/CmdHaddockProject.hs (hunk 6 above)
Comment (Mikolaj) [reply cabal-install/src/Distribution/Client/CmdHaddockProject.hs]: Yeah, we are not aware of any and we are looking for a test bunny. :)

**Comment by Kleidukos** [comment]
@coot for ease of testing, could you write down some QA notes so that we may check that the user-facing changes are the ones we expect? :)

**Comment by coot** [comment]
@Kleidukos where they should be added?

**Comment by Kleidukos** [comment]
@coot in the description of the PR, check out the boxes to tick :)

File: cabal-install/tests/IntegrationTests2.hs (hunk 7 above)
Comment (ulysses4ever) [reply cabal-install/tests/IntegrationTests2.hs:163]: @coot I still see the CPP.

**Comment by coot** [comment]
It doesn't say where such notes should be added. Certainly not in `CONTRIBUTING.md` file, or am I wrong?

**Comment by Kleidukos** [comment]
@coot you're right, I'm fixing this in https://github.com/haskell/cabal/pull/9036. Just write them in the description of your PR, please. :)

**Comment by coot** [comment]
@Kleidukos done.

File: cabal-install/src/Distribution/Client/CmdHaddockProject.hs (hunk 6 above)
Comment (ulysses4ever) [reply cabal-install/src/Distribution/Client/CmdHaddockProject.hs]: @coot the rumor is, this is one example: https://hackage.haskell.org/package/lsp-types

File: cabal-install/tests/IntegrationTests2.hs (hunk 7 above)
Comment (coot) [reply cabal-install/tests/IntegrationTests2.hs]: Not any more :)

**Comment by coot** [comment]
@ulysses4ever is there anything more you'd like to me address in this PR?

**Comment by ulysses4ever** [comment]
@coot right. I'm sorry I dropped the ball on this one. The issues I saw seem to have been fixed, than you so much! Overall, the patch is a bit above my pay grade: I am very shallow on certain things this patch does. It'd be best if someone more knowledgeable took a look at it and approved. If this won't happen soon enough I'll try my best. Can't promise the timeline because this requires me to dig into things, and I very rarely can afford it these days, unfortunately.

**Comment by coot** [comment]
@Mikolaj could you suggest another reviewer for this PR.

File: cabal-install/tests/IntegrationTests2/haddock-project/dependencies/a.cabal (hunk 2 above)
Comment (ulysses4ever) [reply cabal-install/tests/IntegrationTests2/haddock-project/dependencies/a.cabal:1]: The same test now leaves in `cabal-testsuite` (part of this patch: `cabal-testsuite/PackageTests/HaddockProject`). Should this be removed? I don't see a point to run the same test twice. Or is there any substantial difference between the two tests?

**Review by Mikolaj — APPROVED** [review]
After a quick look, LGTM, but a more thorough review would be welcome.

Whether we backport is up to @Kleidukos.

**Comment by Kleidukos** [comment]
@mergifyIO backport 3.10

**Comment by Kleidukos** [comment]
@julialongtin would you like to perform the QA procedure on this PR? :)

**Comment by ulysses4ever** [comment]
@coot you reached 2 approvals now, so you can put the `merge-me` label when you feel like it and hand it over to the bot (it will wait for 2 days before merge as usual). Thank you for your contribution and also for addressing my comments in particular!

**Comment by coot** [comment]
Thanks @ulysses4ever, @Kleidukos & @Mikolaj for cooperation.

**Comment by Mikolaj** [comment]
Thank you, @coot. That's a long struggle, but many people waited years for these features and here they are finally, more and more usable.

**Comment by coot** [comment]
Shouldn't mergify do its job by now?

**Comment by ulysses4ever** [comment]
I think you commented before the full 48 hours passed. And more the timer is probably reset. But let's fix it.

**Comment by Mikolaj** [comment]
@mergifyio refresh

**Comment by Mikolaj** [comment]
It says "Unable to update: user coot is unknown. Please make sure coot has logged in Mergify dashboard."

What was that about?

**Comment by ulysses4ever** [comment]
In the failure like this (" ❌ Queue: Embarked in merge train"), rebase is usually the way to go (Mergify fails to rebase a PR from a non-admin user on its own). "Refresh" works better when the bot thinks that some checks are not satisfied.

**Comment by ulysses4ever** [comment]
@Mergify rebase
