### PR TITLE
Fix assertion failure when combining build-tool-depends and --enable-documentation

### LINKED ISSUE #6006: Assertion failure at Distribution/Client/ProjectPlanning.hs:242:5 with --enable-documentation
Repro:

```
≻ rm -rf propellor-5.7.0/
≻ cabal get propellor
Unpacking to propellor-5.7.0/
≻ cd propellor-5.7.0/
≻ cabal build --enable-documentation
Resolving dependencies...
Build profile: -w ghc-8.6.4 -O1
In order, the following will be built (use -v for more details):
Assertion failed
CallStack (from HasCallStack):
  assert, called at ./Distribution/Client/ProjectPlanning.hs:242:5 in main:Distribution.Client.ProjectPlanning
```

This is the problematic assertion:

https://github.com/haskell/cabal/blob/4061bfa2bff42b26c8240d19552dafa2e8252f75/cabal-install/Distribution/Client/ProjectPlanning.hs#L238-L244

### PR DESCRIPTION
**Pull request by mpickering**
Fix assertion failure when combining build-tool-depends and --enable-documentation
    
The `setDocumentation` function was modifying the elaborated package
after the hash was computed. This led to the assertion failing as the
computed hash was different to what was computed in the initial install
plan.
   
 Therefore in order to fix this we either needed to:
    
 . Set elabBuildHaddocks = False at the point where the hash is
   initially computed.
2 Verify that elabBuildHaddocks = True will not lead to unexpected
  results.
    
The latter has been implemented.
    
The elabBuildHaddocks option is only consulted in
`hasValidHaddockTargets`, at which point documentation building the
executable component is disabled because elabHaddockExecutables is
False.
    
In the added test we ensure this by checking that we didn't build
documentation for the executable which is built because of
build-tool-depends.
    
Fixes #6006 #8313

### CODE REVIEW

File: cabal-install/src/Distribution/Client/ProjectPlanning.hs [hunk 1]
```diff
@@ -3444,24 +3444,6 @@ pruneInstallPlanPass1 pkgs
...
-          case c of
-            CD.ComponentLib -> const True
-            CD.ComponentSubLib _ -> elabHaddockInternal
-            CD.ComponentFLib _ -> elabHaddockForeignLibs
-            CD.ComponentExe _ -> elabHaddockExecutables
-            CD.ComponentTest _ -> elabHaddockTestSuites
-            CD.ComponentBench _ -> elabHaddockBenchmarks
-            CD.ComponentSetup -> const False
-    setDocumentation elab = elab
-
```
Comment (Mikolaj) [inline cabal-install/src/Distribution/Client/ProjectPlanning.hs:3464]: Wow, this is surprising. Why is this no longer needed? Or was it spurious from the start?

A changelog file would be very welcome.

BTW, thank you for the `findDependencyInStore` improvement.

**Review by Mikolaj — CHANGES_REQUESTED** [review]

File: cabal-install/src/Distribution/Client/ProjectPlanning.hs (hunk 1 above)
Comment (mpickering) [reply cabal-install/src/Distribution/Client/ProjectPlanning.hs:3464]: I explained in the commit message

> The `elabBuildHaddocks` option is only consulted in `hasValidHaddockTargets`, at which point documentation building the executable component is disabled because `elabHaddockExecutables` is
`False`.

Comment (mpickering) [reply cabal-install/src/Distribution/Client/ProjectPlanning.hs]: I added a changelog entry.

Comment (Mikolaj) [reply cabal-install/src/Distribution/Client/ProjectPlanning.hs]: Apologies, I usually view not per-commit, but bulk. It's clear now.

**Review by Mikolaj — APPROVED** [review]
Thank you!

**Comment by Mikolaj** [comment]
BTW, the CI failure looks like a server filesystem or network issue, so let me rebase to restart it...

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by mpickering** [comment]
I accidentally force pushed to the wrong branch, should be fixed now.

**Comment by Mikolaj** [comment]
Time for the merge label?

**Comment by Mikolaj** [comment]
This got stuck due to changes CI mandatory tests rule. Rebasing...

**Comment by Mikolaj** [comment]
@mergify rebase
