### PR TITLE
Fix parsing AbiTag for development compilers

### LINKED ISSUE #10170: cabal accidentally doesn't include abi hash for development compilers
The current logic says

```
compilerAbiTag :: AbiTag
      compilerAbiTag = maybe NoAbiTag AbiTag (Map.lookup "Project Unit Id" ghcInfoMap >>= stripPrefix (prettyShow compilerId <> "-"))
```

If we look at `ghc --info` for a development build of GHC then we see..

```
("Project Unit Id","ghc-9.11-inplace")
```

but the version is reported as

```
The Glorious Glasgow Haskell Compilation System, version 9.11.20240612
```

So the call to `stripPrefix` will fail and no ABI tag will be used because the `Project Unit Id` is not prefixed by `ghc-9.11.20240612`.

Perhaps a more robust but confusing tactic is to hash the contents of `Project Unit Id` rather than attempting to parse it.

### PR DESCRIPTION
**Pull request by TeofilC**
When using a development compiler the compilerId isn't a prefix of the Project Unit Id. This led to a failure to parse the AbiTag.

We extend the parsing logic to handle these cases by only removing the common prefix and then any leading '-'s.

Resolves #10170

### Manual QA notes

To test this try using cabal-install with a development version of the compiler, and check that the AbiTag is actually parsed. (I did this with traces locally)

---

Include the following checklist in your PR:

* [X] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [X] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
  * [ ] [Is the change significant?](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#is-my-change-significant) If so, remember to add `significance: significant` in the changelog file.
* [X] The documentation has been updated, if necessary.
* [x] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [ ] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

### CODE REVIEW

**Review by geekosaur — APPROVED** [review]
There's a little part of my hindbrain that thinks `stripCommon` should be in a `where` unless it's going to be used somewhere else as well, in which case it should be moved somewhere common.

**Comment by TeofilC** [comment]
I get you. I would be happy to move it somewhere else if you have a suitable location in mind. I agree that it feels like more of a general utility

**Comment by geekosaur** [comment]
I think someone with a better understanding of the source organization will have to weigh in on that; I'm still learning. (To date I just do reviews and work on CI, and am slowly making my way through the source from an operational standpoint (e.g. understanding IPI, LBI, etc.)

File: Cabal/src/Distribution/Simple/GHC.hs [hunk 1]
```diff
@@ -248,8 +247,21 @@ configure verbosity hcPath hcPkgPath conf0 = do
...
       compilerAbiTag :: AbiTag
-      compilerAbiTag = maybe NoAbiTag AbiTag (Map.lookup "Project Unit Id" ghcInfoMap >>= stripPrefix (prettyShow compilerId <> "-"))
+      compilerAbiTag = maybe NoAbiTag AbiTag (dropWhile (== '-') . stripCommon (prettyShow compilerId) <$> Map.lookup "Project Unit Id" ghcInfoMap)
+
+      -- @stripCommon xs ys@ gives you @ys@ without the common prefix with @xs@.
+      stripCommon :: String -> String -> String
+      stripCommon (x : xs) (y : ys)
+        | x == y = stripCommon xs ys
+        | otherwise = y : ys
+      stripCommon _ ys = ys
```
Comment (mpickering) [inline Cabal/src/Distribution/Simple/GHC.hs]: `Cabal-syntax/src/Distribution/Utils/Generic.hs` is one possible place or `Distribution.Simple.Utils`.

File: Cabal/src/Distribution/Simple/GHC.hs [hunk 2]
```diff
@@ -248,8 +247,21 @@ configure verbosity hcPath hcPkgPath conf0 = do
       compilerId :: CompilerId
       compilerId = CompilerId GHC ghcVersion
 
+      -- The @AbiTag@ is the @Project Unit Id@ but with redundant information from the compiler version removed.
```
Comment (mpickering) [inline Cabal/src/Distribution/Simple/GHC.hs:250]: With this logic the ABITag should not be used by `Cabal` to reconstitute the unit-id, since the unit-id is not always the package version + the hash.

File: Cabal/src/Distribution/Simple/GHC.hs (hunk 1 above)
Comment (TeofilC) [reply Cabal/src/Distribution/Simple/GHC.hs]: Cool I've moved it to `Distribution.Simple.Utils`

File: Cabal/src/Distribution/Simple/GHC.hs (hunk 2 above)
Comment (TeofilC) [reply Cabal/src/Distribution/Simple/GHC.hs:250]: On https://github.com/haskell/cabal/tree/wip/teo-precise-unit-id I'm getting this from "Project Unit Id"

**Comment by mpickering** [comment]
In general, the unit-id of the `ghc` unit may have no relation to the version of the the `ghc` compiler itself. 

A unit-id can be anything but is prefixed by pkg/version by convention, on darwin systems the package names do not contain vowels for example.

That's something to keep in mind for future, but at least this is an improvement for now.
