### PR TITLE
Have projects import trimmed URIs

### LINKED ISSUE #10622: Cabal treats url with trailing whitespace in import `cabal.project` file as a file path
**Describe the bug**

Cabal treats url with trailing whitespace in import `cabal.project` file as a file path

**To Reproduce**

When following along with: [the users guide](https://cabal.readthedocs.io/en/stable/nix-local-build.html#how-can-i-have-a-reproducible-set-of-versions-for-my-dependencies)

1. Add the following to the cabal.project file:

```
packages: .
import: https://www.stackage.org/nightly-2024-12-05/cabal.config 
```

Note: there is a trailing space at the end of the url

2.
```
$ cabal build .
```
=> An error similar to the following is emitted:

```
/home/john-walker/repos/pyrethrum/https:/www.stackage.org/nightly-2024-12-05/cabal.config : withBinaryFile: does not exist (No such file or directory)
```
3. delete the trailing white space.
4. try build again
```
$ cabal build .
```
=> build proceeds as expected

**Expected behavior**

The current behaviour is confusing if you don't notice the white space. A better UX would be to:
1. automatically trim the url OR
2. emit a specific error pertaining to the trailing space

**System information**
 - Operating system: Ubuntu 24.04.1 LTS
 - cabal: cabal 3.12.1.0 
 - ghc:  GHC   9.8.4

### PR DESCRIPTION
**Pull request by philderbeast**
Fixes #10622. Trims URIs before parsing them with `parseURI`. If any project config path doesn't equal its trimmed self then it is displayed quoted so that the whitespace is obvious.

---

**Template Α: This PR modifies [behaviour or interface](https://github.com/cabalism/cabal/blob/master/CONTRIBUTING.md#changelog)**

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
  * [ ] [Is the change significant?](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#is-my-change-significant) If so, remember to add `significance: significant` in the changelog file.
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [x] Tests have been added. Yes doctests and `cabal-testsuite` tests.

### CODE REVIEW

File: cabal-install-solver/src/Distribution/Solver/Types/ProjectConfigPath.hs [hunk 1]
```diff
@@ -60,9 +62,13 @@ instance Structured ProjectConfigPath
...
-docProjectConfigPath (ProjectConfigPath (p :| [])) = text p
-docProjectConfigPath (ProjectConfigPath (p :| ps)) = vcat $
-    text p : [ text " " <+> text "imported by:" <+> text l | l <- ps ]
+docProjectConfigPath (ProjectConfigPath (p :| [])) = quoteUntrimmed p
+docProjectConfigPath (ProjectConfigPath (p :| ps)) = vcat $ quoteUntrimmed p :
+    [ text " " <+> text "imported by:" <+> quoteUntrimmed l | l <- ps ]
+
+-- | If the path has leading or trailing spaces then show it quoted.
+quoteUntrimmed :: FilePath -> Doc
+quoteUntrimmed s = if trim s /= s then quotes (text s) else text s
```
Comment (ulysses4ever) [inline cabal-install-solver/src/Distribution/Solver/Types/ProjectConfigPath.hs:71]: I dount the idea to make spaces explicit with quoting and, at the same time, trim those spaces. My understanding of the need for trimming is that spaces should not be there in the first place. So, my proposal would be to issue a warning instead if we notice `trim s /= s`.

**Comment by ulysses4ever** [comment]
Will need a changelog but otherwise it looks like the right direction overall.

File: cabal-install-solver/src/Distribution/Solver/Types/ProjectConfigPath.hs (hunk 1 above)
Comment (philderbeast) [reply cabal-install-solver/src/Distribution/Solver/Types/ProjectConfigPath.hs:73]: I'm now issuing an error for this case.

Comment (ulysses4ever) [reply cabal-install-solver/src/Distribution/Solver/Types/ProjectConfigPath.hs:73]: Mm, I feel like error is too harsh. I wonder what others think.

Comment (philderbeast) [reply cabal-install-solver/src/Distribution/Solver/Types/ProjectConfigPath.hs:73]: I've softened the error down to a warning.

**Review by geekosaur — APPROVED** [review]

**Comment by geekosaur** [comment]
Huh. First time I've seen RTD fail that way.

**Comment by geekosaur** [comment]
That's normal, since RTD isn't actually part of GitHub Actions. You'll need to change something somewhere to trigger a new build, though. (You may want to hold off a bit though, to let RTD fix whatever's wrong on their end.)

**Comment by philderbeast** [comment]
@geekosaur I've included a W3C quote about URLs in the changelog and added the bug label to this pull request as it fixes a bug.

**Comment by philderbeast** [comment]
@Mikolaj this is a bug fix in need of a second reviewer. Do you think we can get it into the upcoming release?

**Review by geekosaur — APPROVED** [review]

**Comment by geekosaur** [comment]
Uh, what upcoming release?

**Comment by philderbeast** [comment]
@geekosaur I had a hunch there was a release coming up based on bumped version numbers and pull requests being expedited. Is there somewhere where plans for upcoming releases are posted?

**Review by Mikolaj — APPROVED** [review]
LGTM

@Kleidukos is the 3.14.* release manager so up them if/when to include this fix.

**Comment by Kleidukos** [comment]
Why not include it for a cabal 3.14.2.0, but not for 3.14.1.1 :)

**Comment by philderbeast** [comment]
Label merge+no rebase is necessary when the pull request is from an organisation.
