### PR TITLE
standalone tests for `cabal init`

### LINKED ISSUE #7410: `cabal init --tests`  does not create any tests if not using --lib{andexe}
**Describe the bug**

`cabal init --tests`  does not create any tests.

**To Reproduce**

```
% cabal init --tests
Warning: The package list for 'hackage.haskell.org' is 23 days old.
Run 'cabal update' to get the latest list of available packages.

Guessing dependencies...

Generating LICENSE...
Warning: unknown license type, you must put a copy in LICENSE yourself.
Generating CHANGELOG.md...
Generating app/Main.hs...
Generating example.cabal...

Warning: no synopsis given. You should edit the .cabal file and add one.
You may want to edit the .cabal file and add a Description field.
% tree
.
├── app
│   └── Main.hs
├── CHANGELOG.md
└── example.cabal

1 directory, 3 files
```

**Expected behavior**

A directory is created with some tests. The tests are wired into `example.cabal` as appropriate.

**System information**

```
% cabal --version
cabal-install version 3.4.0.0
compiled using version 3.4.0.0 of the Cabal library 
% uname
Linux
```

### PR DESCRIPTION
**Pull request by ptkato**
This PR adds a new functionality to `cabal init`, standalone tests, as discussed in #7410.

Closes #7410.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

### CODE REVIEW

**Comment by ptkato** [comment]
@emilypi here we go, I do believe these changes cover everything in that issue, yes?

Another point to thing about, the `--tests` flag might have become a little too cryptic.

File: cabal-install/src/Distribution/Client/Init/FlagExtractors.hs [hunk 1]
```diff
@@ -135,7 +135,11 @@ getExtraDocFiles = pure
 
 -- | Ask whether the project builds a library or executable.
 getPackageType :: Interactive m => InitFlags -> m PackageType -> m PackageType
-getPackageType flags = fromFlagOrPrompt (packageType flags)
+getPackageType InitFlags
+  { initializeTestSuite = Flag True
+  , packageType         = NoFlag
+  } _ = return TestSuite
+getPackageType flags act = fromFlagOrPrompt (packageType flags) act
```
Comment (emilypi) [inline cabal-install/src/Distribution/Client/Init/FlagExtractors.hs:142]: Nice. that's easy i suppose.

File: cabal-install/src/Distribution/Client/Init/Interactive/Command.hs [hunk 2]
```diff
@@ -137,6 +137,16 @@ createProject v pkgIx srcDb initFlags = do
       return $ ProjectSettings
         (mkOpts comments cabalSpec) pkgDesc (Just libTarget)
         (Just exeTarget) testTarget
+    
+    TestSuite -> do
+      testTarget <- addLibDepToTest pkgName <$>
```
Comment (emilypi) [inline cabal-install/src/Distribution/Client/Init/Interactive/Command.hs:142]: if we have just a test suite, there'll be no lib dependency.

File: cabal-install/src/Distribution/Client/Init/Interactive/Command.hs [hunk 3]
```diff
@@ -229,7 +239,7 @@ genTestTarget
     => InitFlags
     -> InstalledPackageIndex
     -> m (Maybe TestTarget)
-genTestTarget flags pkgs = initializeTestSuitePrompt flags >>= go
+genTestTarget flags pkgs = initializeTestSuitePrompt (flags {initializeTestSuite = NoFlag}) >>= go
```
Comment (emilypi) [inline cabal-install/src/Distribution/Client/Init/Interactive/Command.hs:242]: If i have `--lib --tests`, then this stomps all over the test flag.

File: cabal-install/src/Distribution/Client/Init/Simple.hs [hunk 4]
```diff
@@ -62,6 +62,12 @@ createProject v _pkgIx _srcDb initFlags = do
         return $ ProjectSettings
           (mkOpts False cabalSpec) pkgDesc
           (Just libTarget) (Just exeTarget) testTarget
+      
+      TestSuite -> do
+        testTarget <- addLibDepToTest pkgName <$> genSimpleTestTarget initFlags
```
Comment (emilypi) [inline cabal-install/src/Distribution/Client/Init/Simple.hs:67]: same here - no need for lib dep.

**Review by emilypi — CHANGES_REQUESTED** [review]
Looking good! Some comments, and I think we should golden test this.

File: cabal-install/src/Distribution/Client/Init/Interactive/Command.hs (hunk 3 above)
Comment (ptkato) [reply cabal-install/src/Distribution/Client/Init/Interactive/Command.hs:241]: How so? Can you please elaborate? As I see it, `initializeTestSuite` must be set to `NoFlag` at that point, so it always prompt for testing, like you mentioned in https://github.com/haskell/cabal/issues/7410#issuecomment-849913926, `--tests` corresponds for a test suite package type, and `lib`/`--libandexe` will always ask for testing, hardcoding it to `NoFlag` basically does that. The only problem I see is when one passes only `--tests`, then it would ask when it should go straight through.

Comment (ptkato) [reply cabal-install/src/Distribution/Client/Init/Interactive/Command.hs:241]: I see what you mean now.

Comment (ptkato) [reply cabal-install/src/Distribution/Client/Init/Interactive/Command.hs]: Okay, fixed, turns out I over-complicated things and it was more straightforward than I thought.

File: cabal-install/src/Distribution/Client/Init/Interactive/Command.hs [hunk 5]
```diff
@@ -139,9 +139,10 @@ createProject v pkgIx srcDb initFlags = do
         (Just exeTarget) testTarget
     
     TestSuite -> do
-      testTarget <- genTestTarget initFlags pkgIx
+      let initFlags' = initFlags { initializeTestSuite = Flag True }
```
Comment (ptkato) [inline cabal-install/src/Distribution/Client/Init/Interactive/Command.hs:142]: Just an addendum: this is necessary in `--interactive` because if both package type and test flags are **not** passed, the user will be prompted for a package type, and it now includes `TestSuite` in the list. In short, that means you could have a `TestSuite` target, with `initializeTestSuite` set to `NoFlag`, which would prompt the user if they want a test suite or not, considering that the target is `TestSuite`, that prompt behaviour is undesired.

**Comment by ptkato** [comment]
Hello there @emilypi @fgaz,

I believe this one is ready for some reviewing action.

**Review by emilypi — APPROVED** [review]

File: cabal-install/src/Distribution/Client/Init/Interactive/Command.hs (hunk 5 above)
Comment (Mikolaj) [reply cabal-install/src/Distribution/Client/Init/Interactive/Command.hs:142]: That would make a great comment IMHO.

File: cabal-install/tests/UnitTests/Distribution/Client/Init/NonInteractive.hs [hunk 6]
```diff
@@ -323,7 +320,7 @@ driverFunctionTest pkgIx srcDb comp = testGroup "createProject"
               , "[\"test/Main.hs\", \"test/Foo.hs\", \"test/bar.y\"]"
               ]
 
-        case (_runPrompt $ createProject comp silent pkgIx srcDb (emptyFlags {initializeTestSuite = Flag True})) inputs of
+        case (_runPrompt $ createProject comp silent pkgIx srcDb (emptyFlags {initializeTestSuite = Flag True, packageType = Flag LibraryAndExecutable })) inputs of
```
Comment (Mikolaj) [inline cabal-install/tests/UnitTests/Distribution/Client/Init/NonInteractive.hs:323]: This is a woefully long line, it doesn't even fit in github display.

File: cabal-install/tests/UnitTests/Distribution/Client/Init/NonInteractive.hs [hunk 7]
```diff
@@ -462,7 +456,7 @@ driverFunctionTest pkgIx srcDb comp = testGroup "createProject"
               , "[\"test/Main.hs\", \"test/Foo.hs\", \"test/bar.y\"]"
               ]
 
-        case (_runPrompt $ createProject comp silent pkgIx srcDb (emptyFlags {initializeTestSuite = Flag True})) inputs of
+        case (_runPrompt $ createProject comp silent pkgIx srcDb (emptyFlags {initializeTestSuite = Flag True, packageType = Flag Library})) inputs of
```
Comment (Mikolaj) [inline cabal-install/tests/UnitTests/Distribution/Client/Init/NonInteractive.hs:459]: Long line.

File: cabal-install/tests/UnitTests/Distribution/Client/Init/NonInteractive.hs (hunk 6 above)
Comment (Mikolaj) [reply cabal-install/tests/UnitTests/Distribution/Client/Init/NonInteractive.hs:323]: If indentation/minimal diff is the problem, I'd got with 1 character indentation to keep the diff small, but break the line.

Comment (Mikolaj) [reply cabal-install/tests/UnitTests/Distribution/Client/Init/NonInteractive.hs:323]: But that's probably not the problem. Perhaps a `let` or `where` with the big argument would help?

**Review by Mikolaj — APPROVED** [review]
Looks very solid from the surface.

File: cabal-install/src/Distribution/Client/Init/Interactive/Command.hs (hunk 5 above)
Comment (ptkato) [reply cabal-install/src/Distribution/Client/Init/Interactive/Command.hs:142]: I actually just thought of that, I shall make it so.
