### PR TITLE
Make sure that cabal-install honours --with-ghc-pkg option

### LINKED ISSUE #11373: Cabal 3.16.0.0 chooses discovered ghc-pkg binary over user-provided binary, leading to version mismatch when doing WASM builds with GHCup-managed GHC
**Describe the bug**
`cabal build` doesn't respect user-provided `ghc-pkg` path (in some circumstances), causing version mismatch between compiler and compiler-package commands. This occurs which using GHCup-managed WASM GHC toolchain

```
Cloning into '/root/cabal-wasm-bug/dist-newstyle/src/miso-7fdae9da4bdb552ef2daf21700284a28ca9d60f6abf96b737c89243d4bad27dc'...
remote: Enumerating objects: 194, done.
remote: Counting objects: 100% (194/194), done.
remote: Compressing objects: 100% (164/164), done.
remote: Total 194 (delta 26), reused 93 (delta 6), pack-reused 0 (from 0)
Receiving objects: 100% (194/194), 266.10 KiB | 5.91 MiB/s, done.
Resolving deltas: 100% (26/26), done.
From https://github.com/dmjio/miso
 * branch            2e8dd81f9731229f83cac6137843ec3a9d498b86 -> FETCH_HEAD
HEAD is now at 2e8dd81 Reset `components` global state on hydration failure. (#1299)
Error: [Cabal-4000]
Version mismatch between ghc and ghc-pkg: /root/.ghcup/bin/wasm32-wasi-ghc is version 9.12.2.20250327 /root/.ghcup/bin/ghc-pkg is version 9.6.7
```

**To Reproduce**
Follow the steps in https://github.com/andremarianiello/cabal-wasm-bug to reproduce the bug.

**Expected behavior**
I expect the project to build successfully using wasm GHC and cabal 3.16.0.0, just like with 3.14.2.0

**System information**
 - Operating system
 Linux - CentOS stream 9
 - `cabal`, `ghc` versions
 Cabal
```sh
# cabal --version
cabal-install version 3.16.0.0
compiled using version 3.16.0.0 of the Cabal library (in-tree)
```

For ghc I am using WASM ghc 9.12.2. See README for details

**Additional context**
It seems like in 3.16.0.0 that cabal is choosing the `ghc-pkg` binary over the user-specified `wasm32-wasi-ghc-pkg` binary, so the build is failing. But this appears to have worked in 3.14.2.0.

### PR DESCRIPTION
**Pull request by mpickering**
The cause of this bug was when ProgramDb is serialised (by caching), the `UnconfiguredPrograms` are discarded. `cabal-install` resolves this by adding back the relevant `UnconfiguredPrograms` in `compilerProgramDb`.

The cause of the bug was the order programs were added back. I have clarified the logic of the function now to:

1. Add back all unconfigured programs, and handle an explicit ghc-pkg path.
2. Then configure ghc-pkg and check it's the right version.

This makes sure that the user-supplied path is honoured in both situations.

Fixes #11373

Please read [Github PR Conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions) and then fill in *one* of these two templates.

---

**Template Α: This PR modifies [behaviour or interface](https://github.com/cabalism/cabal/blob/master/CONTRIBUTING.md#changelog)**

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
  * [ ] [Is the change significant?](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#is-my-change-significant) If so, remember to add `significance: significant` in the changelog file.
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [x] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

---

**Template B: This PR does not modify behaviour or interface**

*E.g. the PR only touches documentation or tests, does refactorings, etc.*

Include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).

### CODE REVIEW

File: changelog.d/with-ghc-pkg.md [hunk 1]
```diff
@@ -0,0 +1,9 @@
+---
+synopsis: Honour `--with-hc-pkg` when supplied by the user
```
Comment (ffaf1) [inline changelog.d/with-ghc-pkg.md]:
```suggestion
synopsis: Honour `--with-ghc-pkg` when supplied by the user
```

File: changelog.d/with-ghc-pkg.md [hunk 2]
```diff
@@ -0,0 +1,9 @@
...
+packages: [cabal-install]
+prs: [11450]
+issues: [11373]
+---
+
+`cabal-install` now properly honours when a user supplies `--with-hc-pkg`.
```
Comment (ffaf1) [inline changelog.d/with-ghc-pkg.md]:
```suggestion
`cabal-install` now properly honours when a user supplies `--with-ghc-pkg`.
```

File: changelog.d/with-ghc-pkg.md (hunk 1 above)
Comment (hasufell) [reply changelog.d/with-ghc-pkg.md]: @ffaf1 only `--with-hc-pkg` is documented: https://cabal.readthedocs.io/en/stable/cabal-project-description-file.html#cfg-flag---with-hc-pkg

File: changelog.d/with-ghc-pkg.md (hunk 2 above)
Comment (geekosaur) [reply changelog.d/with-ghc-pkg.md]: Doesn't this violate cabal's feeble attempts to pretend it supports multiple Haskell compilers?

File: cabal-testsuite/PackageTests/WithGhcPkg/with-ghc-pkg.cabal [hunk 3]
```diff
@@ -0,0 +1,10 @@
+cabal-version:      3.0
+name:               with-ghc-pkg
+version:            0.1.0.0
+build-type:         Simple
+
+executable with-ghc-pkg
+  main-is:          Main.hs
+  hs-source-dirs:   app
+  build-depends:    base >=4.14 && <5
```
Comment (sheaf) [inline cabal-testsuite/PackageTests/WithGhcPkg/with-ghc-pkg.cabal]:
```suggestion
  build-depends:    base >=4.13 && <5
```

File: Cabal/src/Distribution/Simple/GHC.hs [hunk 4]
```diff
@@ -318,20 +299,45 @@ compilerProgramDb verbosity comp progdb1 hcPkgPath = do
...
+          { programFindLocation = guessGhcPkgFromGhcPath ghcProg
+          }
+      progdb2 =
+        userMaybeSpecifyPath "ghc-pkg" hcPkgPath $
+          addKnownProgram haddockProgram' $
+            addKnownProgram hsc2hsProgram' $
+              addKnownProgram hpcProgram' $
+                addKnownProgram runghcProgram' $
+                  addKnownProgram ghcPkgProgram' $
+                    progdb1
```
Comment (philderbeast) [inline Cabal/src/Distribution/Simple/GHC.hs:315]: The `Cabal/src/Distribution/Simple/GHCJS.h` module has very similar code. Does this need updating too?

https://github.com/haskell/cabal/blob/321ce3aaa4749e213970153b5be9804df6a9d5b1/Cabal/src/Distribution/Simple/GHCJS.hs#L188-L247

Comment (mpickering) [reply Cabal/src/Distribution/Simple/GHC.hs:315]: @philderbeast Do you think it's worth it to update this codepath? The GHCJS codepath is untested and unmaintained, I think the last GHCJS release was corresponding to 8.10 and the modern way is to use the javascript backend. I couldn't be confident that anyway I did change it was correct.

File: cabal-testsuite/PackageTests/WithGhcPkg/with-ghc-pkg.cabal (hunk 3 above)
Comment (mpickering) [reply cabal-testsuite/PackageTests/WithGhcPkg/with-ghc-pkg.cabal]: That fixed CI, thanks Sam.

**Comment by mpickering** [comment]
Would I be able to merge this important bugfix whilst the discussion on #11609 continues?

File: Cabal/src/Distribution/Simple/GHC.hs (hunk 4 above)
Comment (philderbeast) [reply Cabal/src/Distribution/Simple/GHC.hs:315]: Even having used GHCJS a fair bit a while back, I can't say without more research and asking around so opened #11609. Keeping this pull request focused on GHC itself is all good by me.

**Comment by mpickering** [comment]
I require one more approval to merge, if anyone fancies helping out?

File: Cabal/src/Distribution/Simple/GHC.hs [hunk 5]
```diff
@@ -318,20 +299,45 @@ compilerProgramDb verbosity comp progdb1 hcPkgPath = do
...
-        addKnownProgram haddockProgram' $
-          addKnownProgram hsc2hsProgram' $
-            addKnownProgram hpcProgram' $
-              addKnownProgram runghcProgram' progdb2
+      ghcPkgProgram' =
+        ghcPkgProgram
+          { programFindLocation = guessGhcPkgFromGhcPath ghcProg
+          }
+      progdb2 =
+        userMaybeSpecifyPath "ghc-pkg" hcPkgPath $
```
Comment (sheaf) [inline Cabal/src/Distribution/Simple/GHC.hs:308]: Can you leave a comment here pointing back to the ticket and a short explanation of the fix/the order in which things need to be done?

**Review by ulysses4ever — APPROVED** [review]
Superficially, this looks good to me. 

I'd appreciate it if @sheaf's comment(s) (current and, hopefully, future ones) were addressed before merging.

File: Cabal/src/Distribution/Simple/GHC.hs (hunk 5 above)
Comment (mpickering) [reply Cabal/src/Distribution/Simple/GHC.hs:308]: Done.
