### PR TITLE
Simplify -Werror warning

### LINKED ISSUE #8257: Cabal check incorrectly assumes package has -Wall -Werror
**Describe the bug**

In some cases (I believe when `ghc-options: -Werror` is given), `cabal check` reports a warning about `'ghc-options: -Wall -Werror'`, although `-Wall` is not set. This makes it, for example, impossible to upload such a package to hackage (see https://github.com/haskell/hackage-server/issues/1088).

**To Reproduce**

```
$ mkdir tmp
$ cd tmp
$ cabal init
$ echo "    ghc-options: -W -Werror" >> tmp.cabal
$ cabal check
Warning: These warnings may cause trouble when distributing the package:
Warning: No 'category' field.
Warning: The following errors will cause portability problems on other
environments:
Warning: No 'synopsis' or 'description' field.
Warning: The 'license' field is missing or is NONE.
Warning: 'ghc-options: -Wall -Werror' makes the package very easy to break
with future GHC versions because new GHC versions often add new warnings. Use
just 'ghc-options: -Wall' instead. Alternatively, if you want to use this,
make it conditional based on a Cabal configuration flag (with 'manual: True'
and 'default: False') and enable that flag during development.
Warning: Hackage would reject this package.
```

Let us disregard the warnings about the missing fields, those are fine. I'm worried about `Warning: 'ghc-options: -Wall -Werror' makes the package very easy to break [...]`.

**Expected behavior**

Either no warning, or a correct warning message (e.g. warning about `-Werror` together with any enabled warning flag). I think it's fairer to have no warning here. `-W -Werror` is less likely to break in future GHC versions than `-Wall -Werror`, and should be allowed. (Maybe even good practice.)

**System information**
 - Operating system: NixOS unstable
```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.0.2

$ cabal --version
cabal-install version 3.6.2.0
compiled using version 3.6.3.0 of the Cabal library 
```

### PR DESCRIPTION
**Pull request by ffaf1**
-W -Wall is too (correctly) refused by Hackage.

Closes #8257.

---
Please include the following checklist in your PR:

* [X] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [X] Minor: not changelog worthy.
* [X] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Review by gbaz — APPROVED** [review]

File: Cabal/src/Distribution/PackageDescription/Check.hs [hunk 1]
```diff
@@ -1576,10 +1576,10 @@ checkDevelopmentOnlyFlagsOptions fieldName ghcOptions =
...
     check has_WerrorWall $
       PackageDistInexcusable $
-           "'" ++ fieldName ++ ": -Wall -Werror' makes the package very easy to "
-        ++ "break with future GHC versions because new GHC versions often "
-        ++ "add new warnings. Use just '" ++ fieldName ++ ": -Wall' instead."
-        ++ extraExplanation
+           "'" ++ fieldName ++ ": -Werror with -W or -Wall makes the package "
+        ++ "very easy to break with future GHC versions because new GHC "
+        ++ "versions often add new warnings. Use just '" ++ fieldName
+        ++ ": -Wall' instead." ++ extraExplanation
```
Comment (andreasabel) [inline Cabal/src/Distribution/PackageDescription/Check.hs:1582]: +1
Minor comment: this diff is larger than need be.  Only the first line changed, the other lines were rewrapped.  I'd prefer a half-full line over extra diff caused by wrapping.

Larger comment: Should the text "Use just ... -Wall instead" also be fixed?  I suggest to delete it simply.  The message to the user is not to use `-Werror`, what else the user chooses, is their own business.

Comment (ffaf1) [reply Cabal/src/Distribution/PackageDescription/Check.hs]: good suggestion, will fixup the commit

**Comment by turion** [comment]
Another possibility might be joining the warning messages for `-Werror` and `-Werror -W`/`-Werror -Wall` into a single one, triggering only on `-Werror`.

**Review by andreasabel — APPROVED** [review]
Excellent!
