### PR TITLE
cabal init -n: avoid extra blank lines

### LINKED ISSUE #8236: cabal init -n sometimes puts two newlines instead of one in .cabal file
**Describe the bug**

cabal init terminates the .cabal file with two newlines instead of one

**To Reproduce**

```
$ cabal init -n
[...]
$ tail *.cabal

    -- Other library packages from which modules are imported.
    build-depends:    base ^>=4.16.1.0

    -- Directories containing source files.
    hs-source-dirs:   app

    -- Base language which the package is written in.
    default-language: Haskell2010

```

**Expected behavior**

Files should be terminated with a single newline character

**System information**
 - cabal HEAD (a715d0473b0bca458a625ab308cef2f65d854799)

cc @ptkato @emilypi

### PR DESCRIPTION
**Pull request by ulysses4ever**
fix #8236

`cabal init -n`'s strategy is to create a list of field descriptions (the `PrettyField` type), which then gets transformed into a list of `Block`s, which, finally, goes into a list of strings and those strings go right into the generated `.cabal` file.

Some fields may be deemed unnecessary depending on the `init`'s flags (e.g. by default there's an `executable` field but no `library` field). Those fields are represented by the `PrettyEmpty` constructor of `PrettyField`. On the next stage, `PrettyEmpty` goes into a block with empty contents and no "margins" (cf. the `Margin` datatype). In theory, such empty blocks should turn into nothing in the output file. Unfortunately, the algorithm turning blocks into lines, `flattenBlocks`, is a bit tricky and does show sensitivity to empty blocks, producing spurious empty lines.

The simplest solution to this issue that I could think of is filtering out empty blocks before converting blocks to lines. This PR implements the idea.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by ulysses4ever** [comment]
Hmm, funny: the failure doesn't reproduce locally...

**Comment by Mikolaj** [comment]
May be a filesystem issue? Let's re-run.

**Comment by ulysses4ever** [comment]
@emilypi @ptkato this PR seems to fix extra new lines in `.cabal` files generated by `cabal init -n`. Could you take a quick look and say if it makes sense to you? There are probably other ways to fight it (e.g. not generate empty blacks in the first place) but post-filtering looked like a more straightforward approach.

File: cabal-install/src/Distribution/Client/Init/FileCreators.hs [hunk 1]
```diff
@@ -80,8 +80,6 @@ writeProject (ProjectSettings opts pkgDesc libTarget exeTarget testTarget)
         when (existingCabal /= cabalContents) $
           message opts T.Warning "A .cabal file was found and not updated, if updating is desired please use the '--overwrite' option."
 
-      -- clear out last line for presentation.
-      T.putStrLn ""
```
Comment (emilypi) [inline cabal-install/src/Distribution/Client/Init/FileCreators.hs:84]: why? This is purely for logging in terminal output. It has nothing to do with formatting files.

**Review by emilypi — CHANGES_REQUESTED** [review]
One spurious change, the rest is sufficient. Nice job!

File: cabal-install/src/Distribution/Client/Init/FileCreators.hs (hunk 1 above)
Comment (ulysses4ever) [reply cabal-install/src/Distribution/Client/Init/FileCreators.hs:84]: It is true that it's irrelevant to the contents of `.cabal` file. But it produces an extra empty line on the terminal (so you get two trailing empty lines), and this look completely unnecessary. So, I took liberty to remove it. In theory, this could go into a separate PR, but it feels like too much for such a simple change. Maybe a reasonable middle ground would be to put it into a separate commit, if you think it is worth it. If you firmly believe that a second trailing empty line should stay, I'm fine with reverting this change.

This is also not how all other commands behave and not how `init` used to behave: they all put one empty line, not two, in the end. E.g. `cabal-install` 3.6.2:

```
tmp/cabal-test-init/A via ❄️  impure (shell) 
❯ cabal init -n -m

Guessing dependencies...

Generating LICENSE...
Warning: unknown license type, you must put a copy in LICENSE yourself.
Generating CHANGELOG.md...
Generating app/Main.hs...
Generating A.cabal...

Warning: no synopsis given. You should edit the .cabal file and add one.
You may want to edit the .cabal file and add a Description field.

tmp/cabal-test-init/A via λ 9.0.2 via ❄️  impure (shell) 
❯ cabal build
Resolving dependencies...
Build profile: -w ghc-9.0.2 -O1
In order, the following will be built (use -v for more details):
 - A-0.1.0.0 (exe:A) (first run)
Configuring executable 'A' for A-0.1.0.0..
Preprocessing executable 'A' for A-0.1.0.0..
Building executable 'A' for A-0.1.0.0..
[1 of 1] Compiling Main             ( app/Main.hs, /home/artem/tmp/cabal-test-init/A/dist-newstyle/build/x86_64-linux/ghc-9.0.2/A-0.1.0.0/x/A/build/A/A-tmp/Main.o )
Linking /home/artem/tmp/cabal-test-init/A/dist-newstyle/build/x86_64-linux/ghc-9.0.2/A-0.1.0.0/x/A/build/A/A ...

tmp/cabal-test-init/A via λ 9.0.2 via ❄️  impure (shell) took 3s 
❯ 
```

For comparison, the current `init` with two trailing empty lines:
```
tmp/cabal-test-init/A via ❄️  impure (shell) 
❯ ~/bin/cabal-head init -n -m
Warning: this is a debug build with assertions enabled.
[Log] Guessing dependencies...
[Log] Using cabal specification: 3.6
[Warning] unknown license type, you must put a copy in LICENSE yourself.
[Log] Creating fresh file CHANGELOG.md...
[Log] Creating fresh directory ./app...
[Log] Creating fresh file app/Main.hs...
[Log] Creating fresh file A.cabal...
[Warning] No synopsis given. You should edit the .cabal file and add one.
[Info] You may want to edit the .cabal file and add a Description field.


tmp/cabal-test-init/A via λ 9.0.2 via ❄️  impure (shell) took 2s 
❯
```

**Comment by ulysses4ever** [comment]
I updated the description, which now should be more helpful to potential reviewers.

File: cabal-install/src/Distribution/Client/Init/FileCreators.hs (hunk 1 above)
Comment (emilypi) [reply cabal-install/src/Distribution/Client/Init/FileCreators.hs:84]: But where is that second space coming from? It seems to be a function of your terminal 

```

tmp/cabal-test-init/A via λ 9.0.2 via ❄️  impure (shell) 
```

Is not trailing output in mine: 

```
[1 of 1] Compiling Main             ( main/Main.hs, /Users/emilypillmore/haskell/cabal/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cabal-install-3.9.0.0/x/cabal/build/cabal/cabal-tmp/Main.o )
Linking /Users/emilypillmore/haskell/cabal/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cabal-install-3.9.0.0/x/cabal/build/cabal/cabal ...
Warning: this is a debug build with assertions enabled.
[Log] Guessing dependencies...
[Log] Using cabal specification: 3.6
[Warning] unknown license type, you must put a copy in LICENSE yourself.
[Log] Creating fresh file CHANGELOG.md...
[Log] Creating fresh directory ./app...
[Log] Creating fresh file app/Main.hs...
[Log] Creating fresh file tmp.cabal...
[Warning] No synopsis given. You should edit the .cabal file and add one.
[Info] You may want to edit the .cabal file and add a Description field.
λ П tmp → λ git t8236* → 
```

Comment (emilypi) [reply cabal-install/src/Distribution/Client/Init/FileCreators.hs:84]: So it seems to me that you're using a nonstandard terminal here that appends data in the form of a newline and a message about what shell you're using. I'd say that's not something I'd care to support.

Comment (ulysses4ever) [reply cabal-install/src/Distribution/Client/Init/FileCreators.hs:84]: On your end, do you see that the current init leaves more trailing vertical space than init from any past release and also more than build or any other command? If yes, than why would we want having inconsistency between commands?

Comment (ulysses4ever) [reply cabal-install/src/Distribution/Client/Init/FileCreators.hs:84]: (By current I mean `master`).

Comment (emilypi) [reply cabal-install/src/Distribution/Client/Init/FileCreators.hs:84]: cabal build: 

```
λ П tmp → λ git t8236* → cabal build
cabal: No targets given and there is no package in the current directory. Use
the target 'all' for all packages in the project or specify packages or
components by name or location. See 'cabal build --help' for more details on
target options.

λ П tmp → λ git t8236* → 
```

cabal init -n -m :

```
[1 of 1] Compiling Main             ( main/Main.hs, /Users/emilypillmore/haskell/cabal/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cabal-install-3.9.0.0/x/cabal/noopt/build/cabal/cabal-tmp/Main.o )
Linking /Users/emilypillmore/haskell/cabal/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cabal-install-3.9.0.0/x/cabal/noopt/build/cabal/cabal ...
Warning: this is a debug build of cabal-install with assertions enabled.
[Log] Guessing dependencies...
[Log] Using cabal specification: 3.6
[Warning] unknown license type, you must put a copy in LICENSE yourself.
[Log] Creating fresh file CHANGELOG.md...
[Log] Creating fresh directory ./app...
[Log] Creating fresh file app/Main.hs...
[Log] Creating fresh file tmp.cabal...
[Warning] No synopsis given. You should edit the .cabal file and add one.
[Info] You may want to edit the .cabal file and add a Description field.

λ П tmp → λ git master* → 
```

Comment (emilypi) [reply cabal-install/src/Distribution/Client/Init/FileCreators.hs:84]: It seems to me that the single-line space clearing done _after_ the command output is finished in terminal is currently standard in master. Its removal introduces inconsistency.

Comment (ulysses4ever) [reply cabal-install/src/Distribution/Client/Init/FileCreators.hs]: Fair, thank you for experimenting. I just reverted this change.

**Review by emilypi — APPROVED** [review]

**Comment by ulysses4ever** [comment]
@Mergify backport 3.8
