### PR TITLE
Fix --program-suffix resulting in invalid symlink

### LINKED ISSUE #8823: `cabal install EXE --program-suffix=SUF` fails in copy step
Trying to install an executable (in this case, `cabal` itself) with `cabal` built from `master`:
```shell-session
$ cabal install cabal-install --program-suffix=-new-check
...
Building executable 'cabal' for cabal-install-3.9.0.0..
[1 of 1] Compiling Main             ( main/Main.hs, dist/build/cabal/cabal-tmp/Main.o )
[2 of 2] Linking dist/build/cabal/cabal
Installing executable cabal in /Users/abel/.cabal/store/ghc-9.4.4/incoming/new-90296/Users/abel/.cabal/store/ghc-9.4.4/cbl-nstll-3.9.0.0-b132ff27/bin
Warning: The directory
/Users/abel/.cabal/store/ghc-9.4.4/incoming/new-90296/Users/abel/.cabal/store/ghc-9.4.4/cbl-nstll-3.9.0.0-b132ff27/bin
is not in the system search path.
Copying 'cabal' to '/Users/abel/.cabal/bin/cabal-new-check'
/Users/abel/.cabal/store/ghc-9.4.4/cbl-nstll-3.9.0.0-b132ff27/bin/cabal: copyFile:atomicCopyFileContents:withReplacementFile:copyFileToHandle:withBinaryFile: does not exist (No such file or directory)
```
I have this in my `.cabal/config`:
```
install-method: copy
overwrite-policy: always
```
I am on macOS, as you can see from the garbled package names.
(I am having a dejavu, haven't I reported this already?)

The problem is that in `~/.cabal/store/ghc-9.4.4/cbl-nstll-3.9.0.0-b132ff27/bin/` there is no executable `cabal`, but there is `cabal-new-check`.

Workaround:  Take matters in your own hand and do the copy step yourself:
```shell-session
$ cp ~/.cabal/store/ghc-9.4.4/cbl-nstll-3.9.0.0-b132ff27/bin/cabal-new-check ~/.cabal/bin/
```

Label `newcomer`: I _suppose_ the bug is a simple oversight and can be easily fixed.  However, there should also be a test case...

### LINKED ISSUE #9919: `cabal install` program-suffix is applied to the binary name in the store
**Describe the bug**

**To Reproduce**
With cabal HEAD (774ff0463f1797cac75c19e08727c076b4cb20d3), try installing any program, in my example `HLS` via:
```sh
$ cabal install exe:haskell-language-server -w ghc-9.6.4 --installdir /home/hugin/bin/ --program-suffix -9.6.4 --with-compiler=ghc-9.6.4 
```

After it finished compiling, the symlink looks good:
```sh
$ ls -al ~/bin/
haskell-language-server-9.6.4 -> ../.cabal/store/ghc-9.6.4/haskell-language-server-2.7.0.0-e-haskell-language-server-6719e6073284fd7edd180b3c8c9ea8c6482ea148b4407d215635b68fe07d055a/bin/haskell-language-server
```

but the path doesn't exist. The binary in the store has the `program-suffix` `-9.6.4` applied.

```sh
$ ls ~/.cabal/store/ghc-9.6.4/haskell-language-server-2.7.0.0-e-haskell-language-server-6719e6073284fd7edd180b3c8c9ea8c6482ea148b4407d215635b68fe07d055a/bin
haskell-language-server-9.6.4*
```

which is incorrect.

**Expected behavior**

This should create an executable `haskell-language-server` in the cabal store and a symlink to `haskell-language-server-9.6.4` in `~/.cabal/bin`.

**System information**
 - `cabal HEAD`, `ghc-9.6.4`
 
**Additional context**

The PR https://github.com/haskell/cabal/pull/6207 introduced the behaviour that `program-suffix` are applied to the symlink or copied binary only.

### PR DESCRIPTION
**Pull request by wismill**
Please read [Github PR Conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions) and then fill in *one* of these two templates.

---

**Template Α: This PR modifies [behaviour or interface](https://github.com/cabalism/cabal/blob/master/CONTRIBUTING.md#changelog)**

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [ ] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

---

Fixes #9919
Fixes #8823

Based on [this comment](https://github.com/haskell/cabal/issues/8823#issuecomment-2079197342).

It took me a lot of time to understand where to look at and I am still unsure this fix does not introduce side effects. I would need some guidance if improvements are needed.

### CODE REVIEW

**Review by geekosaur — APPROVED** [review]

File: cabal-install/src/Distribution/Client/CmdInstall.hs [hunk 1]
```diff
@@ -540,7 +540,9 @@ installAction flags@NixStyleFlags{extraFlags, configFlags, installFlags, project
         -- BuildOutcomes because we also need the component names
           traverseInstall (installCheckUnitExes InstallCheckInstall) installCfg
   where
-    configFlags' = disableTestsBenchsByDefault configFlags
+    -- Filter `configProgSuffix` out, in order to get the canonical executable
+    -- in the store.
+    configFlags' = (disableTestsBenchsByDefault configFlags){configProgSuffix = NoFlag}
```
Comment (fendor) [inline cabal-install/src/Distribution/Client/CmdInstall.hs:545]: Wouldn't this likely also apply to the flag `configProgPrefix`?

**Review by fendor — COMMENTED** [review]
Thanks for tackling this very annoying issue! I am wondering, whether it would be easy to add a regression test that makes sure this doesn't break again, e.g. a `PackageTests/ConfigProgTest` which installs a local executable with `--program-suffix` into the current directory and simply tests, whether the binary can be executed?

File: cabal-install/src/Distribution/Client/CmdInstall.hs (hunk 1 above)
Comment (wismill) [reply cabal-install/src/Distribution/Client/CmdInstall.hs]: Yes. I updated the code to fix it too.

**Comment by wismill** [comment]
I have not seen that somebody pushed some commits before force-pushing… Was it just a rebase?

**Comment by wismill** [comment]
Updated code: fix `--program-prefix` as well, add a test for both affix options and both `--install-methods`. I think it fixes #8823 as well.

Reworked commit message for full explanation:

Currently the options `--program-{prefix,suffix}` for cabal install
affects the name of the file in the install directory *and* the
executable name in the store. The installation fails:

- If using `--install-method=symlink`, the *target* of the symlink is
  not affected by the affix options and it results in an invalid symlink.
- If using `--install-method=copy`, the copy fails because the source
  is not found.

Another issue is that it affects the computation of the hash of the 
build directory in the store, resulting in needless rebuild when using
successively different affix options.

Fixed by making the name of the executable in the store canonical, i.e.
always ignoring the program affix options.

Added a test for all the combinations of `--install-method` and program
affixes options.

**Comment by wismill** [comment]
Rebased

**Review by geekosaur — APPROVED** [review]

File: cabal-install/src/Distribution/Client/CmdInstall.hs [hunk 2]
```diff
@@ -1101,6 +1103,14 @@ disableTestsBenchsByDefault configFlags =
     , configBenchmarks = Flag False <> configBenchmarks configFlags
     }
 
+-- | Disables program prefix and suffix.
```
Comment (fendor) [inline cabal-install/src/Distribution/Client/CmdInstall.hs:1106]: Could we expand on this comment a bit? Like, why are we doing this, potentially linking to the issues, etc...
Otherwise, the reasoning might be lost in the future!

**Review by fendor — APPROVED** [review]
LGTM, thanks! 

I have one documentation nitpick, please explain in `ignoreProgramAffixes` why we are ignoring these prefixes, so that the knowledge isn't lost in the future :)

File: cabal-install/src/Distribution/Client/CmdInstall.hs (hunk 2 above)
Comment (wismill) [reply cabal-install/src/Distribution/Client/CmdInstall.hs]: Yes, I left the explanation at the use site, but since it is used only once let’s move it at the definition site. I expanded the explanation to explain both aspects: package hash & fix for install method.

**Comment by ulysses4ever** [comment]
@mergify backport 3.12
