### PR TITLE
use with compiler flags in key of cached project config

### LINKED ISSUE #8772: Caching issue with conditionals in project files
**Describe the bug**

There seems to be a cache invalidation issue when there are conditionals in `cabal.project` files.
Changing the build configuration (eg ghc version) should invaldate the cache but it appears not to.

**To Reproduce**

Set up a project with 2 packages, one that builds with ghc version A, the other builds with ghc-version B.

Reproducing example here: https://github.com/wz1000/cabal-bug

```
$ tree
.
├── build92
│   ├── build92.cabal
│   ├── LICENSE
│   └── MyLib.hs
├── build94
│   ├── build94.cabal
│   ├── LICENSE
│   └── MyLib.hs
└── cabal.project
$ cat cabal.project
if impl(ghc >= 9.4)
  packages: ./build94/
if impl(ghc < 9.4)
  packages: ./build92/
$ diff -c1 build92/build92.cabal build94/build94.cabal                                                                                                                                                                                         
*** build92/build92.cabal	2023-02-16 17:29:15.377391010 +0530
--- build94/build94.cabal	2023-02-16 17:34:31.424605778 +0530
***************
*** 1,3 ****
  cabal-version:      3.0
! name:               build92
  version:            0.1.0.0
--- 1,3 ----
  cabal-version:      3.0
! name:               build94
  version:            0.1.0.0
***************
*** 17,19 ****
  library
!     if impl(ghc >= 9.4)
        buildable: False
--- 17,19 ----
  library
!     if impl(ghc < 9.4)
        buildable: False

$ cabal build -w ghc-9.2 all
Resolving dependencies...
Build profile: -w ghc-9.2.6 -O1
In order, the following will be built (use -v for more details):
 - build92-0.1.0.0 (lib) (first run)
Warning: build92.cabal:20:5: Unknown field: import. Common stanza imports
should be at the top of the enclosing section
Configuring library for build92-0.1.0.0..
Preprocessing library for build92-0.1.0.0..
Building library for build92-0.1.0.0..
[1 of 1] Compiling MyLib            ( MyLib.hs, /data/builds/cabal-bug/dist-newstyle/build/x86_64-linux/ghc-9.2.6/build92-0.1.0.0/build/MyLib.o, /data/builds/cabal-bug/dist-newstyle/build/x86_64-linux/ghc-9.2.6/build92-0.1.0.0/build/MyLib.dyn_o )

$ cabal build -w ghc-9.4 all
Resolving dependencies...
Error: cabal: Cannot build all the packages in the project because none of the
components are available to build: the library is marked as 'buildable: False'

$ rm -rf dist-newstyle
$ cabal build -w ghc-9.4 all
Resolving dependencies...
Build profile: -w ghc-9.4.4 -O1
In order, the following will be built (use -v for more details):
 - build94-0.1.0.0 (lib) (first run)
Warning: build94.cabal:20:5: Unknown field: import. Common stanza imports
should be at the top of the enclosing section
Configuring library for build94-0.1.0.0..
Preprocessing library for build94-0.1.0.0..
Building library for build94-0.1.0.0..
[1 of 1] Compiling MyLib            ( MyLib.hs, /data/builds/cabal-bug/dist-newstyle/build/x86_64-linux/ghc-9.4.4/build94-0.1.0.0/build/MyLib.o, /data/builds/cabal-bug/dist-newstyle/build/x86_64-linux/ghc-9.4.4/build94-0.1.0.0/build/MyLib.dyn_o )
```

**Expected behavior**

The build `-w ghc 9.4` should succeed without having to delete `dist-newstyle`

**System information**
 - Operating system: Linux
 - `cabal`, `ghc` versions: cabal-install 3.8.1.0

### PR DESCRIPTION
**Pull request by gbaz**
Resolves  #8772, #8699

adds more keys to the cache in rebuildProjectConfig, to ensure it gets rebuilt when the compiler may change.

* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ ] Manual QA (There is a reproducer in both tickets)

### CODE REVIEW

File: cabal-install/src/Distribution/Client/ProjectPlanning.hs [hunk 1]
```diff
@@ -321,9 +321,17 @@ rebuildProjectConfig verbosity
...
+    progsearchpath <- liftIO $ getSystemSearchPath
+
+    let fileMonitorProjectConfig = newFileMonitor (distProjectCacheFile "config")
+
     fileMonitorProjectConfigKey <- do
       configPath <- getConfigFilePath projectConfigConfigFile
-      return (configPath, distProjectFile "")
+      return (configPath, distProjectFile "",
+                        (projectConfigHcFlavor, projectConfigHcPath, projectConfigHcPkg),
+                        progsearchpath,
```
Comment (michaelpj) [inline cabal-install/src/Distribution/Client/ProjectPlanning.hs:332]: Does this mean that if I run `cabal` in a directory with a slightly modified `PATH`, then it's going to be a complete cache miss on everything? Even it doesn't change what `ghc` etc. gets picked? `direnv` users will be sad if so.

Comment (gbaz) [reply cabal-install/src/Distribution/Client/ProjectPlanning.hs:332]: My understanding is this will only be a cache miss on parsing and evaluating the conditionals in a project file, which should be pretty low-cost. But we certainly need to give this a workout to be sure.

**Comment by gbaz** [comment]
@Bodigrim @wz1000 can you test if this resolves the issue for you?

**Review by Kleidukos — APPROVED** [review]

**Comment by gbaz** [comment]
We need an additional approval to merge. A manual test from @Bodigrim or @wz1000 would be a big help in this direction.

**Review by Bodigrim — APPROVED** [review]
Works for me.

**Comment by Mikolaj** [comment]
@mergify backport 3.10
