### PR TITLE
Inidication that a field is optional for cabal init prompts

### LINKED ISSUE #7464: Cabal init: It is unclear which prompts are optional
**Describe the bug**
When using `cabal init --exe` (but I think that generalises to all fields), it is unclear which prompts are actually optional.

**To Reproduce**
Take this example interaction:
```
> cabal init --exe
Please choose version of the Cabal specification to use:
   1) 1.24  (legacy)
   2) 2.0   (+ support for Backpack, internal sub-libs, '^>=' operator)
   3) 2.2   (+ support for 'common', 'elif', redundant commas, SPDX)
   4) 2.4   (+ support for '**' globbing)
 * 5) 3.0   (+ set notation for ==, common stanzas in ifs, more redundant commas, better pkgconfig-depends)
   6) 3.4   (+ support for 'pkg:sublib' syntax, active repo configuration, rich index-state syntax)
Your choice? [default: 3.0] 
Package name? [default: test-dir] 
Package version? [default: 0.1.0.0] 
Please choose a license:
   1) BSD-2-Clause
   2) BSD-3-Clause
   3) Apache-2.0
   4) MIT
   5) MPL-2.0
   6) ISC
   7) GPL-2.0-only
   8) GPL-3.0-only
   9) LGPL-2.1-only
  10) LGPL-3.0-only
  11) AGPL-3.0-only
  12) GPL-2.0-or-later
  13) GPL-3.0-or-later
  14) LGPL-2.1-or-later
  15) LGPL-3.0-or-later
  16) AGPL-3.0-or-later
  17) Other (specify)
Your choice? 
Empty input is not a valid choice.
Your choice? 4
Author name? 
Maintainer email? 
Project homepage URL? 
Project synopsis? 
Project category:
   1) Codec
   2) Concurrency
   3) Control
   4) Data
   5) Database
   6) Development
   7) Distribution
   8) Game
   9) Graphics
  10) Language
  11) Math
  12) Network
  13) Sound
  14) System
  15) Testing
  16) Text
  17) Web
  18) Other (specify)
Your choice? [default: (none)] 
What is the main module of the executable:
 * 1) Main.hs
   2) Main.lhs
   3) Other (specify)
Your choice? [default: Main.hs] 1
Application directory:
 * 1) app
   2) exe
   3) src-exe
   4) Other (specify)
Your choice? [default: app] 1
Choose a language for your executable:
 * 1) Haskell2010
   2) Haskell98
   3) Other (specify)
Your choice? [default: Haskell2010] 
Add informative comments to each field in the cabal file. (y/n)? [default: y] 

Using cabal specification: 3.0


Creating LICENSE...
Creating file LICENSE...
Creating CHANGELOG.md...
Creating file CHANGELOG.md...
Creating directory ./app...
Creating file app/Main.hs...
Creating file test-dir.cabal...

Warning: no synopsis given. You should edit the .cabal file and add one.
You may want to edit the .cabal file and add a Description field.
``` 

I basically hammered "enter" until once it told me, I couldn't. 
I am unable to tell that the fields 
```
Author name? 
Maintainer email? 
Project homepage URL? 
Project synopsis? 
Project category:
```
are basically optional, but it would be nice if it was.

**Expected behavior**
Communicate to the user which prompts are actually optional

**System information**
 - Arch linux
 - `cabal HEAD`.

### PR DESCRIPTION
**Pull request by ptkato**
This PR aims to fix #7464. For any field that is both optional and don't have a default value, an `"[optional]"` "tag" will be appended next to the input location.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

### CODE REVIEW

**Comment by ptkato** [comment]
Heya @emilypi, @Mikolaj, can you please review?

File: cabal-install/src/Distribution/Client/Init/Prompt.hs [hunk 1]
```diff
@@ -143,14 +144,14 @@ promptDefault
       -- ^ pretty-printer
     -> String
       -- ^ prompt message
-    -> Maybe t
+    -> (Either Bool t)
```
Comment (Mikolaj) [inline cabal-install/src/Distribution/Client/Init/Prompt.hs:147]: Given that the type and its constructors appear with this meaning in so many places, would you like to define a custom datatype `InitValueDefault t | InitValueMandatory | InitValueOptional` (but with better names)? Boolean blindness is one thing, but here it's more complex and I quickly forget which constructor means what. By convention `Left` is an error, but this convention doesn't help here and I think there are no other conventions that would help.

**Review by Mikolaj — CHANGES_REQUESTED** [review]

File: cabal-install/src/Distribution/Client/Init/Prompt.hs (hunk 1 above)
Comment (Mikolaj) [reply cabal-install/src/Distribution/Client/Init/Prompt.hs:147]: Actually, should this be `InitValueDefault !t`? I'm so used to `StrictData` (which we don't use in cabal for some reason), that I forgot the trade-offs.

Comment (ptkato) [reply cabal-install/src/Distribution/Client/Init/Prompt.hs]: Here we go, custom datatyped.

Comment (Mikolaj) [reply cabal-install/src/Distribution/Client/Init/Prompt.hs]: Thank you!

File: cabal-install/src/Distribution/Client/Init/Types.hs [hunk 2]
```diff
@@ -422,6 +424,19 @@ type IsLiterate = Bool
 --
 type IsSimple = Bool
 
+-- | Defines whether or not if a prompt will have a default value,
```
Comment (Mikolaj) [inline cabal-install/src/Distribution/Client/Init/Types.hs:427]: spurious `if`

File: cabal-install/src/Distribution/Client/Init/Types.hs [hunk 3]
```diff
@@ -422,6 +424,19 @@ type IsLiterate = Bool
...
+--   is optional, or is mandatory.
+data DefaultPrompt t
+  = DefaultPrompt t
+  | OptionalPrompt
+  | MandatoryPrompt
```
Comment (Mikolaj) [inline cabal-install/src/Distribution/Client/Init/Types.hs:432]: There is a convention that the common part of constructor name is a prefix. However, the suffix here reads very naturally, so perhaps this version is fine. Also, people nowadays use IDEs, so they don't need a prefix to know what the type is.

**Review by Mikolaj — APPROVED** [review]

File: cabal-install/src/Distribution/Client/Init/Types.hs (hunk 2 above)
Comment (ptkato) [reply cabal-install/src/Distribution/Client/Init/Types.hs]: Removed.

File: cabal-install/src/Distribution/Client/Init/Types.hs [hunk 4]
```diff
@@ -422,6 +424,19 @@ type IsLiterate = Bool
...
+  deriving Eq
+
+instance Functor DefaultPrompt where
+  fmap _ OptionalPrompt = OptionalPrompt
+  fmap _ MandatoryPrompt = MandatoryPrompt
+  fmap f (DefaultPrompt g) = DefaultPrompt $ f g
```
Comment (emilypi) [inline cabal-install/src/Distribution/Client/Init/Types.hs:438]: Optional: just derive `Functor`.

**Review by emilypi — APPROVED** [review]
LGTM

File: cabal-install/src/Distribution/Client/Init/Types.hs (hunk 4 above)
Comment (ptkato) [reply cabal-install/src/Distribution/Client/Init/Types.hs]: Done.
