### PR TITLE
Deduplicate path separator duplicates

### LINKED ISSUE #10645: When using configuration from show duplicate paths
**Describe the bug**
The "when using configuration from" message is duplicating paths on Windows but these are the same path, ignoring path separator differences.

**To Reproduce**

```
$ cat else.project 
import: dir-else/else.config

$ cat dir-else/else.config 
if false
else
    _
    packages: no-pkg-here
```

* On Ubuntu

```
$ ~/.ghcup/bin/cabal-3.12.1.0 build all --dry-run --project-file=else.project
...
Warning: /.../else.project,
else.project: Unrecognized section '_' on line 3
When using configuration from:
  - dir-else/else.config
  - else.project
The following errors occurred:
  - The package location 'no-pkg-here' does not exist.
```

* On Windows

```
$ cabal build all --dry-run --project-file=else.project
Warning:
C:\...\else.project,
else.project: Unrecognized section '_' on line 3
When using configuration from:
  - dir-else/else.config
  - dir-else\else.config
  - else.project
The following errors occurred:
  - The package location 'no-pkg-here' does not exist.
```

**Expected behavior**

That there'd only be one entry for each project configuration file.

**System information**
 - Operating system compared are Windows 10 Pro and Ubuntu 24.10
 - cabal version is `3.12.1.0` and also seeing the same problem with 37272267206d5962a4c61ed193ce47813cf18809:

```
$ git rev-parse HEAD
37272267206d5962a4c61ed193ce47813cf18809
```

### PR DESCRIPTION
**Pull request by philderbeast**
Fixes #10645, a small Windows gotcha missed with #10546.

I really had to get into the weeds with this one. The `assertOutputContains` function was modifying the output (a test actual value) before comparision with the unmodified actual value. This change was not visible. I've added an `assertOn` function (that `assertOutputContains` calls) that takes a `NeedleHaystack` configuration for how the search, expectation and display are made. I had wanted to add a pilcrow `¶` for line endings but the terminal output is restricted to ASCII so I've marked line beginnings with `^` and line endings with `$`. The needle (the expected output fragment) is shown annotated this way as can the haystack (the output). The haystack is not shown annotated with line delimiters but can be.

The `concatOutput` function, I've renamed to `lineBreaksToSpaces`. There's more detail on the `cabal-testsuite` changes in the changelog entry. One benefit of using an `.md` extension for `changelog.d/pr-10646.md` is that typos are caught by CI.

---

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
  * [ ] [Is the change significant?](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#is-my-change-significant) If so, remember to add `significance: significant` in the changelog file.
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [x] Tests have been added. Yes, a doctest.

### CODE REVIEW

**Review by geekosaur — APPROVED** [review]
I'm confused: is the .md file a GitHub artifact, or did you really add two `changelog.d` entries?

**Comment by philderbeast** [comment]
> I'm confused: is the .md file a GitHub artifact, or did you really add two `changelog.d` entries?

Thanks for catching that mistake of mine @geekosaur. I let the `.md` slip in. I rename locally to check the markdown preview. I've deleted that extra file now.

Can we use a `.md` extension for `changelog.d` entries?

**Comment by geekosaur** [comment]
`changelog-d` doesn't care; the only special name is `config`, where its own configuration is stored, and you can't use subdirectories.

**Comment by philderbeast** [comment]
Reverting to draft while I settle some Windows versus POSIX file path issues.

File: cabal-testsuite/src/Test/Cabal/NeedleHaystack.hs [hunk 1]
```diff
@@ -0,0 +1,183 @@
...
+symNeedleHaystack bwd fwd = let tx = TxContains bwd fwd in NeedleHaystack True False tx tx
+
+-- | Multiline needle and haystack functions with symmetric conversions. Going
+-- forward converts line breaks to @"\\n"@.  Going backward adds visible
+-- delimiters to lines.
+multilineNeedleHaystack :: NeedleHaystack
+multilineNeedleHaystack = symNeedleHaystack delimitLines encodeLf
+
+-- | Minimal set up for finding the needle in the haystack. Doesn't change the
+-- strings and doesn't displaying the haystack in any assertion failure message.
```
Comment (geekosaur) [inline cabal-testsuite/src/Test/Cabal/NeedleHaystack.hs:69]:
```suggestion
-- strings and doesn't display the haystack in any assertion failure message.
```

File: cabal-testsuite/src/Test/Cabal/NeedleHaystack.hs [hunk 2]
```diff
@@ -0,0 +1,183 @@
...
+--
+-- >>> Data.List.unlines $ lines "abc"
+-- "abc\n"
+--
+-- >>> unlines $ lines "abc"
+-- "abc"
+unlines :: [String] -> String
+unlines = maybe "" fst . unsnoc . Prelude.unlines
+
+-- | @unsnoc@ is only in base >= 4.19 so we copy its definition here rather than
```
Comment (geekosaur) [inline cabal-testsuite/src/Test/Cabal/NeedleHaystack.hs:116]: Maybe this belongs in a `Distribution.Compat` module?

File: cabal-testsuite/src/Test/Cabal/Prelude.hs [hunk 3]
```diff
@@ -1255,3 +1268,32 @@ findDependencyInStore pkgName = do
                       [] -> error $ "Could not find " <> pkgName' <> " when searching for " <> pkgName' <> " in\n" <> show packageDirs
                       (dir:_) -> dir
       pure (storeDir </> storeDirForGhcVersion </> libDir)
+
+-- | It can easier to paste expected output verbatim into a text file,
```
Comment (geekosaur) [inline cabal-testsuite/src/Test/Cabal/Prelude.hs:1272]:
```suggestion
-- | It can be easier to paste expected output verbatim into a text file,
```

File: changelog.d/pr-10646.md [hunk 4]
```diff
@@ -0,0 +1,209 @@
...
+--
+-- >>> lineBreaksToSpaces "foo\nbar\r\nbaz\n"
+-- "foo bar baz"
+--
+-- >>> lineBreaksToSpaces "\nfoo\nbar\r\nbaz\n"
+-- " foo bar baz"
+lineBreaksToSpaces :: String -> String
+```
+
+With this set up, false positives were possible. An expected value using string
```
Comment (geekosaur) [inline changelog.d/pr-10646.md:89]:
```suggestion
With this setup, false positives were possible. An expected value using string
```

**Review by geekosaur — APPROVED** [review]

File: cabal-testsuite/src/Test/Cabal/NeedleHaystack.hs (hunk 2 above)
Comment (philderbeast) [reply cabal-testsuite/src/Test/Cabal/NeedleHaystack.hs:116]: Thanks @geekosaur. I should have looked harder. I found an `unsnoc` in `Cabal-syntax`, so switched to using that one:

https://github.com/haskell/cabal/blob/5ad146cd1aa28c6d34be124ab41352fa1878771f/Cabal-syntax/src/Distribution/Utils/Generic.hs#L531-L533

Like `unsnoc` in base, it uses lazy pattern matching but is implemented using `unsnocNE`.

Comment (geekosaur) [reply cabal-testsuite/src/Test/Cabal/NeedleHaystack.hs]: Actually I'd have the same question there, but maybe that makes it a more intrusive change requiring its own PR.

**Review by Mikolaj — APPROVED** [review]
That was a tricky one, but the tests make it easier for the reviewer to trust the solution without spending hours to get a deep understanding. The PR will be a good test of our tools and the process. I think it would be great to also include this great write-up from the changelog in a Note or maybe in a test linked to by name from the code?

**Comment by philderbeast** [comment]
@Mikolaj I've added a note `[Multiline Needles]` and referenced this from `assertOn` and `assertOutputContains` with pretty much the content from the changelog but converted to haddock format and without the doctest output that can be found elsewhere in `cabal-testsuite/src/Test/Cabal/NeedleHaystack.hs`.

**Comment by philderbeast** [comment]
> That was a tricky one

Yes it was and I'll have to squash those ~70 commits before applying a merge label.

**Comment by philderbeast** [comment]
Label merge+no rebase is necessary when the pull request is from an organisation.

**Comment by Kleidukos** [comment]
@mergifyIO backport 3.14

**Comment by Kleidukos** [comment]
@Mergifyio backport 3.14

**Comment by Kleidukos** [comment]
bloody hell.

**Comment by Kleidukos** [comment]
@Mergifyio backport 3.14

**Comment by Kleidukos** [comment]
curse you, mergify!
