### PR TITLE
Fix default Nix configuration option in generated ~/.cabal/config file

### LINKED ISSUE #8864: Fresh ~/.cabal/config written by cabal 3.10 crashes any older cabal
This was originally reported in https://github.com/haskell/actions/issues/202, partially worked around there, but affects any users and any mixed-GHC CI (either testing many GHCs with the same CI cache or picking a random cabal version for a given GHC).

Judging by the dates of the PRs involved, this seems to affect already cabal 3.8.1.0 (please correct if not).

This was probably caused by the helpful and seemingly benign https://github.com/haskell/cabal/pull/8054, later amended in https://github.com/haskell/cabal/pull/8522, that make Nix flags easier to read. Note that old cabal happily ignore ~/.cabal/config options they don't understand, but choke on old options they recognize, but can't parse in a new way. That seems to be the root cause of the breakage.

I think, without a very good reason, we should not let cabal break the config file for old cabals, so let's think how to fix this. Ideally, without reverting the PRs in question.

@cbclemmer: I'm a bit lost in the history of these changes. Do you perhaps remember why we ended up changing the config option at all? Do you have any suggestions how to eat the cake (improve the command-line options) and have it too (parse the config option using the old parsing code in old cabals)?

### PR DESCRIPTION
**Pull request by cbclemmer**
---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

Should close #8864 

In PR #8522, I did not test the default generated config, and made an incorrect assumption about its contents. This led to the Nix configuration option being uncommented in the ~/.cabal/config file when generated for a user for the first time.

In this PR, I have updated the default value of the Nix configuration option to be empty. This causes the pretty print function, which writes the default config, to comment out the Nix configuration option. This change ensures compatibility, allowing newer Cabal versions to generate configuration files suitable for older Cabal versions.

### CODE REVIEW

**Review by ulysses4ever — APPROVED** [review]

**Comment by ulysses4ever** [comment]
Thank you!

**Comment by chreekat** [comment]
Just an observation from a non-maintainer: one thing that would make this patch more valuable than it already is would be to add some documentation to the test, and maybe clarify the comment on the implementation (*why* do we "need to return PP.empty from viewAsFieldDescr").

File: cabal-install/tests/IntegrationTests2.hs [hunk 1]
```diff
@@ -1938,13 +1940,17 @@ testNixFlags = do
...
   trueConfig <- loadConfig verbosity (Flag (basedir </> "nix-config/nix-true"))
   falseConfig <- loadConfig verbosity (Flag (basedir </> "nix-config/nix-false"))
 
   Nothing @=? (fromFlag . globalNix . savedGlobalFlags $ defaultConfig)
   Just True @=? (fromFlag . globalNix . savedGlobalFlags $ trueConfig)
   Just False @=? (fromFlag . globalNix . savedGlobalFlags $ falseConfig)
+
+  defaultConfigFile <- readFile (basedir </> "nix-config/default-config")
+  True @=? isInfixOf "-- nix:\n" defaultConfigFile
+
```
Comment (gbaz) [inline cabal-install/tests/IntegrationTests2.hs:1953]: can we generalize this test to ensure that essentially all options are commented out in the default config, not just nix?

Comment (gbaz) [reply cabal-install/tests/IntegrationTests2.hs:1953]: i.e. the repo perhaps and a few other things should not be commented, but it would be much better to have a much more uniform test.

**Comment by Mikolaj** [comment]
Could we move this forward? The world needs this PR.

**Review by gbaz — APPROVED** [review]

**Comment by Mikolaj** [comment]
@mergify rebase

**Comment by Mikolaj** [comment]
Failed again. Rerunning failed jobs...

**Comment by Mikolaj** [comment]
@cbclemmer: it seems, the new test started failing on Windows after updating to new GHC or after some changes of setup of the CI machines. Are you able to guess what's going on with this access denied problem? The path is looking funny, but I'm not sure what I'm looking at.

**Comment by cbclemmer** [comment]
@Mikolaj I added a test that will update `cabal-install/tests/IntegrationTests2/config/default-config` with whatever the current default is and I'm not sure why it's failing. It must have something to do with the CI file permissions because the test works on my machine

**Comment by Mikolaj** [comment]
Uhoh. Let's try to debug. Does anybody have any ideas? The error is

```
Exception: tests\IntegrationTests2\config/default-config.tmp: renameFile:renamePath:MoveFileEx "\\\\?\\D:\\a\\cabal\\cabal\\cabal-install\\tests\\IntegrationTests2\\config\\default-config.tmp" Just "\\\\?\\D:\\a\\cabal\\cabal\\cabal-install\\tests\\IntegrationTests2\\config\\default-config": permission denied (Access is denied.)
```

Printing both paths aligned:

```
Exception: tests\IntegrationTests2\config/default-config.tmp: renameFile:renamePath:MoveFileEx 
"\\\\?\\D:\\a\\cabal\\cabal\\cabal-install\\tests\\IntegrationTests2\\config\\default-config.tmp" Just 
"\\\\?\\D:\\a\\cabal\\cabal\\cabal-install\\tests\\IntegrationTests2\\config\\default-config": permission denied (Access is denied.)
```

shows they differ just by the `,tmp`. Do you recognize the paths? Should the `\\config\\` directory exist by that point?

**Comment by cbclemmer** [comment]
@Mikolaj The file should be committed and present at that time, but I've also tried it with the file and it gives the same error. The test that fails writes the file to the folder, so it would override it. Now that I think of it, the nix flag test does the same thing in the test above it so it may not have closed the file handle properly. I've added a commit that will remove the reference to the default config in the nix test, that may help

**Comment by Mikolaj** [comment]
I guess that's progress?

```
Test Default Flags:             FAIL
      tests\IntegrationTests2.hs:1975:
      expected: True
       but got: False
```

**Comment by Mikolaj** [comment]
@cbclemmer: Joking aside. is this test result now explainable?

**Comment by cbclemmer** [comment]
@Mikolaj Sorry, I've been super busy lately but recently I have had more time. The issue was that Windows used a different setting for that parameter than Linux. To fix this I first changed the test to compare the strings on the assertion rather than an auxiliary function, which let me see what the matching line said and allowed me to come to the explanation above. Then to fix it I just compared the string before the colon so that the system differences for the values (and the ones that included the user's home directory) would not be tested because that's not the point of this test anyway. Then I went through all of the default config values and ensured that they are all present and tested for whether they are commented or not. The only drawback to my approach is that it does not test whether specific options are under a heading, but it does test whether they are indented or not. Everything should be good to go now.

**Comment by Mikolaj** [comment]
Good sleuthing. Would you set the squash+merge_me label?

**Comment by cbclemmer** [comment]
@Mikolaj Done

**Comment by Mikolaj** [comment]
@mergify backport 3.10
