### PR TITLE
Make interactive setup delegate CTRL+C

### LINKED ISSUE #3899: cabal new-repl does not handle SIGINT correctly
In the old cabal repl you could cancel your input with SIGINT like this:

```
Prelude> 5 <CTRL+C>  
Prelude> 
```

and it would cancel the input and give you a new prelude line

in `cabal new-repl`  It immediatelly crashes the repl and then produces the following error:

```
*Generics.SOP.Record
λ> 5 
*Generics.SOP.Record
λ> 
╭─arian@laptop  ~/Projects/records-sop  ‹master*› 
╰─$                                                                               130 ↵

<stdin>: hGetChar: hardware fault (Input/output error) 
```

```
╰─$ cabal --version                                                                 1 ↵
cabal-install version 1.24.0.0
compiled using version 1.24.0.0 of the Cabal library 
```

### PR DESCRIPTION
**Pull request by arianvp**
Fixes #3899

When cabal new-repl spawns ghci, it spawns this as a subprocess.
In UNIX like systems, if a CTRL+C is sent to this child process
it also bubbles up to the parent process, causing it to terminate.
Also see https://hackage.haskell.org/package/process-1.4.2.0/docs/System-Process.html#g:4.

However, this is not what we want for interactive subprocesses.
Interactive processes usually define their own handlers for CTRL+C,
for example GHCi uses CTRL+C to reset the input buffer. So instead
of terminating on CTRL+C we want to delegate CTRL+C to GHCi
and let it do its thing.

Luckily, we can enable CTRL+C delegation such that the parent
process ignores the CTRL+C and instead delegates it to the
child process.

### CODE REVIEW

File: cabal-install/Distribution/Client/SetupWrapper.hs [hunk 1]
```diff
@@ -385,6 +393,30 @@ buildTypeAction Make      = Make.defaultMainArgs
 buildTypeAction Custom               = error "buildTypeAction Custom"
 buildTypeAction (UnknownBuildType _) = error "buildTypeAction UnknownBuildType"
 
+runProcess' :: FilePath                 -- ^ Filename of the executable
```
Comment (hvr) [inline cabal-install/Distribution/Client/SetupWrapper.hs]: A haddock string explaining the difference to `runProcess` would be nice

File: cabal-install/Distribution/Client/SetupWrapper.hs [hunk 2]
```diff
@@ -439,12 +471,14 @@ externalSetupMethod path verbosity options _ args = do
       searchpath <- programSearchPathAsPATHVar
                     (map ProgramSearchPathDir (useExtraPathEnv options) ++
                       getProgramSearchPath (useProgramDb options))
-      env        <- getEffectiveEnvironment [("PATH", Just searchpath)
+      env'        <- getEffectiveEnvironment [("PATH", Just searchpath)
                                             ,("HASKELL_DIST_DIR", Just (useDistPref options))]
 
-      process <- runProcess path' args
-                  (useWorkingDir options) env Nothing
+      -- TODO use createProcess
```
Comment (dcoutts) [inline cabal-install/Distribution/Client/SetupWrapper.hs]: Can we add the same TODO at the definition of runProcess', that really we should just switch all uses over, or be more deliberate in our creation of a `createProcess` wrapper.

Comment (arianvp) [inline cabal-install/Distribution/Client/SetupWrapper.hs]: The only reason I defined a runProcess' was to deduplicate code actually.  But I guess I could inline it

That TODO was meant to be removed.

**Comment by arianvp** [comment]
I've tried to resolve all remarks. Lets hope CI finds no additional issues.

**Comment by ezyang** [comment]
Travis failure looks intermittent, I restarted it.

**Comment by arianvp** [comment]
Can i merge this ? Travis says aye. What about backporting? How is the workflow for that?

**Comment by ezyang** [comment]
Thanks for fixing the merge conflict. Let's wait for the build to green again and merge. @23Skidoo is release manager for 1.24.

**Comment by arianvp** [comment]
Sorry for the milestone change. Github UI is confusing. Fixed it again

**Comment by ezyang** [comment]
Looks like there are build failures on 7.6 and 7.8. Do you need help fixing them?

**Comment by arianvp** [comment]
Seem to be some issues with imports overlapping with the New prelude? I think i can fix this

**Comment by ezyang** [comment]
Yep, sounds about right to me. If you're on Ubuntu, you can use hvr's PPA https://launchpad.net/~hvr/+archive/ubuntu/ghc to conveniently install an older version of GHC.

**Comment by dcoutts** [comment]
Ok, lets merge as soon as it goes green.

**Comment by 23Skidoo** [comment]
@arianvp If you want this in 1.24, please feel free to make a pull request against the 1.24 branch.

**Comment by arianvp** [comment]
@23Skidoo I tried cherry picking but got some daunting merge conflicts on 1.24 which I dont have enough knowledge of to fix.  I can manually craft a commit though

**Comment by arianvp** [comment]
CI Is green now. Lets merge! :)

**Comment by 23Skidoo** [comment]
Merged, thanks!
