### PR TITLE
Fix #8400 by marking output of `cabal list-bin`

### LINKED ISSUE #8400: `cabal list-bin` does not produce marked output
Lifted from https://github.com/haskell/cabal/pull/8392#issuecomment-1219171877 
```
$ cabal list-bin cabal '-vnormal +markoutput +nowrap'
Warning: this is a debug build of cabal-install with assertions enabled.
-----BEGIN CABAL OUTPUT-----
Up to date
-----END CABAL OUTPUT-----
/Users/abel/bin/src/cabal/dist-newstyle/build/x86_64-osx/ghc-9.2.4/cabal-install-3.9.0.0/x/cabal/build/cabal/cabal
```
This means the interesting output will not be part of a simple golden value.

The reason is that a plain `putStr` is used for the output: https://github.com/haskell/cabal/blob/a97e1f13bdb28a3f761d55845f14a9072bee17ca/cabal-install/src/Distribution/Client/CmdListBin.hs#L136
That's not in line with convention.  Output should be produced by the predefined API: https://github.com/haskell/cabal/blob/a97e1f13bdb28a3f761d55845f14a9072bee17ca/Cabal/src/Distribution/Simple/Utils.hs#L34-L37
See also:
- https://github.com/haskell/cabal/pull/8396

### LINKED ISSUE #8664: cabal list-bin is broken
Since b2be49cad5adc43d82dc2199199f298f455f51f1 (#8622) `cabal list-bin` no longer produces any output on any project I try it on.  If I change the use of `info` back to `putStrLn`, it works again.

Steps to reproduce the behavior: In the cabal repository itself: `cabal list-bin cabal`

It is also possible that I am holding it wrong (I don't understand this entire `info` machinery), but I don't see how a command like `list-bin` can possibly require any complexity or subtle behaviour.

### PR DESCRIPTION
**Pull request by andreasabel**
Fix #8400 by marking output of `cabal list-bin`

The regular output of `cabal list-bin` should go to stdout always, but be marked for the sake of the testsuite.

- fixes #8400 
- fixes #8664 

If this PR is merged quickly, we do not need:
- #8668

Replaces:
- #8622

### CODE REVIEW

**Comment by andreasabel** [comment]
@bacchanalia : I do not understand why the following `assertOutputContains` succeeds:
https://github.com/haskell/cabal/blob/bcfc79ce1e286b1df1fef31139044c0e0503d5c7/cabal-testsuite/PackageTests/ListBin/Script/cabal.test.hs#L4-L8
The output is just this:
https://github.com/haskell/cabal/blob/bcfc79ce1e286b1df1fef31139044c0e0503d5c7/cabal-testsuite/PackageTests/ListBin/Script/cabal.out#L2-L5
I'd like to change the assertion into something that would fail if `list-bin` didn't print the path to the script, but first I'd like to understand why the current check does not fail.

**Review by athas — APPROVED** [review]
Looks correct to me.

**Comment by Mikolaj** [comment]
That's a puzzling CI failure. Looks like a random corruption, but I can't rule out it's somehow caused by this PR. @andreasabel: could you have a look?

**Comment by andreasabel** [comment]
> LGTM, except for the test result on Windows, which may be wrong due to Windows path separators that, for whatever reason, are not translated properly.

Thanks, good catch: https://github.com/haskell/cabal/actions/runs/3910085986/jobs/6681874680#step:18:138
```
dist\build\x86_64-windows\ghc-9.4.2\SelectedComponent-1.0.0\build\testexe\testexe.exe
```
The path is printed with backslashes under Windows, need to fix that...

**Review by Cmdv — APPROVED** [review]
LGTM 👍

**Review by ulysses4ever — APPROVED** [review]
Good to know about `withOutputMarker`, and thank you for fixing the issue!

File: cabal-install/src/Distribution/Client/CmdListBin.hs [hunk 1]
```diff
@@ -133,7 +133,14 @@ listbinAction flags@NixStyleFlags{..} args globalFlags = do
 
     case binfiles of
         []     -> die' verbosity "No target found"
-        [exe] -> info normal exe
+        [exe]  -> putStr $ withOutputMarker verbosity exe
```
Comment (Bodigrim) [inline cabal-install/src/Distribution/Client/CmdListBin.hs:136]: Why not `putStrLn`?

Comment (Mikolaj) [reply cabal-install/src/Distribution/Client/CmdListBin.hs:136]: Ouch, all tests had EOF at the end, so this wasn't visible.

Comment (andreasabel) [reply cabal-install/src/Distribution/Client/CmdListBin.hs:136]: Yeah, `putStrLn` would be better in the normal operation.  I guess I got pulled towards `putStr` because the `withOutputMarker` puts the EOL character there: https://github.com/haskell/cabal/blob/a78d77b7edd758b9cda3617111445397ac4e2673/Cabal/src/Distribution/Simple/Utils.hs#L622-L625
