### PR TITLE
Require cabal.project packages and/or optional-packages field

### LINKED ISSUE #7401: Error message is wrong
The error message claims there is no .cabal file nor a cabal.project,
when in fact they both exist.

```
Verse$ cabal --version
cabal-install version 3.4.0.0
compiled using version 3.4.0.0 of the Cabal library
Verse$ cabal build
Warning: There are no packages or optional-packages in the project
cabal.exe: There is no <pkgname>.cabal package file or cabal.project file. To
build packages locally you need at minimum a <pkgname>.cabal file. You can use
'cabal init' to create one.

For non-trivial projects you will also want a cabal.project file in the root
directory of your project. This file lists the packages in your project and
all other build configuration. See the Cabal user guide for full details.

Verse$ ls -l
total 14
-rw-r--r-- 1 lennart.augustsson Domain Users   14 May 18 17:18 cabal.project
-rw-r--r-- 1 lennart.augustsson Domain Users  113 May 18 16:33 CHANGELOG.md
drwxr-xr-x 1 lennart.augustsson Domain Users    0 May 18 15:39 dist-newstyle
drwxr-xr-x 1 lennart.augustsson Domain Users    0 May 18 17:12 src
-rw-r--r-- 1 lennart.augustsson Domain Users 1305 May 18 17:15 Verse.cabal
```

### PR DESCRIPTION
**Pull request by tbidne**
Resolves #7401.

Turns the prior warning into an error. This has the effect that the misleading messages are never logged, since the new error causes an immediate failure.

I attempted to add as many test cases as I could think of, so there may be some redundancy (e.g. I checked explicit vs. implicit targets, and evidently it doesn't matter).

I also added the project file path to the error message. This is grabbed [here](https://github.com/tbidne/cabal/blob/949c1c554a8a77300dea1a3242ded281f2508810/cabal-install/src/Distribution/Client/ProjectOrchestration.hs#L311):

```haskell
establishProjectBaseContextWithRoot
  :: Verbosity
  -> ProjectConfig
  -> ProjectRoot
  -> CurrentCommand
  -> IO ProjectBaseContext
establishProjectBaseContextWithRoot verbosity cliConfig projectRoot currentCommand = do
  let haddockOutputDir = flagToMaybe (packageConfigHaddockOutputDir (projectConfigLocalPackages cliConfig))
  let distDirLayout = defaultDistDirLayout projectRoot mdistDirectory haddockOutputDir

  ...

  -- Get path from distDirLayout here...
  let projPath = distProjectFileMain (distProjectFile distDirLayout)
  when (null (projectPackages projectConfig) && null (projectPackagesOptional projectConfig)) $
    dieWithException verbosity (ProjectConfigNoPackages projPath)
```

This seems right to me, though someone should double-check this makes sense.

Thanks!

---

**Template Α: This PR modifies [behaviour or interface](https://github.com/cabalism/cabal/blob/master/CONTRIBUTING.md#changelog)**

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
  * [ ] [Is the change significant?](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#is-my-change-significant) If so, remember to add `significance: significant` in the changelog file.
* [x] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [x] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

### CODE REVIEW

File: changelog.d/pr-11574 [hunk 1]
```diff
@@ -0,0 +1,20 @@
+synopsis: Require cabal.project packages and/or optional-packages field.
+packages: cabal-install
+prs: #11574
+issues: #7401
+significance:
```
Comment (geekosaur) [inline changelog.d/pr-11574:5]: This probably counts as "significant". In addition, it should be documented in [the project file](https://github.com/haskell/cabal/blob/master/doc/cabal-project-description-file.rst) section of the manual.

Comment (tbidne) [reply changelog.d/pr-11574:5]: Fair point on significance, but the requirement is documented [here](https://github.com/haskell/cabal/blob/master/doc/cabal-project-description-file.rst#specifying-the-local-packages), right?

> You _must_ provide a non-empty list of local packages in your project, filling out either a `packages` field or an `optional-packages` field or both to satisfy this requirement.

This PR really only changes the error message, since leaving off both fields will currently show a different (misleading) error message. Happy to add something if you think the docs can be improved.

Comment (ulysses4ever) [reply changelog.d/pr-11574:5]: I don't think it counts as significant since it only changed the error message but it's a vague notion anyway

**Review by geekosaur — APPROVED** [review]

File: changelog.d/pr-11574 (hunk 1 above)
Comment (philderbeast) [reply changelog.d/pr-11574:5]: > Turns the prior warning into an error.

From this PR's description.
