### PR TITLE
Use default install directory if not specified.

### LINKED ISSUE #5967: Verbosity argument parser broken in 3.0?
2.4 works:
```
[FL973] ~ % /opt/cabal/2.4/bin/cabal -vnormal+nowrap+markoutput v2-update 
-----BEGIN CABAL OUTPUT-----
Downloading the latest package list from hackage.haskell.org
-----END CABAL OUTPUT-----
^C
```

3.0: fails
```
[FL973] ~ % /opt/cabal/3.0/bin/cabal -vnormal+nowrap+markoutput v2-update
normal+nowrap+markoutput
CallStack (from HasCallStack):
  error, called at ./Distribution/ReadE.hs:42:24 in Cabal-3.0.0.0-1HTIZuMKheaKipyRNcxZjh:Distribution.ReadE
```

Note, single modifiers work

```
[FL973] ~ % /opt/cabal/3.0/bin/cabal -vnormal+nowrap v2-update 
Downloading the latest package list from hackage.haskell.org
^C
[FL973] ~ % /opt/cabal/3.0/bin/cabal -vnormal+markoutput v2-update
-----BEGIN CABAL OUTPUT-----
Downloading the latest package list from hackage.haskell.org
-----END CABAL OUTPUT-----
^C
```

as well with space it seems:

```haskell
[FL973] ~ % /opt/cabal/3.0/bin/cabal '-vnormal+nowrap +markoutput' v2-update
-----BEGIN CABAL OUTPUT-----
Downloading the latest package list from hackage.haskell.org
-----END CABAL OUTPUT-----
^C
```

### LINKED ISSUE #5973: cabal-install-3.0 requires --installdir option which doesn't exist in existing ~/.cabal/configs
```
% cabal new-install hlint
Resolving dependencies...
Build profile: -w ghc-8.4.4 -O1
In order, the following will be built (use -v for more details):
 - hlint-2.1.15 (lib) (requires build)
 - hlint-2.1.15 (exe:hlint) (requires build)
Starting     hlint-2.1.15 (lib)
Building     hlint-2.1.15 (lib)
Installing   hlint-2.1.15 (lib)
Completed    hlint-2.1.15 (lib)
Starting     hlint-2.1.15 (exe:hlint)
Building     hlint-2.1.15 (exe:hlint)
Installing   hlint-2.1.15 (exe:hlint)
Completed    hlint-2.1.15 (exe:hlint)
cabal: installdir is not defined. Set it in your cabal config file or use
--installdir=<path>
```

- it fails only at the end
- why it cannot use default if it's not specified?

### PR DESCRIPTION
**Pull request by m-renaud**
Cabal 3.0.0.0 added the `--installdir` option to specify the location that binaries should be installed in. Running a `cabal user-config update` would populate the config file with the default value, but the `cabal install` program would error if it wasn't set. This change uses the default value that would be written to the config if its unset, and outputs a warning.

Previous error:
```
cabal: installdir is not defined. Set it in your cabal config file or use
--installdir=<path>
```

New warning (install succeds):
```
Warning: installdir is not defined. Set it in your cabal config file or use
--installdir=<path>. Using default installdir: "/path/to/the/default/installdir/bin"

```

This resolves #5973  

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users have been recorded in the changelog.
* [x] The documentation has been updated, if necessary.
* [x] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

/cc @phadej @fgaz

### CODE REVIEW

File: cabal-install/Distribution/Client/CmdInstall.hs [hunk 1]
```diff
@@ -659,9 +660,10 @@ installExes verbosity baseCtx buildCtx platform compiler
       mkFinalExeName exe = prefix <> unUnqualComponentName exe <> suffix <.> exeExtension platform
       installdirUnknown =
         "installdir is not defined. Set it in your cabal config file "
-        ++ "or use --installdir=<path>"
+        ++ "or use --installdir=<path>. Using default installdir."
```
Comment (vrom911) [inline cabal-install/Distribution/Client/CmdInstall.hs]: It would be convenient if the default path was displayed here as well.

Comment (m-renaud) [reply cabal-install/Distribution/Client/CmdInstall.hs]: Done. New format:

```
Warning: installdir is not defined. Set it in your cabal config file or use
--installdir=<path>. Using default installdir: "/home/mrenaud/.cabal/bin"
```

File: cabal-install/Distribution/Client/CmdInstall.hs [hunk 2]
```diff
@@ -658,12 +658,13 @@ installExes verbosity baseCtx buildCtx platform compiler
 
       mkFinalExeName :: UnqualComponentName -> FilePath
       mkFinalExeName exe = prefix <> unUnqualComponentName exe <> suffix <.> exeExtension platform
-      installdirUnknown =
+      installdirUnknown path =
```
Comment (phadej) [inline cabal-install/Distribution/Client/CmdInstall.hs]: `installPath` is in scope, so doesn't need to be passed as an argument? does it?

Comment (m-renaud) [reply cabal-install/Distribution/Client/CmdInstall.hs]: You're completely right, updated.

File: cabal-install/Distribution/Client/CmdInstall.hs [hunk 3]
```diff
@@ -658,13 +658,12 @@ installExes verbosity baseCtx buildCtx platform compiler
 
       mkFinalExeName :: UnqualComponentName -> FilePath
       mkFinalExeName exe = prefix <> unUnqualComponentName exe <> suffix <.> exeExtension platform
-      installdirUnknown path =
+      installdirUnknown =
         "installdir is not defined. Set it in your cabal config file "
-        ++ "or use --installdir=<path>. Using default installdir: " ++ show path
+        ++ "or use --installdir=<path>. Using default installdir: " ++ show installPath
 
   installdir <- fromFlagOrDefault
```
Comment (phadej) [inline cabal-install/Distribution/Client/CmdInstall.hs]: this can be `let installdir = ... ` now, can't it. There are no effects happening?

Sorry for not spotting on the first look

**Comment by m-renaud** [comment]
The "Windows / test ghc-8.6.5" test has failed for every PR I've made in the last week or so, is this a known issue? Anyways, I think this is ready to merge.

**Comment by phadej** [comment]
@m-renaud yes it is, https://github.com/haskell/cabal/issues/6627

**Comment by m-renaud** [comment]
@phadej should we merge this in before the next cabal-install release? It appears that the Windows failure is blocking the merge, at least from the GitHub UI.

**Comment by m-renaud** [comment]
Done. CI re-running run.

OOC, why not use "Squash and Merge" button and re-write the commit message to be added to the master branch there?

**Comment by phadej** [comment]
Because perfectly, I'd not use GitHub merge button at all, but let CI push to master the merge commit it tested (given the PR is accepted). We could get quite close to that with current CI setup, but GitHub actions doesn't support restarting individual jobs inside the workflow, so we cannot have whole CI as a single workflow (and thus know that all checks passed).

**Comment by tomsmeding** [comment]
Sorry for coming back to this from #5973 — is there any reason why the warning message does not mention that `cabal user-config update` is something that the user might want to do?

**Comment by fgaz** [comment]
@tomsmeding not really, I just didn't think of adding it
