### PR TITLE
Change license :: License to Either SPDX.License License

### LINKED ISSUE #2547: Consider adopting/support SPDX licence identifiers
See table at https://spdx.org/licenses (or http://git.spdx.org/?p=license-list.git;a=summary)   and or SPDX spec at http://spdx.org/SPDX-specifications/spdx-version-2.0

In addition to a comprehensive list of software-licences, SPDX 2.0 also specifies an "license expression syntax":

> This new syntax supports the ability to use a simple “+” operator after a license short identifier to indicate “or later version” (e.g. `GPL-2.0+`). It also supports the ability to declare an SPDX-identified license exception using the “WITH” operator (e.g. `GPL-2.0+ WITH Autoconf-exception-2.0`). SPDX has defined a list of license exceptions to use after the “WITH” operator. 

This was suggested in http://www.reddit.com/r/haskell/comments/338eg9/could_we_update_distributionversion_to_recognize/cqiyep4

/cc @dcoutts @cartazio

### PR DESCRIPTION
**Pull request by phadej**
~WIP: [ci skip] Have to fix cabal-tests and check that we don't break
older (i.e all) ghc-pkgs~

Resolves #2547

I introduce SimpleLicenseExpression to make "OrAnyLater LicenseRef"
unrepresentable. That also simplifies types.

license field is parsed as old License when cabal-version <2.2,
and as SPDX expression otherwise. NONE is recognised.

There are also IPI changes, there both old and SPDX license expressions
are accepted, as both can occur in package database.

Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/#conventions).
* [ ] Any changes that could be relevant to users have been recorded in the changelog.
* [ ] The documentation has been updated, if necessary.
* [ ] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Comment by phadej** [comment]
I probably end up introducing `spdx` field into IPI, so `license` field can be left intact, and new field used for SPDX stuff. I have to run `cabal-tests` to see how badly things are broken right now.

**Comment by phadej** [comment]
I made `Register` write SPDX info with GHC >= 8.4 only. That will do it. Simple.

File: Cabal/Distribution/Simple/Register.hs [hunk 1]
```diff
@@ -407,7 +408,11 @@ generalInstalledPackageInfo adjustRelIncDirs pkg abi_hash lib lbi clbi installDi
     IPI.instantiatedWith   = componentInstantiatedWith clbi,
     IPI.sourceLibName      = libName lib,
     IPI.compatPackageKey   = componentCompatPackageKey clbi,
-    IPI.license            = license     pkg,
+    -- If GHC >= 8.4 we register with SDPX, otherwise with legacy license
+    IPI.license            =
+        if ghc84
+        then Left $ either id licenseToSPDX $ licenseRaw pkg
```
Comment (phadej) [inline Cabal/Distribution/Simple/Register.hs]: This choice converts everything to SPDX, so in GHC-8.4 package databases will only be SPDX expressions.
Alternatively we can let `licenseRaw` to go though unmodified, or convert only "sure" things (e.g. MIT, BSD3, GPL-3, not `PublicDomain` or `OtherLicense`)

**Comment by phadej** [comment]
How it's possible that in GHC-7.8.4 output https://travis-ci.org/haskell/cabal/jobs/330116951#L2091 I see

```
Linked component graph:
    unit my-0
        include base-4.11.0.0
```

File: Cabal/Distribution/Simple/Register.hs (hunk 1 above)
Comment (hvr) [reply Cabal/Distribution/Simple/Register.hs]: Sounds good to me :-)

**Comment by phadej** [comment]
ping @ezyang , any ideas why tests fail on older GHC?

**Comment by phadej** [comment]
Ah I see, it actually tests with `ghc-head`! I have to skip that tests before GHC-head is updated :)

**Comment by 23Skidoo** [comment]
You can change the GHC version check to `8.4.0.2018MMDD`: make this a month or two in the future now and update later once you know the correct snapshot date.

**Comment by phadej** [comment]
@23Skidoo head is 8.5 so that won't work, I'll just temporarily skip the test for 8.4+ and unskip it when Cabal is updated in GHC-tree.

**Comment by phadej** [comment]
@23Skidoo do you want to take a closer look, or should I merge?

**Comment by 23Skidoo** [comment]
I'll try to later today, feel free to merge if I won't.

**Comment by phadej** [comment]
I merged this now, any comments are still welcome
