### PR TITLE
Fix environment variable handling when running executables 

### LINKED ISSUE #10718: Cabal 3.14.1.0 invokes test binaries with a corrupt (duplicated) environment variable list
## Describe the bug

`cabal 3.14.1.0` invokes test binaries with with an invalid environment variable list that contains duplicate entries.

As documented by POSIX: https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/V1_chap08.html

> If more than one string in an environment of a process has the same *name*, the consequences are undefined.

This is causing the `directory` CI tests to fail: https://github.com/haskell/directory/actions/runs/12595046406

The bug is *not* found in `cabal 3.12.1.0`.

## To Reproduce

```haskell
-- Main.hs
module Main where
import Data.List (sort)
import System.Environment (getEnvironment)
main = print =<< fmap sort getEnvironment
```

```cabal
-- foo.cabal
cabal-version:      3.0
name:               foo
version:            0.1.0.0
build-type:         Simple

test-suite test
    build-depends:    base
    default-language: Haskell2010
    main-is:          Main.hs
    type:             exitcode-stdio-1.0
```

```shell
$ cabal test
```

### Actual output

```
[("COLORTERM","truecolor"),("COLORTERM","truecolor"),("DBUS_SESSION_BUS_ADDRESS",...),("DBUS_SESSION_BUS_ADDRESS",...),...
```

## Expected behavior

There should not be any duplicates, i.e.

```
[("COLORTERM","truecolor"),("DBUS_SESSION_BUS_ADDRESS",...),...
```

## System information

 - Operating system: Tested on Ubuntu (Github Actions) + WSL Debian
 - Reproducible on `cabal 3.14.1.0`. *Not* reproducible on `cabal 3.12.1.0`.
 - Reproducible on several GHC versions.

### PR DESCRIPTION
**Pull request by mpickering**
This fixes a bug where environment variables were duplicated when running executables.

```
overrideEnv <- fromMaybe [] <$> getEffectiveEnvironment ([("PATH", Just newPath)] ++ envOverrides)
let shellEnv = overrideEnv ++ existingEnv
```

Since getEffectiveEnvironment already calls getEnvironment internally, if any overrides
are passed then the result is a complete environment. Appending it to
the already existing environment results in duplicated environment variables.

The fix:
* Added getFullEnvironment function to handle the common pattern correctly
* Updated code in Bench, Test/ExeV10, Test/LibV09, and Client/Run to use this function

In the future it would be good to generalise `getFullEnvironment`
further so it can also handle the `addLibraryPath` case, which modifies
an environment variable, rather than merely setting or unsetting it.

Fixes #10718.

---

**Template Α: This PR modifies [behaviour or interface](https://github.com/cabalism/cabal/blob/master/CONTRIBUTING.md#changelog)**

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
  * [ ] [Is the change significant?](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#is-my-change-significant) If so, remember to add `significance: significant` in the changelog file.
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [x] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

---

**Template B: This PR does not modify behaviour or interface**

*E.g. the PR only touches documentation or tests, does refactorings, etc.*

Include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [ ] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).

### CODE REVIEW

File: Cabal/src/Distribution/Simple/Program/Run.hs [hunk 1]
```diff
@@ -248,6 +249,17 @@ getEffectiveEnvironment overrides =
...
+-- | Like 'getEffectiveEnvironment', but when no overrides are specified,
+-- returns the full environment instead of 'Nothing'.
+getFullEnvironment
+  :: [(String, Maybe String)]
+  -> IO [(String, String)]
+getFullEnvironment overrides = do
+  menv <- getEffectiveEnvironment overrides
+  case menv of
+    Just env -> return env
+    Nothing -> getEnvironment
```
Comment (sheaf) [inline Cabal/src/Distribution/Simple/Program/Run.hs:261]: I don't like this code, because it relies on the following invariant of `getEffectiveEnvironment`: it only returns `Nothing` when passed an empty list. Without knowing this, it looks that `getEffectiveEnvironment` can "fail" and that in that case we are discarding the overrides. I suppose it makes sense if you think of `getEffectiveEnvironment` as returning exactly what you would put in the `env` field of `CallProcess` (where `Nothing` means: use the ambient environment).

If you don't want to change any of that, could you at least add a comment, e.g. "`getEffectiveEnvironment` returns `Nothing` precisely when there are no overrides"?

**Review by sheaf — APPROVED** [review]
Great, thanks for doing this.

**Comment by Mikolaj** [comment]
Let me take the liberty of assuming this is ready for review and marking it so.

**Comment by ulysses4ever** [comment]
We badly need the second review for this one.

File: Cabal/src/Distribution/Simple/Program/Run.hs (hunk 1 above)
Comment (ulysses4ever) [reply Cabal/src/Distribution/Simple/Program/Run.hs:261]: I guess by "add a comment" @sheaf meant a comment in the implementation. @mpickering do you want to do that?

**Review by ulysses4ever — APPROVED** [review]
LGTM, and a special thank you for the test.

**Comment by Mikolaj** [comment]
Am I right this should be backported to 3.14? Let me set the label tentatively.

**Comment by Mikolaj** [comment]
@mergify backport 3.14
