### PR TITLE
Ignore invalid Unicode in pkg-config descriptions

### LINKED ISSUE #9608: Cabal 3.10.2.1 cannot parse `pkg-config`: `hGetContents: invalid argument (invalid byte sequence)`
**Describe the bug**

Trying to run `cabal build` on https://github.com/fossas/fossa-cli/tree/64c2f202dc923e3784267cf1d974a952da5baf09 works with Cabal 3.6.2.0, but not with Cabal 3.10.2.1. Here's the error message:

```
$ cabal build --minimize-conflict-set --verbose
this build was affected by the following (project) config files:
- /home/leo/src/fossa/fossa-cli/cabal.project
Running: /home/leo/.ghcup/bin/ghc --print-global-package-db
Reading available packages of hackage.haskell.org...
Using historical state as of 2024-01-02T10:02:41Z as explicitly requested (via
command line / project configuration)
index-state(hackage.haskell.org) = 2024-01-02T10:02:41Z (HEAD =
2024-01-10T22:03:12Z)
Running: /usr/bin/pkg-config --version
Running: /usr/bin/pkg-config --variable pc_path pkg-config
Running: /usr/bin/pkg-config --version
Running: /usr/bin/pkg-config --list-all
Failed to query pkg-config, Cabal will continue without solving for pkg-config
constraints: output of /usr/bin/pkg-config: hGetContents: invalid argument
(invalid byte sequence)
Resolving dependencies...
CallStack (from HasCallStack):
  withMetadata, called at src/Distribution/Simple/Utils.hs:368:14 in Cabal-3.10.2.1-inplace:Distribution.Simple.Utils
Error: cabal: Could not resolve dependencies:
[__0] trying: spectrometer-0.1.0.0 (user goal)
[__1] trying: lzma-0.0.1.0 (dependency of spectrometer)
[__2] rejecting: lzma:+pkgconfig (conflict: pkg-config package liblzma>=5.2.2,
not found in the pkg-config database)
[__2] rejecting: lzma:-pkgconfig (manual flag can only be changed explicitly)
[__2] fail (backjumping, conflict set: lzma, lzma:pkgconfig)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: lzma (8), spectrometer (7),
lzma:pkgconfig (3)
```

This is strange, because `/usr/bin/pkg-config --list-all` exits zero, and `/usr/bin/pkg-config --modversion liblzma` outputs `5.4.5`. Here are some `pkg-config` outputs:

```
$ /usr/bin/pkg-config --version
2.1.0

$ /usr/bin/pkg-config --variable pc_path pkg-config
/usr/lib/pkgconfig:/usr/share/pkgconfig
```

I have also the output of `/usr/bin/pkg-config --list-all`, available here: [pkg-config-list-all.txt](https://github.com/haskell/cabal/files/13895409/pkg-config-list-all.txt).

I'm on Arch Linux (which symlinks `pkg-config` to `pkgconf`), and I suspect this may be related to #8930, which also impacts me. I've been having troubles with `pkg-config` in general (see #8495 and #8494) since Cabal 3.8 when the `pkg-config` logic was changed. The commit in this bug report also does not build on Cabal 3.8.1.0 for me, failing with the same error message.

**To Reproduce**

`cabal build` on https://github.com/fossas/fossa-cli/tree/64c2f202dc923e3784267cf1d974a952da5baf09 using Cabal 3.8.* or 3.10.* reliably reproduces this issue for me, although it may be because of my machine's specific `pkg-config` database.

**Expected behavior**

I expect the build to succeed building in Cabal 3.10, since it succeeded in Cabal 3.6, and my `pkg-config` database clearly has the required package.

**System information**

 - Operating system: Arch Linux
 - Cabal:
   - Tested with and affects: 3.8.1.0, 3.10.2.0, 3.10.2.1
   - Tested with and does not affect: 3.6.2.0-p1
 - GHC: 9.4.7

### PR DESCRIPTION
**Pull request by tomsmeding**
Previously, if any of the pkg-config packages on the system had invalid Unicode in their description fields (like the Intel vpl package has at the time of writing, 2024-01-11, see #9608), cabal would crash because it tried to interpret the entire `pkg-config --list-all` output as Unicode.

This change, as suggested by gbaz in <https://github.com/haskell/cabal/issues/9608#issuecomment-1886120831>, switches to using a lazy ByteString for reading in the output, splitting on the first space in byte land, and then parsing only the package _name_ to a String.

For further future-proofing, package names that don't parse as valid Unicode don't crash Cabal, but are instead ignored.

Fixes #9608.

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* The documentation has been updated, if necessary. _(unnecessary, bug fix)_
* [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included. _(unnecessary, no CLI change)_
* [x] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

### CODE REVIEW

File: cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs [hunk 1]
```diff
@@ -63,10 +68,14 @@ readPkgConfigDb verbosity progdb = handle ioErrorHandler $ do
     case mpkgConfig of
       Nothing             -> noPkgConfig "Cannot find pkg-config program"
       Just (pkgConfig, _) -> do
-        pkgList <- lines <$> getProgramOutput verbosity pkgConfig ["--list-all"]
+        -- To prevent malformed Unicode in the descriptions from crashing cabal,
+        -- read without interpreting any encoding first. (#9608)
+        pkgList <- LBS.split 10 <$> getProgramInvocationLBS verbosity (programInvocation pkgConfig ["--list-all"])
```
Comment (alt-romes) [inline cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs:73]: I suggest we avoid the literal `10`, it confused me initially
```suggestion
        pkgList <- LBS.split (fromEnum '\n') <$> getProgramInvocationLBS verbosity (programInvocation pkgConfig ["--list-all"])
```

**Review by alt-romes — APPROVED** [review]
Good work!

**Review by Mikolaj — APPROVED** [review]
LGTM

File: cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs (hunk 1 above)
Comment (tomsmeding) [reply cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs:73]: It should be a `Word8`, so that'd become `fromIntegral (ord '\n')` which is quite verbose. But fair point, maybe one shouldn't assume extensive familiarity with ASCII from Cabal contributors :D

Comment (alt-romes) [reply cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs:73]: I suppose you could also just add `-- 10 is ASCII for '\n'`, or `-- split on newlines (10 == fromEnum '\n')

Comment (tomsmeding) [reply cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs]: I made it the verbose version, and just added a newline ;)

[the remark this answers is not in the document]
Comment (tomsmeding) [reply cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs]: That's an ASCII newline. This has been changed on alt-romes' suggestion to `fromIntegral (ord '\n')` in a later commit.

**Comment by Mikolaj** [comment]
BTW, would it be possible to add a small test with sample invalid characters preceded by valid ones?

File: cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs [hunk 2]
```diff
@@ -63,10 +68,14 @@ readPkgConfigDb verbosity progdb = handle ioErrorHandler $ do
...
         -- The output of @pkg-config --list-all@ also includes a description
         -- for each package, which we do not need.
-        let pkgNames = map (takeWhile (not . isSpace)) pkgList
+        let pkgNamesLBS = map (LBS.takeWhile (not . isSpace . chr . fromIntegral)) pkgList
```
[the remark this answers is not in the document]
Comment (tomsmeding) [reply cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs:77]: It will not! You are correct, `isSpace` also recognises non-breaking spaces (U+00A0) which, when considered mod 256, have the high bit set and can thus occur in UTF-8 text as part of a multi-byte unicode codepoint. I had naively expected there to be no space characters in the Unicode range between 127 and 256, which would have made this work due to the UTF-8 encoding.

What do you suggest? Something like `not . isAsciiSpace` where ``isAsciiSpace n = n `elem` map (fromIntegral . ord) " \t"``?

File: cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs (hunk 1 above)
[the remark this answers is not in the document]
Comment (Mikolaj) [reply cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs]: That's already spotted by @alt-romes and fixed by the author.

File: cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs [hunk 3]
```diff
@@ -63,10 +68,15 @@ readPkgConfigDb verbosity progdb = handle ioErrorHandler $ do
...
+        -- To prevent malformed Unicode in the descriptions from crashing cabal,
+        -- read without interpreting any encoding first. (#9608)
+        pkgList <- LBS.split (fromIntegral (ord '\n')) <$>
+                     getProgramInvocationLBS verbosity (programInvocation pkgConfig ["--list-all"])
         -- The output of @pkg-config --list-all@ also includes a description
         -- for each package, which we do not need.
-        let pkgNames = map (takeWhile (not . isSpace)) pkgList
+        let pkgNamesLBS = map (LBS.takeWhile (not . isSpace . chr . fromIntegral)) pkgList
+        -- Now decode as UTF8 and convert to String, dropping any that fail decoding.
+        let pkgNames = rights $ map (fmap T.unpack . T.decodeUtf8' . LBS.toStrict) pkgNamesLBS
```
Comment (michaelpj) [inline cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs:79]: Dropping things without giving any output saying that you're doing that seems likely to lead to very hard-to-debug issues later. Can we log (at high verbosity) saying that we're ignoring an entry because it has invalid unicode?

Comment (tomsmeding) [reply cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs]: Thanks! You're right. I'm now logging something at `Verbose` level, which seems to be `-v2` (but not 100% sure). The test also checks this.

**Comment by Mikolaj** [comment]
CI:

```
src/Distribution/Solver/Types/PkgConfigDb.hs:87:55: error:
    Not in scope: ‘T.decodeUtf8Lenient’
    Neither ‘Data.Text’ nor ‘Data.Text.Encoding’ exports ‘decodeUtf8Lenient’.
   |
87 |                             Left _ -> Left (T.unpack (T.decodeUtf8Lenient sbsname))
```

for a 9.2.7 buid.

**Comment by Mikolaj** [comment]
CI still grumpy. This time likely related to the changes themselves.

**Comment by tomsmeding** [comment]
@Mikolaj My latest commit fixes the failure in PackageTests/ExtraProgPath that I saw in the CI. It's an ugly fix, though, and you (plural) will probably have opinions on how to do this in cabal. Feel free to edit however you wish; from now on I'll have very little time work work on this until Monday 2024-01-22.

**Review by geekosaur — APPROVED** [review]

**Comment by Mikolaj** [comment]
@mergify rebase

File: cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs [hunk 4]
```diff
@@ -63,10 +71,38 @@ readPkgConfigDb verbosity progdb = handle ioErrorHandler $ do
     case mpkgConfig of
       Nothing             -> noPkgConfig "Cannot find pkg-config program"
       Just (pkgConfig, _) -> do
-        pkgList <- lines <$> getProgramOutput verbosity pkgConfig ["--list-all"]
-        -- The output of @pkg-config --list-all@ also includes a description
-        -- for each package, which we do not need.
-        let pkgNames = map (takeWhile (not . isSpace)) pkgList
+        -- To prevent malformed Unicode in the descriptions from crashing cabal,
+        -- read without interpreting any encoding first. (#9608)
+        pkgList <- LBS.split (fromIntegral (ord '\n')) <$>
```
Comment (mpickering) [inline cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs:76]: This implementation doesn't seem very nice to me, it at least should be abstracted into it's own function.

* How about using `getProgramInvocationsIODataAndErrors`? Which doesn't crash when the `exitCode` is not `ExitSuccess`
* Could you use a parser abstraction to parse the input (you can use `Parsec` interface in `cabal-install-solver`)

In any case I don't think all this low level logic should be inlined here, so how about a new top level function `getPkgConfigPkgList` to encapsulate it all.

**Review by mpickering — DISMISSED** [review]

File: cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs (hunk 4 above)
Comment (gbaz) [reply cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs:76]: I think using parsec to split a package list on newlines is extreme overkill. Additionally, I don't think this is a lot of logic to inline, just well documented logic. And finally its actually the _bulk_ of the function -- the existing top level function is _already_ the encapsulation.

**Review by gbaz — APPROVED** [review]

**Comment by Mikolaj** [comment]
Let me restart the CI. The current failure starts with the following on macos:

```
Running: /Users/runner/work/cabal/cabal/cabal-testsuite/PackageTests/PkgConfigParse/./pkg-config --list-all
Failed to query pkg-config, Cabal will continue without solving for pkg-config
constraints:
/Users/runner/work/cabal/cabal/cabal-testsuite/PackageTests/PkgConfigParse/./pkg-config:
createProcess: posix_spawnp: does not exist (No such file or directory)
```

**Comment by Mikolaj** [comment]
@mergify backport 3.10

**Comment by tomsmeding** [comment]
Thanks everyone for the reviews! And also thanks everyone for the help, in particular @Mikolaj :)
