### PR TITLE
Regenerate Lexer.hs with latest Alex (fix #8892)

### LINKED ISSUE #8892: Cabal-syntax lexer: out-of-bound array access with the JS backend
**Describe the bug**
Due to [a bug in Alex](https://github.com/haskell/alex/pull/223), Cabal-syntax's lexer performs an out-of-bound array access. For GHC's native backends it's just a data corruption but for the JS backend it leads to a runtime JS exception (out-of-bound array access).

**To Reproduce**
Build and run some `setup` program with the JS backend. E.g. test `ImpSafeOnly` in GHC's testsuite

**Expected behavior**
Don't crash.

**System information**
 - GHC's JS backend in HEAD

**Additional context**
- We could fix by manually patching `Lexer.hs`
- Or wait for a new release of Alex (>= 3.2.7.2) and use it to regenerate `Lexer.hs`

### PR DESCRIPTION
**Pull request by hsyl20**
Regenerate Lexer.hs with Alex 3.2.7.2 to fix issue ##8892 (out-of-bound access due to https://github.com/haskell/alex/pull/223).

---
Please include the following checklist in your PR:

* [ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [X] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [X] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Review by ulysses4ever — APPROVED** [review]
Thanks! Sounds like something worth backporting to 3.10, @Mikolaj ?

**Review by Mikolaj — APPROVED** [review]
Yes, definitely, let's backport.

I guess some old test results require a bit of tweaking, too.

**Comment by Mikolaj** [comment]
@mergify backport 3.10

**Comment by hsyl20** [comment]
I've updated to require Alex 3.2.7.3 which doesn't generate files that require `PatternGuards` (see upstream ticket)

**Comment by ulysses4ever** [comment]
@hsyl20 when you have time, could you look into the test failure? I guess, just updating the reference should be enough? (I haven't looked too close though) Updating (via `--accept`) is described in cabal-testsuite/README.md.

**Comment by hsyl20** [comment]
The new failure seems to confirm this.

**Comment by hsyl20** [comment]
New commit with message:

>    Lexer: report indentation warnings at column 1
>
>    We use a Latin1 generated parser with Alex, but we also parses Unicode BOM, unbreakable spaces, etc. In recent Alex, the reported column isn't expressed in Unicode chars anymore but in bytes/ASCII chars (probably due to https://github.com/haskell/alex/commit/ae525e34edf017544e8ef4457d7e57cf2081dcf9 but I haven't checked), which broke our tests (see https://github.com/haskell/cabal/pull/8896).
>
> To work around this we report indentation warnings at token start position, instead of token end position (i.e. always 1). Otherwise position makes no sense anymore for the user.

I've tried to switch to a utf8 lexer instead of latin1 but it makes many more tests fail. I don't even know if `.cabal` files supposed to be UTF-8 though.

**Comment by ulysses4ever** [comment]
This all sounds a bit worrying. @andreasabel, as the author of the corresponding `alex` commit, maybe you have a feeling for what's going on here?

For the sake of discussion, maybe we should preserve links to failing workflows. I know they will die at some point, but at least it gives us some time to contemplate on different approaches.

File: Cabal-syntax/src/Distribution/Fields/Lexer.hs [hunk 1]
```diff
@@ -454,35 +498,56 @@ alexScanUser user__ input__ (I# (sc))
...
         let
                 base   = alexIndexInt32OffAddr alex_base s
-                offset = (base +# ord_c)
-                check  = alexIndexInt16OffAddr alex_check offset
+                offset = PLUS(base,ord_c)
 
-                new_s = if GTE(offset,0#) && EQ(check,ord_c)
+                new_s = if GTE(offset,ILIT(0))
+                          && let check  = alexIndexInt16OffAddr alex_check offset
+                             in  EQ(check,ord_c)
```
Comment (andreasabel) [inline Cabal-syntax/src/Distribution/Fields/Lexer.hs:517]: This comes from this Alex commit: [haskell/alex@`e96c347` (#224)](https://github.com/haskell/alex/pull/224/commits/e96c3478f64bd34b51d313911341c54e90898faf)

I do not see how this should have introduced the problems we are seeing.
`GTE` `ILIT` and `EQ` are macros, yes, but they do not have side effects, so moving the `check` binding into a local `let` should not be a semantic change except making things lazier.

**Comment by andreasabel** [comment]
> This all sounds a bit worrying. @andreasabel, as the author of the corresponding `alex` commit, maybe you have a feeling for what's going on here?

I currently do not have time to dig deeper, but I think the latest `alex` commit is not to be blamed, see my comment: https://github.com/haskell/cabal/pull/8896/files#r1168715008

**Comment by hsyl20** [comment]
Yes I also think it's just the result of this change: https://github.com/haskell/alex/commit/ae525e34edf017544e8ef4457d7e57cf2081dcf9#diff-007f894e1221eb8cafde8fdf0ee317bd32859704c27652c29cbb5417a9d5c37dR179-R185

Which has been introduced in Alex 3.2.7

**Comment by andreasabel** [comment]
Ok, this was 3 years ago, I don't remember much of it.  
If I introduced a bug in Alex, please report it.  
But maybe the source here needs some adjustment to work with Alex 3.2.7.  If this is the case, the Alex violates the PVP, please also report it then.

**Comment by ulysses4ever** [comment]
Technically, this has two approvals and can be merged: the author is expected to add either `merge-me` or `merge+squash` label to the PR. But the alex issue is concerning. Indeed, may be worth reporting...

File: Cabal-tests/tests/ParserTests/regressions/Octree-0.5.format [hunk 2]
```diff
@@ -1,4 +1,4 @@
-Octree-0.5.cabal:39:3: Non breaking spaces at 39:3, 41:3, 43:3
+Octree-0.5.cabal:39:1: Non breaking spaces at 39:1, 41:1, 43:1
```
Comment (andreasabel) [inline Cabal-tests/tests/ParserTests/regressions/Octree-0.5.format:1]: Are these new positions (column 1) better than the old ones or worse?

Comment (hsyl20) [reply Cabal-tests/tests/ParserTests/regressions/Octree-0.5.format:1]: I think they are slightly better because the indentation token starts at column 1. It was a bit weird to report the position of the next token.

**Comment by hsyl20** [comment]
I've opened an upstream ticket: https://github.com/haskell/alex/issues/227

File: Cabal-tests/tests/ParserTests/regressions/Octree-0.5.format (hunk 2 above)
Comment (andreasabel) [reply Cabal-tests/tests/ParserTests/regressions/Octree-0.5.format:1]: Ok, then I book this as "bug fix" for Alex.

**Comment by andreabedini** [comment]
@hsyl20 
>  I don't even know if .cabal files are supposed to be UTF-8 though.

The [documentation](https://cabal.readthedocs.io/en/stable/cabal-package.html#package-descriptions) confirms they are UTF-8.

> The package description file must have a name ending in “.cabal”. It must be a Unicode text file encoded using valid UTF-8.

**Comment by hsyl20** [comment]
So in theory we could use Alex unicode support. But since then I've read in https://amelia.how/posts/parsing-layout.html that:

> Nobody uses the Unicode support, not even GHC: The community wisdom is to trick Alex into reading Unicode by compressing Unicode classes down into high byte characters. Yeah, yikes.
