### PR TITLE
Print info about current project file in use to stderr and ignore the imports by default

### LINKED ISSUE #10547: Printing current project file to stdout (#10507) breaks the usual list-bin workflow
**Describe the bug**
After #10507 I can't do the usual trick with assigning the output of `cabal list-bin` to a shell variable.

**To Reproduce**

This example uses the changelog-d project but can be any package with an executable in it.

```
❯ set ch (cabal list-bin exe:changelog-d)   # that's fish equivalent for bash `export ch=$(cabal list-bin...)`
Warning: this is a debug build of cabal-install with assertions enabled.

❯ echo $ch
Configuration is affected by the following files: - cabal.project /home/artem/Dev/cabal/changelogs-3.14/changelog-d-fork/dist-newstyle/build/x86_64-linux/ghc-9.6.5/changelog-d-1.0.1/x/changelog-d/build/changelog-d/changelog-d
```

Notice that the variable now holds not only the path to the executable but also the message about the project file. Needless to say, this worked before #10507.

**Expected behavior**

The `$ch` variable only holds the path.

**System information**
 - Operating system: NixOS 24.05
 - `cabal-head` , `ghc` 9.6.5

---

# How to fix

Besides reverting #10507, we could change the output to `stderr` (notice how `Warning: this is a debug build... ` works fine). ~~I don't know an easy way to do it except swap `notice` with `warn`~~ NVM, it's `verboseStderr verbosity`

https://github.com/haskell/cabal/blob/287d347aeeb4475c7f32c9e180834f5a6bddb7dd/cabal-install/src/Distribution/Client/ProjectPlanning.hs#L402

~~This is not morally correct because `warn*` message are meant for "Non fatal conditions that may be indicative of an error or problem" (according to the docs). But maybe it's okay?~~

### PR DESCRIPTION
**Pull request by ulysses4ever**
fix #10547 by printing the project config info to stderr. 

Also, report only top-level project configs with the default verbosity. Otherwise, imported config files can still be seen in the verbose mode.

## Manual Q/A

Try to reproduce  #10547

---

**Template Α: This PR modifies [behaviour or interface](https://github.com/cabalism/cabal/blob/master/CONTRIBUTING.md#changelog)**

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [N/A] This fixes code that has not been released yet. ~~Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).~~
  * [x] NO ~~[Is the change significant?](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#is-my-change-significant) If so, remember to add `significance: significant` in the changelog file.~~
* [N/A] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [ ] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

### CODE REVIEW

**Comment by ulysses4ever** [comment]
Oh my, the two hundred tests now fail because `warn` attaches `Warning: ` to the message..

**Comment by ulysses4ever** [comment]
I just ran `list-bin` on Cabal repo and the output is a hot mess:

```
❯ cabal list-bin cabal
Warning: this is a debug build of cabal-install with assertions enabled.
Configuration is affected by the following files:
- cabal.project
Configuration is affected by the following files:
- project-cabal/constraints.config
imported by: cabal.project
Configuration is affected by the following files:
- project-cabal/ghc-latest.config
imported by: cabal.project
Configuration is affected by the following files:
- project-cabal/ghc-options.config
imported by: cabal.project
Configuration is affected by the following files:
- project-cabal/pkgs.config
imported by: cabal.project
Configuration is affected by the following files:
- project-cabal/pkgs/benchmarks.config
imported by: project-cabal/pkgs.config
imported by: cabal.project
Configuration is affected by the following files:
- project-cabal/pkgs/buildinfo.config
imported by: project-cabal/pkgs.config
imported by: cabal.project
Configuration is affected by the following files:
- project-cabal/pkgs/cabal.config
imported by: project-cabal/pkgs.config
imported by: cabal.project
Configuration is affected by the following files:
- project-cabal/pkgs/install.config
imported by: project-cabal/pkgs.config
imported by: cabal.project
Configuration is affected by the following files:
- project-cabal/pkgs/integration-tests.config
imported by: project-cabal/pkgs.config
imported by: cabal.project
Configuration is affected by the following files:
- project-cabal/pkgs/tests.config
imported by: project-cabal/pkgs.config
imported by: cabal.project
/home/artem/Dev/cabal/repo/dist-newstyle/build/x86_64-linux/ghc-9.10.1/cabal-install-3.15.0.0/x/cabal/build/cabal/cabal
```

**Comment by ulysses4ever** [comment]
Okay, I figured how to print to stderr without reaching to `warn`: `verboseStderr verbosity`.

I'm also fixing the above mentioned issue with multiple `Configuration is affected`. It still looks quite chatty for Cabal, which uses plenty of imports since recently. Maybe we should find a way to print only top-level project files.

**Comment by philderbeast** [comment]
> Maybe we should find a way to print only top-level project files.

I'm working on something similar, see branch [fix/y-fork-project-import-warning-only](https://github.com/cabalism/cabal/tree/fix/y-fork-project-import-warning-only). I've seen the loss of indent in those messages before and corrected it by changing from `warn` to `noticeDoc`.

**Comment by ulysses4ever** [comment]
All right, now it prints only top-level project config files in the default verbosity. In the verbose mode it prints the whole thing (imported project files too). The formatting of imports is not great but it's okay for verbose mode and can be fixed later if desired.

**Comment by ulysses4ever** [comment]
@Kleidukos, https://github.com/haskell/cabal/pull/10507 (backported to 3.14) turned out severely undercooked. This PR fixes it for the most part. So, I hope it can be backported too. Otherwise, it’d be desirable to revert the backport of 10507.

File: cabal-install/src/Distribution/Client/ProjectConfig.hs [hunk 1]
```diff
@@ -1753,3 +1754,9 @@ checkBadPerPackageCompilerPaths compilerPrograms packagesConfig =
        ] of
     [] -> return ()
     ps -> throwIO (BadPerPackageCompilerPaths ps)
+
+-- | Filter out non-top-level project configs
```
Comment (ffaf1) [inline cabal-install/src/Distribution/Client/ProjectConfig.hs:1758]: Missing 
```suggestion
-- | Filter out non-top-level project configs.
```

**Review by geekosaur — APPROVED** [review]

File: cabal-install/src/Distribution/Client/ProjectPlanning.hs [hunk 2]
```diff
@@ -397,13 +398,13 @@ rebuildProjectConfig
...
 
-    sequence_
-      [ do
-        notice verbosity . render . vcat $
-          text "Configuration is affected by the following files:"
-            : [text "-" <+> docProjectConfigPath path]
-      | Explicit path <- Set.toList $ projectConfigProvenance projectConfig
-      ]
+    let configfiles =
+          [ text "-" <+> docProjectConfigPath path
```
Comment (ffaf1) [inline cabal-install/src/Distribution/Client/ProjectPlanning.hs:402]: Not a big fan of list comprehensions, but I understand this was not originally written by you and this is a time sensitive PR.

**Review by ffaf1 — APPROVED** [review]

File: cabal-install/src/Distribution/Client/ProjectPlanning.hs (hunk 2 above)
Comment (ulysses4ever) [reply cabal-install/src/Distribution/Client/ProjectPlanning.hs:402]: I'm happy to improve it. Do you have suggestions?

Comment (ulysses4ever) [reply cabal-install/src/Distribution/Client/ProjectPlanning.hs:402]: Like, it'd be easy to rewrite it with `do` but I'm not sure that's better. And if we wanna stay away from syntactic sugar altogether, this looks like a rather ugly fold to me.

Comment (ffaf1) [reply cabal-install/src/Distribution/Client/ProjectPlanning.hs:402]: I see now we are filtering out `Implicit`. It is OK then!

Comment (ulysses4ever) [reply cabal-install/src/Distribution/Client/ProjectPlanning.hs:402]: Yes!

**Comment by ulysses4ever** [comment]
This fixes a regression on master that was backported to 3.14. In the interest of getting it into the release, I'm skipping the two-days delay.

**Comment by ulysses4ever** [comment]
@mergify backport 3.14
