### PR TITLE
Hack around wrong .mix directories for tests

### LINKED ISSUE #5213: cabal new-test doesn't work with library-coverage for components with other-modules
```
$ cabal --version
cabal-install version 2.0.0.0
compiled using version 2.0.1.0 of the Cabal library
```

I'll work on preparing a minimal example in a bit. In the meantime, you can trigger this issue with `scotty-0.11.0`:

```
$ cabal get scotty-0.11.0
Unpacking to scotty-0.11.0/
$ cd scotty-0.11.0/
$ cat > cabal.project << EOF
> packages: .
> package scotty
>   library-coverage: true
> EOF
$ cabal new-test
Resolving dependencies...
In order, the following will be built (use -v for more details):
 - scotty-0.11.0 (lib) (first run)
 - scotty-0.11.0 (test:spec) (first run)
Configuring library for scotty-0.11.0..
Preprocessing library for scotty-0.11.0..
Building library for scotty-0.11.0..
<build output elided>
Configuring test suite 'spec' for scotty-0.11.0..
Preprocessing test suite 'spec' for scotty-0.11.0..
Building test suite 'spec' for scotty-0.11.0..
<build output elided>
Running 1 test suites...
Test suite spec: RUNNING...
<test output elided>
Test suite spec: PASS
Test suite logged to:
/home/ryanglscott/Documents/Hacking/Haskell/scotty-0.11.0/dist-newstyle/build/x86_64-linux/ghc-8.2.2/scotty-0.11.0/c/spec/test/scotty-0.11.0-spec.log
hpc: can not find scotty-0.11.0-inplace/Web.Scotty.Util in ./.hpc, /home/ryanglscott/Documents/Hacking/Haskell/scotty-0.11.0/dist-newstyle/build/x86_64-linux/ghc-8.2.2/scotty-0.11.0/c/spec/hpc/vanilla/mix/scotty-0.11.0, /home/ryanglscott/Documents/Hacking/Haskell/scotty-0.11.0/dist-newstyle/build/x86_64-linux/ghc-8.2.2/scotty-0.11.0/c/spec/hpc/vanilla/mix/spec
CallStack (from HasCallStack):
  error, called at libraries/hpc/Trace/Hpc/Mix.hs:122:15 in hpc-0.6.0.3:Trace.Hpc.Mix
cabal: Tests failed for test:spec from scotty-0.11.0.
```

This error doesn't happen for another project, `wai-middleware-static-0.8.1`. Unlike `scotty`, `wai-middleware-static` has no `other-modules`, so I suspect that is the culprit here.

### PR DESCRIPTION
**Pull request by Mikolaj**
This should fix #5213, except for multilib, which case is disabled anyway.

The correct way to fix this is to rethink directories for .mix HPC files (one directory per component is wrong) and pass around some generic package directory prefixes (not passed currectly) that enable looking up or creating the directories from each component. This should work even if components are HPC-processed in separate cabal runs (e.g., first library, only then tests). Perhaps then multilib can be enabled, unless HPC itself or GHC can't handle it.

---
Please include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.

Please also shortly describe how you tested your change. Bonus points for added tests!

### CODE REVIEW

**Review by gbaz — APPROVED** [review]

**Comment by gbaz** [comment]
Its a fine hack for now, easier than the rather invasive looking Right Thing alternative.

**Comment by Mikolaj** [comment]
I feel dirty anyway, but thank you. :)

**Comment by Mikolaj** [comment]
@RyanGlScott, @davean, @cartazio, @fgaz, @ocharles: would one of you have a moment to review? thank you!

File: Cabal/src/Distribution/Simple/Hpc.hs [hunk 1]
```diff
@@ -68,7 +68,15 @@ mixDir :: FilePath  -- ^ \"dist/\" prefix
...
        -> FilePath  -- ^ Component name
        -> FilePath  -- ^ Directory containing test suite's .mix files
-mixDir distPref way name = hpcDir distPref way </> "mix" </> name
+mixDir distPref way name = hpcDir distPrefBuild way </> "mix" </> name
+ where
+  -- This is a hack for HPC over test suites, needed to match the directory
+  -- where HPC stores .mix files when the main library of the same package
+  -- is being processed, perhaps in a previous cabal run (#5213).
+  distPrefElements = splitDirectories distPref
+  distPrefBuild = case drop (length distPrefElements - 2) distPrefElements of
```
Comment (RyanGlScott) [inline Cabal/src/Distribution/Simple/Hpc.hs:77]: Why `- 2` here? Perhaps it would be worthwhile to include an example of the directory you're trying to access in the comments above, which would make the directory structure more apparent.

**Review by RyanGlScott — COMMENTED** [review]
Hooray!

File: Cabal/src/Distribution/Simple/Hpc.hs (hunk 1 above)
Comment (Mikolaj) [reply Cabal/src/Distribution/Simple/Hpc.hs:77]: Will do. The last 2 components are `t/theTestName/`, hence 2.

Comment (Mikolaj) [reply Cabal/src/Distribution/Simple/Hpc.hs:82]: Done.

**Comment by Mikolaj** [comment]
CI is acting up again.

**Comment by ocharles** [comment]
I'm not sure I can give this a review, but I grabbed this PR and using it can successfully run `cabal test ch-persistence --enable-coverage`. Now whether that's due to this PR or mine, I can't say - but things certainly don't get worse with this PR!

**Comment by Mikolaj** [comment]
> I'm not sure I can give this a review, but I grabbed this PR and using it can successfully run `cabal test ch-persistence --enable-coverage`. Now whether that's due to this PR or mine, I can't say - but things certainly don't get worse with this PR!

Thank you. That's good news either way.

**Comment by ocharles** [comment]
I may have spoken too soon. If I do `cabal test ch-persistence --enable-coverage`, it works. If I do `cabal test ch-persistence` with

```
package ch-persistence
  coverage: True
```

I get

```
/home/ollie/work/circuithub/dist-newstyle/build/x86_64-linux/ghc-8.10.4/ch-persistence-1.0/t/tests/noopt/test/ch-persistence-1.0-tests.log
hpc: can not find ch-persistence-1.0-inplace/CircuitHub.Query.Progress in ./.hpc, /home/ollie/work/circuithub/dist-newstyle/build/x86_64-linux/ghc-8.10.4/ch-persistence-1.0/t/tests/noopt/hpc/vanilla/mix/ch-persistence-1.0, /home/ollie/work/circuithub/dist-newstyle/build/x86_64-linux/ghc-8.10.4/ch-persistence-1.0/t/tests/noopt/hpc/vanilla/mix/tests
CallStack (from HasCallStack):
  error, called at libraries/hpc/Trace/Hpc/Mix.hs:122:15 in hpc-0.6.1.0:Trace.Hpc.Mix
cabal: Tests failed for test:tests from ch-persistence-1.0
```

In this case, `CircuitHub.Query.Progress` is an `exposed-module` of `ch-persistence`.

I note that `--enable-coverage` builds _everything_ with coverage, but the `cabal.project.local` variant only builds `ch-persistence` with coverage.

**Comment by Mikolaj** [comment]
I think my hack should cover that and it looks as if the hack was not applied at all. How can I reproduce? Which repo is that?

**Comment by ocharles** [comment]
Unfortunately this is private code that I can't share. I'll double check that I'm using your code from this PR.

**Comment by Mikolaj** [comment]
In the failed run, the output of something like `find . -name "*CircuitHub.Query.Progress.mix*"` would be helpful, too. Perhaps the paths can be more complex than I assumed.

**Comment by ocharles** [comment]
I've confirmed that the `cabal` I'm calling is patched:

```
sed -n '73{p;q}' (nix show-derivation (nix-store --query --deriver (which cabal)) | jq -r .'"/nix/store/phdr8slb3dgs5kb9jxjw0ngirsbhyhaz-cabal-install-exe-cabal-3.5.0.0.drv"'.env.src)/../Cabal/src/Distribution/Simple/Hpc.hs
  -- This is a hack for HPC over test suites, needed to match the directory
```

Here is the output of `fd '.*'` for `ch-persistence` with (`good`) and without (`bad`) `--enable-coverage`: https://gist.github.com/ocharles/5369f72d195ecd0a8a37f301d27bd3b8

**Comment by ocharles** [comment]
What's very odd is that the `.mix` files seem to be in the same place, so maybe the `hpc` call itself is wrong.

Here is the "wrong" call (that crashes):

```
[pid 353787] execve("/nix/store/mlqhmb29fxlw89321s9imafnmphrcsr1-ghc-shell-for-packages-ghc-8.10.4-env/bin/hpc", ["/nix/store/mlqhmb29fxlw89321s9imafnmphrcsr1-ghc-shell-for-packages-ghc-8.10.4-env/bin/hpc", "markup", "/home/ollie/work/circuithub/dist-newstyle/build/x86_64-linux/ghc-8.10.4/ch-persistence-1.0/t/tests/noopt/hpc/vanilla/tix/tests/tests.tix", "--destdir=/home/ollie/work/circuithub/dist-newstyle/build/x86_64-linux/ghc-8.10.4/ch-persistence-1.0/t/tests/noopt/hpc/vanilla/html/tests", "--hpcdir=/home/ollie/work/circuithub/dist-newstyle/build/x86_64-linux/ghc-8.10.4/ch-persistence-1.0/t/tests/noopt/hpc/vanilla/mix/tests", "--hpcdir=/home/ollie/work/circuithub/dist-newstyle/build/x86_64-linux/ghc-8.10.4/ch-persistence-1.0/t/tests/noopt/hpc/vanilla/mix/ch-persistence-1.0", "--include=CircuitHub.Pallet", "--include=CircuitHub.Pallet.FromPalletToInstalledSpace", "--include=CircuitHub.Pallet.TrayInstallation", "--include=CircuitHub.Pallet.UpdateCircuitHubTraysFromMycronic", "--include=CircuitHub.Persistence.Bin", "--include=CircuitHub.Persistence.Bin.Bin", "--include=CircuitHub.Persistence.Board", "--include=CircuitHub.Persistence.BoardOrder", "--include=CircuitHub.Persistence.BoardQuote", "--include=CircuitHub.Persistence.Bom", "--include=CircuitHub.Persistence.BomAggr", "--include=CircuitHub.Persistence.BomPart", "--include=CircuitHub.Persistence.BomSnapshot", "--include=CircuitHub.Persistence.BomSnapshotAggr", "--include=CircuitHub.Persistence.Category", "--include=CircuitHub.Persistence.Charge", "--include=CircuitHub.Persistence.Costs", "--include=CircuitHub.Persistence.CostTrack", "--include=CircuitHub.Persistence.CostType", "--include=CircuitHub.Persistence.Datasheet", "--include=CircuitHub.Persistence.Firmware", "--include=CircuitHub.Persistence.Footprint", "--include=CircuitHub.Persistence.Inst", "--include=CircuitHub.Persistence.Issue", "--include=CircuitHub.Persistence.Lot", "--include=CircuitHub.Persistence.Lot.Factoryless", "--include=CircuitHub.Persistence.Lot.Lot", "--include=CircuitHub.Persistence.Lot.NewLot", "--include=CircuitHub.Persistence.Lot.PurchaseOrder", "--include=CircuitHub.Persistence.Order", "--include=CircuitHub.Persistence.OrderAttachment", "--include=CircuitHub.Persistence.OrderBomSubstitutionApproval", "--include=CircuitHub.Persistence.OrderConsignmentAddressNotice", "--include=CircuitHub.Persistence.OrderConsignmentTrackingNumber", "--include=CircuitHub.Persistence.OrderPlacementDetails", "--include=CircuitHub.Persistence.OrderSubstitution", "--include=CircuitHub.Persistence.OrderSubstitutionAggr", "--include=CircuitHub.Persistence.OrderSubstitutionNotice", "--include=CircuitHub.Persistence.Organization", "--include=CircuitHub.Persistence.Outputs", "--include=CircuitHub.Persistence.Package", "--include=CircuitHub.Persistence.Pallet", "--include=CircuitHub.Persistence.Pallet.InstalledPallet", "--include=CircuitHub.Persistence.Pallet.InstalledTray", "--include=CircuitHub.Persistence.Pallet.NewInstalledPallet", "--include=CircuitHub.Persistence.Pallet.TrayEvent", "--include=CircuitHub.Persistence.Pallet.TrayLocation", "--include=CircuitHub.Persistence.Pallet.UpdateInstalledTray", "--include=CircuitHub.Persistence.Panel", "--include=CircuitHub.Persistence.Part", "--include=CircuitHub.Persistence.PartAggregate", "--include=CircuitHub.Persistence.PartRank", "--include=CircuitHub.Persistence.Periscope", "--include=CircuitHub.Persistence.Placement", "--include=CircuitHub.Persistence.PostgreSQL", "--include=CircuitHub.Persistence.PostgreSQL.Statement", "--include=CircuitHub.Persistence.PostgreSQL.TestDatabase", "--include=CircuitHub.Persistence.Progress", "--include=CircuitHub.Persistence.Project", "--include=CircuitHub.Persistence.PurchaseOrder", "--include=CircuitHub.Persistence.PurchaseOrderEx", "--include=CircuitHub.Persistence.PurchasingBomShortage", "--include=CircuitHub.Persistence.Quote", "--include=CircuitHub.Persistence.Rack", "--include=CircuitHub.Persistence.Rack.Location", "--include=CircuitHub.Persistence.Revision", "--include=CircuitHub.Persistence.Schematic", "--include=CircuitHub.Persistence.Source", "--include=CircuitHub.Persistence.Stock", "--include=CircuitHub.Persistence.Stripe", "--include=CircuitHub.Persistence.Substitute", "--include=CircuitHub.Persistence.Transaction", "--include=CircuitHub.Persistence.User", "--include=CircuitHub.Persistence.UserAddress", "--include=CircuitHub.Persistence.Workcell", "--include=CircuitHub.Persistence.Workcell.RackSlot", "--include=CircuitHub.Query.Bin", "--include=CircuitHub.Query.Board", "--include=CircuitHub.Query.BoardOrder", "--include=CircuitHub.Query.BoardSnapshot", "--include=CircuitHub.Query.BOM", "--include=CircuitHub.Query.BomPart", "--include=CircuitHub.Query.BomSnapshot", "--include=CircuitHub.Query.BomSnapshotLineage", "--include=CircuitHub.Query.Category", "--include=CircuitHub.Query.Charge", "--include=CircuitHub.Query.Component", "--include=CircuitHub.Query.Costs", "--include=CircuitHub.Query.CostSummary", "--include=CircuitHub.Query.CostType", "--include=CircuitHub.Query.Datasheet", "--include=CircuitHub.Query.Factory", "--include=CircuitHub.Query.Firmware", "--include=CircuitHub.Query.Footprint", "--include=CircuitHub.Query.Inst", "--include=CircuitHub.Query.Issue", "--include=CircuitHub.Query.Lot", "--include=CircuitHub.Query.Lot.Lots", "--include=CircuitHub.Query.MyData.Pallet", "--include=CircuitHub.Query.Order", "--include=CircuitHub.Query.OrderAttachment", "--include=CircuitHub.Query.OrderBomSubstitutionApproval", "--include=CircuitHub.Query.OrderConsignmentAddressNotice", "--include=CircuitHub.Query.OrderConsignmentTrackingNumber", "--include=CircuitHub.Query.OrderStats", "--include=CircuitHub.Query.OrderSubstitution", "--include=CircuitHub.Query.OrderSubstitutionAggr", "--include=CircuitHub.Query.OrderSubstitutionNotice", "--include=CircuitHub.Query.Organization", "--include=CircuitHub.Query.Package", "--include=CircuitHub.Query.Pallet", "--include=CircuitHub.Query.Pallet.InstalledPallets", "--include=CircuitHub.Query.Panel", "--include=CircuitHub.Query.Panelisation", "--include=CircuitHub.Query.Part", "--include=CircuitHub.Query.PartAggr", "--include=CircuitHub.Query.PartCost", "--include=CircuitHub.Query.PartFootprint", "--include=CircuitHub.Query.PartRank", "--include=CircuitHub.Query.PartSpec", "--include=CircuitHub.Query.PartSpecAggr", "--include=CircuitHub.Query.PartTestCentered", "--include=CircuitHub.Query.Periscope.BoardOrderStatus", "--include=CircuitHub.Query.Periscope.BoardsPerPanel", "--include=CircuitHub.Query.Periscope.ConsignedParts", "--include=CircuitHub.Query.Periscope.ConsignedPartsOverview", "--include=CircuitHub.Query.Periscope.Flow", "--include=CircuitHub.Query.Periscope.JetPrintStatus", "--include=CircuitHub.Query.Periscope.PackageProgramming", "--include=CircuitHub.Query.Periscope.PanelInfo", "--include=CircuitHub.Query.Periscope.PanelStateCount", "--include=CircuitHub.Query.Periscope.PartNotes", "--include=CircuitHub.Query.Periscope.PartsPipeline", "--include=CircuitHub.Query.Periscope.PartsPipelineInBin", "--include=CircuitHub.Query.Periscope.PartsPipelineOnPallet", "--include=CircuitHub.Query.Periscope.PartsPipelineOnTray", "--include=CircuitHub.Query.Periscope.PartsPipelinePurchaseOrder", "--include=CircuitHub.Query.Periscope.PartsPipelineSummary", "--include=CircuitHub.Query.Periscope.PlacementCount", "--include=CircuitHub.Query.Periscope.ShippedBoards", "--include=CircuitHub.Query.Periscope.SideDetails", "--include=CircuitHub.Query.Periscope.Substitutions", "--include=CircuitHub.Query.Placement", "--include=CircuitHub.Query.Privacy", "--include=CircuitHub.Query.Progress", "--include=CircuitHub.Query.Project", "--include=CircuitHub.Query.PurchaseOrder", "--include=CircuitHub.Query.PurchaseOrderEx", "--include=CircuitHub.Query.PurchaseOrderPartEx", "--include=CircuitHub.Query.PurchasingBomAggr", "--include=CircuitHub.Query.Quote", "--include=CircuitHub.Query.Rack", "--include=CircuitHub.Query.ReceivedToEntry", "--include=CircuitHub.Query.Revision", "--include=CircuitHub.Query.Schematic", "--include=CircuitHub.Query.Shipment", "--include=CircuitHub.Query.ShipmentEx", "--include=CircuitHub.Query.Source", "--include=CircuitHub.Query.Stripe", "--include=CircuitHub.Query.Substitute", "--include=CircuitHub.Query.SubstituteAggr", "--include=CircuitHub.Query.SubstituteFootprintComparison", "--include=CircuitHub.Query.SubstituteManufactureInfo", "--include=CircuitHub.Query.Task", "--include=CircuitHub.Query.Tray", "--include=CircuitHub.Query.User", "--include=CircuitHub.Query.UserAddress", "--include=Mycronic.DatabaseTag", "--include=Mycronic.Persistence", "--include=Mycronic.Persistence.Component", "--include=Mycronic.Persistence.Component.UpdateComponentPackage", "--include=Mycronic.Persistence.Events", "--include=Mycronic.Persistence.Layout", "--include=Mycronic.Persistence.Pallet", "--include=Mycronic.Persistence.Pallet.PalletInAtm", "--include=Mycronic.Persistence.Pallet.Traydata", "--include=Mycronic.Persistence.Pallet.UpdateTraydata", "--include=Mycronic.Query.Atm", "--include=Mycronic.Query.Boardposition", "--include=Mycronic.Query.Centering", "--include=Mycronic.Query.Component", "--include=Mycronic.Query.Gluedisp", "--include=Mycronic.Query.Leadgroup", "--include=Mycronic.Query.Machine", "--include=Mycronic.Query.Packheader", "--include=Mycronic.Query.Pallet", "--include=Mycronic.Query.Pallet.PalletsInAtms", "--include=Mycronic.Query.Referenceimage", "--include=Mycronic.Query.Referenceimageregion", "--include=Mycronic.Query.Schemas", "--include=Mycronic.Query.Segment", "--include=Mycronic.Query.Togglepoint", "--include=Mycronic.Query.Traydata", "--include=Mycronic.Query.Traypos", "--include=Mycronic.Query.Traytype", "--include=Rel8.Paginate"], 0x42000ea010 /* 187 vars */ <unfinished ...>
```

And here is the working call

```
[pid 379913] execve("/nix/store/vi6pnxbv5lsnvv0l96gcr04bjlmcjnxr-ghc-8.10.4/lib/ghc-8.10.4/bin/hpc", ["/nix/store/vi6pnxbv5lsnvv0l96gcr04bjlmcjnxr-ghc-8.10.4/lib/ghc-8.10.4/bin/hpc", "markup", "/home/ollie/work/circuithub/dist-newstyle/build/x86_64-linux/ghc-8.10.4/ch-persistence-1.0/noopt/hpc/vanilla/tix/ch-persistence-1.0/ch-persistence-1.0.tix", "--destdir=/home/ollie/work/circuithub/dist-newstyle/build/x86_64-linux/ghc-8.10.4/ch-persistence-1.0/noopt/hpc/vanilla/html/ch-persistence-1.0", "--hpcdir=/home/ollie/work/circuithub/dist-newstyle/build/x86_64-linux/ghc-8.10.4/ch-persistence-1.0/noopt/hpc/vanilla/mix/ch-persistence-1.0", "--hpcdir=/home/ollie/work/circuithub/dist-newstyle/build/x86_64-linux/ghc-8.10.4/ch-persistence-1.0/noopt/hpc/vanilla/mix/tests", "--include=CircuitHub.Pallet", "--include=CircuitHub.Pallet.FromPalletToInstalledSpace", "--include=CircuitHub.Pallet.TrayInstallation", "--include=CircuitHub.Pallet.UpdateCircuitHubTraysFromMycronic", "--include=CircuitHub.Persistence.Bin", "--include=CircuitHub.Persistence.Bin.Bin", "--include=CircuitHub.Persistence.Board", "--include=CircuitHub.Persistence.BoardOrder", "--include=CircuitHub.Persistence.BoardQuote", "--include=CircuitHub.Persistence.Bom", "--include=CircuitHub.Persistence.BomAggr", "--include=CircuitHub.Persistence.BomPart", "--include=CircuitHub.Persistence.BomSnapshot", "--include=CircuitHub.Persistence.BomSnapshotAggr", "--include=CircuitHub.Persistence.Category", "--include=CircuitHub.Persistence.Charge", "--include=CircuitHub.Persistence.Costs", "--include=CircuitHub.Persistence.CostTrack", "--include=CircuitHub.Persistence.CostType", "--include=CircuitHub.Persistence.Datasheet", "--include=CircuitHub.Persistence.Firmware", "--include=CircuitHub.Persistence.Footprint", "--include=CircuitHub.Persistence.Inst", "--include=CircuitHub.Persistence.Issue", "--include=CircuitHub.Persistence.Lot", "--include=CircuitHub.Persistence.Lot.Factoryless", "--include=CircuitHub.Persistence.Lot.Lot", "--include=CircuitHub.Persistence.Lot.NewLot", "--include=CircuitHub.Persistence.Lot.PurchaseOrder", "--include=CircuitHub.Persistence.Order", "--include=CircuitHub.Persistence.OrderAttachment", "--include=CircuitHub.Persistence.OrderBomSubstitutionApproval", "--include=CircuitHub.Persistence.OrderConsignmentAddressNotice", "--include=CircuitHub.Persistence.OrderConsignmentTrackingNumber", "--include=CircuitHub.Persistence.OrderPlacementDetails", "--include=CircuitHub.Persistence.OrderSubstitution", "--include=CircuitHub.Persistence.OrderSubstitutionAggr", "--include=CircuitHub.Persistence.OrderSubstitutionNotice", "--include=CircuitHub.Persistence.Organization", "--include=CircuitHub.Persistence.Outputs", "--include=CircuitHub.Persistence.Package", "--include=CircuitHub.Persistence.Pallet", "--include=CircuitHub.Persistence.Pallet.InstalledPallet", "--include=CircuitHub.Persistence.Pallet.InstalledTray", "--include=CircuitHub.Persistence.Pallet.NewInstalledPallet", "--include=CircuitHub.Persistence.Pallet.TrayEvent", "--include=CircuitHub.Persistence.Pallet.TrayLocation", "--include=CircuitHub.Persistence.Pallet.UpdateInstalledTray", "--include=CircuitHub.Persistence.Panel", "--include=CircuitHub.Persistence.Part", "--include=CircuitHub.Persistence.PartAggregate", "--include=CircuitHub.Persistence.PartRank", "--include=CircuitHub.Persistence.Periscope", "--include=CircuitHub.Persistence.Placement", "--include=CircuitHub.Persistence.PostgreSQL", "--include=CircuitHub.Persistence.PostgreSQL.Statement", "--include=CircuitHub.Persistence.PostgreSQL.TestDatabase", "--include=CircuitHub.Persistence.Progress", "--include=CircuitHub.Persistence.Project", "--include=CircuitHub.Persistence.PurchaseOrder", "--include=CircuitHub.Persistence.PurchaseOrderEx", "--include=CircuitHub.Persistence.PurchasingBomShortage", "--include=CircuitHub.Persistence.Quote", "--include=CircuitHub.Persistence.Rack", "--include=CircuitHub.Persistence.Rack.Location", "--include=CircuitHub.Persistence.Revision", "--include=CircuitHub.Persistence.Schematic", "--include=CircuitHub.Persistence.Source", "--include=CircuitHub.Persistence.Stock", "--include=CircuitHub.Persistence.Stripe", "--include=CircuitHub.Persistence.Substitute", "--include=CircuitHub.Persistence.Transaction", "--include=CircuitHub.Persistence.User", "--include=CircuitHub.Persistence.UserAddress", "--include=CircuitHub.Persistence.Workcell", "--include=CircuitHub.Persistence.Workcell.RackSlot", "--include=CircuitHub.Query.Bin", "--include=CircuitHub.Query.Board", "--include=CircuitHub.Query.BoardOrder", "--include=CircuitHub.Query.BoardSnapshot", "--include=CircuitHub.Query.BOM", "--include=CircuitHub.Query.BomPart", "--include=CircuitHub.Query.BomSnapshot", "--include=CircuitHub.Query.BomSnapshotLineage", "--include=CircuitHub.Query.Category", "--include=CircuitHub.Query.Charge", "--include=CircuitHub.Query.Component", "--include=CircuitHub.Query.Costs", "--include=CircuitHub.Query.CostSummary", "--include=CircuitHub.Query.CostType", "--include=CircuitHub.Query.Datasheet", "--include=CircuitHub.Query.Factory", "--include=CircuitHub.Query.Firmware", "--include=CircuitHub.Query.Footprint", "--include=CircuitHub.Query.Inst", "--include=CircuitHub.Query.Issue", "--include=CircuitHub.Query.Lot", "--include=CircuitHub.Query.Lot.Lots", "--include=CircuitHub.Query.MyData.Pallet", "--include=CircuitHub.Query.Order", "--include=CircuitHub.Query.OrderAttachment", "--include=CircuitHub.Query.OrderBomSubstitutionApproval", "--include=CircuitHub.Query.OrderConsignmentAddressNotice", "--include=CircuitHub.Query.OrderConsignmentTrackingNumber", "--include=CircuitHub.Query.OrderStats", "--include=CircuitHub.Query.OrderSubstitution", "--include=CircuitHub.Query.OrderSubstitutionAggr", "--include=CircuitHub.Query.OrderSubstitutionNotice", "--include=CircuitHub.Query.Organization", "--include=CircuitHub.Query.Package", "--include=CircuitHub.Query.Pallet", "--include=CircuitHub.Query.Pallet.InstalledPallets", "--include=CircuitHub.Query.Panel", "--include=CircuitHub.Query.Panelisation", "--include=CircuitHub.Query.Part", "--include=CircuitHub.Query.PartAggr", "--include=CircuitHub.Query.PartCost", "--include=CircuitHub.Query.PartFootprint", "--include=CircuitHub.Query.PartRank", "--include=CircuitHub.Query.PartSpec", "--include=CircuitHub.Query.PartSpecAggr", "--include=CircuitHub.Query.PartTestCentered", "--include=CircuitHub.Query.Periscope.BoardOrderStatus", "--include=CircuitHub.Query.Periscope.BoardsPerPanel", "--include=CircuitHub.Query.Periscope.ConsignedParts", "--include=CircuitHub.Query.Periscope.ConsignedPartsOverview", "--include=CircuitHub.Query.Periscope.Flow", "--include=CircuitHub.Query.Periscope.JetPrintStatus", "--include=CircuitHub.Query.Periscope.PackageProgramming", "--include=CircuitHub.Query.Periscope.PanelInfo", "--include=CircuitHub.Query.Periscope.PanelStateCount", "--include=CircuitHub.Query.Periscope.PartNotes", "--include=CircuitHub.Query.Periscope.PartsPipeline", "--include=CircuitHub.Query.Periscope.PartsPipelineInBin", "--include=CircuitHub.Query.Periscope.PartsPipelineOnPallet", "--include=CircuitHub.Query.Periscope.PartsPipelineOnTray", "--include=CircuitHub.Query.Periscope.PartsPipelinePurchaseOrder", "--include=CircuitHub.Query.Periscope.PartsPipelineSummary", "--include=CircuitHub.Query.Periscope.PlacementCount", "--include=CircuitHub.Query.Periscope.ShippedBoards", "--include=CircuitHub.Query.Periscope.SideDetails", "--include=CircuitHub.Query.Periscope.Substitutions", "--include=CircuitHub.Query.Placement", "--include=CircuitHub.Query.Privacy", "--include=CircuitHub.Query.Progress", "--include=CircuitHub.Query.Project", "--include=CircuitHub.Query.PurchaseOrder", "--include=CircuitHub.Query.PurchaseOrderEx", "--include=CircuitHub.Query.PurchaseOrderPartEx", "--include=CircuitHub.Query.PurchasingBomAggr", "--include=CircuitHub.Query.Quote", "--include=CircuitHub.Query.Rack", "--include=CircuitHub.Query.ReceivedToEntry", "--include=CircuitHub.Query.Revision", "--include=CircuitHub.Query.Schematic", "--include=CircuitHub.Query.Shipment", "--include=CircuitHub.Query.ShipmentEx", "--include=CircuitHub.Query.Source", "--include=CircuitHub.Query.Stripe", "--include=CircuitHub.Query.Substitute", "--include=CircuitHub.Query.SubstituteAggr", "--include=CircuitHub.Query.SubstituteFootprintComparison", "--include=CircuitHub.Query.SubstituteManufactureInfo", "--include=CircuitHub.Query.Task", "--include=CircuitHub.Query.Tray", "--include=CircuitHub.Query.User", "--include=CircuitHub.Query.UserAddress", "--include=Mycronic.DatabaseTag", "--include=Mycronic.Persistence", "--include=Mycronic.Persistence.Component", "--include=Mycronic.Persistence.Component.UpdateComponentPackage", "--include=Mycronic.Persistence.Events", "--include=Mycronic.Persistence.Layout", "--include=Mycronic.Persistence.Pallet", "--include=Mycronic.Persistence.Pallet.PalletInAtm", "--include=Mycronic.Persistence.Pallet.Traydata", "--include=Mycronic.Persistence.Pallet.UpdateTraydata", "--include=Mycronic.Query.Atm", "--include=Mycronic.Query.Boardposition", "--include=Mycronic.Query.Centering", "--include=Mycronic.Query.Component", "--include=Mycronic.Query.Gluedisp", "--include=Mycronic.Query.Leadgroup", "--include=Mycronic.Query.Machine", "--include=Mycronic.Query.Packheader", "--include=Mycronic.Query.Pallet", "--include=Mycronic.Query.Pallet.PalletsInAtms", "--include=Mycronic.Query.Referenceimage", "--include=Mycronic.Query.Referenceimageregion", "--include=Mycronic.Query.Schemas", "--include=Mycronic.Query.Segment", "--include=Mycronic.Query.Togglepoint", "--include=Mycronic.Query.Traydata", "--include=Mycronic.Query.Traypos", "--include=Mycronic.Query.Traytype", "--include=Rel8.Paginate"], 0x1bbd008 /* 187 vars */) = 0
```

**Comment by Mikolaj** [comment]
> Here is the output of fd '.*' for ch-persistence with (good) and without (bad) --enable-coverage

Thank you. The offending file is in exactly the same places in both cases, just as you note, and the places seems fine, so probably here the hack worked. The offending call to `hpc` indeed has arguments as if the hack wasn't applied.

I would try to reproduce, but the regression test contained in this very PR is as close as possible already (coverage via cabal.project, not commandline option) and it works fine.

Out of curiosity, why is the `execve` different between the two calls?

**Comment by Mikolaj** [comment]
OK, I got a repro by adding

    optimization: False

to cabal.project. Will investigate.

**Comment by ocharles** [comment]
Wow, that is bizzare - but also something that's in my `cabal.project`! For the record, here's what I have:

<details>

```
-- See: https://cabal.readthedocs.io/en/latest/nix-local-build.html#developing-multiple-packages
-- This file is for local, dev builds only. Release builds done by Hydra are configured through Nix.

optimization:
  False

-- You can tune these settings according to your own machine by setting them in
-- cabal.project.local.
jobs:
  2

program-options
  ghc-options:
    -j2 -optl-fuse-ld=gold -fwrite-ide-info -fhide-source-paths
  ld-options:
    -fuse-ld=gold

package *
  ghc-options:
    -j2 -optl-fuse-ld=gold -fwrite-ide-info -fhide-source-paths
  ld-options:
    -fuse-ld=gold

packages:
  ./api/circuithub-api.cabal
  ./ch-authorize/*.cabal
  ./ch-aws/*.cabal
  ./ch-deploy/*.cabal
  ./ch-eda-all/ch-eda-core/*.cabal
  ./ch-eda-all/ch-eda-gerber/*.cabal
  ./ch-eda-all/ch-eda-integrater/*.cabal
  ./ch-eda-all/ch-eda-kicad/*.cabal
  ./ch-eda-all/ch-eda-gencad/*.cabal
  ./ch-eda-all/ch-eda/*.cabal
  ./ch-linear/*.cabal
  ./ch-model-hedgehog/*.cabal
  ./ch-model/*.cabal
  ./ch-persistence/*.cabal
  ./ch-segment/*.cabal
  ./ch-shippo/*.cabal
  ./ch-stripe/*.cabal
  ./ch-wai-extra/*.cabal
  ./daemons/**/*.cabal
  ./effects/**/*.cabal
  ./ex-pool-prometheus/*.cabal
  ./machine-learning/*.cabal
  ./mouse-proxy/*.cabal
  ./octopart/*.cabal
  ./pallet-loader/**/*.cabal
  ./picofactory/aoi/*.cabal
  ./picofactory/coordinator/*.cabal
  ./picofactory/jet-printer-programming/*.cabal
  ./picofactory/jpctl/*.cabal
  ./picofactory/my300/*.cabal
  ./picofactory/pallet-allocation/*.cabal
  ./picofactory/panelisation/*.cabal
  ./picofactory/pnp/*.cabal
  ./picofactory/ur10/ur10.cabal
  ./prelude/*.cabal
  ./quoting/*.cabal
  ./reconciliation/*.cabal

allow-newer:
  filepicker-policy:base

-- Needed for opencv
constraints: inline-c == 0.8.0.1, inline-c-cpp == 0.3.0.3

-- New versions don't seem to build
constraints: funflow == 1.5.0

-- servant-hmac-auth doesn't build with 0.18.2 due to internal API changes.
constraints: servant-client == 0.18, servant-client-core == 0.18

allow-newer: reactive-banana-gi-gtk:haskell-gi-base

constraints: streaming-bytestring == 0.1.6

-- 0.2.4.2 only works on GHC 9
constraints: th-utilities == 0.2.4.1

-- Use GTK 3
constraints: gi-gtk < 4

-- Without this cabal seems to pick 1.0.0.1, which doesn't build on GHC 8.10.
constraints: sexpresso == 1.1.0.0

allow-newer: active:base
allow-newer: comparable-key:hashable
allow-newer: diagrams-cairo:base
allow-newer: diagrams-core:base
allow-newer: diagrams-lib:base
allow-newer: diagrams-rasterific:base
allow-newer: diagrams-svg:base
allow-newer: dual-tree:base
allow-newer: mandrill:aeson
allow-newer: monoid-extras:base
allow-newer: monoidal-containers:aeson
allow-newer: network-bsd:network
allow-newer: reactive-banana:hashable
allow-newer: socket-activation:network
allow-newer: statestack:base
allow-newer: svg-builder:base

allow-newer: diagrams-contrib:*, force-layout:*

-- Without this, Cabal (or Haskell.nix) seems to get confused and occasionally tries 2.7.10 || 2.8. For now, we just pin it to 2.7.10
constraints: hspec-discover ==2.7.10
```

</details>

**Comment by cartazio** [comment]
Future me thanks all of you for progressing this stuff!!  Hpc / program coverage tooling is such a gem and everyone will benefit from this effort

**Comment by Mikolaj** [comment]
@ocharles: could you try if it works for you now? The hack unfortunately got a bit more complex, because the paths turned out to be so (and they are even more complex when there are multiple components involved (more precisely, when `distParamUnitId /= distParamComponentId`, whatever that means), but I think HPC currently is disabled in these cases).

**Comment by ocharles** [comment]
@Mikolaj I can confirm that

```
cabal clean
cabal test ch-persistence --enable-coverage
```

and (with `coverage: True` for `package ch-persistence` in `cabal.project`)

```
cabal clean
cabal test
```

Both produce coverage reports :tada: Thank you for doing the extra work here!

**Comment by Mikolaj** [comment]
@ocharles: thank you. I take it as a favourable review and commence merging.

**Comment by TomMD** [comment]
@Mikolaj Moving discussion here after having mentioned an issue on the mailing list 3.6 release announcement. 

I've built cabal head (26b99e3d28a65c82dbe2f2a5b3404b1e83e540f3) and tried to get coverage information for my private project.  The results were markup failing. After having `git clean -fdx` then using exclusively the new cabal:

```
% ~/.cabal/bin/cabal --version
cabal-install version 3.5
compiled using version 3.5.0.0 of the Cabal library
% git clean -fdx && ~/.cabal/bin/cabal test -v --enable-coverage the-tests
<snip>
Test suite the-tests: RUNNING...                                                                                                               /Users/tommd/Projects/some-project/packages/dist-newstyle/build/x86_64-osx/ghc-8.10.1/package-with-the-test-0.1.0.0/build/the-tests/the-tests
Test suite the-tests: PASS
Test suite logged to:
/Users/tommd/Projects/some-project/packages/dist-newstyle/build/x86_64-osx/ghc-8.10.1/package-with-the-test-0.1.0.0/test/package-with-the-test-0.1.0.0-the-tests.log                                                                                                                          /Users/tommd/.ghcup/bin/hpc markup /Users/tommd/Projects/some-project/packages/dist-newstyle/build/x86_64-osx/ghc-8.10.1/package-with-the-test-0.1.0.0/hpc/vanilla/tix/the-tests/the-tests.tix '--destdir=/Users/tommd/Projects/some-project/packages/dist-newstyle/build/x86_64-osx/ghc-8.10.1/package-with-the-test-0.1.0.0/hpc/vanilla/html/the-tests' '--hpcdir=/Users/tommd/Projects/some-project/packages/dist-newstyle/build/x86_64-osx/ghc-8.10.1/package-with-the-test-0.1.0.0/hpc/vanilla/mix/the-tests' '--hpcdir=/Users/tommd/Projects/some-project/packages/dist-newstyle/build/x86_64-osx/ghc-8.10.1/package-with-the-test-0.1.0.0/hpc/vanilla/mix/package-with-the-test-0.1.0.0' '--exclude=package-with-the-test.Host.Xyz.UrlParsingTest' '--exclude=package-with-the-test.Host.UtilsTest' '--exclude=TestUtil' '--exclude=Main'                                          hpc: can not find service-api-0.1.0.0-inplace/Service.Server.Types in ./.hpc, /Users/tommd/Projects/some-project/packages/dist-newstyle/build/x86_64-osx/ghc-8.10.1/package-with-the-test-0.1.0.0/hpc/vanilla/mix/package-with-the-test-0.1.0.0, /Users/tommd/Projects/some-project/packages/dist-newstyle/build/x86_64-osx/ghc-8.10.1/package-with-the-test-0.1.0.0/hpc/vanilla/mix/the-tests
CallStack (from HasCallStack):
  error, called at libraries/hpc/Trace/Hpc/Mix.hs:122:15 in hpc-0.6.1.0:Trace.Hpc.Mix

cabal: Tests failed for package-with-the-test-0.1.0.0-inplace.
```

This is with a project file in the form:

```
packages:
    a,
    b,
    c

source-repository-package
  type: git
  location: https://github.com/TomMD/dep-repo-1.git
  tag: aba843cb671d0da116de701f9433712505f97aad

source-repository-package
  type: git
  location: https://github.com/TomMD/dep-repo-2.git
  tag: aba843cb671d0da116de701f9433712505f97aae

source-repository-package
  type: git
  location: https://github.com/TomMD/dep-repo-3.git
  tag: aba843cb671d0da116de701f9433712505f97aaf
```

Also a cabal freeze file exists.

**Comment by Mikolaj** [comment]
@TomMD: thank you very much for the details. They do look like my fix may not be helping, but I really can't tell if it's applied.

Let me rephrase what you did: you've build tag Cabal-v3.6.0.0 (26b99e3) of branch 3.6, which does not include my fix (this PR). Then you used cabal 3.5 not from this branch (I assume cabal from this branch would be 3.6) which does or does not include my fix. Then you've got output (the paths) as if my fix worked, but it all ended up in an error anyway.

Could you confirm or deny an of the above. :) Also, any chance of a reproducer I could try?

**Comment by TomMD** [comment]
@Mikolaj Sorry for the wrong information - that hash was 3.6 as you noticed and I forgot I changed git head after building last night.  The cabal I'm running is 60bdc5f2a690aa62c5c679ba94e8b44560837bfa 

1. I built cabal 3.5 from master as of commit 60bdc5f2a690aa62c5c679ba94e8b44560837bfa.  This was installed at ~/.cabal/bin/cabal
2. Observe that branch contains your commit: `% git log | grep ee0ce41f702664c7a8ddb16da6858d2dd489c52e` ->
`commit ee0ce41f702664c7a8ddb16da6858d2dd489c52e`
3. Run the above `cabal test ...` command
4. I got the output (the paths) above
5. While I am not sure what your fix was supposed to do, I do not see what I'd expect of `'--hpcdir=dist-newstyle/build/x86_64-osx/ghc-8.10.1/service-api-0.1.0.0/hpc/vanilla/mix/...`

I'll work on a sharable reproducer.

**Comment by Mikolaj** [comment]
Thank you again. My fix was basically removing the `t/nameOfYourTestComponent` from the middle of the path, which seems desirable (library .mix files are at the shorter paths), but if there are cases one needs both the shorter and longer path, that can be easily arranged.

**Comment by TomMD** [comment]
I've narrowed the problem down to doc-test style custom setup.   For my case, now that I know the issue I can avoid it without problem.

https://github.com/TomMD/reproduce-cabal-hpc-failure

**Comment by Mikolaj** [comment]
IIRC custom setup for doctest is now deprecated. If you still require a custom setup, please let doctest devs know and we'll try to help from cabal side.

Having said that, does my PR break a setup that worked without it, e.g,. that worked with the cabal 3.6.0 binary? If so I'd try to patch it. Otherwise, given that HPC directory handling needs a total overhaul, it makes sense to wait.

**Comment by TomMD** [comment]
Without the custom setup your branch works fine. Thank you for all the work.

**Comment by Mikolaj** [comment]
@TomMD: OK, thank you for the confirmation, standing by. Please let us know if anything else breaks. Cheers!

**Comment by Mikolaj** [comment]
@Mergifyio backport 3.6

The backport will fail, because test outputs are changed by other commits, but I will fixup the backport PR.
