### PR TITLE
Die if dynamic executable is requested on Windows

### LINKED ISSUE #9807: Alert the user that on Windows, with configuration `executable-dynamic: True` executables (including build-tools) cannot be built
This issue is singled out from: 
- #9784 

Adding `executable-dynamic: True` to the cabal configuration on Windows will fail executables to build.
This include situations where you just want to build a library, but it has `build-tool-depends: alex` or similar causing the linking of build-tool `alex` to fail.

Reproduced on a fresh Haskell installation: https://github.com/agda/agda/actions/runs/8213506540/job/22465003537#step:10:233
```
Building executable 'alex' for alex-3.5.1.0..
[ 1 of 19] Compiling DFS              ( src\DFS.hs, dist\build\alex\alex-tmp\DFS.dyn_o )

src\DFS.hs:24:8: error: [GHC-88719]
Error:     Could not load module ‘Prelude’.
    Perhaps you haven't installed the "dyn" libraries for package ‘base-4.19.1.0’?
```

### PR DESCRIPTION
**Pull request by jasagredo**
Closes #9807

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [x] The documentation has been updated, if necessary.
* [x] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [x] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

# QA

Trying to build with `--enable-executable-dynamic` will now stop before attempting to compile.

### CODE REVIEW

File: Cabal/src/Distribution/Simple/Errors.hs [hunk 1]
```diff
@@ -622,10 +622,10 @@ exceptionMessage e = case e of
           ++ "non-standard location you can use the --with-gcc "
           ++ "flag to specify it."
       ]
-  NoOSSupport os ->
+  NoOSSupport os what ->
     "Operating system: "
       ++ prettyShow os
-      ++ ", does not support relocatable builds"
+      ++ ", does not support " ++ what
```
Comment (geekosaur) [inline Cabal/src/Distribution/Simple/Errors.hs:628]: Fourmolu doesn't like this.
```suggestion
      ++ ", does not support "
      ++ what
```

**Review by geekosaur — CHANGES_REQUESTED** [review]

**Review by ulysses4ever — APPROVED** [review]
Cool. thanks!

**Comment by Kleidukos** [comment]
@jasagredo can you update this wiki page with a short paragraph on the Windows situation? https://gitlab.haskell.org/ghc/ghc/-/wikis/Linking

**Review by geekosaur — APPROVED** [review]
Not sure I'm an ideal reviewer given that I don't have a Windows install.

**Comment by jasagredo** [comment]
> @jasagredo can you update this wiki page with a short paragraph on the Windows situation? https://gitlab.haskell.org/ghc/ghc/-/wikis/Linking

@Kleidukos I wish I could. I know that it doesn't work, but I don't know _why_ it doesn't work 😄

**Comment by Kleidukos** [comment]
@jasagredo curse. Send me the paragraph and I'll integrate it. :)

**Comment by jasagredo** [comment]
This is the only info I have https://gitlab.haskell.org/ghc/ghc/-/wikis/windows-dynamic-linking and maybe it is outdated, I don't know 😢
