### PR TITLE
cabal-install: Be less eager to configure external programs

### LINKED ISSUE #10692: [3.14] Initial configuration of programs does not use build-tool-depends
**Describe the bug**
The store path in which the alex build tool is placed does not correspond with the one used later on to build Cabal-syntax.

**To Reproduce**

```
➜ PROJ=$(mktemp -d)
➜ cd $PROJ
➜ cabal init -n -d Cabal-syntax==3.14.1.0 -d base
...
➜ cabal-3.14.1.0 build
Resolving dependencies...
Build profile: -w ghc-9.6.6 -O1
In order, the following will be built (use -v for more details):
 - alex-3.5.2.0 (exe:alex) (requires build)
 - Cabal-syntax-3.14.1.0 (lib) (requires build)
 - tmp-Xg8Fj7x2N4-0.1.0.0 (exe:tmp-Xg8Fj7x2N4) (first run)
Starting     alex-3.5.2.0 (exe:alex)
Building     alex-3.5.2.0 (exe:alex)
Installing   alex-3.5.2.0 (exe:alex)
Completed    alex-3.5.2.0 (exe:alex)
Starting     Cabal-syntax-3.14.1.0 (lib)
Building     Cabal-syntax-3.14.1.0 (lib)

Failed to build Cabal-syntax-3.14.1.0.
Build log (
C:\Users\Javier\AppData\Local\cabal\logs\ghc-9.6.6\Cabal-syntax-3.14.1.0-cd5ebad5757c2e92bfba1d2f77f930f4e00add04.log
):
Preprocessing library for Cabal-syntax-3.14.1.0...
alex.exe: C:\Users\Javier\AppData\Local\cabal\store\ghc-9.6.6\alex-3.5.1.0-868184b46a75d3f1207acacf299a27ecc42d81d8\share/AlexTemplate.hs: openFile: does not exist (No such file or directory)
Error: [Cabal-7125]
Failed to build Cabal-syntax-3.14.1.0 (which is required by exe:tmp-Xg8Fj7x2N4 from tmp-Xg8Fj7x2N4-0.1.0.0). See the build log above for details.
➜ ls 'C:\Users\Javier\AppData\Local\cabal\store\ghc-9.6.6\' | grep alex
alex-3.5.2.0-291af4c4dce682a2c469bb7d8ce8566bb62a9bb1
```

I removed all the `alex` folders before starting this process. This doesn't happen on 3.12.1.0.

**System information**
 - Windows 11 24H2, MSYS2.
 - `cabal`: 3.14.1.0
 - `ghc`: 9.6.6

On Linux it does work:
```
javier@javier-VirtualBox:~$ PROJ=$(mktemp -d)
javier@javier-VirtualBox:~$ cd $PROJ
javier@javier-VirtualBox:/tmp/tmp.btAJnhl1KU$ cabal init -n -d Cabal-syntax==3.14.1.0 -d base
...
javier@javier-VirtualBox:/tmp/tmp.btAJnhl1KU$ cabal build
Resolving dependencies...
Build profile: -w ghc-9.4.8 -O1
In order, the following will be built (use -v for more details):
 - alex-3.5.2.0 (exe:alex) (requires download & build)
 - Cabal-syntax-3.14.1.0 (lib) (requires download & build)
 - tmp-btAJnhl1KU-0.1.0.0 (exe:tmp-btAJnhl1KU) (first run)
Downloading  alex-3.5.2.0
Downloaded   alex-3.5.2.0
Downloading  Cabal-syntax-3.14.1.0
Starting     alex-3.5.2.0 (exe:alex)
Downloaded   Cabal-syntax-3.14.1.0
Building     alex-3.5.2.0 (exe:alex)
Installing   alex-3.5.2.0 (exe:alex)
Completed    alex-3.5.2.0 (exe:alex)
Starting     Cabal-syntax-3.14.1.0 (lib)
Building     Cabal-syntax-3.14.1.0 (lib)
Installing   Cabal-syntax-3.14.1.0 (lib)
Completed    Cabal-syntax-3.14.1.0 (lib)
Configuring executable 'tmp-btAJnhl1KU' for tmp-btAJnhl1KU-0.1.0.0...
Preprocessing executable 'tmp-btAJnhl1KU' for tmp-btAJnhl1KU-0.1.0.0...
Building executable 'tmp-btAJnhl1KU' for tmp-btAJnhl1KU-0.1.0.0...
[1 of 1] Compiling Main             ( app/Main.hs, dist-newstyle/build/x86_64-linux/ghc-9.4.8/tmp-btAJnhl1KU-0.1.0.0/x/tmp-btAJnhl1KU/build/tmp-btAJnhl1KU/tmp-btAJnhl1KU-tmp/Main.o )
[2 of 2] Linking dist-newstyle/build/x86_64-linux/ghc-9.4.8/tmp-btAJnhl1KU-0.1.0.0/x/tmp-btAJnhl1KU/build/tmp-btAJnhl1KU/tmp-btAJnhl1KU
```

### PR DESCRIPTION
**Pull request by mpickering**
In configureCompiler the call to configureAllKnownPrograms was too eager. When called it selected the version of tools from PATH (such as alex), and then when a package was configured these tools were passed using `--with-alex` options to configure, which meant that the build-tool-depends versions were not used. (See #10692)

Why was this call introduced in the first place? Because configureCompiler would a different result depending on whether:

* It is run for the first time, the `ProgramDb` will contain unconfigured programs.
* It is run subsequently, `ProgramDb` is read from disk, it does not contain unconfigured programs.

A surgical way to fix this is to avoid configuring the programs, and manually adding back the builtinPrograms to the ProgramDb, so the ProgramDb returned by configureCompiler always contains all the unconfigured programs.

The testcase is not so easy to write because

* The bug only surfaces when the build-tool you are depending on is known (ie alex, happy etc)
* But then it is tricky to write a test, as we can't depend on the known tools or bundle the source for them.
* So we create a fake "alex", which cabal then invokes on a fake ".x" file. This is maybe a bit fragile if the way cabal invokes alex changes in future, but then the test can be modified as well.

Also see #2241 and #9840

Fixes #10692

Please read [Github PR Conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions) and then fill in *one* of these two templates.

---

**Template Α: This PR modifies [behaviour or interface](https://github.com/cabalism/cabal/blob/master/CONTRIBUTING.md#changelog)**

Include the following checklist in your PR:

* [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [x] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
  * [ ] [Is the change significant?](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#is-my-change-significant) If so, remember to add `significance: significant` in the changelog file.
* [ ] The documentation has been updated, if necessary.
* [ ] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [x] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)

### CODE REVIEW

**Comment by ulysses4ever** [comment]
Hey @mpickering! Any chance you could take a brief look at https://github.com/haskell/cabal/issues/2015? I believe it's closely related to the issue here. In particular, `cabal repl` runs with `$PATH` effective at the time of configuring, not at the time of running `cabal repl`. So, if you run `cabal build` on clean checkout, then change `$PATH`, then run `cabal repl`, inside the repl you won't see the change. This keeps blowing people's heads...

I tried to look into it, and it seems to stem, as you say, from storing the compiler's configuration on disk, and configuration includes `$PATH`. But I don't know what'd be the least intrusive way to fix it. E.g. should we just reconfigure from scratch inside `cabal repl`? Or should we treat `$PATH` in a special way, and maybe try to invalidate only it on every `cabal repl` run.

The code for `cabal repl` had a big update from your multi-repl patch. That's another reason I thought you may be a great candidate for guiding or, indeed, solving #2015.

**Comment by mpickering** [comment]
@ulysses4ever I've just been assigned to look at these two regressions, but I will comment on the issue about how I would begin with that problem.

File: changelog.d/pr-10731 [hunk 1]
```diff
@@ -0,0 +1,12 @@
+synopsis: Fix regression where build-tool-depends are not used
+packages: cabal-install
+prs: #10731
+
```
Comment (jasagredo) [inline changelog.d/pr-10731:4]:
```suggestion
issues: #10692 
```

File: cabal-testsuite/PackageTests/BuildToolDependsExternal/scripts/alex
Comment (jasagredo) [inline cabal-testsuite/PackageTests/BuildToolDependsExternal/scripts/alex:1]: Maybe you need to add a `alex.exe` + `alex.shim` for this to also work on Windows?

Comment (jasagredo) [reply cabal-testsuite/PackageTests/BuildToolDependsExternal/scripts/alex:1]: I mean, the test passes but it probably won't use the hacky alex substitute?

Comment (mpickering) [reply cabal-testsuite/PackageTests/BuildToolDependsExternal/scripts/alex:1]: Yes, it's not supposed to use the `scripts/alex` version. If it does, then any error that we get is good.

Comment (jasagredo) [reply cabal-testsuite/PackageTests/BuildToolDependsExternal/scripts/alex:1]: What I mean is that on Windows the `scripts/alex` file won't be considered as an executable in PATH, and therefore we are not testing that this works as expected, i.e. that the PATH executables are ignored.

Comment (mpickering) [reply cabal-testsuite/PackageTests/BuildToolDependsExternal/scripts/alex:1]: I see, so I can either leave this PR as it is, or an I can skip the test on windows if you think that's better?

File: cabal-install/src/Distribution/Client/ProjectPlanning.hs [hunk 2]
```diff
@@ -475,7 +475,7 @@ configureCompiler
     let fileMonitorCompiler = newFileMonitor $ distProjectCacheFile "compiler"
 
     progsearchpath <- liftIO $ getSystemSearchPath
-    rerunIfChanged
+    (recomp_comp, recomp_plat, recomp_progdb) <- rerunIfChanged
```
Comment (sheaf) [inline cabal-install/src/Distribution/Client/ProjectPlanning.hs:478]: If we use the `ProgramDb` from cache, we will be lacking precisely the unconfigured programs.

Let's look at every line of code in this block and see if we might be dropping information.


```hs
progdb <- liftIO $ prependProgramSearchPath verbosity extraPath [] defaultProgramDb
```

We start with `defaultProgramDb`, a list of unconfigured programs. Any that doesn't get configured will get dropped, so we need to add them back in afterwards; this is what you're doing currently in this patch with the call to `restoreProgramDb`. Good, but this should be written down in a comment.

`prependProgramSearchPath` just sets the `progSearchPath` of the `ProgramDb`, and that gets serialised & deserialised just fine. So that's OK as well, but also deserves a comment.

```hs
let progdb' = userSpecifyPaths (Map.toList (getMapLast packageConfigProgramPaths)) progdb
```

This overrides the PATH to any unconfigured programs in the `ProgramDb`. For example, if `packageConfigProgramPaths` includes a specific PATH for `alex`, this **would get dropped** by `Binary` round-tripping. I think the reasoning here that we don't need to re-apply it is as follows:

  - If we successfully configure the program, then we are no longer dropping information.
  - If we fail to configure the program, then for some reason the given PATH was not suitable, e.g. because no executable existed at that PATH or the executable is the wrong version or etc. So it's also OK to drop that search path information, but this logic should be written down in a comment.

```hs
        (comp, plat, progdb'') <-
          liftIO $
            Cabal.configCompilerEx
              hcFlavor
              hcPath
              hcPkg
              progdb'
              verbosity
```

OK, now here is where it gets problematic. One might initially think that `configCompilerEx` will in the end just add `ghc` as a configured program and otherwise not change the `ProgramDb`. However, that is not the case; this code crucially also modifies unconfigured programs. A key place where this is done is in `configureToolchain`:

```hs
configureToolchain
  :: GhcImplInfo
  -> ConfiguredProgram
  -> Map String String
  -> ProgramDb
  -> ProgramDb
configureToolchain _implInfo ghcProg ghcInfo =
  addKnownProgram
    gccProgram
      { programFindLocation = findProg gccProgramName extraGccPath
      , programPostConf = configureGcc
      }
    . addKnownProgram
      ldProgram
        { programFindLocation = findProg ldProgramName extraLdPath
        , programPostConf = \v cp ->
            -- Call any existing configuration first and then add any new configuration
            configureLd v =<< programPostConf ldProgram v cp
        }
    . addKnownProgram
      arProgram
        { programFindLocation = findProg arProgramName extraArPath
        }
    . addKnownProgram
      stripProgram
        { programFindLocation = findProg stripProgramName extraStripPath
        }
```

Here we are, in essence, adding new search paths for e.g. `ar`, `ld` etc. The problem is that if we don't then proceed to configure these tools, they will get dropped by `Binary` serialisation, and when we reload from cache we might no longer be able to find `ar`. This is what caused the `The program 'ar' is required but it could not be found.` bug reported in #9840. You can see then how the `configureAllKnownPrograms` line I added fixed that problem, and removing that line re-introduces the bug. I conclude that the current change (of simply adding back `defaultProgramDb` and removing the `configureAllKnownPrograms` line) is **not** sufficient.

**Review by sheaf — CHANGES_REQUESTED** [review]

**Comment by mpickering** [comment]
@sheaf and I discussed this and for the backport, the have gone with a revert of the original patch.

I have added two new tests which check for regressions introduced in the original patch. 

In the future we will work on a proper fix the original issue the reverted patch attempted to fix.

**Review by sheaf — APPROVED** [review]

File: cabal-testsuite/PackageTests/BuildToolDependsExternal/scripts/alex
Comment (sheaf) [reply cabal-testsuite/PackageTests/BuildToolDependsExternal/scripts/alex:1]: @jasagredo I am trying to make the test pass on Windows, but I am a bit confused about how the `.shim` mechanism works.

Would you happen to know how I can define the following (all in e.g. the `scripts` folder):

  - `alex` (shell script)
  - `alex.exe` (copied over from other shims, and will parse `alex.shim`)
  - `alex.shim`, which runs `sh` on the `alex` shell script in the current directory

The problem is that I don't know how to specify a relative path in `alex.shim` that points to the `alex` file alongside it in the same directory. I tried some things using e.g. `dirname` but none of that worked.

Comment (jasagredo) [reply cabal-testsuite/PackageTests/BuildToolDependsExternal/scripts/alex:1]: See this file https://github.com/haskell/cabal/blob/master/cabal-testsuite/PackageTests/GhcPkgGuess/Symlink/bin/ghc.shim

And the corresponding logic to fill that in: https://github.com/haskell/cabal/blob/master/cabal-testsuite/PackageTests/GhcPkgGuess/Symlink/setup.test.hs#L5-L13

I know it is ugly ¯\_(ツ)_/¯

Comment (jasagredo) [reply cabal-testsuite/PackageTests/BuildToolDependsExternal/scripts/alex:1]: You might need to pass `scripts/alex` in the arguments in the shim though

Comment (sheaf) [reply cabal-testsuite/PackageTests/BuildToolDependsExternal/scripts/alex:1]: OK, thanks for the help. I wrote some horrible code that seems to work.

Comment (jasagredo) [reply cabal-testsuite/PackageTests/BuildToolDependsExternal/scripts/alex:1]: As ugly as the code I wrote myself for the other tests 😄 but if it works I guess it is good enough!

**Comment by sheaf** [comment]
This should be ready now if anyone wants to take a look? @ulysses4ever @jasagredo perhaps?

**Comment by mpickering** [comment]
Is there anyone available to provide the second review on this patch?

**Review by jasagredo — APPROVED** [review]
It is unfortunate that we have to revert back to the wasteful re-computation of the step, but at least this fixes my issue. Thanks!

**Comment by Mikolaj** [comment]
@mergify backport 3.14
